### ISSUE TITLE
Certain settings toggles 

### ISSUE THREAD

**Issue by vincentbavitz** [oxen-io/session-desktop#1032]
Certain settings toggles (media permissions, menu bar, etc) behave as if setFn is undefined in only partially reproducible cases.

Works for one individual clone from clearnet, and yet not on another clean clone on another machine.

To investigate:
Check ``background.js`` for ``window.toggle*`` functions and ``setSettingValue`` along with ``getSettingValue``. Look into ``SessionSettings.tsx`` for ``setfn`` and ensure all are valid and defined where necessary.

**Comment by Bilb** [comment]
Did not ever run into that case so I will keep close that for now
