### ISSUE TITLE
Better Retry options when Send Failed

### ISSUE THREAD

**Issue by nooblag** [oxen-io/session-desktop#1069]
Hi team,

You're doing amazing work!

I have a suggestion about message fails. In screenshot below is an example of a message failing on Desktop. Could something be implemented to auto-retry, or a button to click to retry sending? At the moment, when this happens, it means retyping message or copy/paste and hitting send to try again.

![loki](https://user-images.githubusercontent.com/1122344/78785270-382cf500-79ea-11ea-9d64-a4b41a11dc15.PNG)

Thanks!

**Comment by nooblag** [comment]
PS -- I should be clearer, I recognise there is option in "..." menu, but it's not easily apparent how to try again from the UI? My suggestion is perhaps a "Try again" message/button should appear next to "Send Failed" text?

**Comment by Bilb** [comment]
we do auto-retry now
