### ISSUE TITLE
tray icon is not shown on Linux

### ISSUE THREAD

**Issue by ykne** [oxen-io/session-desktop#1081]
Signal messenger, from which session UI is derived, requires --use-tray-icon option to display tray icon.

Starting session-desktop with --use-tray-icon on Ubuntu 18.04.3 LTS GNOME causes segfault.
Starting session-desktop with --use-tray-icon on Fedora 31 GNOME causes application behave as if there is tray icon, e.g. clicking on X closes UI but leaves application running but tray icon is not shown and thus there is no way to bring UI back.

Session 1.0.6 downloaded from official site.

**Comment by danrobi11** [comment]
same here MX Linux debian no tray icon. Also black icon in taskbar
![lokinetGUI-black-icon-taskbar](https://user-images.githubusercontent.com/48020114/79620983-c63a6700-80df-11ea-97a1-e1f4fea6b8db.png)

**Comment by LuNiKoFf** [comment]
no icon with Debian Buster on Awesome Windows Manager

**Comment by danrobi11** [comment]
Well it works if you run with --tray 
However, I was wondering if the icon was black on your end too?

**Comment by danrobi11** [comment]
Still no tray service with v1.3.0 (flatpak)
OS: MX 19.2 (patito feo) x86_64
SysV init version: 2.93
Debian GNU/Linux 10 (buster)
Kernel: 4.19.0-9-amd64
WM: Fluxbox

**Comment by psposito** [comment]
No tray icon on Artix Linux, XFCE Desktop

**Comment by ykne** [comment]
Several latest signal-desktop releases now show tray icon again. It used to be missing after electron upgrade.

**Comment by FatBirdie** [comment]
No tray icon on Cinnamon either

Its happened to many times now that Session is accidentally closed.
Hope we can see an update soon with 'close to tray'.

**Comment by trymeouteh** [comment]
No cinnamon tray icon. When I click the close button it closes the app when I expect it to minimised the app.

**Comment by FatBirdie** [comment]
Would be lovely to see an update for this feature soon.

**Comment by dm17** [comment]
@LuNiKoFf tray icon working for you these days? I'm using Awesome as well and session via flatpak.
