### ISSUE TITLE
Unable to link AppImage using Session ID located on my Android device

### ISSUE THREAD

**Issue by brainard52** [oxen-io/session-desktop#1101]
I installed 1.1.0 by downloading the APK from the website. I also downloaded the AppImage (1.0.7) and ran it on Fedora 31. I navigated to Devices > Link on my Android device. When I clicked "Sign In" and then "Link Device to Existing Session ID", I pasted my Session ID in and clicked "Link Device. This did nothing on my Android device, and the Desktop app didn't do anything either.

**Comment by galambborong** [comment]
I'm having the same issue (Android APK 1.1.0 being where my account is, Manjaro 20.0, XFCE with Session v1.0.7 being where I am attempting to link).

**Comment by KeeJef** [comment]
We have updated Session with a new Session Desktop and Android version, are these issues still persisting?
