### ISSUE TITLE
Replace 1024x1024 icon with scalable icon

### ISSUE THREAD

**Issue by jagerman** [oxen-io/session-desktop#1103]
**Describe the bug**
The 512x512 and 1024x1024 images included in the package are blurry, obviously upscaled images.  The source code contains a "icon_1024.png", but this is also upscaled *and has resolution 1008x1008* (which is surely not helping since it has to be upscaled *again* from there to 1024x1024 for the installed icon).  At a guess I'd say they are generated from the 256x256, but if so they should just be dropped and let the OS upscale from the largest available (and also save a pointless 200kB from the installed contents).

Also I notice that the install .deb does not contain a scalable icon at all: if possible please include the .svg icon in the package instead of the 512/1024 sizes, which will likely look better than any of the presized `png`s.

**Screenshots or Logs**
The following is a 1:1 (not locally scaled) portion of the icon:

![image](https://user-images.githubusercontent.com/4459524/80283643-90087300-86ef-11ea-8633-1cef3f3d8557.png)

**Comment by Bilb** [comment]
Electron does not seem to be able to use .svg files for app icons. https://www.electron.build/icons

the tool we use (electron-icon-maker) is indeed using as base icon the blurry 1024px one so I updated that image with a non scaled up one. https://github.com/oxen-io/session-desktop/pull/1738
