### ISSUE TITLE
Feature request: reddit style posts + threading in private/open groups

### ISSUE THREAD

**Issue by alahj** [oxen-io/session-desktop#1119]
Right now, posts to the groups are made in a single stream.   This makes it hard to find/follow threads of interest (especially if a group gets above a certain size).  IMO, it would be better if there were reddit style lists of post titles with threaded comments underneath.

**Comment by KeeJef** [comment]
We have discussed threading quite a bit internally, and most of the time we have come to the conclusion that it does not fit the UX we are aiming for in Session. Threading tends to suit applications that are used in professional/workplace environments like Slack. 

But i will leave the issue open for any compelling arguments to be made.

**Comment by alahj** [comment]
Speaking for myself, I find that apps that require me to filter through endless stream of babble from strangers, most of which is not of interest to me, wastes too much time.  I also like to refer back to interesting threads and posts I make.   As a result, I don't participate much on those apps with the garden hose style of discussion (Discord, Telegram).  

If I may be so bold, whats wrong with Signal being like Slack? (Which isn't as good as Reddit, but better than Discord, Telegram.)

**Comment by KeeJef** [comment]
Closing this because it doesn't match well with the current UX we are trying to build which is more focused towards competing with Telegram/Signal/Whatsapp

**Comment by secularaloha** [comment]
This is too bad. Threaded conversations could be a feature that takes Session above the others. This is one of the features that makes Slack better than any other messenger by far.

So what if Signal/Telegram/WhatsApp add threaded conversations, then Session will follow?

If Session is really competing against Telegram/Signal/WhatsApp, then threads should be considered.

Telegram: https://core.telegram.org/api/threads

Signal: https://www.androidpolice.com/signal-slack-threads-android/

WhatsApp: https://tech.hindustantimes.com/tech/news/whatsapp-rolls-out-chat-threads-to-beta-testers-71616677082662.html
