### ISSUE TITLE
‘Error handling incoming message’ after deleting contact

### ISSUE THREAD

**Issue by Brice-W** [oxen-io/session-desktop#1121]
**Describe the bug**
On Desktop, if I delete a contact and that contact then writes to me, I receive a few times ‘Error handling incoming message’

**To Reproduce**
B = any platform

Desktop is friend with B
Desktop deletes B
B messages Desktop
Desktop receives ‘Error handling incoming message’ a few times

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.
<img width="298" alt="Screen Shot 2020-05-07 at 10 40 30 am" src="https://user-images.githubusercontent.com/62363622/81241971-325d1a80-904f-11ea-86be-f020d3181990.png">

**Other information (please complete the following information):**

* Device: Mac
* OS: MacOS 10.15.4
* Session Version or Git commit hash: 1.0.7 or commit f9c13e4018c33a478171fbf63b2116ed69444c5f

**Comment by Bilb** [comment]
Shouldn't happen anymore with our new Protocol
