### ISSUE TITLE
[Mac] Session just keeps telling me to quit the program and update

### ISSUE THREAD

**Issue by mogspls** [oxen-io/session-desktop#1165]
For some reason it just keeps telling me that there's an available update of Session on Mac, then when I click update, it doesn't relaunch, and I'm not able to send messages.
<img width="893" alt="Screen Shot 2020-06-06 at 8 45 15 PM" src="https://user-images.githubusercontent.com/44018580/83944502-89186880-a836-11ea-8f1a-c39b670ca92e.png">

[Update] I just had to restart my mac and it fixed itself for some reason. Sorry for bothering you guys

[UPDATE] NOPE IT WENT BACK TO NOT BEING ABLE TO SEND MESSAGES

**Comment by KeeJef** [comment]
Which version are you currently on? if the automatic update isn't working could you try manually updating by downloading and installing the latest release here https://github.com/loki-project/session-desktop/releases/tag/v1.0.9

**Comment by mogspls** [comment]
1.0.9

Thanks I'll let you know

**Comment by Marky-N** [comment]
This update function still doesn't work on Mac.

**Comment by Bilb** [comment]
Could you give 1.6.5 a try?

**Comment by Marky-N** [comment]
I believe it worked smoothly the update last update, but of course can't be tested without a new version of Session released or installing old version of Session.

**Comment by Bilb** [comment]
@Marky-N we are about to publish a new release. Let me know how it goes for the 1.6.6 upgrade

**Comment by Marky-N** [comment]
So, Pressed "Download" and chose "Restart Session" (which doesn't restart Session but only closes it). Starting Session manually, still old 1.6.5 version in use and instant pop-up to download new version.
Third time, the update went somehow through. Also seems manual closing of Session, compared to the Restart-button increases the chance of the update to go through.

**Comment by KeeJef** [comment]
Marking this as as resolved
