### ISSUE TITLE
spike in RAM usage and contant cpu processing

### ISSUE THREAD

**Issue by boistordu** [oxen-io/session-desktop#1202]
**Describe the bug**
constant CPU processing between 5 -8% on a 7Y75 intel cpu (I know low end) but while doing nothing at all. I don't remember doing that before. 
Because of this constant CPU processing, RAM is building up. I let it run a whole night and ended up with 1.5G taken by session.
 

**To Reproduce**
Nothing in particular.
For the moment I'm investigating with another team a bad interaction between bitlocker, glasswire and kaspersky. Maybe it is related but I highly doubt so.  Session is calculating something, I guess some routes, again and again

**Screenshots or Logs**
https://www.dropbox.com/s/06hlmg7ptjfrrqa/log.log?dl=0
I don't know if it's safe or what kind of information these logs have since it is 7G I didn't open it. 
If you can't download it right away it's maybe because I'm still uploading it. 
I don't know either from when it has data. But it could be useful to rotate logs more often if it is a several weeks or months of data inside.

**Other information (please complete the following information):**
Bitlocker is activate ,most of the kaspersky components besides the firewall are deactivated for the moment due to investigation.
* Device: [e.g. PC, Mac] PC
* OS: Windows 10 Pro [version 10.0.19041.329]
* Session Version or Git commit hash:
1.0.9

**Comment by Mikunj** [comment]
Thanks for the report, we'll be looking into this shortly :)

**Comment by henk717** [comment]
Can relate on my Majaro KDE laptop which has a 4200M CPU.
The high CPU usage seems related to the web rendering portion of the electron app, and high CPU and ram usage is consistent with other electron apps i have tried that suffer from this.

Minimizing the program reduces the CPU usage significantly and on my systems the FPS of minimized apps gets limited, this might mean its related to the rendering portion directly.

It may be worth researching options that can be used to limit the resource usage of the chrome stack embedded in the app itself as it would likely cure both the CPU and the RAM usage.

**Comment by HassanZahin** [comment]
It would be better if session desktop switches to qt or something similar. Web apps always suffer from inefficient use of given resource.

**Comment by dkleehammer** [comment]
Same on System76 Lemur Pro with Pop OS.

**Comment by boistordu** [comment]
Even with the new versions? 
It s probably a problem with electron anyway

**Comment by Pingmin** [comment]
I found this :

Session on Linux, top's memory, res: 670M, virt: 60G

![20210913-the-memory-usage-of-session-desktop-on-linux](https://user-images.githubusercontent.com/836846/133187826-b9fd0fe6-a30c-4a41-85c1-6bbfb6557e64.png)

**Comment by Bilb** [comment]
Closing this in favor of #1555
