### ISSUE TITLE
[Feature Request] Ability to paste an image from the clipboard into a message

### ISSUE THREAD

**Issue by gitmaker032** [oxen-io/session-desktop#1265]
Now you can only paste text from the clipboard. Considering how often you have to copy screenshots and pictures to the clipboard, the ability to paste images from the clipboard is sorely lacking.

**OS:** Windows 10
**Session version:** 1.1.2

**Comment by dang102** [comment]
really need this copy/cut/paste! with out it won't work for me!

**Comment by vincentbavitz** [comment]
Great idea!

**Comment by feroxaquila** [comment]
I came here to post the same thing. I've been in the need of this feature many times. Can I somehow upvote for this feature suggestion so it gets higher priority if more people are giving a vote?

**Comment by FatBirdie** [comment]
I don't like this idea at all. If it gets implemented, please add an option to turn it off.

**Comment by Bilb** [comment]
@FatBirdie you could just not press CTRL-V on the screen when this feature gets implemented. I mean, if you don't use it, you don't see it. No need to have an option to turn it off. Or am I missing something?

**Comment by klorophatu** [comment]
I would also like for this feature to be implemented!

**Comment by justusranvier** [comment]
This is the most noticeable missing feature of Session compared to other messaging clients.

**Comment by Kellegram** [comment]
Lack of this basic features is certainly a big negative, hopefully this issue will not get ignored.

**Comment by TheEvilSkeleton** [comment]
I agree.

**Comment by M09NST3R** [comment]
I probably send more pictures from clipboard than text-only messages, so this is indeed a big challenge

**Comment by Norbert80** [comment]
Implemented. Pasting images works in Desktop build v1.6.4. ==> This issue can be closed.

**Comment by xanoni** [comment]
> Implemented. Pasting images works in Desktop build v1.6.4. ==> This issue can be closed.

yes confirmed, it's working fine. Thank you.
