### ISSUE TITLE
Audio Notifications

### ISSUE THREAD

**Issue by ITwrx** [oxen-io/session-desktop#1305]
i'm using the linux desktop appimage v1.2.1.

audio and gnome desktop notifications would be nice for me. No audio notifications is a deal breaker for usability, IMO. 

thanks

**Comment by DylanSijanivandi** [comment]
I have the same experience on the Mac version. My workaround is to use the android version for notifications.

**Comment by Bilb** [comment]
@ITwrx this is more about audio notifications than just notification right?

**Comment by ITwrx** [comment]
@Bilb Yes, audio notification is more important to me (by a good margin) than visual desktop environment notification. I moved to xfce on my main workstation anyways so the gnome notification is not that important to me at all anymore. :)

**Comment by ITwrx** [comment]
it's pretty funny that i didn't even mention that i'm running fedora (then 33, now 34) in my OP.

**Comment by henk717** [comment]
Any plans on adding this? It is my primary reason I am unble to use Session as my primary messenger since I keep missing messages all the time. Element by comparison has a notification sound inside the app and I never miss it. If Session has its own built in notification sound instead of relying on a non-existant OS notification sound i would no longer be missing messages.

**Comment by rauldipeas** [comment]
We really need this feature, please implement it.

It's something so complicated?

**Comment by scorpius2k1** [comment]
+1 to this feature request opened for over 2 years now. Linux desktop app notification pops up, but no audible sound (event sounds are enabled on my system). This is true for all desktop environments (KDE, XFCE, OpenBox, i3, etc). For comparison, Signal messenger plays notification sounds properly. This is a critical feature for most to have an audible notification.

**Comment by ITwrx** [comment]
Also, this is a big deal for privacy, as typical phone OSes (especially as typically used) are fundamentally insecure/untrustworthy. FOSS desktop OSes can be much better. This means if Session really cares about privacy/security, then FOSS desktop OS should be a high priority, even if there are less users to attract. Incomplete FOSS desktop support in a way that prevents practical/basic usage is not a good look for Session, and i doubt i'm the only one to think of it this way. Not to imply any negative motives of Session/Oxen. I'm just saying that if you want users to trust the software/devs, privacy/security has to trump popularity.

**Comment by ITwrx** [comment]
@Bilb great news. thanks for your work. will be looking for the next release to start trying out session for real world use.
