### ISSUE TITLE
Sessions doesn't run on mint 20 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by dang102** [oxen-io/session-desktop#1310]
**Describe the bug**

**To Reproduce**

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac]
* OS: [e.g. Ubuntu 16.04, Windows 10]
* Session Version or Git commit hash:

**Comment by dang102** [comment]
Still not working !

**Comment by dang102** [comment]
Seem like nothing work ive tryed so many thing it don't work in mint 20 work everywhere else!

**Comment by Bilb** [comment]
1.6.10 works fine on my mint 20 vm
