### ISSUE TITLE
[Feature Request] Add option to use system theme

### ISSUE THREAD

**Issue by vherrmann** [oxen-io/session-desktop#1328]
Now with the introduction of the light mode, i would love session to switch between dark and light side dependent on my system's theme.

**Comment by KeeJef** [comment]
If you are working on this as a good first issue

Please use the same copy from mobile in the Settings menu:

Setting Header: **Auto night-mode**
Copy: **Match system settings**

Location: Between Themes and Zoom Factor in Appearance
Toggle & Padding: As per settings in Permissions
