### ISSUE TITLE
Define a standard name for the AppImage (remove release numbers)

### ISSUE THREAD

**Issue by invalid-error** [oxen-io/session-desktop#1369]
It is a common practice to add product release numbers and infos to the installer name.
like: _session-messenger-desktop-**linux-x86_64-1.3.1**.AppImage_

From a user point of view it has limited benefits when the AppImage has an auto-updater.
In addition, it has one disadvantage when you add a desktop app launcher since you have to fix the file name for every update.

**Comment by Bilb** [comment]
Usually, AppImage have the version in the filename and we want to keep it that way.
You can probably make your Desktop App shortcut be something like
```
[Desktop Entry]
...
Exec=sh -c "sh -c /path/to//session-desktop-linux-*.AppImage | sort -V | tail -1"
```

**Comment by curt-wise** [comment]
Operating System: Kubuntu 22.10
KDE Plasma Version: 5.25.5

1. You can open the application launcher which is placed in the left bottom.
2. Go to "Menu Editor"
3. Go to internet and add a new item
4. You can put the name of the app as "Session"
5. The [icon](https://github.com/oxen-io/session-desktop/blob/clearnet/images/session/session_icon.svg)
6. And the command `/home/<user>/Programs/session-desktop-linux-x86_64-*.AppImage`
