### ISSUE TITLE
no updates in groups on one windows host

### ISSUE THREAD

**Issue by boistordu** [oxen-io/session-desktop#1386]
**Describe the bug**
on one of my PC hosts the messages isn't going through for my groups. But only the groups, the private messages are doing fine for example and I can send messages to the groups from this host and they are receiving it.
Apparently in the logs it says that it can't reach the ratchet ID from the groups? But the other PC can so....

* Device: PC
* OS:win 10 pro 2004
* Session Version or Git commit hash: 2f5072c3178d93e9a3f54457001c6c1e223b3fdc
[log.log](https://github.com/loki-project/session-desktop/files/5473585/log.log)

**Comment by boistordu** [comment]
by the way your messenger is still noticed by defender as pua coinminer

**Comment by boistordu** [comment]
small update: 
it does happen also on my other windows hosts connected to the same groups. not the iphones for example

**Comment by boistordu** [comment]
Si no one knows why apparently this host can't get groupid etc as the error messages are mentioning ?

**Comment by boistordu** [comment]
Still happening with the new version 1.4.1

**Comment by KeeJef** [comment]
Im not sure i understand your error report, Is this for a closed group or open group?

**Comment by boistordu** [comment]
It s for private groups. What don t you understand in the error log @KeeJef ?

**Comment by boistordu** [comment]
KeeJef the problem has gotten worse to th point I can t text my friend anymore rom my iPhone or my pc. He has an android, I can text him wih another android. 
I can text between all my peripherals.

Friend session 
058f1ca105dc44cfc2d0a118a2528befaafb50018b3cd6e5f6cc7de71efc010700

One of my session
059014ee179b060799e0e3e13ed4994a057e5c3d4ac78812f430b3091e76aed472

**Comment by KeeJef** [comment]
are you running the same account on multiple devices?

**Comment by boistordu** [comment]
@KeeJef  No all different accounts as requested by your message/guidelines saying that you've deactivate this option because too buggy at the moment.
We have made several tests. It seems that some of my hosts have direct access to his account and several have not like the one I have stated before. 
The one that does not have access to it, they can't message him at all

**Comment by KeeJef** [comment]
Lots will be changing over the coming weeks with 1-1 messaging and closed groups , i suggest you wait for those changes, which are likely to fix this error

**Comment by boistordu** [comment]
Okey no problem. Hope to get to it soon then.thanks

**Comment by Bilb** [comment]
Closing as this looks fixed. Feel free to reopen if that's not the case
