### ISSUE TITLE
can't install new 1.4.0 at one point it was looking for one drive I dont use ??

### ISSUE THREAD

**Issue by dang102** [oxen-io/session-desktop#1389]
**Describe the bug**
can't install new 1.4.0 at one point it was looking for one drive I dont use ?? Say i don't have accsses! I can't get on
at all now linux or windows!

![image](https://user-images.githubusercontent.com/20941959/98606913-18c6b500-22b6-11eb-8f66-05657fdb447d.png)

**To Reproduce**
don't know anymore that try to install it!
**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac]
* OS: [e.g. Ubuntu 16.04, Windows 10]
* Session Version or Git commit hash:
Sorry im on windows 10

**Comment by Bilb** [comment]
Is that still the case on 1.5.0?
