### ISSUE TITLE
Sessions ID won't send or receive new session

### ISSUE THREAD

**Issue by toomuchacid** [oxen-io/session-desktop#1402]
Debug Log:
https://debuglogs.org/92b5ef07081edefda207b128cfb15f736e4fb5dc6deb01d8c2edd80688c6d295

**Comment by KeeJef** [comment]
What version number are you running?

**Comment by KeeJef** [comment]
Try and restart, we did find and issue with the seed nodes giving out inaccurate Service Nodes

**Comment by dang102** [comment]
Reset only works sometime and/or may have to restart many time till it works been many ver. doing this!! Was in the Linux ver. now its doing it on windows ver. and some phones!

**Comment by Bilb** [comment]
Hey does this still happen on 1.6.0?

**Comment by KeeJef** [comment]
Closed, need more info
