### ISSUE TITLE
Join open group

### ISSUE THREAD

**Issue by FatBirdie** [oxen-io/session-desktop#1413]
Text field for adding URL allows for line break, which seems not allowed when entering an URL for group.

**Comment by Bilb** [comment]
@FatBirdie Can you enter a line break just by typing ALT+Enter or we are talking about a copy pasted value with a line break included?

**Comment by FatBirdie** [comment]
Hey @Bilb 
No, does not seem possible to do a linebreak in the text-field by hand, only when copy/pasting a selection of text containing a linebreak.

**Comment by Bilb** [comment]
Should be fixed on 1.4.7. Feel free to reopen if not
