### ISSUE TITLE
(Feature Request) My idea of a perfect messaging app.

### ISSUE THREAD

**Issue by Synkstar** [oxen-io/session-desktop#1414]
Here is a list of features:
- Bot support
- Large group chats like discord servers with roles and permissions etc.
- End to end encrypted and fully private.
- Ability to send files directly to trusted people with unlimited file size. Or proxied over some sort of network.
- Has a public profile.
- Screen sharing.
- Easy to use for even basic computer users.

The idea is basically everything that discord has but fully private. This is an ideal app because Ive never seen a private messaging app with those sorts of features. The closest one Ive seen is keybase they have the idea of the encryption down with bots but are missing lots of other stuff and arent fully opensource. In an ideal world open source would be a legal requirement and privacy should be a default but the problem is large corporations etc control the internet and want everyone's data. 

This would be possible to make but would be extremely hard without lots of people involved.

I do not expect this to actually happen but if it does it would definitely become the most popular chatting app. I cant do something like this alone personally and it would have to be open source anyways. 

This would solve the problem of the censorship on these chatting apps to if you made it like you just block the person if they are being mean instead of having to report and ban them. Isnt censoring someone for saying something technically violating the constitution if your in the US. A tech company can't uphold the constitution correct me if im wrong. Its called free speech...

**Comment by LorisTecnology** [comment]
great idea

**Comment by Synkstar** [comment]
Thanks. I think I figured out why they are able to censor you. Basically its because they own everything you post legally as you agree to this in the TOS. But I'm pretty sure the constitution would be above stuff like that so its kinda little bit of a grey area to me.

**Comment by KeeJef** [comment]
We are working towards some of these features as listed in other issues, going to close this for now
