### ISSUE TITLE
[Question] Which TCP/UDP ports must be open?

### ISSUE THREAD

**Issue by beantaco** [oxen-io/session-desktop#1415]
In order to make Session Desktop function properly (ie: send/receive messages and be anonymous/private/secure):

1. Which TCP/UDP ports must be open?
2. What issues can occur if not all required ports are open?

Hopefully answers to these questions will be helpful for system administrators. Hardening a firewall, by dropping all traffic by default, requires knowledge of what ports are required for all software that runs over networks.

For example, Tails blocks most traffic other than Tor, using a firewall that has a default policy of drop. In order to make Session work in Tails, knowledge of Session's required ports may be required. See #1139.

**Comment by neuroscr** [comment]
443 TCP outgoing for the seed nodes, and 22021 TCP outgoing for more snode comms

**Comment by beantaco** [comment]
UDP port 53 is also required. I suspect Session performs DNS queries for some reason. *Aside: This means system administrators cannot make Session work and block UDP port 53 at the same time. In contrast, Tor does DNS queries through Tor, not on UDP port 53.*

I allowed just UDP port 53 and TCP ports 443 and 22021 initially, but Session doesn't start up or send/receive messages reliably.

In addition to the above, I had to allow a very wide range of TCP ports between 19000 and 65535. The ports used appear to be mostly between 20000 and 24000.

I guess that if only some required ports are allowed and other ports are blocked, that will harm anonymity since Session will only be able to connect to certain nodes and not others. If this is true, all ports that nodes may use must be allowed.

Is there some kind of requirement or standard for nodes to use TCP ports within a certain range? Lastly, is this information documented anywhere?

**Comment by danrobi11** [comment]
> having to allow a very wide range of TCP ports between 19000 and 65535 

Thats far from ideal. We need the ability to set specific udp/tcp ports, like i2p.

**Comment by danrobi11** [comment]
Can we expect proper port config for session any time soon ? 

Im still waiting for that in order to be able to use session :/

Thanks!

**Comment by neuroscr** [comment]
It’s controlled by service node operators. There’s nothing you can control client side regarding this.

**Comment by danrobi11** [comment]
@neuroscr Thanks! At least now I'll no longer wait for nothing.

**Comment by beantaco** [comment]
@neuroscr Thank you!

1. What constraints on TCP/UDP port numbers must snode operators currently follow, if any?
2. Given Session has no control, what is the best way forward to constrain TCP/UDP port numbers to a specific set of values?
