### ISSUE TITLE
[Feature request] list of blocked Session IDs (import / export / optionally subscribe a ID-list)

### ISSUE THREAD

**Issue by invalid-error** [oxen-io/session-desktop#1422]
It will be just a matter of time when spammers, trolls and haters find their way to Session. In order to protect users it would be very useful to have a possibility to import / export blocked ID lists.

Ultimately, Session should offer a subscribe option to auto-update blocked lists. When implementing this feature a white list is also mandatory to allow users to explicitly override a blocked ID. 

Needless to say, this will never be perfect but a must have feature for the future.

**Comment by KeeJef** [comment]
I don't think this is the right way to go about this, distributing block lists is going to be cumbersome in the long run and probably not particularly effective. Our current thinking is to let the UI split messages between message requests and trusted messages, new users who message you for the first time would go into the message request section of the UI, and users you already have established conversations with would go in the regular conversations section. This minimizes the viability of spam (kinda like having a spam folder)
