### ISSUE TITLE
Unable to Install desktop client on windows even with Administrator priviliges

### ISSUE THREAD

**Issue by Sachin7878** [oxen-io/session-desktop#1426]
**Describe the bug**
Installer throwing message of insufficient privileges' to even run the installer. 

**To Reproduce**
Double click on desktop installer or Run as administrator.

**Screenshots or Logs**
Error thrown:
![image](https://user-images.githubusercontent.com/22257773/104129725-66819b80-5393-11eb-9b25-9fd322bdc03d.png)

**Other information (please complete the following information):**

* Device: PC
* OS: Windows 10
* Session Version or Git commit hash: 1.4.4

**Comment by anevaiopvn** [comment]
I'm having the same problem. Do you have Windows Defender on and PU protection enabled? I suspect it's because Windows Defender (or some other antivirus?) identifies the installer as a Potentially Unwanted Program.

**Comment by tgburgin** [comment]
![image](https://user-images.githubusercontent.com/3825172/112112724-ca9fb780-8bad-11eb-8eca-3c039e3620dd.png)
Anything you can do to resolve this? Not great having it identified as a CoinMiner (which I really hope it isn't...)

**Comment by KeeJef** [comment]
Session is not a coin miner, Windows defender is incorrectly flagging the software, probably because of some of the cryptographic operations we perform to prevent message spam on the network

**Comment by M09NST3R** [comment]
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by tgburgin** [comment]
i've filed a submission but heard nothing back. I don't know if you'd expect anything unfortunately.

**Comment by KeeJef** [comment]
Closing this as more information is required from OP
