### ISSUE TITLE
Group duplicate

### ISSUE THREAD

**Issue by FatBirdie** [oxen-io/session-desktop#1429]
After using the group function for a while, people were starting to get issues with messages not being delivered or being delayed. Not sure if this is the same as been reported before, but all of the sudden a duplicate group had started from nowhere and members of previous group were thrown in there and the old group is still ongoing.
We now have two groups with the same name and users for some reason.

**Comment by KeeJef** [comment]
Yeah, if everything goes well we are completely overhauling close groups on ~Tuesday 19th, should fix these issues with messages not being delivered and duplicate open groups being created, keep an eye out for the new release

**Comment by FatBirdie** [comment]
@KeeJef Lovely!

**Comment by Bilb** [comment]
@FatBirdie Did you recently got that issue again?

**Comment by FatBirdie** [comment]
@Bilb Haven't forgot about the post, but unfortunately I haven't had the chance to test it out again. The people who were involved in the group chat at the time ditched Session after concluding it was buggy. If I'm ever able to update this for you, I will.
