### ISSUE TITLE
white desktop screen

### ISSUE THREAD

**Issue by d0ubl3puls4r** [oxen-io/session-desktop#1431]
I installed the Session desktop software on Windows 7, when performing the test by exchanging messages with my cell phone, the software screen went white without the possibility of interacting with the tool, I don't know if this problem also affects the Linux version, I haven't tested it yet but I would like you to check this problem, because it makes the software via desktop unusable

**Comment by Bilb** [comment]
Could you send me the logs after the white screen happened?
* Press ALT to show the top menu bar
* Tab `View`
* Select `Debug Logs`
And copy paste in a file and upload here

Thanks

**Comment by yanolol** [comment]
![image](https://user-images.githubusercontent.com/9301076/105077433-46c13600-5a6b-11eb-9d03-55c98a312577.png)
same error here

Windows 10

**Comment by yanolol** [comment]
I create new account to tests and when i send the message return this screen, we cant get log after.

**Comment by Bilb** [comment]
I just found a bug related to this. Can you tell me on what language is your computer?

**Comment by gushk** [comment]
same here

**Comment by Bilb** [comment]
@gushk are you linux?
If yes, could you start starting the app with `LANGUAGE=es yarn start-prod`
This bug seems to be related to the locale being `es-419` which is not handled by one of the library we are using. A fix will be in the next release
