### ISSUE TITLE
password length inconsistency(?) and locked out

### ISSUE THREAD

**Issue by ITwrx** [oxen-io/session-desktop#1446]
**Describe the bug**
i have a password saved in a text file as my session password. it's 98 characters long. Now, when trying to enter my password, i get an error that `the contents of the clipboard exceed 64 characters`. if i enter the first 64 characters it says `invalid password`. i see in #940 it says that the max length is 32. If i trim my saved password to 32 characters i get `invalid password`. What is the actual password length max? did it change through versions? or it just didn't used to say anything and silently trim the password to whatever the max was?

**To Reproduce**
use some older version and set a longer password than the current version accepts. try to login with your password.

**Other information (please complete the following information):**

* Device: x86_64 desktop computer
* OS: Fedora 32
* Session Version or Git commit hash:
session desktop linux 1.4.4 appimage

**Comment by ITwrx** [comment]
now, 1.4.6 asks me if i want to `reset the database`. what database?

**Comment by ITwrx** [comment]
so, i reset the DB and now when looking at the sign in form in 1.4.6 it asks for a recovery phrase (i'm pretty sure the old version didn't have that, or i would have saved it like i save all my other seeds) and says the password needs to be between 6-50 characters long...

I understand that session is under heavy development, but there should be some consistency and a path between versions so people don't lose their display names, like i seem to have...

**Comment by Bilb** [comment]
I just update the password logic and made all the length the same. 
Also, we still disallow setting a password of more than 64 chars, but when trying to unlock or change your password, you will be allowed to enter a 64+ char password. So you can exit your locked out state.

This will be on the next release

**Comment by ITwrx** [comment]
great, thanks! out of curiosity, what is the reason for the 64 char limit?

also, i hope the GUI tells people when they are first creating their password what the char limit is.

**Comment by Bilb** [comment]
@ITwrx yes the user will be warned if he tries to enter a 64+ char password on registration, or setting, or updating a new password.
64 char is arbitrary. We put 32 first but it was not enough for some users.

**Comment by ITwrx** [comment]
@Bilb unfortunately it returned "invalid password". I seriously doubt i have the wrong password stored in my text file. 

any suggestions? or i just need to let my display name stay locked in the ether, and pick a new one?

thanks
