### ISSUE TITLE
[Feature Request] Message pane snap to bottom or stay at scroll height

### ISSUE THREAD

**Issue by reactshow** [oxen-io/session-desktop#1454]
On desktop (don't know about mobile) in the message pane (the right side of the Session app) everything jumps once a new message arrives if you are not scrolled to the bottom of the specific session/chat. This is confusing/annoying when reading messages and causes one e.g. to click/reply to wrong messages. The pane should maybe stay snapped to the bottom or stay at the specific scroll height/message.

* Device: [desktop]
* OS: [Ubuntu]

**Comment by Bilb** [comment]
https://github.com/oxen-io/session-desktop/issues/837
