### ISSUE TITLE
Session Desktop on MacOS taking big amount of CPU

### ISSUE THREAD

**Issue by Marky-N** [oxen-io/session-desktop#1455]
**Describe the bug**
When using Session Desktop on Mac, it uses constantly 10-15% of CPU.

**Screenshots or Logs**
<img width="943" alt="Screenshot 2021-01-22 at 16 36 30" src="https://user-images.githubusercontent.com/77722427/105810680-14a45c80-5fb4-11eb-83ee-5d95f16c6f58.png">
<img width="709" alt="Screenshot 2021-01-27 at 9 05 58" src="https://user-images.githubusercontent.com/77722427/105955606-3b7b9500-607f-11eb-8303-5dcf4411ba9a.png">

**Other information (please complete the following information):**

* Device: MacBook Pro 
* OS: MacOS 11.1
* Session Version or Git commit hash:
<img width="496" alt="Screenshot 2021-01-26 at 8 56 49" src="https://user-images.githubusercontent.com/77722427/105810942-7a90e400-5fb4-11eb-9103-d4b49f4236f8.png">

<img width="302" alt="Screenshot 2021-01-26 at 8 55 10" src="https://user-images.githubusercontent.com/77722427/105810798-4289a100-5fb4-11eb-966b-c121bb62bd02.png">

**Comment by starlightromero** [comment]
I'm on ElementaryOS. Session uses the same 10-15% of CPU on my system. Unfortunately, Electron (which runs on chromium) is a resource intensive framework. This isn't an issue that is easily solvable. It would require a whole re-write of the code at a lower level language

**Comment by neuroscr** [comment]
And there are background timers that make sure new messages haven’t come in and such. Quite a lot going on infact.
