### ISSUE TITLE
Auto Day / Night Theme

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-desktop#1456]
Hi, you have Day / Night theme, this is  awesome but not have function "Auto change theme by time in settings"
I think it's great if the theme switches itself (those who have enabled the function in the settings) and you can specify the specified time in the settings, than do it yourself.

** example ** 
 if day time,  use day theme
 if night time, auto change to night theme
 
 P.S it would be great to see the same on the phone version as well

**Comment by KeeJef** [comment]
If we do #1328 users can install something like this https://github.com/Armin2208/Windows-Auto-Night-Mode and Session would change modes according to the time. So closing this in favor of doing #1328

**Comment by xbvrhlmb** [comment]
the can work in Linux?
