### ISSUE TITLE
Show the status of connections to Loki network

### ISSUE THREAD

**Issue by beantaco** [oxen-io/session-desktop#1462]
Session Android has a simple display of network access that shows 3 hops and each hop's country.

The Session Desktop client (version 1.4.5) shows no information about the client's connection to the Loki network.

For diagnostic purposes, educational purposes and letting the user know what is actually going on, I believe Session Desktop should show the status of Loki network access. Whether that is the number of onion paths established, connection status ("disconnected", "connecting", "established", ...), or otherwise, it would be good for users to know about their Loki network access.

For example, there is an issue that hitting the ENTER key to send a message does and shows nothing, the ENTER key appears to have no effect (see #1272). This issue may be caused by connection issues to the Loki network, but there is no visual feedback in the Session Desktop client UI at all to indicate what the problem may be. Assuming sending messages requires establishment of connection to the Loki network, the user would benefit from seeing connection status to the Loki network before they attempt to send messages.

Removing useless clutter from the UI (moderate minimalism) is good, but hiding potentially useful information from the user (over-minimalism) makes for bad UX.

**Comment by FatBirdie** [comment]
@beantaco nice suggestion

**Comment by Bilb** [comment]
Closing this in favor of https://github.com/oxen-io/session-desktop/issues/1492
