### ISSUE TITLE
[Feature Request] Closed Group - control of the disappearing message timer setting

### ISSUE THREAD

**Issue by invalid-error** [oxen-io/session-desktop#1472]
Since closed group can be up to 100 members there should be A) an option which allows the closed group creators to assign members who have the permission to set the disappearing message timer or B) it should be just controlled by the creator only.

**Comment by KeeJef** [comment]
I think the model of a closed group is necessarily that you should trust all individuals in the closed group, since they have the ability to leak your messages, and kick anyone from the group. Not sure this fits with that model

**Comment by invalid-error** [comment]
If you have a closed group with your relatives yes. But I would say this is not the case for all closed groups.
A closed group have a owner - the creator - and he only should have the permission to set the timer. Optionally, she/he can grant permission to someone in the group but it should not be available to all by default.

I joined and created several closed groups and as soon as someone set / reset the timer it is a long ping-pong timer setting. That's why I made this issue.
