### ISSUE TITLE
Update 1.4.8 not Working

### ISSUE THREAD

**Issue by crop211** [oxen-io/session-desktop#1476]
**********

Hi Session,

I've had Session version 1.4.7 working fine for a while but your new update version 1.4.8 will not work at all.

I'm on MX-Linux 19.3 and both your deb and appimage versions of 1.4.7 worked.

Neither the deb or appimage of version 1.4.8 will start at all.

I first tried a simple update of my 1.4.7 deb installation but it didn't start so I uninstalled Session to try from scratch.

Even after completely removing all traces of Session, a new install of version 1.4.8 will not work.

Upon startup it creates a Session directory in .config, then an empty Dictionaries sub-Directory, then STOPS.

This happened with both the deb and appimage versions. I Cleaned out all Session traces between installs.

Version 1.4.7 creates, as expected, the fully filled out Session directory in .config and then WORKS.

This occurs on kernels 5.8.0-3 and also on my older 4.19.0-14.

So I've had to revert to version 1.4.7

If you have any suggestions please reply.

Thank You.

**********

**Comment by starlightromero** [comment]
This looks like a copy of #1471 . @Bilb updated and pushed a solution. Try downloading 1.4.8 and recompiling.

**Comment by crop211** [comment]
If Session has known that the deb and appimage files for 1.4.8 don't function for 2 days now why are they still online ?
BTW, thanks to starlightromero & Blib for solution suggestions, but I shouldn't have to recompile.

**Comment by Bilb** [comment]
The deb and AppImage 1.4.8 binaries have been updated. You can download them from the release page and they are up to date. no need to recompile

**Comment by crop211** [comment]
Thanks Bilb.
All's O.K. now. The new deb's working fine.
I'd mistakenly assumed that after fixing the first broken version 1.4.8 you'd have called it 1.4.8-1 or 1.4.9.
Never mind. I really appreciate your rapid response and fix.
Thank You.

**Comment by blinkenlight** [comment]
Seriously, WHAT THE FUCK. The windows desktop client does ABSOLUTELY NOTHING after logging in, no matter how many times I try to send a message. Is Session on desktop really fully broken? WTF?

**Comment by Bilb** [comment]
@blinkenlight just give a try. Session v1.4.8  is sending messages as expected for me on windows 10. Did you just create your account or what is an old SessionID?

**Comment by blinkenlight** [comment]
I'd like to retract my previous post - it does indeed work, just as soon as both me and my contact upgraded to the "new" IDs. It still seems disjointed from the Android client (ie. desktop messages only receive their replies on the desktop and vice-versa) but that's another issue. Sorry for getting a bit worked up, it was unwarranted...

**Comment by Bilb** [comment]
Are you talking about syncing messages sent from one device to another?
If yes, this is a work in progress, and is not officially supported yet. https://github.com/oxen-io/session-desktop/pull/1493

**Comment by blinkenlight** [comment]
Oh, I see. Yes. Didn't know that. Thanks!
