### ISSUE TITLE
Unexpected end of data

### ISSUE THREAD

**Issue by binex-dsk** [oxen-io/session-desktop#1477]
**Describe the bug**
When building, yarn gives this error:
```
Now using node v10.13.0 (npm v6.4.1)
yarn install v1.22.10
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
error An unexpected error occurred: "Unexpected end of data".
info If you think this is a bug, please open a bug report with the information provided in "/home/swirl/random/session-desktop/src/session-desktop-1.4.8/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**To Reproduce**
1. Attempt to `yarn install --frozen-lockfile`
2. observe

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem. ok [yarn-error.log](https://github.com/oxen-io/session-desktop/files/5921313/yarn-error.log)

**Other information (please complete the following information):**

* Device: some pc? do you want my model or what

* OS: Artix Linux
* Session Version or Git commit hash: 1.4.8

**Comment by Bilb** [comment]
@binex-dsk I gave it a go and couldn't reproduce the issue.
It's probably network related.

Here is what I did on completely new artix virtual machine (installed with `artix-cinnamon-openrc-20210101-x86_64.iso`)


```
sudo pacman -Sy 
sudo pacman -S git glibc python2  base-devel make
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

git clone https://github.com/oxen-io/session-desktop
cd session-desktop
nvm install 10.13.0
nvm use
npm install -g yarn

export PYHTONPATH=/usr/bin/python2
yarn install --frozen

```

And the `yarn install` finished.
Let me know if that helps
![image](https://user-images.githubusercontent.com/1544279/110397288-b051de00-80c5-11eb-897b-19ea5c3201a6.png)

**Comment by binex-dsk** [comment]
ok for some reason now it's working, but only when it's done the first time. If I try to `yarn install` again after already doing that once, its giving this error now

**Comment by binex-dsk** [comment]
ok that error isn't happening anymore for some reason but now its giving me this error
```
Done in 19.82s.
  • electron-builder  version=22.3.6
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=@journeyapps/sqlcipher@4.0.0, dtrace-provider@0.8.8, node-sass@4.9.3 platform=linux arch=x64
  • rebuilding native dependency  name=dtrace-provider version=0.8.8
  • rebuilding native dependency  name=@journeyapps/sqlcipher version=4.0.0
  • rebuilding native dependency  name=node-sass version=4.9.3
/home/swirl/random/session-desktop/src/session-desktop-1.5.0/node_modules/husky/lib/commands/install.js:20
        throw new Error(".git can't be found");
        ^

Error: .git can't be found
    at Object.install (/home/swirl/random/session-desktop/src/session-desktop-1.5.0/node_modules/husky/lib/commands/install.js:20:15)
    at Object.<anonymous> (/home/swirl/random/session-desktop/src/session-desktop-1.5.0/node_modules/husky/lib/bin.js:50:19)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
==>
```

**Comment by Bilb** [comment]
Did you clone the git repo or downloaded the source code? I cannot reproduce this by cloning the git repo.

**Comment by binex-dsk** [comment]
downloaded the release source tarball, I could do the git repo but I'm doing this for the `session-desktop` AUR package. Try it on the latest source tarball

**Comment by Bilb** [comment]
Ok, in fact we rely on the `.git` to build the app, as we display the latest version and commit on the settings page. 
So trying to build the app from the source code itself won't work. I just tried by checkout the latest release and it's working as expected.
```
git clone https://github.com/oxen-io/session-desktop/ -b master
cd session-desktop
git describe --tags # will print latest tag which should be the latest release
git checkout $(git describe --tags)
yarn install 
yarn grunt

```
let me know if that helps

**Comment by binex-dsk** [comment]
that fixed it thanks
