### ISSUE TITLE
Messages sent on mobile(Android) do not show up on desktop(MacOS)

### ISSUE THREAD

**Issue by nolyoi** [oxen-io/session-desktop#1479]
**Describe the bug**
I have the same keys on my desktop(Mac OS) and Android apps. When sending messages from the Android app, they do not appear in the conversation on the desktop. But, messages sent from the desktop appear in both just fine. I'm guessing this is a bug since they appear in one direction and not the other.

**To Reproduce**
Send from android app, check conversation on desktop app.

**Other information (please complete the following information):**

* Device: Mac and Android
* OS: MacOS and Android
* Session Version or Git commit hash: The latest releases for both apps.

**Comment by KeeJef** [comment]
Session does not officially support multi-device (Restoring the same Session ID on multiple devices) yet, we are working on official support for it right now which should resolve these issues
