### ISSUE TITLE
URL problem

### ISSUE THREAD

**Issue by FatBirdie** [oxen-io/session-desktop#1480]
Its probably a minor issue, but just noticed that URLs (from Odysee) I sent in private message did not become clickable on desktop (although the user on the other end, using mobile did see it as clickable).

This seems to affect all issues of URLs from Oddysee, guessing it has something to do with the URL format (assuming its either "@" or ":" that is causing the problem).
Grabbing a random video URL on the site: https://odysee.com/@AbridgedGoku:9/n64-retro-madness-on-twitch:9
Same issues with the channel URL: https://odysee.com/@AbridgedGoku:9

**Comment by Bilb** [comment]
Hi, yes currently the @ is not allowed in our URLs as it is causing issues on Windows.
In the meantime you can always enable link previews on your settings and the link previews will be generated with a clickable link. Your receiver will need link previews to be enabled too.

**Comment by FatBirdie** [comment]
Also on Linux
