### ISSUE TITLE
Add Setting to allow Enter key to break line OR send message

### ISSUE THREAD

**Issue by trymeouteh** [oxen-io/session-desktop#1486]
Please add a setting on desktop just like on mobile on weather the enter key will send the message or the enter key will break the line in the message.

**Comment by FatBirdie** [comment]
Or even better, like Signal, allow desktop users to enlarge the input box. When input box is regular it sends on enter, when its enlarged it line breaks.

**Comment by nooblag** [comment]
Or even better, add setting that configures a preference for CTRL+ENTER for sending, ENTER just for line breaks?

**Comment by mokkun** [comment]
Does the enter key work at all? At least on the macOS, hitting Enter or Cmd + Enter does nothing. I have to click on the send message button every time.

**Comment by Bilb** [comment]
I think doing what signal does would be better. Not having the compositionbox auto resize but just have two sizes.
- single line: Enter sends message
- 7 line displayed or so: Enter adds a new line character, and CMD+Enter or CTRL+Enter sends the message.

**Comment by KeeJef** [comment]
Relates to #2245 

If you are implementing this as a good first issue here is some additional information on how it should be laid out and what the copy should be.

**Setting info**  

**Header**: Enter Key
**Copy**: Function of the enter key when typing in a conversation.

**Option 1**: ENTER sends a message, SHIFT + ENTER starts a new line 
**Option 2**: SHIFT + ENTER sends a message, ENTER starts a new line

**Location**: In Conversation settings, under Autoplay Audio Messages
**Design**: As per Notification Content in Notifications Settings.
**Notes**: Option 1 should be selected by default


Below is a wireframe, however referencing Notification Content in Notifications Settings should provide a more detailed guide on the actual visual implementation.

![Screenshot_2023-02-14_at_4 48 06_pm](https://user-images.githubusercontent.com/27277414/218925743-e903bb66-ac6f-40b0-8937-73cc812cb7bc.png)

**Comment by KeeJef** [comment]
This is merged, setting will be available in next release
