### ISSUE TITLE
SMS & Phone Call Syncing

### ISSUE THREAD

**Issue by trymeouteh** [oxen-io/session-desktop#1488]
A cool feature Session could add which no other free open source app does is allow you to send and receive SMS messages and have outgoing or incoming calls from your other mobile devices like tablets and desktop devices. Session can use its encryption and Tor like IP cloaking technology to ensure the connection from your phone to your other devices when sending or receiving SMS messages or on a phone call is secure and private as it can be.

This can also make Session a SMS and Dialer app on Linux phones, making Session the all-in-one ecosystem for communication.

**Comment by KeeJef** [comment]
We dont intend to integrate SMS or phone calling functionality over GSM networks, Voice calling will be achieved over IP.
