### ISSUE TITLE
Linux Mobile Client?

### ISSUE THREAD

**Issue by trymeouteh** [oxen-io/session-desktop#1489]
Would be amazing to have the desktop client work on mobile linux devices with a good UI or a mobile linux client. This way even new Linux phone users wont miss out on Session ecosystem.

**Comment by JeffRockatansky** [comment]
This would be a nice feature for Mobile Linux users, like PinePhone, Librem or Fairphone owners.

And there are already around 7 to 10 valid mobile Linux distros.

**Comment by invalid-error** [comment]
see here:
**OPEN [Improve window sizing - support smaller window](https://github.com/oxen-io/session-desktop/issues/1304)**
CLOSED [Feature request: Responsive "desktop" client #1382](https://github.com/oxen-io/session-desktop/issues/1382)
I guess, this is almost all we need. Any rate _thumb up_ or _heart_ hopefully helps to get this in up in prio.

**Comment by KeeJef** [comment]
Closing this for #1304
