### ISSUE TITLE
Optional Import/Export Keystore file for Mnemonic seed

### ISSUE THREAD

**Issue by trymeouteh** [oxen-io/session-desktop#1490]
Jami allows you to import/export your Jami ID to a file which can be import again and as long as you do not lose your file or forget the password to unlock the file you can always recover your Jami ID.

Session could have a file import/export for its user accounts as an alternative to writing down a word phrase. This file could be a json, 7z, gz, etc. I would highly recommended this file require a password which will encrypt the file. And this import/export feature could be added to the app onboarding process.

**Comment by FatBirdie** [comment]
Why? Session has recovery words. Just put it in a text document?

**Comment by Bilb** [comment]
yes, your whole identidy is your mnemonic. Just store it anywhere you want with the encryption you like
