### ISSUE TITLE
Add Onion Path Status Indicator - Helps in Poor Networking Conditions

### ISSUE THREAD

**Issue by henk717** [oxen-io/session-desktop#1492]
**Bug Description**
When used on an unstable network such as a 4G network with a weaker connection, the desktop client will fail to establish a connection with the network. The client has no indicator if it is connected, so this is assumed on the fact that the sending of messages is not possible. You can type them, but you can't submit the message, no error is shown at this time. At the same time no incoming messages are received despite them being available (For example using Authora to trigger a message). The client seemingly never recovers from this state, and no indication is shown to the user that something is wrong other than being unable to submit a message. In contrast, i am not having reliability issues with the android client on the long term. Only moments where it will fail to deliver messages and clearly indicates it did so. The Android version does not suffer from this issue and recovers if disconnects or interruptions on the 4G occur, in Android's case the indicator will turn orange and then green again once the 4G stabalizes.

**To Reproduce**
The easiest method to reproduce this is using the client on a 4G connection if you are in an area where the signal does not have perfect quality and a link between the nodes may not be established in a reliable manner. It is most common when you just start the client as it will never allow messages and will never receive messages. It may take multiple restarts to get a working instance. I am unsure if this is replicatable on a good connection by for example disconnecting or otherwise throttling the connection as i at the time of writing do not have my usual connection at my disposal that Session works reliable on. Once i get a working instance this will remain reliable for a while, so i do not know if sessions break over time or if i am simply failing to receive messages in an otherwise working instance.

** Desired outcome **
There should be an indicator like the mobile version has that can show if you are connected to the session network, this is not in my client so i can not verify why it gets stuck or when and if my instance begins to break over time. And in case of a hindered connection the client should be able to recover from this on its own similar to how the Android version behaves.

**Other information (please complete the following information):**

* Device: Laptop connected to a 4G hotspot
* OS: Manjaro KDE , Appimage version
* Session Version or Git commit hash: 1.4.8
Tested on 4G, my phone is also configured to use my account, this normally reliably works side by side on good connections.

**Comment by Bilb** [comment]
This is included in the latest release
