### ISSUE TITLE
Use system libraries instead

### ISSUE THREAD

**Issue by binex-dsk** [oxen-io/session-desktop#1496]
Currently Session seems to package Electron and a few other libraries. This just causes unnecessary bloat and the system libs will usually be more up-to-date. Keeping an AppImage is a good idea, but for precompiled binaries it shouldn't be doing this. At the very least, allow this as an option or something, so when building we can choose between system or packaged libraries.

**Comment by nooblag** [comment]
Personally, I love it how session is shipped as an AppImage with all it's required dependencies and specific versions of those. Dealing with system libs is a headache!

**Comment by binex-dsk** [comment]
yes, and as I said, keeping the AppImage is a good idea. but for binaries it just doesn't make sense all the time. It should be given as a build option or something

**Comment by Bilb** [comment]
Keeping up with all the platforms is already complex enough
