### ISSUE TITLE
Message window scrolls way up

### ISSUE THREAD

**Issue by FatBirdie** [oxen-io/session-desktop#1510]
I'm confused to exactly how this would be reproduced as it happens inconsistently.
Sometimes when receiving messages, and in few cases when sending, the message window scrolls half way up through messages for no reason.

I don't know if this has anything to do with it, but I've noticed emojis almost always (or always) being part of messages when it happens.

This bug report might not be much of help, but still want to make the issue known. If I find out how to reproduce the issue, I'll update the post.

**Comment by FatBirdie** [comment]
Just want to update with,
I'm still experiencing this issue from time to time. Very sporadically, but it still happens.

**Comment by FatBirdie** [comment]
This issue is happening more and more.
Sending and receiving, the message window scrolls up to about half the scoll length and have to scroll down again, for no reason.

This is happening both on Windows and Linux.

**Comment by Bilb** [comment]
1.6.8 should help. Can you try and let me know?

**Comment by FatBirdie** [comment]
Will do,
if I haven't posted anything in a few weeks you can consider this fixed.
