### ISSUE TITLE
Messages sent via Desktop can't be seen in Mobile (Multi-device account)

### ISSUE THREAD

**Issue by Syakyr** [oxen-io/session-desktop#1511]
**Describe the bug**
Messages sent via the Desktop client is not shown in the Mobile client. However, messages sent via the Mobile client can be seen in the Desktop client.

**To Reproduce**
Type in a private chat using the Desktop client, check the Mobile client.

**Other information (please complete the following information):**

* Device: Linux AppImage
* OS: Pop_OS
* Session Version or Git commit hash: v1.4.9

**Comment by Syakyr** [comment]
v1.4.10 doesn't fix the issue (with v1.7.3 android mobile).

**Comment by Niezborny** [comment]
I believe I have a similar issue (v1.4.5 desktop, v1.7.3 android mobile). Set up an account on Android and synced on desktop. Messages received are visible on both devices. Messages sent (from Android) are only visible on Android.

**Comment by Syakyr** [comment]
Fixed on v1.4.11 (v1.7.3 android mobile).
