### ISSUE TITLE
Wrong order of messages while using multiple devices

### ISSUE THREAD

**Issue by klochden** [oxen-io/session-desktop#1513]
Session 1.7.2 installed on Android 11 Smartphone (Galaxy S 10 Plus) and Windows 10 Desktop (1.4.9). 
While chatting on windows Desktop (private chat), the messages on android, are shown in a completely wrong order.

**Comment by KeeJef** [comment]
We did make some changes to how messages were ordered between different devices in the latest releases, if you update to the latest version of Session on your devices is this issue corrected?
