### ISSUE TITLE
Apperance

### ISSUE THREAD

**Issue by depewzhang** [oxen-io/session-desktop#1514]
I installed Session both on my windows desktop and Ubuntu desktop, however, after the first run, the app will show nothing as in the attached picture.  I don't know how to fix that, and can find no solution, even if I uninstall.  Please help...  Thanks a lot.
![2021-02-24 14-30-51屏幕截图](https://user-images.githubusercontent.com/23442110/108957832-1cd3e280-76ad-11eb-939b-7386667ddb15.png)

**Comment by Bilb** [comment]
Hi @depewzhang could you try by starting Session from the terminal with the Language set to EN.
so 
`LANGUAGE=en session-desktop` for a deb install or
 `LANGUAGE=en <path to the appImage>` ?
Might be related to a locale setup on your computer.

**Comment by depewzhang** [comment]
> Hi @depewzhang could you try by starting Session from the terminal with the Language set to EN.
> so
> `LANGUAGE=en session-desktop` for a deb install or
> `LANGUAGE=en <path to the appImage>` ?
> Might be related to a locale setup on your computer.

Thanks for your help so much!  It finally works as you instructed.  Two more questions if you'd help also:
1) Should I start the app in Ubuntu from the terminal only?  It shows the same if I don't start it from terminal.
2) How should I use it in Windows 10?  Just the same problem in my Windows 10.
Thanks again!  :-)

**Comment by Bilb** [comment]
It's probably related to the locale you are using. Could you please share the logs here on the app startup and after the crash ?
You can see the logs by pressing CTRL+MAJ+i and on the console tab => save as.

For now, on ubuntu you will need to start the app from the terminal like this yeah. I will include a fix on the next release after I had a look at your logs.
It's probably the same issue for Windows.  I don't know how you can do the same on windows. If you can send me the logs I will see to make a fix for both platforms.

Thanks

**Comment by depewzhang** [comment]
For Windows, I'm not sure whether the log file is useful for you, but how can I send it to you?  Thanks a lot.  For Ubuntu, I'm still trying to find way to save the logs...

**Comment by depewzhang** [comment]
Please try the link to see the log for windows?
https://debuglogs.org/af3ac35da771840a892b0cb788588feaf56b45fed6ac517e21890d497f0b7446

**Comment by depewzhang** [comment]
Here is the link for Ubuntu log file:
https://debuglogs.org/4ae02d284d0a99c636d56b5cf14ac6e27bc490c8f74a695e5d3f0b34da1acd38

**Comment by KeeJef** [comment]
looks related to #1541

**Comment by snakyjake1** [comment]
Same issue on Flatpak. Was working, now not.

**Comment by Bilb** [comment]
@snakyjake1 
I got a fix on the 1.5.1 which included a fix and was reportedly working for some users.

Are you already on 1.5.1? 
If yes, can you tell we on what language is your OS?
and does the app start if you start it from the terminal with
`LANGUAGE=en session-desktop`

?

**Comment by depewzhang** [comment]
Thanks for all your effort.  The apps can now be initiated from the logo button.  However, two issues from my experiences:
1) Desktop on Linux: I can't send messages.  I can only type, and the words just remain in the input box but not be sent.
2) Both version (Linux and Windows) can't join any open groups.

Please keep on working, and really appreciate your supports as always.  :-)

**Comment by snakyjake1** [comment]
> 
> 
> @snakyjake1
> I got a fix on the 1.5.1 which included a fix and was reportedly working for some users.
> 
> Are you already on 1.5.1?
> If yes, can you tell we on what language is your OS?
> and does the app start if you start it from the terminal with
> `LANGUAGE=en session-desktop`
> 
> ?

I'm on 1.5.1
language=en
Flatpak
Same problem whether started from terminal or menu.
I've also tried:  flatpak run --env=LANGUAGE=en network.loki.Session
Log: https://pastebin.com/0ZdghHWX

The background is either white if I start with no other windows:
![image](https://user-images.githubusercontent.com/8312560/112328052-3009ac00-8c73-11eb-9fd5-2f3090febe00.png)

Or the background is a copy of whatever window is behind it:
![image](https://user-images.githubusercontent.com/8312560/112327954-18cabe80-8c73-11eb-8b77-0d5cd12d2852.png)

**Comment by snakyjake1** [comment]
Same issue on v1.5.2

**Comment by Bilb** [comment]
At least it's not an issue with the locale. 
The issue with the background being whatever is behind the windows makes me think the app is hanging somewhere, but the logs does not give much details.
Just tried flatpak run on my ubuntu and it starts correctly. 

You are on ubuntu? Which ubuntu version? 
You just installed the app and did not manage to create an account right? Or you might have a leftover of data from an old install? If you did create an account already, did you try create a new account or restoring your seed already?
flatpak session config folder is at `~.var/app/network.loki.Session/config/Session`

**Comment by snakyjake1** [comment]
The AppImage works.
Wonder if this is specific to Flatpak.

Next, I deleted the flatpak session folder and reinstalled Session.

Not sure if these Session/Electron log messages mean anything, but it does look like a "render" and I can't see the menu bar either.

> (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently \"false\".  It will change to be \"true\" in Electron 9.
>
> (electron) 'isMenuBarAutoHide function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.

Additionally, looks like there was a recent Electron update.

**Comment by snakyjake1** [comment]
# SOLUTION

I run machines via Virtualbox.  I am able to get Session to work with **3D Acceleration disabled**.
