### ISSUE TITLE
Session does not run on Tails 4.15.1.

### ISSUE THREAD

**Issue by DonW16** [oxen-io/session-desktop#1520]
When executing session on Tails the following error appears.

![session tails](https://user-images.githubusercontent.com/33807357/109182984-64c63880-7785-11eb-80be-ebfc2c041be5.png)

**Comment by beantaco** [comment]
The error you experience has been reported in other issues. See issues #1058, #1073 and #1418.

The workaround that was suggested is add the `--no-sandbox` option. However, this is a hack, not a solution. If the sandbox really provides no value, it should be removed. Further, issue #1058 currently suggests adding `--no-sandbox` doesn't necessarily work.

Though not related to this issue, even if you successfully launch Session in Tails, be aware that Session will not be able to get through the Tails firewall that blocks most traffic except Tor. See issues #1139 and #1415 for more information.

**Comment by DonW16** [comment]
> The error you experience has been reported in other issues. See issues #1058, #1073 and #1418. Have you found your error is specific to Tails 4.15.1? In other words, did Session AppImage work in previous versions of Tails?

Apologies for opening similar issues, no this is the only version of Tails I have launched session on.

> The workaround that was suggested is add the --no-sandbox option. However, this is a hack, not a solution. If the sandbox really provides no value, it should be removed. Further, issue #1058 currently suggests adding --no-sandbox doesn't necessarily work.

> Though not related to this issue, even if you successfully launch Session in Tails, be aware that Session will not be able to get through the Tails firewall that blocks most traffic except Tor. See issues #1139 and #1415 for more information.

Understood thanks.
