### ISSUE TITLE
[Enhancement] Provide screen breaks and titles for days in message view

### ISSUE THREAD

**Issue by nooblag** [oxen-io/session-desktop#1522]
**Describe the bug**
At the moment, messages all appear after one another with no discernable break in days. It would be good to have a title break up dates so time is more easily discernable in the messages thread.

For example, Rocket Chat does it like this:

![rocketchat](https://user-images.githubusercontent.com/1122344/109353675-cba43880-78d0-11eb-9a04-599eef48f35a.PNG)

**Comment by Bilb** [comment]
We will have this for the next release
