### ISSUE TITLE
Question about the financing of this project

### ISSUE THREAD

**Issue by Coording** [oxen-io/session-desktop#1529]
Hi, the software looks interesting and maybe I can give it a try. But I have a question: How is this project financed monetarily?

Thanks in advance!

**Comment by neuroscr** [comment]
Private sale of token in 2018, now an Australian non-profit. A portion of the blockchain rewards fund continued development.

**Comment by Coording** [comment]
Ok, putting that aside. Do you guys plan to open a donation system?. Thanks for the responses

**Comment by KeeJef** [comment]
The best way to support the project right now is by buying the Oxen, the Loki foundation (Primary developer of Session) benefits whenever the Oxen price increases

**Comment by fenugrec** [comment]
Tangentially related : I understand service nodes earn/mine LOKI$ in return for operating servers, but... you can't buy anything with LOKI$ so what's the motivation for them ? The only real-money transaction is new service nodes buying a stake... kinda smells pyramidal to an ignorant skpetical layman like me ? I would really like for this to work though, don't get me wrong.

**Comment by neuroscr** [comment]
We're not here to debate the usefulness of cryptocurrency but saying you can't buy anything with $OXEN (used to be called $loki) is simply not true.

First, You can exchange $OXEN on several exchanges for other currencies in which you can buy anything.
Second, You can use $OXEN to buy oxen/session/lokinet services such as ONS.
Third, There are a couple vendors that take $OXEN directly; hot sauce and hosting AFAIK. I've even see engraved whiskey glasses

Banks give you a percentage on your saving accounts, are they "pyramidal" too? Stocks that pay dividends? A pyramid scheme would require you to spend money and then take money from your friends to repay it. 

I see it as a dividend, I invest in $oxen and I get paid a dividend for my support of the network. I just like being able to support a non-profit without having to give them money but by just letting them temporarily use my liquidity and they give me interest.

**Comment by fenugrec** [comment]
> saying you can't buy anything with $OXEN (used to be called $loki) is simply not true.

thanks for the reply - I was exaggerating a bit of course ! My questions are genuine curiosity, not just crude criticism, and I won't derail this discussion much farther.

> First, You can exchange $OXEN on several exchanges for other currencies in which you can buy anything.

Ah, that's what's not intuitive to me. Say our nodes are printing monopoly money (we'll call it $OX) for the service they provide. Why would another exchange be interested in trading other "more useful" coins for our monopoly money ? Feels like very risky investment argument. Don't have much appetite for speculation, myself.

> Second, You can use $OXEN to buy oxen/session/lokinet services such as ONS.

Thanks, that's a more convincing usecase already.

> Third, There are a couple vendors that take $OXEN directly;

Also good to know. I'm glad they see a financial incentive in doing that and not just benevolence.

> A pyramid scheme would require you to spend money and then take money from your friends to repay it.

That is exactly how I understood the staking process (before the "exits" you listed). You spend money to get a stake, then all you can show for that is $OX;  the only way to get your fiat back is to "sell" stakes to new players.

In any case, I feel bad for hijacking this issue, feel free to close / ignore my comments. I will definitely be following the development of session and the current audit with much interest !
