### ISSUE TITLE
Cannot send Messages | Invalid Timestamp

### ISSUE THREAD

**Issue by TomRomeo** [oxen-io/session-desktop#1536]
Hello, when I run the session appimage, I can receive messages from other
accounts. When I try to send a Message however, it displayes SEND FAILED in
the app. Taking a look at the debug log reveals that I get a lot of error messages
along the lines of:
```
{"name":"log","hostname":"X","pid":1970,"level":40,"msg":"loki_message:::storeOnNode - send error:  Invalid Timestamp (check your clock) destination 139.162.25.130:22021","time":"2021-03-07T13:46:47.304Z","v":0}
{"name":"log","hostname":"X","pid":1970,"level":40,"msg":"loki_message:::storeOnNode - Timestamp is invalid","time":"2021-03-07T13:46:47.304Z","v":0}
```
Taking a look at the time reveals that the displayed time in the error
message is indeed one hour behind my local time. I am not quite sure how to
fix that tho. My hwclock time is correct and `date` returns the correct time
aswell. I am running Gentoo with OpenRC, maybe that has something to do with
it?

Debug Log is pasted here: https://paste.gg/p/anonymous/35a870ae0ec944449f52778161573650

Regards

**Comment by KeeJef** [comment]
This should be corrected in the next hardfork with some upcoming changes to the Service Node network storage servers, does this occur consistently even when you restart Session?

**Comment by TomRomeo** [comment]
Hello and sorry for the late reply,

it did happen consistently even after multiple restarts of the program and the os.

At least for me the bug is fixxed now. I am not sure if it was due to a recent update. Another thing I changed was enabling ntp, before that my clock was set manually, maybe it wasn't correct enough? Anyways, this is fixxed for me now.
