### ISSUE TITLE
Consider using the Microsoft Store

### ISSUE THREAD

**Issue by buchwasa** [oxen-io/session-desktop#1537]
Hi there, I think Session should be put on the Microsoft Store, especially with the upcoming Windows 10X. 

Porting to support the Microsoft Store can be as simple as using the MSIX packaging tool or using the [docs that electron provides](https://www.electronjs.org/docs/tutorial/windows-store-guide).

**Comment by lenincritus** [comment]
+1 @KeeJef  Downloading from the store directly would protect users from downloading random .exe files on the web

**Comment by RagueI** [comment]
> +1 @KeeJef Downloading from the store directly would protect users from downloading random .exe files on the web

now, microsoft store would require you to firstly login to the account in order to download apps, which is opposed to our goal for anonymous

**Comment by RagueI** [comment]
simply a hash or some sort of signature of the downloadable would suffice

**Comment by Dyras** [comment]
@RagueI I don't think this is true. You can download apps without logging in, at least from what I've noticed.

**Comment by KeeJef** [comment]
There doesn't seem to be significant enough desire for this, it would take a bit of work to go through the process to distribute on Microsoft store and would be something we would need to maintain and interact with for every release. I will reopen if desire grows for this
