### ISSUE TITLE
Opening Session app slowing down as it loads old messages.

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-desktop#1538]
**Describe the bug**
The app slows down as it loads messages from 3 open groups that I am in.
messages should already be loaded all at once or gradually load without risking high cpu and RAM Usage

**To Reproduce**
1. Do not open the app for a day or two
2. log in with your master password/passphrase if required

**Screenshots or Logs**

![session SC](https://user-images.githubusercontent.com/57234536/111125715-4fecf180-8548-11eb-8ef8-3f652d0d6aec.PNG)

**Other information (please complete the following information):**

* Device: PC
* OS: Windows 10
* Session Version or Git commit hash: v1.5.0

**Comment by KeeJef** [comment]
We are aware of this issue, and are looking into possible solutions

**Comment by Bilb** [comment]
the message list has been rewrote and this issue should been fixed now. Please reopen if not
