### ISSUE TITLE
windows 10 bug ?

### ISSUE THREAD

**Issue by pentestcx** [oxen-io/session-desktop#1541]
**Describe the bug**
After entering the password, it cannot be displayed normally
**To Reproduce**
Steps to reproduce the [behavior:](url
![02b737f8d47e38ccb0922947a3a5db69b93aeb8dcf069985c92702260317e484](https://user-images.githubusercontent.com/80863955/111556900-9485c080-87c6-11eb-8e66-241982eeb0a6.png)
![96d12e4e521300de0a58f1be4efcf15c8b9c6cfea55ed985ff330b02f9f45313](https://user-images.githubusercontent.com/80863955/111556937-a6676380-87c6-11eb-8252-9c4b8ff49cc6.png)

)

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**
[](url)
* Device: [e.g. PC, Mac]
* OS: [e.g. Ubuntu 16.04, Windows 10]
* Session Version or Git commit hash:

**Comment by baoabozhilian** [comment]
I have the same problem

**Comment by Bilb** [comment]
@baoabozhilian Could you please tell me what the languages or your windows?

You can see it on the windows settings => Time and language => tab language ?

It looks like this:
![photo_2021-03-19_13-57-42](https://user-images.githubusercontent.com/1544279/111728855-dc3d4280-88c1-11eb-8024-c4d403f17665.jpg)

**Comment by baoabozhilian** [comment]
My language is Chinese
![微信截图_20210319114820](https://user-images.githubusercontent.com/80874548/111729044-1bab6500-88a9-11eb-8288-737396efc1c3.png)

**Comment by pentestcx** [comment]
Can it be repaired

**Comment by Bilb** [comment]
I managed to reproduce the issue. Looks to be coming from the locale. I will get a fix for the next release

**Comment by pentestcx** [comment]
You can try to set the language to Chinese.

**Comment by baoabozhilian** [comment]
@Bilb  Maybe the mac also has Chinese problems, the ios connection is successful, but the mac connection does not respond

**Comment by Bilb** [comment]
1.5.1 included a fix. Is that resolved for you too?
