### ISSUE TITLE
It seems that Session still doesn't work in China

### ISSUE THREAD

**Issue by HostFat** [oxen-io/session-desktop#1547]
https://twitter.com/HouseOfTheRisi4/status/1373033920657170433

> Hi ya! Yep download was not a prob. Was tweeting that Session probably wouldn't work against the GFW because it still needs to contact a loki net "Super node" server" to initiate connections.
> But no worries, nobody reads my tweet - was just a "note to self".

**Comment by KeeJef** [comment]
Is this confirmed? because i have some Chinese contacts that have said that Session is still working in China
