### ISSUE TITLE
Display name rules are not the same for every client.

### ISSUE THREAD

**Issue by chairmantheboring** [oxen-io/session-desktop#1548]
**Describe the bug**
The rules that define what your display name can contain are different between Session Android and Session Desktop. 

**To Reproduce**
1. Set your display name to one containing an invalid character, this can be an emoji or as simple as a period, using Session Android.
2. In Session Desktop, attempt to edit your name and notice that the characters that Session Desktop considers to be invalid disappear from the editor.

**Other information (please complete the following information):**

* Device: Android and Linux
* OS: LineageOS 17.1 and Arch Linux
* Session Version or Git commit hash: Android: 1.8.1. PC: 1.5.0 (AppImage)

**Comment by KeeJef** [comment]
This is something we should standardize, ill add it to the list of tasks to complete

**Comment by Bilb** [comment]
this has been fixed on recent releases
