### ISSUE TITLE
Deleted messages are never deleted

### ISSUE THREAD

**Issue by jimgillo** [oxen-io/session-desktop#1550]
The deleted messages in the db.sqlite database on the Session Desktop are NEVER deleted. they are marked deleted but are always stored in the db.sqlite (the database is still growing)

you should use the sqlite VACUUM command each time the Session Desktop is run, to delete the old messages in the database.

https://sqlite.org/lang_vacuum.html

**Comment by KeeJef** [comment]
we are currently investigating this
