### ISSUE TITLE
Attachments are stored unencrypted on the hard drive

### ISSUE THREAD

**Issue by jimgillo** [oxen-io/session-desktop#1551]
The attachments are stored unencrypted on the hard drive by Session Desktop (Linux and Windows testes).
You should encrypt the stored attachments with the user password and an IV (initialization vector) randomly generate for each files and stored in the header on the file.

**Comment by KeeJef** [comment]
We are testing a potential solution for this now

**Comment by jimgillo** [comment]
you should do like this:

1-for each Desktop Session user: generate a random key with Secure random (KEY USER)

https://developer.android.com/reference/java/security/SecureRandom

2-store this random key KEY USER in the db.sqlite database (which is encrypted with a fixed key or with the user password)

3-generate a random header for EACH attachment with Secure random

4-store the random header in plaintext at the start the encrypted attchment file (HEADER FILE)

3-use the random key KEY USER and the HEADER FILE with chacha20poly1305 to encrypt the attchment

4-NEVER USE THE SAME FIXED KEY FOR EVERYONE!

5-At first start of the new version, encrypt old attachments (from previous versions) on the hard disk (not only encrypt new attachments).

**Comment by Bilb** [comment]
Closing this as the PR got merged
