### ISSUE TITLE
PDF file open and download error as a attachment on android phone

### ISSUE THREAD

**Issue by noneper** [oxen-io/session-desktop#1556]
**Describe the bug**
I send a PDF file on Session desktop to my phone, independent two ID,  open Session on the phone click the files recieved, it said can't open it due to the file already damaged. When I long press try to download it, Session said it met some error can't store it to phone.

* OS: Windows 10
* Session Version or Git commit hash:  1.5.2 for desktop, 1.8.1 on a android phone

**Comment by Bilb** [comment]
This should be fixed now
