### ISSUE TITLE
Space bar sends message when using Chinese keyboard

### ISSUE THREAD

**Issue by claireyangcui** [oxen-io/session-desktop#1558]
**Describe the bug**
Space bar sends message when using Chinese keyboard

**To Reproduce**
type a word using Chinese keyboard on a Mac, and hit the space bar

**Other information (please complete the following information):**
* Device: Mac 
* OS: macOS Big Sur version 11.0.1
* Session Version or Git commit hash: v1.5.2

**Comment by Bilb** [comment]
closing this in favor of https://github.com/oxen-io/session-desktop/issues/1497
