### ISSUE TITLE
Where is the PGP public key?

### ISSUE THREAD

**Issue by igorcmelo** [oxen-io/session-desktop#1559]
**Describe the bug**
I downloaded the app and the signed message with the hashes, but I can't find the public key for verifying the signature.

**Comment by beantaco** [comment]
For as long as I know, Session releases have been signed with @KeeJef's PGP key.

- Fingerprint: `8877 EEBB 9721 ABC5 DF64  9AE4 AC97 1489 5CE4 5D55`
- Public key: https://pastebin.com/Jb4Emn8V

**Comment by KeeJef** [comment]
in the signed message it lists the location of the keys [too](https://github.com/oxen-io/oxen-core/blob/master/utils/gpg_keys/KeeJef.asc), but the above keys linked by @beantaco are correct
