### ISSUE TITLE
Cannot send audio message

### ISSUE THREAD

**Issue by chimp1984** [oxen-io/session-desktop#1560]
**Describe the bug**
Cannot send audio message from OSX desktop app. Audio is playing but nothing to hear.

**To Reproduce**
Record audio and send. It sends and you can replay it but nothing to hear on both sender and receiver.

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac]
Imac 
* OS: [e.g. Ubuntu 16.04, Windows 10]
Big Sur
* Session Version or Git commit hash:
Latest release downloaded 9.4.2021

**Comment by Bilb** [comment]
Will be fixed in the next release.
You will need to disable/enable the microphone in Session settings on macos again
