### ISSUE TITLE
Syncing issue

### ISSUE THREAD

**Issue by Skril3366** [oxen-io/session-desktop#1561]
**Describe the bug**
After having conversation using android app I opened Mac OS app and messages synced incorrectly. Everything I've wrote went to self note and in chat only messages of another user left.

**To Reproduce**
1. Have a chat using Android app
2. Open Desktop(Mac OS) app and wait until messages are synced.

**Other information (please complete the following information):**
* Device: Macbook Pro
* OS: macOS Big Sur 11.2.2
* Session Version: 1.5.2

**Comment by Bilb** [comment]
@Skril3366 Does this issue still happens for you?
