### ISSUE TITLE
Clock out of sync error

### ISSUE THREAD

**Issue by chimp1984** [oxen-io/session-desktop#1562]
**Describe the bug**
When starting up Session and sending a message I got various times the "Your clock is out of sync" error, thought it is not out of sync. After a few seconds it worked then.
The Desktop app could need some love in general. The iOS app seems to work much better.

**To Reproduce**
?

**Screenshots or Logs**
-

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac]
Mac

* OS: [e.g. Ubuntu 16.04, Windows 10]
Big Sur

* Session Version or Git commit hash:
Latest download

**Comment by Bilb** [comment]
Yes, the desktop app needs to build a onion path and fetch it's time difference before being able to send a message. It can take a few seconds when you start the app for this to be done and being able to send a message without the warning.
We plan to add a UI for telling the onion path status so it will fix this issue too.

**Comment by Bilb** [comment]
Hey,
the PoW was removed in the last release so this toast was removed too. Let me know how it goes
