### ISSUE TITLE
Unable to remove anonymous user from closed group.

### ISSUE THREAD

**Issue by chairmantheboring** [oxen-io/session-desktop#1564]
**Describe the bug**
If you have an anonymous user in your closed group, that you've never talked to on this device and you don't have their contact in your contacts list, you cannot remove them. This bug might relate to #1563 

**To Reproduce**
1. Import a device with a Session ID that is in the group.
2. Have contact sync fail somehow (see #1563).
3. Manage group members in the group with the anonymous member.
4. Realize all members except the anonymous member show up in the group member management dialog.

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**
- Device: PC
- OS: Arch Linux
- Session Version or Git commit hash: Session Desktop 1.5.2 (Flatpak)

**Comment by Bilb** [comment]
Just made a PR for that
https://github.com/oxen-io/session-desktop/pull/1611
