### ISSUE TITLE
Emoji Reactions

### ISSUE THREAD

**Issue by ShawnNogi** [oxen-io/session-desktop#1577]
can you also please consider allowing us to make emoji reactions for group chats or private conversations. basically discord's emoji system built into the session app.

![image](https://user-images.githubusercontent.com/39767738/115862084-aa0f8b00-a401-11eb-82b1-5a3502dd54d8.png)

**Comment by kajlando** [comment]
This feature is already on Signal. Would be great if it was here.

**Comment by DillFrescott** [comment]
This is one thing I often found myself missing while using Session compared to other apps. Would be awesome to have!

**Comment by yougotwill** [comment]
Closing since we have released v1.10.0 https://github.com/oxen-io/session-desktop/releases/tag/v1.10.0
