### ISSUE TITLE
Unable to add user in windows

### ISSUE THREAD

**Issue by Ygarr** [oxen-io/session-desktop#1579]
windows 8.1 after copying session id to add user - after pushing button nothing happens

**Comment by Bilb** [comment]
@Ygarr does this still happen?

**Comment by Ygarr** [comment]
Fort now:
HEAD is now at eddcda3d7 Merge pull request #1664 from Bilb/reupload-avatar-everynow-and-then
v10.19.0 is already installed.
Now using node v10.19.0 (npm v6.13.4)
==> Sources are ready.
==> Making package: session-desktop 1.6.4-1 (ср, 26-may-2021 23:37:49 +0300)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
==> ERROR: A failure occurred in build().
    Aborting...
error making: session-desktop

Sorry, had to later

**Comment by Ygarr** [comment]
Also disappeared fresh android version .apk for testing

**Comment by Ygarr** [comment]
Just tested it seems now works good. Think can be closed, thus
