### ISSUE TITLE
Invalid Timestamp (check your clock)

### ISSUE THREAD

**Issue by klochden** [oxen-io/session-desktop#1580]
Exactly since the last update I'm not able to send Messages. Before the Update everything worked fine!
Receiving is not a problem.

My smartphone, connected to the same router has no problems with sending messages!

The windows clock is OK, and before the update everything worked. My router is connected through VPN to another country but I don't think that this is the reason for this issue since my android smartphone is connected to the ame router and as I said before, this problem exists only since the last update!

* Device: Desktop Windows 10
* Session Version: latest

**Comment by klochden** [comment]
After setting the time settings in windows to automatical recognizing the region and so on it worked finally. No idea if this is good or bad because now my clock shows wrong time ( not of my local country)!

**Comment by Bilb** [comment]
@klochden What was your setting before on windows? Like when it was not working?

**Comment by klochden** [comment]
«Set Time Zone Automatically» was disabled.

  
>Вторник, 27 апреля 2021, 2:07 +03:00 от Audric Ackermann ***@***.***>:
> 
> 
***@***.*** What was your setting before on windows? Like when it was not working?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Denis Klochko

**Comment by KeeJef** [comment]
This will be fixed in an upcoming update, when we move away from timestamped pow validation on the storage server network
