### ISSUE TITLE
Feature - Gutman Deletes on messages

### ISSUE THREAD

**Issue by ShawnNogi** [oxen-io/session-desktop#1582]
I don't know how in scope this in for you guys, but how is stuff deleted natively on mobile/desktop clients from the database ? I understand that there inherent security in encryption but would you guys consider Gutman deletion (35 pass overwrite) or at least DOD deletion (7 pass overwrites) on messages?

**Comment by KeeJef** [comment]
Is this relevant for SSD's? pretty sure we already zero data after deletion from the DB, maybe something to implement for harddisks, not sure how many people are still using harddisks

**Comment by Bilb** [comment]
the database is encrypted and vaccuum on every start. Not sure what else needs to be done?
