### ISSUE TITLE
Pasting an image (Using Ctrl-V) doesn't add it to upload a file.

### ISSUE THREAD

**Issue by timmy-time** [oxen-io/session-desktop#1583]
Pasting any file using Ctrl-V doesn't add that file to upload.

**Comment by Bilb** [comment]
Closing this one in favour of https://github.com/oxen-io/session-desktop/issues/1600

**Comment by Bilb** [comment]
Actually this is not the same issue.
#1616 is specific for images as content and not files as select file from the file explorer and paste it.

**Comment by ShawnNogi** [comment]
Looks like this is now fixed right? update seems to have added the feature

**Comment by Norbert80** [comment]
Pasting images works in Desktop build v1.6.4. ==> This issue can be closed.
