### ISSUE TITLE
Do not automatically scroll screen when new messages arrive.

### ISSUE THREAD

**Issue by snakyjake1** [oxen-io/session-desktop#1585]
### Current:
When new messages arrive, the screen is automatically scrolled to the end to show the most recent received message.  This makes it very difficult to see/know where I last left off from reading the last unread message.  I have to scroll back up, and look for messages and timestamps of where I last read the messages.  This is especially frustrating in very active groups with many messages.

### Request:
Do not automatically scroll screen when new messages arrive.

### Info:
* Device: Desktop
* OS: Linux
* Session Version: v1.5.4

**Comment by beantaco** [comment]
I currently can't confirm this behavior, but if it indeed happens it must be highly frustrating.

**Comment by Bilb** [comment]
Should be fixed in 1.6.10. Let me know if that's not the case
