### ISSUE TITLE
Attachments send from Android to desktop are received twice on desktop side

### ISSUE THREAD

**Issue by Norbert80** [oxen-io/session-desktop#1590]
Attachments send from Android to desktop are received twice on desktop side

Found with:

Session Desktop Linux v1.5.4
Session Android v1.9.1

See also
https://github.com/oxen-io/session-android/issues/522

**Comment by Norbert80** [comment]
Seems to be fixed in Android Desktop v1.6.0. Closing this issue.

**Comment by Norbert80** [comment]
Sorry, I must have been too quick. I experience this again on v1.6.0. Re-open.

**Comment by Bilb** [comment]
Hey, I have probably a fix for this one on this PR already merged. It will be in the next release https://github.com/oxen-io/session-desktop/pull/1608

**Comment by Norbert80** [comment]
> Hey, I have probably a fix for this one on this PR already merged. It will be in the next release #1608

@Bilb thanks. But I still see this issue with v1.6.1.

**Comment by Norbert80** [comment]
![grafik](https://user-images.githubusercontent.com/6921696/118166951-6d461b00-b426-11eb-86a5-5129e99665a4.png)

**Comment by Norbert80** [comment]
Seems to be fixed in Session Desktop v1.6.3.
==> Closing
