### ISSUE TITLE
Wrong default file name when saving received files

### ISSUE THREAD

**Issue by Norbert80** [oxen-io/session-desktop#1593]
For received attachments the correct file name is displayed in the message bubble (for example: "document.odt"). However, when saving the file, the default file name is something like "session-attachment-2021-05-05-172305.vnd.oasis.opendocument".

 I use Session v1.5.4 Desktop/Linux.

**Comment by Norbert80** [comment]
v1.5.5 is still affected.

**Comment by Norbert80** [comment]
v1.6.0 is still affected.

**Comment by Norbert80** [comment]
@Bilb may I ask you to have a look on this issue? It really prevents us from "productive" usage of Session Desktop.

**Comment by Norbert80** [comment]
@Bilb thank you very much for the patch. However I am wondering if we really need a dedicated patch for each type of file name extension. Is there no general solution possible?

If not it would be great to add the complete set of ODF format extensions to the supported list. Not odt only. The complete list is:

Source:
https://en.wikipedia.org/wiki/OpenDocument_technical_specification#Documents



File type | Extension | MIME Type | ODF specification
-- | -- | -- | --
Text | .odt | application/vnd.oasis.opendocument.text | 1.0
Spreadsheet | .ods | application/vnd.oasis.opendocument.spreadsheet | 1.0
Presentation | .odp | application/vnd.oasis.opendocument.presentation | 1.0
Drawing | .odg | application/vnd.oasis.opendocument.graphics | 1.0
Chart | .odc | application/vnd.oasis.opendocument.chart | 1.0
Formula | .odf | application/vnd.oasis.opendocument.formula | 1.0
Image | .odi | application/vnd.oasis.opendocument.image | 1.0
Master Document | .odm | application/vnd.oasis.opendocument.text-master | 1.0
Database | .odb | application/vnd.sun.xml.base[2][3] | not defined in ODF 1.0/1.1 specifications;used in OpenOffice.org 2.x
Database | .odb | application/vnd.oasis.opendocument.base | ODF 1.2;used in OpenOffice.org 3.x
Database | .odb | application/vnd.oasis.opendocument.database | defined in IANA registration
all OpenDocument single/flat XML files | not defined | text/xml | 1.0

Source:
https://en.wikipedia.org/wiki/OpenDocument_technical_specification#Templates

File type | Extension | MIME Type | ODF specification
-- | -- | -- | --
Text | .ott | application/vnd.oasis.opendocument.text-template | 1.0
Spreadsheet | .ots | application/vnd.oasis.opendocument.spreadsheet-template | 1.0
Presentation | .otp | application/vnd.oasis.opendocument.presentation-template | 1.0
Drawing | .otg | application/vnd.oasis.opendocument.graphics-template | 1.0
Chart template | .otc | application/vnd.oasis.opendocument.chart-template | 1.0
Formula template | .otf | application/vnd.oasis.opendocument.formula-template | 1.0
Image template | .oti | application/vnd.oasis.opendocument.image-template | 1.0
Web page template | .oth | application/vnd.oasis.opendocument.text-web | 1.0

**Comment by Norbert80** [comment]
I really think that the one patch per file extension is not a good idea. We should find a generic solution.

**Comment by Bilb** [comment]
@Norbert80 the fix is to use the file extension when the mimetype starts with 'application'. 

I agree the PR title is not very explicit, but all of the mimetype you mentioned above will have the correct extension. 

Let me know if you still have issues with this after the next release

**Comment by Norbert80** [comment]
@Bilb thanks for the explanation. I also get "bad" file names for ZIP files. For example: "session-attachment-2021-05-13-123753.zip". Is this also addressed by your patch?

**Comment by Norbert80** [comment]
@Bilb please re-open this issue. I just have installed v1.6.3 and still get "session-attachment-2021-05-20-085027.zip" as file name.

**Comment by Bilb** [comment]
So the extension is correct but not the filename itself right? I thought all along that the request was only about the extension so the 'vnd.oasis.opendocument' part and not the session-attachment part

**Comment by Norbert80** [comment]
@Bilb:

Yes, the file extension is correct. I think it is self-explanatory that the user expects the full file name in the original here.

**Comment by Norbert80** [comment]
@Bilb thanks, but I cannot find any comment or line in
https://github.com/oxen-io/session-desktop/commit/72ddbb7db2f8dc28772cf3c41eb3f48f3537efb9
which implies that this file name issue will be addressed. In which release will this patch be included?

**Comment by Norbert80** [comment]
@Bilb thank so far but the commit does NOT fix this issue. v1.6.0 is still affected. Please re-open!

**Comment by Norbert80** [comment]
I confirm that this issue is fixed in v1.6.5. Thanks!
