### ISSUE TITLE
No messages from public group

### ISSUE THREAD

**Issue by FatBirdie** [oxen-io/session-desktop#1609]
It has happened a few times now that everything goes silent in a public group I'm in.
Private conversations go on as normal, and I think all is okay. I restart Session, and messages that are hours or days old (depending on how long its been since I last restart Session) appears in the group which was not there before.

What can I do to help debug this issue?

**Comment by Bilb** [comment]
Hey, is it a new open group or an old one? When did you join it?

**Comment by FatBirdie** [comment]
Its listed in your "Session Open Group Directory"
Joined may be a week ago.

**Comment by Bilb** [comment]
Can you reach out to me on my Session account please so we can debug this ? It's on my github profile Session ID 054774a456f15c7aca42fe8d245983549000311aaebcf58ce246250c41fe227676

**Comment by peepopoggers** [comment]
any updates

**Comment by FatBirdie** [comment]
Haven't had any more issues. I think this issue can be closed.
