### ISSUE TITLE
Missing translations for some strings [Russian]

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-desktop#1615]
Not have translate in other language 

**Login Screen** 
![Session_login_page_translate](https://user-images.githubusercontent.com/43858033/117646594-9cddf480-b194-11eb-949e-8c45c6b0569b.png)

**Dialog files**
no work name no have parameters $name$

![Session_dialog_files](https://user-images.githubusercontent.com/43858033/117647211-5b017e00-b195-11eb-8ed4-7121382fba6d.png)
![Session_dialog_more](https://user-images.githubusercontent.com/43858033/117648098-7de06200-b196-11eb-95a6-fb58365b883c.png)

**Settings Block Contact**
![Session_block_contact](https://user-images.githubusercontent.com/43858033/117647123-40c7a000-b195-11eb-81ba-3ad4c57e0659.png)

** Settings**
![Session_settings](https://user-images.githubusercontent.com/43858033/117647349-884e2c00-b195-11eb-9a76-cf909b646e3a.png)
![Session_settings2](https://user-images.githubusercontent.com/43858033/117647360-8d12e000-b195-11eb-9d96-68376ca3bdd0.png)

**Comment by Bilb** [comment]
feel free to update the russian translation by clicking on the settings page (gear icon) => and the help us translate session button
