### ISSUE TITLE
Option to change UI font

### ISSUE THREAD

**Issue by 4DA** [oxen-io/session-desktop#1617]
As I can see Session Desktop uses Cyrillic "serif" font (at least on Ubuntu 20.04).

I think, option to change default font (or at least ensuring "sans" Cyrillic) would be greatly appreciated.

Session desktop version: 1.6.0

![image](https://user-images.githubusercontent.com/364499/117724801-f5d97700-b1ec-11eb-9634-11e57d7fb1ad.png)

**Comment by Bilb** [comment]
Looks to be related to the fact that Public sans does not support Cyrillic so electron was falling back to Liberation Serif just for those char. 
I made a PR to switch to Roboto which does support Cyrillic direclty

**Comment by 4DA** [comment]
I hate to say it, but I've updated to session 1.6.1 and issue is still there for me

![image](https://user-images.githubusercontent.com/364499/118030476-049b6780-b36e-11eb-8059-96b997f0aa93.png)
text: съешь ещё этих мягких французских булок, да выпей чаю

**Comment by Bilb** [comment]
1.6.1 was only a tiny bug fix release because some users had issue starting the app on qubes os and fedora. It does not include the commit to fix the font yet.
