### ISSUE TITLE
Group messages are never deleted

### ISSUE THREAD

**Issue by jimgillo** [oxen-io/session-desktop#1629]
When you leave a group, all messages exchanged in this group are still in the database and are never erased (even after years).
When you leave a group, the name and URL (hhtps://group....) of all groups you joined remains in the database too (Table: Servers).

You should delete all the group messages when a group is left and the name of the groups too. If it's too long to erase, display a warning message to the user on the time required for erasure (are you ok to erase now : Yes / No) and if the user answers No, have an option to erase messages of these groups left when the user wants.

**Comment by peepopoggers** [comment]
+1

**Comment by Bilb** [comment]
Hi, this issue should be fixed since like a month ago (#1703). Let me know if that's not the case
