### ISSUE TITLE
Sudden exit upon log file related error

### ISSUE THREAD

**Issue by beantaco** [oxen-io/session-desktop#1634]
When using Session Desktop version 1.5.x (I don't remember exactly) it exited suddenly with exit code of 1. The GUI suddenly disappeared from sight after Session Desktop was running idly for several minutes.
I'm running a Debian related OS on amd64.

The logs are gone and I haven't been able to reproduce it, but fortunately I launched it from terminal so I was able to catch the error message that appeared in the terminal:

~~~
{...log entry...}
{...log entry...}
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/<username>/.config/Session/logs/log.log'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/stream.js:294:12
    at FSReqCallback.oncomplete (fs.js:146:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/<username>/.config/Session/logs/log.log'
}
~~~

**Comment by KeeJef** [comment]
Has this happened since?

**Comment by Bilb** [comment]
I do know this still happens

**Comment by Bilb** [comment]
Closing as no news
