### ISSUE TITLE
Invite desktop user to backup private key as done on mobile

### ISSUE THREAD

**Issue by lrq3000** [oxen-io/session-desktop#1636]
**Describe the bug**
The registration process on desktop doesn't require the user to copy/save the private key as it does on mobile, so non technical users may unknowingly lose their account if they create one on desktop and aren't aware of how blockchains work.

**To Reproduce**
Try to create a new account on desktop app.

* Device: PC
* OS: Windows 10
* Session Version or Git commit hash: latest stable release

**Comment by peepopoggers** [comment]
+1
