### ISSUE TITLE
Add Green Color  in Night Theme or give user choice color for icon and background text

### ISSUE THREAD

**Issue by ghost** [oxen-io/session-desktop#1645]
Perhaps not everyone will agree with me, but in the night theme everything is very monotonous and I would like a little green as there is in the day theme (as the green color has become a symbol of the logo and very often use)

**Thinks**
Perhaps it would be nice to give the user to choose the self color of the background text and icons (like Twitter)
That is, the topic is bright and night remain in the same colors but icons and selection text can be assigned to your color.

**Comment by xbvrhlmb** [comment]
anybody make this ? :) really Android version have this Desktop not have
grey color self message not cool :)

**Comment by eyeberic** [comment]
Bumping on this feature-request as there have been some feedback recently from user's using the Light mode, that the white text on green background makes it very illegible. 

Moving forward, this feature's implementation should be modular enough to allow users to explicitly define their choice of: 

- [ ] User's message text colour
- [ ] User's message background colour
- [ ] Others' message text colour
- [ ] Others' message background colour
- [ ] (Low priority) Chat background colour: **Overrides** colour specified from system theme, or Session Light/Dark mode
- [ ] (Lowest priority) Chat background image: Users can **either** choose an image, **or** a solid colour

**Comment by gnrlus** [comment]
Good app colors are extremely important. The dark gray backdrop in dark mode is acceptable. Solid bright green is actually not a good idea for dark theme. The eye is most sensitive to green and blue and when working late and you are being blasted with that level of, and these frequencies of radiation, the brain's sleep signals get impeded. If I'm going to use this app all the time I definitely need full control over the foreground and background colors of the message bubbles of both parties. In my Signal Desktop the two are different shades of gray and that is plenty distinct and yet it doesn't burn my retina with bright green and give me a migraine. (Some people are really sensitive!)

**Comment by gnrlus** [comment]
> ![1](https://user-images.githubusercontent.com/43858033/127739585-03c16206-1ccb-4f16-877f-d018081b5b2c.png) anybody make this ? :) really Android version have this Desktop not have grey color self message not cool :)

The example under 'Desktop' is far more preferable to me than the example under 'phone'.

**Comment by gnrlus** [comment]
![sample_colors](https://user-images.githubusercontent.com/90088274/167273707-5b3b72d8-b0c8-4886-9bac-5922ef86af4f.png)
This would be perfect for me but I think this app should have complete color customization with at least an 8-bit color array, as opposed to a handful of colors or themes.

**Comment by KeeJef** [comment]
Theming has now been released for Session desktop, not everything listed here is available but you can tune the theme of Session  with a number of preset options which should be enough for most users. Closing this for now

**Comment by gnrlus** [comment]
> ![sample_colors](https://user-images.githubusercontent.com/90088274/167273707-5b3b72d8-b0c8-4886-9bac-5922ef86af4f.png) Is there a dollar amount I might offer in exchange for adding the specific colors I suggested? Or at least a golden yellow text?
