### ISSUE TITLE
nothing but a blank screen

### ISSUE THREAD

**Issue by 2011** [oxen-io/session-desktop#1650]
**Describe the bug**

As the title says.... After starting the app, I see only a blank white background.

**Screenshots or Logs**

[session.log](https://github.com/oxen-io/session-desktop/files/6523196/session.log)

**Other information (please complete the following information):**

Linux (built from source) attempting to run (as the log file attachment shows) session-desktop-linux-x86_64-1.6.3.AppImage

**Comment by Bilb** [comment]
Nothing is visible on the logs. Weird. Which os and version are you using to build the appImage?

**Comment by 2011** [comment]
> Nothing is visible on the logs. Weird. Which os and version are you using to build the appImage?

I didn't build the AppImage. I obtained it from this link:

https://github.com/oxen-io/session-desktop/releases/download/v1.6.3/session-desktop-linux-x86_64-1.6.3.AppImage

I have since downloaded version 1.6.4, and it behaves exactly the same.

**Comment by Bilb** [comment]
do you have a backup of your mnemonic? If yes, could you remove the session folder completely and give the latest release a try? `~/.config/Session/`

Can you tell me on what is based your built from source Linux?

**Comment by 2011** [comment]
> do you have a backup of your mnemonic?

First experience on any platform with the application, so no mnemonic yet.

> If yes, could you remove the session folder completely and give the latest release a try?

Did both of those, with no change (same behavior).

> Can you tell me on what is based your built from source Linux?

I believe that I have a reasonably modern system (5.10.27 kernel, with the following versions of dependencies, as tracked from the dynamic libraries shown by "ldd squashfs-root/session-desktop-bin" after extracting the AppImage):

alsa-lib-1.2.4
at-spi2-atk-2.38.0
at-spi2-core-2.40.1
atk-2.36.0
bzip2-1.0.8
cairo-1.16.0
cryptsetup-2.3.4
cups-2.3.3
dbus-1.12.20
eudev-3.2.10
expat-2.4.1
fontconfig-2.13.1
freetype-2.10.4
fribidi-1.0.10
gcc-10.3.0
gdk-pixbuf-2.42.6
glib-2.68.2
glibc-2.33
gmp-6.2.1
gnutls-3.7.1
graphite2-1.3.14
gtk+-3.24.29
harfbuzz-2.8.1
json-c-0.15
libX11-1.7.1
libXScrnSaver-1.2.3
libXau-1.0.9
libXcomposite-0.4.5
libXcursor-1.2.0
libXdamage-1.1.5
libXdmcp-1.1.3
libXext-1.3.4
libXfixes-6.0.0
libXi-1.7.10
libXinerama-1.1.4
libXrandr-1.5.2
libXrender-0.9.10
libXtst-1.2.3
libbsd-0.10.0
libepoxy-1.5.5
libffi-3.3
libglvnd-1.3.3
libidn2-2.3.0
libpcre-8.44
libpng-1.6.37
libtasn1-4.16.0
libunistring-0.9.10
libxcb-1.14
lvm2-2.02.187
nettle-3.7.2
nspr-4.30
nss-3.63.1
openssl-1.1.1k
pango-1.48.5
pixman-0.40.0
util-linux-2.36.2
zlib-1.2.11

Don't understand some of these dependencies (why does Session require libgcc_s.so.1?), but I will leave that topic for another day.

**Comment by Bilb** [comment]
Anyway I can build a similar system as yours to debug your  issue?
`libgcc` is apparently a dependency included by the electron-builder. Not sure why it's needed though

**Comment by 2011** [comment]
@Bilb Why did you close this? The problem still exists (even in 1.6.6).

**Comment by Bilb** [comment]
Hey, I closed it as I did not get a reply on my last comment. I need to have a way to have a similar system to be able to debug this. 
Can you give me details about how to build one?

**Comment by 2011** [comment]
Linux from Scratch has complete documentation for building a source-based system. You might find Gentoo slightly easier, though, since it has a package manager that does dependency handling.

**Comment by Bilb** [comment]
thanks for the update :)
