### ISSUE TITLE
[Branding] Text in Session logo is too dark to display properly in dark mode

### ISSUE THREAD

**Issue by lrq3000** [oxen-io/session-desktop#1659]
While working on integrating Session's logo (provided in the branding material on the Session website), I found that the text is set to a too dark grey color to be legible when dark mode is enabled on the website I am integrating the logo into.

Here is a modified version where the text is set to 50% of grey, which ensures it displays as good on clear and dark backgrounds:

[session.zip](https://github.com/oxen-io/session-desktop/files/6535227/session.zip)

**Comment by Bilb** [comment]
Hi,
just to be sure, it has nothing to do with the app itself right?

**Comment by Bilb** [comment]
@lrq3000 on the app itself, we have the text and the logo separated. 
on dark theme, no filter is set and the text is in white.
![image](https://user-images.githubusercontent.com/1544279/120140069-165d8580-c21d-11eb-9855-e8f1ae0619a2.png)

but on light mode we saturate the color for it to appear completely dark.
You can probably do the same on your side. 
![image](https://user-images.githubusercontent.com/1544279/120140119-2ffecd00-c21d-11eb-920e-84a08e9ad386.png)

**Comment by lrq3000** [comment]
Ok thank you for the clarification. I was talking about the branding
material (Media Kit) offered on the website:

https://getsession.org/wp-content/uploads/2020/03/Session_Brandmarks.zip

Since i did not find a dark mode version offered in and it's unclear where
to provide feedbacks on this kind of matter, i posted here.

I take note that you prefer the text to be white in dark mode. I would
suggest to include dark mode images in the Media Kit to avoid ambiguities.

Le lun. 31 mai 2021 à 06:33, Audric Ackermann ***@***.***> a
écrit :

**Comment by KeeJef** [comment]
hey @lrq3000 i did make a PR to your PR for privacy tools a few weeks ago to change the logo to include no text as that was the standard of the logos included on that page, not sure if you saw that https://github.com/lrq3000/privacytools.io/pull/2

**Comment by lrq3000** [comment]
@KeeJef Thank you for the heads-up, I indeed missed the notification somehow. It's now merged (and it makes my job easier without the text ^^).
