### ISSUE TITLE
[Session Implementation Proposal] One Time Session-ID use

### ISSUE THREAD

**Issue by cryptoxico** [oxen-io/session-desktop#1688]
**Why One Time session-ID use ?**
Even if session has a very secure layer of anonymity, our session identifiers remain pseudonymous and not anonymous.
Which is why i'm asking for an option that allows One Time Adress use like monero.

**Comment by ShawnNogi** [comment]
I second this idea. No idea how radical this is though... think session is based off of session ids being public in a sense. might mean changing all the code so probably not possible. i hope they consider it though. also heard the idea of regenerating session-ids that may be better then nothing.

**Comment by KeeJef** [comment]
i think the long term solution to this is #1809 instead of just allowing ephemeral ID's which can become hard to manage if they are being used too frequently
