### ISSUE TITLE
i cant install the npm

### ISSUE THREAD

**Issue by omg-itsme** [oxen-io/session-desktop#1694]
root@root-ThinkPad:~/oxen-io/session-desktop$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: session-desktop@1.6.5
npm ERR! Found: grunt@1.0.1
npm ERR! node_modules/grunt
npm ERR!   dev grunt@"1.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer grunt@"~0.4.5" from grunt-gitinfo@0.1.7
npm ERR! node_modules/grunt-gitinfo
npm ERR!   dev grunt-gitinfo@"0.1.7" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-12T07_13_57_506Z-debug.log
root@root-ThinkPad:~/oxen-io/session-desktop$                            

guide me to fix it

**Comment by Bilb** [comment]
Can you please  follow the instructions at 
https://github.com/oxen-io/session-desktop/blob/clearnet/BUILDING.md#prerequisites

And let me know how it goes?

**Comment by omg-itsme** [comment]
Yes Bilb, I followed but again i face some issues.


root@root-ThinkPad:~/oxen-io/session-desktop# yarn install --frozen-lock
yarn install v1.22.10
warning ../../../package.json: No license field
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
warning " > mic-recorder-to-mp3@2.2.2" has unmet peer dependency "webrtc-adapter@>=4.1.1".
warning " > styled-components@5.1.1" has unmet peer dependency "react-is@>= 16.8.0".
warning " > grunt-gitinfo@0.1.7" has incorrect peer dependency "grunt@~0.4.5".
warning "react-styleguidist > webpack-dev-server@2.11.5" has incorrect peer dependency "webpack@^2.2.0 || ^3.0.0".
warning "react-styleguidist > webpack-dev-server > webpack-dev-middleware@1.12.2" has incorrect peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
warning " > ts-mock-imports@1.3.0" has incorrect peer dependency "typescript@>=2.6.1 < 4".
warning " > tslint-microsoft-contrib@6.0.0" has incorrect peer dependency "typescript@^2.1.0 || ^3.0.0".
[5/6] Building fresh packages...
[1/14] ⢀ @journeyapps/sqlcipher
[2/14] ⢀ dtrace-provider
[3/14] ⢀ node-sass
[8/14] ⢀ electron
error /home/oxen-io/session-desktop/node_modules/@journeyapps/sqlcipher: Command failed.
Exit code: 1
Command: node-pre-gyp install --build-from-source
Arguments: 
Directory: /home/oxen-io/session-desktop/node_modules/@journeyapps/sqlcipher
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@10.19.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info build requesting source compile
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.19.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.19.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/oxen-io/session-desktop/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/oxen-io/session-desktop/node_modules/@journeyapps/sqlcipher/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/oxen-io/session-desktop/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/10.19.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.19.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/oxen-io/session-desktop/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.19.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/oxen-io/session-desktop/node_modules/@journeyapps/sqlcipher',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.19.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/oxen-io/session-desktop/node_modules/@journeyapps/sqlcipher/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlcipher-amalgamation-3030001/sqlite3.c
/bin/sh: 1: python: not found
make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlcipher-amalgamation-3030001/sqlite3.c] Error 127
make: Leaving directory '/home/oxen-io/session-desktop/node_modules/@journeyapps/sqlcipher/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/oxen-io/session-desktop/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.8.0-55-generic
gyp ERR! command "/usr/bin/node" "/home/oxen-io/session-desktop/node_modules/node-gyp/bin/node-gyp.js" "build" "--build-from-source" "--module=/home/oxen-io/session-desktop/node_modules/@journeyapps/sqlcipher/lib/binding/node-v64-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/oxen-io/session-desktop/node_modules/@journeyapps/sqlcipher/lib/binding/node-v64-linux-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /home/oxen-io/session-desktop/node_modules/@journeyapps/sqlcipher
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /home/oxen-io/session-desktop/node_modules/node-gyp/bin/node-gyp.js build --build-from-source --module=/home/oxen-io/session-desktop/node_modules/@journeyapps/sqlcipher/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/oxen-io/session-desktop/node_modules/@journeyapps/sqlcipher/lib/binding/node-v64-linux-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/oxen-io/session-desktop/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.8.0-55-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/oxen-io/session-desktop/node_modules/@journeyapps/sqlcipher/node_modules/.bin/node-pre-gyp" "install" "--build-from-source"
node-pre-gyp ERR! cwd /home/oxen-io/session-desktop/node_modules/@journeyapps/sqlcipher
node-pre-gyp ERR! node -v v10.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /home/oxen-io/session-desktop/node_modules/node-gyp/bin/node-gyp.js build --build-from-so



root@root-ThinkPad:~/projects/oxen-io/session-desktop#

**Comment by omg-itsme** [comment]
I face this problem fresh even though I have tried it. and i send that
issue in github

**Comment by Bilb** [comment]
@omg-itsme on your logs there is a `/bin/sh: 1: python: not found`.
Try making sure python2.7 is installed

**Comment by omg-itsme** [comment]
***@***.***:/home/root#
***@***.***:/home/root# python2.7 --version
Python 2.7.18
***@***.***:/home/root#

I'm having this version of python and python3 also but why is this
happening....

**Comment by omg-itsme** [comment]
root@root:/home/root# 
root@root:/home/root# python2.7 --version
Python 2.7.18
root@root:/home/root# 

I already installed and i'm having the above version of python2.7 but why is this
happening....

**Comment by Bilb** [comment]
what does `python --version` return ?

**Comment by omg-itsme** [comment]
python3  --version

Python 3.8.5

python2 --version

Python 2.7.18

But nothing for

python --version

**Comment by Bilb** [comment]
you should be able to just
`alias python='/usr/bin/python2.7` before calling your build command.

Another way would be to follow the update-alternatives over here https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux#h2-change-python-version-system-wide

**Comment by peepopoggers** [comment]
dont you think it would be a better idea to use commands like python2 ... rather than python ...

**Comment by Bilb** [comment]
this is not something I control, it's coming from the node-gyp package itself. Feel free to open an issue on their side
