### ISSUE TITLE
Notification sound (& LED) does not work on Xiaomi Mi 10 Pro

### ISSUE THREAD

**Issue by pythonInRelay** [oxen-io/session-desktop#1729]
I've a [Xiaomi Mi 10 Pro](https://www.mi.com/global/mi-10-pro/) with Session installed from the Google Play Store. EDIT: I have tried the latest .apk from Github and it has the exact same issue. I only really get notifications when my phone screen is on, or app is open. I never get the sound.

It does not play a notification tone when I get a message. Only very, very rarely when I open the app do I get the tone (sometimes many overlapping), but the LED never flashes when I have a message, no matter what color I pick.

The phone does vibrate after a few seconds when a message is received, however neither the LED option works or the notification sound plays.

I am using:

* Mi 10 Pro phone
* Battery optimizations disabled for Session
* Autostart allowed
* Vibrate on
* DND/Silent mode off
* Fast Notifications setting in Session

All of my other apps that get push notifications function totally normally, for example Telegram.

I will also make clear that the messages ARE received immediately, there is just no notification/indication of getting a message unless my phone is unlocked and the screen is on. Even in that case, the tone still does not play and the LED never flashes regardless.

I've also tried changing the tone numerous times.

**Comment by Bilb** [comment]
Hi. this is a session-android issue not a Session desktop issue
