### ISSUE TITLE
"Clear All Data" button doesn't work

### ISSUE THREAD

**Issue by 144** [oxen-io/session-desktop#1730]
**Describe the bug**
"Clear All Data" button doesn't work at all.

**To Reproduce**
Settings -> Press "Clear All Data" button.

**Screenshots or Logs**
[video](https://streamable.com/unaf8a)

**Other information (please complete the following information):**

* Device: PC
* OS: Windows 10 (21H1)
* Session Version or Git commit hash: v1.6.5 (c992deb6f8f738ed747d0787dedc919ed8f80ff8)

**Comment by netCrunch** [comment]
oblodisz gosciu Xd ?

**Comment by Bilb** [comment]
@144 could you give 1.6.6 a try?

**Comment by 144** [comment]
> 
> 
> @144 could you give 1.6.6 a try?

It works now, thanks!
