### ISSUE TITLE
Scaling + new messages doesn't reset.

### ISSUE THREAD

**Issue by FatBirdie** [oxen-io/session-desktop#1742]
If there is a new message in a group (have not tested private chat, but assume its the same)
And you go to change the text scaling before reading the message, you then go to read it, Session desktop will not reset the counter and it will say (1) or however many messages there are including "X unread message" in the message window.

Beyond that,
there are still issues on desktop with new messages not being cleared sometimes.Even if one goes to read a new message, he (1) is still there and one has to scroll up and down again in the message window in order to clear out the number of new messages. 
Don't know if these two relates to each other.

**Comment by Bilb** [comment]
Should be fixed in 1.6.8
