### ISSUE TITLE
[Windows] Update Fails and leaves last version inoperant.

### ISSUE THREAD

**Issue by overtinkering** [oxen-io/session-desktop#1749]
When starting Session suggests update, update reports failed install, only possible to cancel or close (been waiting several minutes)

Session.exe is not anymore where the launcher shortcut pointed to.

Steps to reproduce the behavior: Start session when a new version is available.

* Device: PC
* OS: Windows 10 latest updates applied
* Session Version difficult to tell now that is gone, but i'd say last official(no git).
*

**Comment by overtinkering** [comment]
the issue turned worse. I managed to install 1.6.6 over it without losing my messaages and contacts (BTW we need backup feature ASAP!). It still suggest to update at start. Accepting makes Session inoperant again. Rejecting update shows messages, but refuses to send new messages because 1.6.6 (last available as full install) is too old to interoperate (go figure).

**Comment by Bilb** [comment]
Can you five 1.6.8 a try?
