### ISSUE TITLE
[Windows] Trojan:Win32/Emali.A!cl

### ISSUE THREAD

**Issue by 6heads** [oxen-io/session-desktop#1755]
When I download V1.6.6 from https://getsession.org/windows and scan it using Windows Defender a virus is detected.

**Comment by Bilb** [comment]
Could you send me a report or a screeenshot of the result please?
Looking at virusTotal output, the binary of 1.6.6 is not marked as coinminer anymore.
https://www.virustotal.com/gui/file/1692ff44e625bb50cf6d9e970e5c488e00308d4f9815595b36656b38cbf85994/detection

**Comment by 6heads** [comment]
I send it to microsoft for a deeper analysis, and it was confirmed, that it's all ok.
