### ISSUE TITLE
Metadata protection

### ISSUE THREAD

**Issue by FatBirdie** [oxen-io/session-desktop#1756]
I'm assuming the "Send Link Previews" refer to the metadata protection dialog which is displayed whenever a URL is pasted.

Very annoying to have to click "Cancel" for every single URL pasted. If the setting is set to "off", then it should be silent?

**Comment by Bilb** [comment]
we are working on this

**Comment by FatBirdie** [comment]
One more thing related to this

When the 'metadata' dialog appears, it still allows for the message to be sent. Also, it does not make either OK/Cancel buttons active.

Additionally, when the dialog appears, and you click in the middle of the window somewhere (outside the dialog), all tex gets highlighted. Aliases, message window, msg box, except the dialog itself. No major thing, but thought I'd mention it.

**Comment by Bilb** [comment]
can you confirm this is fixed in 1.6.10?

**Comment by FatBirdie** [comment]
This seems to be okay
