### ISSUE TITLE
Copy/paste linebreak

### ISSUE THREAD

**Issue by FatBirdie** [oxen-io/session-desktop#1758]
I just copied text from a message in an open group, containing line breaks.

When I went to paste it, all the line breaks are replaced by "" (nothing)

**Comment by peepopoggers** [comment]
![image](https://user-images.githubusercontent.com/72892531/124365982-f833dc80-dc43-11eb-8919-29663542e73d.png)

It might be a text display issue compared to an actual input issue, as i was able to copy what you typed without issue.

**Comment by peepopoggers** [comment]
![image](https://user-images.githubusercontent.com/72892531/124366010-329d7980-dc44-11eb-8a43-95b801bd0e22.png)

Confirmed to happen when you select text with cursor. When using "copy text" button this does not happen.

**Comment by Bilb** [comment]
Should be fixed in 1.6.11

**Comment by Bilb** [comment]
Reopening as it works for message sent by someone else, but it looks like message sent by yourself gets all new line removed

**Comment by Bilb** [comment]
Fixed in 1.7.3
