### ISSUE TITLE
Please add a systray

### ISSUE THREAD

**Issue by joenepraat** [oxen-io/session-desktop#1759]
**Describe the bug**
On Ubuntu Linux, Session doesn't have a systray icon. It also doesn't run in another way in the background. That means that the application needs to be open all the time in the dock. 

**To Reproduce**
Close Session and you won't receive notifications on the desktop anymore.

**Screenshots or Logs**
N/A

**Other information (please complete the following information):**

* Device: PC
* OS: Ubuntu 20.04
* Session Version or Git commit hash: v1.6.6 (Flatpak)

**Comment by peepopoggers** [comment]
Confirmed, no systray on linux. 
I have an electron systray setup (probably very scuffed) that works on linux.

```js
const mainWindower = createWindow();
	let tray = null;
	tray = new Tray(path.join(__dirname, './public/FAVICONIMAGE.png'));

	const trayOptionHandler = option => {
		// TrayOptionHandler = trayOptionHandler.bind(trayOptionHandler);
		if (option === 'open') {
			mainWindower.show();
			tray.destroy();
			tray = new Tray(path.join(__dirname, './public/FAVICONIMAGE.png'));
			const contextMenu = Menu.buildFromTemplate([
				{label: 'Open Session', type: 'normal', click: () => trayOptionHandler('open')},
				{label: 'Quit Session', type: 'normal', click: () => trayOptionHandler('close')}
			]);

			tray.setToolTip('Session');
			tray.setTitle('session');
			tray.setContextMenu(contextMenu);
		}

		if (option === 'close') {
			mainWindower.removeAllListeners('close');
			mainWindower.removeAllListeners('window-all-closed');
			app.quit();
		}
	};

	const contextMenu = Menu.buildFromTemplate([
		{label: 'Open Session', type: 'normal', click: () => trayOptionHandler('open')},
		{label: 'Quit', type: 'normal', click: () => trayOptionHandler('close')}
	]);
	tray.setToolTip('Session');
	tray.setTitle('Session');
	tray.setContextMenu(contextMenu);

	mainWindower.on('close', event => {
		event.preventDefault();
		mainWindow.hide();
	});
```

**Comment by peepopoggers** [comment]
smth like this ^ maybe (there is way better logic than this)

**Comment by ShawnNogi** [comment]
Would be nice to have this on windows as well..

**Comment by Yanta0205** [comment]
+1. And the ability to start minimized.

**Comment by Bilb** [comment]
A setting should be shown in 1.6.11

**Comment by joenepraat** [comment]
Thanks! It works!

**Comment by joenepraat** [comment]
@Bilb I said it works, but there is a unfortunately a problem. When I minimize the Session desktop app to the systray (with the x button), the application is closed after a while (~10 min.).

**Comment by peepopoggers** [comment]
Sounds great

**Comment by rauldipeas** [comment]
There's possible to implement a notification badge to the tray icon when new messages arrived?
