### ISSUE TITLE
Sent Emoticons differ from the ones from Emoji Picker

### ISSUE THREAD

**Issue by 144** [oxen-io/session-desktop#1761]
**Describe the bug**
Sent Emoticons differ from the ones from Emoji Picker

**To Reproduce**
Open "Emoji Picker" -> Select Emoji (for example "gun") -> Send it

**Screenshots or Logs**
[Picker](https://i.imgur.com/R8bkQLZ.png) | [Sent](https://i.imgur.com/Rh33xRx.png)

**Other information:**

* Device: PC
* OS: Windows 10
* Session Version: 1.6.6

**Comment by peepopoggers** [comment]
maybe it is different twemoji versions? :thinking:

**Comment by peepopoggers** [comment]
the real gun was only standard a few years back compared to water

**Comment by Flam3z** [comment]
Pretty sure the real gun was removed entirely due to the amount of school shootings at that time but I could course be wrong but it makes sense.

**Comment by Bilb** [comment]
Probably linked to https://github.com/oxen-io/session-desktop/issues/1905

**Comment by peepopoggers** [comment]
Able to replicate on popos appimage. I don't know much about how emojis are processed but does session use an outdated version of twemoji for the emoji picker?

**Comment by peepopoggers** [comment]
Okay, looked into it. The emoji picker uses an emoji sheet and when they are displayed on their own the sheet is not used, therefore the sheet must be outdated.

**Comment by Bilb** [comment]
this should be fixed as we now rely on unicode
