### ISSUE TITLE
Suggestion: Seperate groups and messages

### ISSUE THREAD

**Issue by peepopoggers** [oxen-io/session-desktop#1762]
If you are in lots of groups, differing DMs and groups can be difficult.
It would be useful to seperate groups and DMs into seperate categories so that they are easier to browse.

If this is very intentional decision to have both groups and DMs in the same list, maybe it could be a togglable settings option.
Thanks :)

**Comment by peepopoggers** [comment]
Hmm, I just realized, there is "contacts"

**Comment by peepopoggers** [comment]
but then its like:
groups+dms
&
dms

which might not be the best setup.

**Comment by peepopoggers** [comment]
Might be better to seperate DMs and groups completely :shrug:

**Comment by Bilb** [comment]
We originally had a group tab after the contact tab, but that did not make much sense to have to check different tab to see which chat was active. So we decided to keep them all in a single tab. You can mute notifications if needed on a per conversation basis
