### ISSUE TITLE
Suggestion: Preview emojis while typing

### ISSUE THREAD

**Issue by peepopoggers** [oxen-io/session-desktop#1763]
When typing emoji names, for example, `:joy:`, it would be convenient to see a preview to confirm that it was typed in correctly and to know you typed the right emoji.

The ideal display would be a little popup box above the text bar displaying the emoji/emojis that match the text.

Element (matrix client) has a very nice example of such an implimentation.
![image](https://user-images.githubusercontent.com/72892531/124366377-51513f80-dc47-11eb-9c3a-7c38e269b9e3.png)
This could be introduced to the session client (with a bit of ctrl+c and ctrl+v :smile_cat:) and would improve user experience.

**Comment by yougotwill** [comment]
This feature has been added. Closing
