### ISSUE TITLE
Clicking around popup elements should exit them

### ISSUE THREAD

**Issue by peepopoggers** [oxen-io/session-desktop#1764]
**Describe the bug**
It is pretty commonplace for popups to close when clicking the area around them, however on the session client, the only way to close them is by clicking x

**To Reproduce**
open "path","profile","recovery phrase",etc  -  all using popup element

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/72892531/124366432-d50b2c00-dc47-11eb-8d6a-8c11c21df445.png)

Fix would be adding a feature such as:
when whole page clicked (while popup open) if popup is not under cursor as of time of click, close element.

**Comment by Bilb** [comment]
Should be fixed in 1.6.8
