### ISSUE TITLE
Improvement: Remove the two-button controls below left sidebar

### ISSUE THREAD

**Issue by peepo5** [oxen-io/session-desktop#1765]
These buttons change page-to-page and are not consistent in their use cases.
You can add someone to dm using the + on Messages, but you have to go to the bottom to add a group.
It was actually hard to find howto join a public group because it felt unnatural to go to that area of the page.

Areas that would need to be removed (controls moved):
![image](https://user-images.githubusercontent.com/72892531/124366521-55ca2800-dc48-11eb-900f-51b823f3fc42.png)
![image](https://user-images.githubusercontent.com/72892531/124366523-5cf13600-dc48-11eb-8111-17f30297f500.png)

## Settings:

Before:
![image](https://user-images.githubusercontent.com/72892531/124366615-fd475a80-dc48-11eb-982e-3ea27a9a6a9a.png)

After:
![image](https://user-images.githubusercontent.com/72892531/124366601-e30d7c80-dc48-11eb-88c2-ebd8aa3a4e26.png)

## Messages

Before:
![image](https://user-images.githubusercontent.com/72892531/124366710-8eb6cc80-dc49-11eb-8d5e-54c41de17ff3.png)

After:
NOTE: The color being different is probably not the best design choice: there is a limit of what I can do in inspect element, but the ideal setup would be a new icon inferring adding a group. More comments in additional notes.
![image](https://user-images.githubusercontent.com/72892531/124366687-63cc7880-dc49-11eb-93a8-bb1fd57187d7.png)

## Additional notes

Even though making these changes is an opinionated issue, I feel that this layout will help new users much more.
A different design change for messages could be having a popup with multi-options like below:

![image](https://user-images.githubusercontent.com/72892531/124366833-8317d580-dc4a-11eb-9e77-733bcd14272d.png)

**Comment by peepopoggers** [comment]
I feel the two-button controls section can be used in a much more meaningful way.
If functions are randomly distributed across UI it can be confusing for new users.
If more options are added in the future, they can be used, but the placement must make sense.

**Comment by KeeJef** [comment]
This is now resolved, we have changed the settings menu and updated the way you join communities and create closed groups
