### ISSUE TITLE
Suggestion: Enter password only once

### ISSUE THREAD

**Issue by 144** [oxen-io/session-desktop#1768]
Having to enter password 2 times is kinda annoying, first to open the app and second time when you want to change/view something in the settings.

![image](https://i.imgur.com/xXXdj1b.png)

**Comment by Bilb** [comment]
well, this is to make sure someone doesn't come and grab your recovery phrase nor change your settings while you are away.
@KeeJef do we want to just ask for it when showing the recovery phrase instead and change/delete the password?

**Comment by KeeJef** [comment]
Yeah settings probably don't need to be behind a password prompt, i think this should just be for showing the recovery phrase

**Comment by Bilb** [comment]
Easy enough then. We just want it for the login screen and the recovery phrase dialog

**Comment by Bilb** [comment]
closed in favor of https://github.com/oxen-io/session-desktop/pull/3059/
