### ISSUE TITLE
[FTR] Add in Settings block Alt button show browser menu

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-desktop#1769]
If use key Alt in client show top browser menu

maybe better have functional blocked show this menu, because if i use alt  + tab or other keybind i see this menu constantly and the window jumps it is very unpleasant.

**Comment by Bilb** [comment]
Hey, 
I don't reproduce this issue, the menu is shown if and  only if I press ALT alone and not a combination of ALT + something.
What's your OS?

**Comment by xbvrhlmb** [comment]
Linux
I meant to disable in the settings reacting the Alt button (show menu)
because if i write text and miss click alt UI show/hide this menu

**Comment by Bilb** [comment]
Yeah, I think electron does that by default to make sure the menu is always accessible to the user, but we have the setting to toggle it in Session.
So I will disable the alt button

**Comment by xbvrhlmb** [comment]
the thing is that when I put "Turn off alt" in the setting and after restarting the client, it works again, that is, I constantly need to go to the settings and click "Hide the system menu"
