### ISSUE TITLE
Windows 1.6.7 installer, trigger antivirus software euristics.

### ISSUE THREAD

**Issue by rjmalagon** [oxen-io/session-desktop#1771]
I already send false positive reports to Microsoft and BKAV. But some analysis tools finds some warnings about the uninstaller routine and other little things.

I am not qualified to bring a personal opinion, but I report this for your consideration.

session-desktop-win-1.6.7.exe
https://www.virustotal.com/gui/file/60bbf160bf48a8ac7847610196bd339a98d9c8c86659d714693dfc87c515332c/relations

Uninstall Session.exe
https://www.virustotal.com/gui/file/b1a18aba038fed98ff3f1c716858d8635040090748da283845136348139e1e56/detection

nsDialogs.dll 
https://www.virustotal.com/gui/file/1e40211af65923c2f4fd02ce021458a7745d28e2f383835e3015e96575632172/detection

**Comment by ShawnNogi** [comment]
Perhaps the uninstall session flag can be fixed if the file is signed?

**Comment by Bilb** [comment]
Hi,
Looks like this could come from electron-builder. Going to update to 22.5.0 for the next release to see if that fixes the issue.
https://github.com/electron-userland/electron-builder/issues/4793

**Comment by Bilb** [comment]
Could come from electron-builder itself. Going to include version 22.5.0 for next release to see if that helps.
https://github.com/electron-userland/electron-builder/issues/4793

**Comment by KeeJef** [comment]
Any improvements for virus protection in recent releases? this has been a constant and persisting issue for us

**Comment by Bilb** [comment]
I'll close this as we do not have any news about this
