### ISSUE TITLE
Messages are marked as read without being focused

### ISSUE THREAD

**Issue by ChrisMiuchiz** [oxen-io/session-desktop#1772]
**Describe the bug**
The app does not ensure that it is focused before marking messages as read. Since this also controls when and if notifications are displayed, it also causes a failure to notify the user of incoming messages if a chat is open but not visible (for example, on another workspace).

**To Reproduce**
Open a conversation
Hide Session (for example, by going to another workspace)
Receive a message in the open conversation

**Screenshots or Logs**
N/A

* Device: Desktop
* OS: Ubuntu 20.04
* Session Version or Git commit hash: v1.6.7

**Comment by Bilb** [comment]
@Brice-W is working on this

**Comment by Bilb** [comment]
Should be fixed in 1.6.8
