### ISSUE TITLE
Some messages in open groups randomly are not received by session-desktop

### ISSUE THREAD

**Issue by laurin-1** [oxen-io/session-desktop#1773]
Some messages in open groups are not received, when others reply to them they're shown as "original message not found". This seems to happen randomly, but doesn't appear to happen with messages from all users, only some, I know that at least a few of them use the same Session ID on multiple devices, this may or may not be the cause for the bug.
Only session-desktop seems to be affected by this, the mobile apps don't appear to have this bug, at least according to other users.

I confirmed this as well while testing out the bot, it received some open group messages that the desktop client didn't. 
This bug has been around for some time now and has been confirmed to me by a couple of users, it affects at least Linux distros and Windows, but probably MacOS as well, since it's the same electron app on all three platforms.
I'm currently using the package from the repo on Debian bullseye, version 1.6.7, but the bug existed on previous versions as well.
(The bug happens both with and without using Lokinet)
![issue1](https://user-images.githubusercontent.com/87230375/125162583-fceb1a00-e188-11eb-9cb5-2d6cd513d340.png)
![issue2](https://user-images.githubusercontent.com/87230375/125162593-08d6dc00-e189-11eb-8912-17b80294c4e9.png)
![issue3](https://user-images.githubusercontent.com/87230375/125162598-0ffdea00-e189-11eb-961d-bbe3948e1268.png)

**Comment by laurin-1** [comment]
Still occuring with version 1.6.9 btw.

**Comment by laurin-1** [comment]
Since this affects messages sent by the bot as well, it doesn't seem to have anything to do with users using the same Session ID on multiple devices, it just really seems to be random.

**Comment by KeeJef** [comment]
Regarding messages not received, the one that happened yesterday in the Session open group seemed to be related to some of the duplicate message filtering we're doing on desktop clientside, we have lowered the limit for that. Original message not found could be related to a different issue, not sure 
![image](https://user-images.githubusercontent.com/27277414/127959126-48c4ec9e-7169-464a-8bff-5f0cdc84416e.png)

**Comment by laurin-1** [comment]
Was the duplicate message filtering introduced with version 1.6.7?
Personally, I'd rather receive some duplicate messages instead of not receiving some messages at all.
Maybe lowering the limit will make the bug occur less often.

**Comment by Bilb** [comment]
I am not sure this would be the same bug. 
The bug I fixed recently (by lowering the sensibility) helps specifically for two messages which are the same AND are sent by the same user (here the bot sends the same message everytime you ask it). 
But what you see in the description of this issue seems to be another issue.
I'll keep this issue open until I find out

**Comment by laurin-1** [comment]
Alright, thanks for having a look for it.

**Comment by eyeberic** [comment]
Not sure if this is the same issue or not. 

Noticed that this issue just happened in the "Session" open group. 

Also, there seems to be some discrepancy even from the Sender's side, when trying to "sync" past messages sent by the Sender themselves. 

### Timestamp reference (for trace-back) 

(Reply to KeeJef's message)

- Sent: 1629430041112
- Received: 1629430038663

(Welcome message)

- Sent: 1629430320103
- Received: 1629430318809

### Reference images

_Note: Arrow indicates position where message is missing. Rectangle box is a message in question._

**Sender's POV**

Desktop Client

![Message_Missing_Desktop_Sender](https://user-images.githubusercontent.com/88373201/130178972-8baa96e5-4c46-4f46-9d61-4e01f1912910.png)

Mobile Client (Android)

![Message_Missing_Android_Sender](https://user-images.githubusercontent.com/88373201/130179022-98966660-a69e-441e-b8dd-b2caa47d43bb.png)

** Receiver's POV**

Desktop Client

![Message_Missing_Desktop_Receiver](https://user-images.githubusercontent.com/88373201/130179078-79b31a59-13ff-438a-bcb1-7985e9ec339e.png)

Mobile Client (Android)

![Message_Missing_Android_Receiver](https://user-images.githubusercontent.com/88373201/130179106-26e42435-f598-4daf-8d81-d38e9e3d3903.png)

**Comment by Bilb** [comment]
Going to close this issue as this error shouldn't happen anymore. Let me know if I should keep it opened

**Comment by laurin-1** [comment]
I haven't noticed this issue recently, so I suppose the fix works, thanks for addressing and closing it.
