### ISSUE TITLE
Issues with sending and receiving attachments after updating to 1.6.7

### ISSUE THREAD

**Issue by laurin-1** [oxen-io/session-desktop#1774]
After updating to 1.6.7, some attachments sent by other users randomly are not received by session-desktop, they're just continually shown as loading, but without ever actually being loaded. It affects open groups and private chats, and probably also closed groups, it seems to occur randomly, some attachments are loaded while others are not. 
![issue2-2](https://user-images.githubusercontent.com/87230375/125163153-1c377680-e18c-11eb-8b96-7cf50b00e5b0.png)

The bigger issue though is that after the update sending messages with attachments randomly fails for some attachments with the error "send failed", resending or restarting the client doesn't fix the problem, after multiple tries it's sometimes possible to send the attachment, however this isn't always the case. This affects both .jpg/.jpeg, .png, .mp4 and probably other types of attachments as well, some attachments, namely small screenshots, usually get sent without issues though.
![issue2-1](https://user-images.githubusercontent.com/87230375/125163385-31f96b80-e18d-11eb-9d1f-69287ac54851.png)

I'm using the package from the repo on Debian bullseye, version 1.6.7, the bug did not occur with previous versions. Another user that uses session-desktop on Windows confirmed that he/she experienced the same problem as well.

**Comment by ShawnNogi** [comment]
Windows user here. I am also experiencing all these issues which appears to occur at random.

**Comment by Bilb** [comment]
Hey, is this still hapenning?

**Comment by laurin-1** [comment]
Unfortunately yes, it's also occuring while using 1.6.9, the error that's being displayed under "More information" is "upload to fileopengroupv2 of ... failed" in open groups and "upload to file server v2 of ... failed" in closed groups btw.

**Comment by laurin-1** [comment]
"Large" attachments(less than 6MB of course) like short videos seem to be affected a lot more often than smaller ones like images, which mostly get sent and received without problems.

**Comment by laurin-1** [comment]
I'm hopeful that the commit will fix the bug, because I was able to confirm that it seems to be dependent on latency/connection speed by using Lokinet in addition to Session, which essentially causes double onion routing, the bug almost always occurs, when only using Session then only sometimes.
![screenshot1](https://user-images.githubusercontent.com/87230375/128870036-f53a37a2-d4fd-4248-a683-0b81fb6b815d.png)

**Comment by laurin-1** [comment]
I haven't had any issues recently regarding sending and receiving attachments, so it appears to be fixed, I'm going to close this issue now, thanks for fixing it.
