### ISSUE TITLE
Transparent PNGs do not work in application

### ISSUE THREAD

**Issue by ShawnNogi** [oxen-io/session-desktop#1776]
**Describe the bug**
Transparent PNGs when uploaded have black background instead of being truly transparent. 

**To Reproduce**
Post a transparent PNG

![image](https://user-images.githubusercontent.com/39767738/125179338-c8448600-e1bb-11eb-95b4-77c96a5ca70e.png)

Environment:
Windows 10
Session v 1.6.7

**Comment by Bilb** [comment]
Should be fixed in 1.6.8
