### ISSUE TITLE
Clock out of sync error with specific NTP servers 

### ISSUE THREAD

**Issue by Yanta0205** [oxen-io/session-desktop#1780]
**Description of the bug**

REFER UPDATE AT BOTTOM DATED AUG 12 2021

Session is totally unusable for private use as it cannot send or receive private messages to or from anyone.

Trying to send messages with Windows Session client 1.6.7 to PC on same network and to a remote PC. All three PCs get the same error when attempting to send;

WARN  2021-07-15T12:39:49.325Z Its an clock out of sync error 

The PCs are all in the same state - Sydney Australia. All PCs are on GMT+1000. All PCs have their time less than a second difference from a website that gives current time. 

Using a VPN - The error persists both on and off VPN.
Checked all Windows time related services and they are all running.
Can't see anything obvious in the event logs.
Also turned Windows Firewall off. Same error.

**To Reproduce**
Installed Session 1.6.7 on Windows 10 x64 1809 LTSC 17763.1999.
Shared the session IDs via email
Click + to send a message
Paste the session ID
Type "Hi there" (minus quotes) and click up arrow bottom right.
Within 2 seconds under the text of the message it says "send Failed" and a red stop sign.
Right click message and select More Information

![session_fail](https://user-images.githubusercontent.com/81943074/125790342-7ef8b80d-af75-452a-90e8-3afcf81ef44e.png)
[session_log.zip](https://github.com/oxen-io/session-desktop/files/6823184/session_log.zip)

**Screenshots or Logs**
From Developer console
sendOnionRequestHandlingSnodeEject (C:\Program Files\Session\resources\app.asar\ts\session\snode_api\onions.js:440)
    at async onionFetchRetryable (C:\Program Files\Session\resources\app.asar\ts\session\snode_api\onions.js:550)
    at async RetryOperation._fn (C:\Program Files\Session\resources\app.asar\node_modules\p-retry\index.js:41)
C:\Program Files\Session\resources\app.asar\js\logging.js:114 WARN  2021-07-15T12:48:32.345Z Its an clock out of sync error 
C:\Program Files\Session\resources\app.asar\js\logging.js:114 WARN  2021-07-15T12:48:32.346Z loki_message:::store - send error: Error

UPDATE 24th July: More testing:
Changed the time server for several PCs I'm testing with to 0.au.pool.ntp.org. Then update. I notice that when I try to send a 1-1 message the sent time is advancing, but the receive time seems to be staying static.
![example1](https://user-images.githubusercontent.com/81943074/126860923-e452ae2c-11eb-4c84-9667-67575c0120ab.png)
![example2](https://user-images.githubusercontent.com/81943074/126860925-88b3f414-76bd-4c6a-aa98-e2aa241b3204.png)

WORKAROUND

remove the US time servers, and then setting each PC to use the 0.au.pool.ntp.org through 3.au.pool.ntp.org and synchnising seems to work. Have tested with PCs on LAN, in same state and overseas. Can successfully send/receive. When a US based time server is set as the default the error recurs.

100% reproducible. Of 12 PCs with session installed the same error occurs and setting the NTP servers to AU based servers resolves the issue 100% of the time.

**Other information (please complete the following information):**
* Device: [e.g. PC, Mac] Intel PC I9-10940X
* OS: [e.g. Ubuntu 16.04, Windows 10] Windows 10 17763.1999 x64
* Session Version or Git commit hash: 1.6.7

On AUG 12 2021 I wiped Session from my system completely.
Deleted any left over folders and then installed desktop 1.6.10 after a reboot.
Created a new account then asked people who were previous contacts to send me a message,
They could, however any attempt to respond failed with the same "Clock out of sync" error. 
All I had to do to work around it was select a different NTP server. 
0.au.pool.ntp.org was default - Failed
1.au.pool.ntp.org set & sync'd - Successful
0.au.pool.ntp.org set & sync'd - Succsessful
windows.time.com set & sync'd - Failed.

It seems whatever is the NTP server at the time the app is installed it fails.

**Comment by Bilb** [comment]
@Yanta0205 can you let me know if that still happens in 1.7.3?
