### ISSUE TITLE
[Feature request] Increase allowed file size

### ISSUE THREAD

**Issue by nooblag** [oxen-io/session-desktop#1782]
Is there any scope to possibly increase allowable file sizes from 6MB to maybe 200 or 300MB? At the moment 6MB is too restrictive even to send some images, let alone video messages, etc.

**Comment by KeeJef** [comment]
We are looking at this, currently the cap is not on the file server, its on the onion requests system which has a cap of about 6mb that it can send in one request. The plan is to open this up when Lokinet support is added which will allow for more effective streaming of files

**Comment by nooblag** [comment]
Cool, that's great news! Thanks for considering! :smiley:
