### ISSUE TITLE
Sessions on Mac has been reconginzed as malicious software on Jamf

### ISSUE THREAD

**Issue by ookangzheng** [oxen-io/session-desktop#1790]
**Describe the bug**
Jamf has quarantine Session Mac desktop app as malicious software.

<img width="743" alt="Screen Shot 2021-07-26 at 14 30 01" src="https://user-images.githubusercontent.com/6301735/126943192-cd06d6b4-110b-4d10-bfb5-ee618c1e8a7c.png">

* Device: Mac 
* OS: 11.6
* Session Version: latest version

**Comment by Bilb** [comment]
Hey, virustotal checks are alright  with the last three versions, so I don't know what I can do more.

For instance, this is the result with 1.6.7.dmg https://www.virustotal.com/gui/file/730d5ff3a72b7cdcda14680552bd422e4ed88a514d2de9918be4781c05f97bfa/detection

**Comment by ookangzheng** [comment]
I reported to Jamf, and they reply me this link: https://www.osstatus.com/search/results?platform=all&framework=all&search=-67011
