### ISSUE TITLE
Draft Messages

### ISSUE THREAD

**Issue by GoldenHashtag** [oxen-io/session-desktop#1791]
**Describe the bug**
Unsent messages are not saved as draft when switching contact or exiting program.
It's more of a feature request than bug report but c'mon, this is a basic functionality every IM app already has.

1. Choose a contact (Note to self included)
2. Type some character into message box but don't hit send key
3. Switch to another contact from left side, then switch back
4. Already typed characters are lost

**Other information (please complete the following information):
Session on Android has draft support.

* Device: PC
* OS: Windows 10
* Session Version or Git commit hash: 1.6.7

**Comment by Bilb** [comment]
Next release will include a very basic draft message feature (only text, not saved between restart but only conversation switch)
