### ISSUE TITLE
Invalid password, despite knowing it.

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-desktop#1798]
Ever Since I updated to the latest version Session has been claiming that is the wrong password despite me changing the password several times. This has happened on and off in the past but has seemed to fix itself in random versions but now im back to the same issue.

**Comment by Bilb** [comment]
Hi, is it since the update to 1.6.8?

**Comment by Flam3z** [comment]
yes

**Comment by Bilb** [comment]
did not mean to close it yet

**Comment by invalid-error** [comment]
Just be clear here, when you upgrade a password protected Session Linux client from 1.6.7 to 1.6.8 it doesn't accept your password anymore. It is a major bug!

**Comment by KeeJef** [comment]
We just released 1.6.9 should fix this

**Comment by Flam3z** [comment]
fixed, love u devs :)
