### ISSUE TITLE
App icon is "broken"

### ISSUE THREAD

**Issue by 144** [oxen-io/session-desktop#1803]
**Describe the bug**
Since the last update Session icon is scaled in a weird way.

**To Reproduce**
Download latest Windows version of Session

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/17101532/127325563-a63d898f-d905-413c-8556-d83020667589.png)
![image](https://user-images.githubusercontent.com/17101532/127325598-b6508b5e-8eaa-4324-9de5-acd10ba4cdc3.png)
![image](https://user-images.githubusercontent.com/17101532/127325636-322345a9-d897-49f4-bd4b-e560af86f55d.png)

**Other information (please complete the following information):**

* Device: PC
* OS: Windows 10 21H1
* Session Version: 1.6.9

**Comment by Bilb** [comment]
Should be fixed in 1.6.10
