### ISSUE TITLE
App becomes unusable when a new version is released

### ISSUE THREAD

**Issue by beantaco** [oxen-io/session-desktop#1805]
If I haven't updated my Session client for a little while, I see this message on a red background:

> This version of Session has expired. Please upgrade to the latest version to continue messaging.
> Upgrade

For example, I saw this before I upgraded from 1.6.7 to 1.6.9.

I understand/support informing users there is a new version available, warning users that old versions of the app may be vulnerable, and disabling very old clients that are incompatible with the latest protocol/client. Displaying the red warning message is fine.

However, disabling the client because it's running one or two point releases seems to be overkill. Disabling old clients upon every point release causes Session users to need to *immediately* download the new client, which may be impossible or impractical for them, or else they lose access to messaging. It denies people under certain conditions to reliably use Session: unreliable or slow internet, capped data plans, people who don't have root, etc.

**Comment by Bilb** [comment]
I just tried 1.6.7 and it doesn't require you to update to continue using the app. It shows a red warning, but you can still type and send messages, and get your messages.

Are you sure you were in 1.6.7 before?

**Comment by beantaco** [comment]
Sorry, I failed to confirm the client actually becomes disabled. If the client does not get disabled, no further action is required on this issue.
