### ISSUE TITLE
Session's app icon doesn't show correctly

### ISSUE THREAD

**Issue by beantaco** [oxen-io/session-desktop#1806]
A few versions ago prior to 1.6.9 (installed with Debian package), Session's app icon stopped showing correctly. I expect to see the Session icon with the green "S" but for a while I see just a generic window icon.

Note: I am referring to the icon of the running process, not the icon of the installer (AppImage, Debian package, etc.) or the shortcut/launch/panel icon.

**Comment by KeeJef** [comment]
Related to, closing because these will all be fixed together #1803

**Comment by mdPlusPlus** [comment]
I think this bug has gotten reintroduced at some point, at least for the Linux AppImages.  
It might be resolved with thie PR https://github.com/oxen-io/session-desktop/pull/2381 but I wasn't able to try it out yet.
