### ISSUE TITLE
1.6.9 doesn't place focus on textbox when replying to a message.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#1808]
**Describe the bug**

Previous versions of Session Desktop correctly placed the focus on the cursor in the new message textbox after the user chose to quote-reply to a message.

1.6.9 doesn't give focus to the textbox, so the extra step of clicking in the box must be performed before one can type.

**To Reproduce**
Right-click and choose to Reply to a message. Start typing. Nothing happens. The textbox is not focused.

**Screenshots or Logs**

**Other information (please complete the following information):**

* Device: PC
* OS: Fedora Linux 34
* Session Version or Git commit hash: 1.6.9 official.

**Comment by Bilb** [comment]
should be fixed in 1.6.10

**Comment by ianmacd** [comment]
> should be fixed in 1.6.10

Verified.
