### ISSUE TITLE
"Send link previews" bug is back

### ISSUE THREAD

**Issue by 144** [oxen-io/session-desktop#1810]
**Describe the bug**
It asks you for "link preview" each time you send a link, as described in previous issues.

**To Reproduce**
Send a link.

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: PC
* OS: Windows 10
* Session Version: 1.6.9

**Comment by Bilb** [comment]
should be fixed in 1.6.10
