### ISSUE TITLE
Minimize to tray fails due to missing session_icon_256.png

### ISSUE THREAD

**Issue by pakar** [oxen-io/session-desktop#1816]
**Describe the bug**
Minimize to tray does not work on Ubuntu 20.04 due to "session_icon_256.png" is missing.

**To Reproduce**
Install session-desktop from deb repository (https://deb.oxen.io/)
Attempt to start session:
$ /opt/Session/session-desktop --use-tray-icon

**Screenshots or Logs**
Unhandled Promise Rejection: TypeError: Error processing argument at index 0, conversion failure from /opt/Session/resources/app.asar/images/session/session_icon_256.png
    at createTrayIcon (/opt/Session/resources/app.asar/app/tray_icon.js:20:10)
    at showMainWindow (/opt/Session/resources/app.asar/main.js:703:12)
    at async App.<anonymous> (/opt/Session/resources/app.asar/main.js:644:5)
{"name":"log","hostname":"ryzen","pid":526247,"level":50,"msg":"Unhandled Promise Rejection: TypeError: Error processing argument at index 0, conversion failure from [REDACTED]/app.asar/images/session/session_icon_256.png\n    at createTrayIcon ([REDACTED]/app.asar/app/tray_icon.js:20:10)\n    at showMainWindow ([REDACTED]/app.asar/main.js:703:12)\n    at async App.<anonymous> ([REDACTED]/app.asar/main.js:644:5)","time":"2021-07-30T12:56:41.174Z","v":0}

**Other information (please complete the following information):**

* Device: PC
* OS: Ubuntu 20.04
* Session Version or Git commit hash: 1.6.9

**Comment by FatBirdie** [comment]
Didn't know --use-tray-icon was a thing, I've been hoping for a good while now that the option would show up under settings but after now testing the switch I can confirm that it crashes Session appimage on Mint/Cinnamon.

**Comment by Bilb** [comment]
Should be fixed on 1.6.10
