### ISSUE TITLE
Feature Request: Video Recorder

### ISSUE THREAD

**Issue by KlimaRitter** [oxen-io/session-desktop#1817]
Feature Request to record videos directly out of session (like it is possible already with photos)

**Comment by KeeJef** [comment]
Do you mean the ability to save videos people sent to you via Session, or some in app recording feature?

**Comment by Flam3z** [comment]
I think they mean an in app recorder

**Comment by KeeJef** [comment]
Yeah that's not going to be something we are going to implement, that can be handled by an external application
