### ISSUE TITLE
Random message from public group is stuck at the screen

### ISSUE THREAD

**Issue by 144** [oxen-io/session-desktop#1820]
**Describe the bug**
Random message from public group is stuck at the screen. After loading open group messages one of them is stuck at the screen and Session is pretty much unusable.

**To Reproduce**
Join open group and start scrolling through messages while they are loading (first time it happened for me, might be hard to reproduce)

**Screenshots or Logs**
[video](https://streamable.com/9gcrh0)

**Other information (please complete the following information):**

* Device: PC
* OS: Windows 10
* Session Version: 1.6.9

**Comment by Bilb** [comment]
@144 can you let me know if 1.6.10 fixes the issue (it should)

**Comment by 144** [comment]
> 
> 
> @144 can you let me know if 1.6.10 fixes the issue (it should)

Everything seems to work fine now, thanks!
