### ISSUE TITLE
[Feature request] hyperlinks

### ISSUE THREAD

**Issue by FatBirdie** [oxen-io/session-desktop#1836]
I'm not sure to what extent this is possible to do:

Would it be possible for Session to register hyperlinks like sessionid:// or sessiongroup:// for hyperlinking Session IDs and groups in html/on websites? Could be very useful if possible to implement.

**Comment by Bilb** [comment]
Is this the same as https://github.com/oxen-io/session-desktop/issues/1072 ?

**Comment by FatBirdie** [comment]
Sorry, didn't know it was already proposed. This is the same.
