### ISSUE TITLE
Unread messages counter to exclude counting unread messages from muted (all) chats

### ISSUE THREAD

**Issue by eyeberic** [oxen-io/session-desktop#1840]
### Current: 

- Unread message counter counts for all unread messages regardless of notification setting for that conversation. 

### Expected: 

- Unread message counter should only count unread messages from chats that are set to either **notify for all messages** / **tagged (@'d) messages**, and not include messages from chats with **notifications disabled**. 

### Example: 

![Unread_Indicator](https://user-images.githubusercontent.com/88373201/128802654-45f4c74d-d13f-480a-aaa2-523e948d0101.png)

**Comment by Bilb** [comment]
Should be fixed in 1.6.11

**Comment by eyeberic** [comment]
Issue verified to be resolved with #1876
