### ISSUE TITLE
Clicking on notification popup for new message does not bring conversation to focus

### ISSUE THREAD

**Issue by eyeberic** [oxen-io/session-desktop#1841]
**Describe the bug**

- When a new message notification arrives, clicking on it does not bring the relevant conversation to focus, but instead goes to Session splash screen. 
- Even when the conversation is already open and in the background (minimize), click on the notification will still redirect to the Session splash screen. 
- Bug was not present in previous version of v.1.6.9

**To Reproduce**

1. Receive a pop-up notification about a new message
2. Click on the notification
3. Session app is brought forward to the foreground, but redirects to the Session splash screen

**Screenshots or Logs**

![Splash_Page](https://user-images.githubusercontent.com/88373201/128804955-79a5b470-a403-4138-bcea-60a3ab3565be.png)

_(Image has been edited to hide conversation list, mainly focusing on the Splash Screen)_

**Other information (please complete the following information):**

* Device: Linux (AppImage)
* OS: Zorin OS 15 (Ubuntu 18.04.1)
* Session Version or Git commit hash: v1.6.10

**Comment by Bilb** [comment]
Got a fix which will be in the next release

**Comment by eyeberic** [comment]
Closing issue: Issue verified to have been resolved in #1876

**Comment by Bilb** [comment]
too quick haha, I was about to close it. A new release was just published
