### ISSUE TITLE
[FR] URI pop-up window with 'Copy' option

### ISSUE THREAD

**Issue by invalid-error** [oxen-io/session-desktop#1842]
When you click on a weblink (within a message) it just allows you to

A. `Cancel` the operation
B. `Open` the link in your (default) browser

It would be nice to have a third option:

C. **`Copy`** to clipboard 

As a side note, for the readability it would be also better to add a new line for the URI. Currently, it is one text block.

**Comment by Bilb** [comment]
Should be fixed in 1.6.11
