### ISSUE TITLE
Messages from the future

### ISSUE THREAD

**Issue by Marky-N** [oxen-io/session-desktop#1844]
**Describe the bug**
Had a person message me for first time and the message came with the time stamp note, "in 4 hours". Don't know anything about the senders

**To Reproduce**
No idea how to reproduce it.

**Screenshots or Logs**
iOS:
![20210811_125303000_iOS](https://user-images.githubusercontent.com/77722427/129036372-5dd4fa34-77de-4091-ab04-c7cfc76903dd.jpg)

Desktop:
<img width="695" alt="Screenshot 2021-08-11 at 15 53 28" src="https://user-images.githubusercontent.com/77722427/129036450-ed6c5709-5f74-4db2-8bef-de65750eebca.png">

**Other information (please complete the following information):**

* Device: MacOS / iOS iPhone 11, 11.5.1/14.7.1
* OS: [e.g. Ubuntu 16.04, Windows 10]
* Session Version 1.6.10 / 1.11.13

**Comment by peepopoggers** [comment]
ooo spooky

**Comment by Bilb** [comment]
Hi,
we have an idea of where that might come from.
The fix won't probably on the next release as it's UI only but probably in the one after. I'll tag this issue

**Comment by peepopoggers** [comment]
:+1:

**Comment by Bilb** [comment]
Should not happen anymore
