### ISSUE TITLE
iOS App Crashes when trying to Scan QR Code to link PC to iPhone

### ISSUE THREAD

**Issue by White-BrownFox** [oxen-io/session-desktop#1845]
When I try to link my iPhone (iOS 14.7.1) to my PC (Ubuntu 21.04), the app crashes on my phone immediately and the process fails .
Both Session apps on my iPhone and Ubuntu are latest versions as of Aug 12 2021.

**Comment by Bilb** [comment]
Hi,
Can you make sure you tried to scan the Qrcode of your seed phrase and not  the one from your pubkey.
So the one shown in the Settings tab -> Recovery Phrase.

![image](https://user-images.githubusercontent.com/1544279/129285173-88fbde5b-0609-4186-b0d8-8fe317a5aa37.png)
