### ISSUE TITLE
Hebrew font to small

### ISSUE THREAD

**Issue by infernusec** [oxen-io/session-desktop#1848]
**Describe the bug**
The hebrew font looks bad on desktop app, its small and unreadable...

- Please allow to change the font with Installed local fonts on machine...

**To Reproduce**
Send a hebrew text to someone..

**Screenshots or Logs**
https://i.imgur.com/F9EzjLT.jpg 

**Other information (please complete the following information):**

* Device: PC
* OS:  Fedora 34
* Session Version or Git commit hash: 1.6.10

**Comment by Bilb** [comment]
Is this still happening?
