### ISSUE TITLE
Moderator's crown symbol is not displayed

### ISSUE THREAD

**Issue by invalid-error** [oxen-io/session-desktop#1857]
**Describe the bug**
Moderator's crown symbol is not visible in the open group 'Oxen'.

**Screenshots or Logs** (time stamp: 2021, Aug. 17th)
![image](https://user-images.githubusercontent.com/55282571/129682577-b60ddbf6-11e0-41b7-92de-6234be93d53e.png)

* Session Version or Git commit hash:
AppImage 1.6.10

* Note
Crowns are visible in the open group 'Session' and 'lokinet'
(also no issue on linked Android client)

**Comment by Bilb** [comment]
Can you tell me if switching to another conversation and opening Oxen again fixes the issue? I'm trying to find the root cause

**Comment by invalid-error** [comment]
> Can you tell me if switching to another conversation and opening Oxen again fixes the issue?

Still no crowns, Screenshots or Logs (time stamp: 2021, Aug. 24th), AppImage 1.6.11
![Screenshot-Session-NoModeratorCrowns-2](https://user-images.githubusercontent.com/55282571/130572786-5611ddbc-d26a-481d-8ca7-9eedd2522448.png)

**Comment by Bilb** [comment]
Does this still happens?

**Comment by invalid-error** [comment]
> Does this still happens in 1.7.1?

No, looks good now. Thanks for the fix.
