### ISSUE TITLE
Replying on message with link, loads no preview

### ISSUE THREAD

**Issue by Marky-N** [oxen-io/session-desktop#1859]
**Describe the bug**
When replying to a message with a link, it doesn't load the preview.

**To Reproduce**

**Screenshots or Logs**
![Screenshot 2021-08-17 at 12 00 57](https://user-images.githubusercontent.com/77722427/129696777-212e96b5-27dd-4c80-a8ed-c003e93a5fac.png)

**Other information (please complete the following information):**

* Device: MacBook Pro
* OS: MacOS 11.5.1
* Session Version or Git commit hash: 1.6.10

**Comment by KeeJef** [comment]
I dont think this is an issue with Session, for example a link preview for https://session.directory/ cannot be generated in Telegram, perhaps Session directory is missing the necessary meta tags https://andrejgajdos.com/how-to-create-a-link-preview/

**Comment by Marky-N** [comment]
![Screenshot 2021-09-28 at 8 49 05](https://user-images.githubusercontent.com/77722427/135030547-595d6159-b87e-48af-be3d-245173afd43c.png)
The point was not about Session.directory website, that was just used as an example. As you can see in the image, it will load the preview, but as I wrote in the original ticket, it doesn't load the preview for a link "if answering to a message".
