### ISSUE TITLE
[Translate] Avatar Edit

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-desktop#1863]
No translate in other language

1) Open self profile
2) Focus avatar

![session_avatar_edit](https://user-images.githubusercontent.com/43858033/129932573-21f71aeb-8bc9-4c1b-a9cf-c9a5c20f06e2.png)

**Comment by Bilb** [comment]
https://crowdin.com/project/session-desktop

**Comment by xbvrhlmb** [comment]
@Bilb  not fixed
