### ISSUE TITLE
[Translate] alert body message and delete message other language

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-desktop#1864]
No translate in other language
![session_body](https://user-images.githubusercontent.com/43858033/129932830-78d21376-afbd-4430-bf71-a582a6e0f8ed.png)

![session_delete](https://user-images.githubusercontent.com/43858033/129932858-6966e680-5d5f-4a91-9521-ca9930caeb35.png)

**Comment by Bilb** [comment]
https://crowdin.com/project/session-desktop
