### ISSUE TITLE
[Translate] Group Page

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-desktop#1865]
No translate in other language

if open "Make new group" button "Done" no translate

![session_group](https://user-images.githubusercontent.com/43858033/129933016-37ba4dce-0bd1-4797-bb9d-c299e35c0c99.png)

*Join group*

![session_group2](https://user-images.githubusercontent.com/43858033/129933018-546deaae-2433-48be-b1ee-e51bb46bb221.png)

**Comment by Bilb** [comment]
https://crowdin.com/project/session-desktop
