### ISSUE TITLE
Client freezes / lags when switching between chats

### ISSUE THREAD

**Issue by eyeberic** [oxen-io/session-desktop#1878]
### Describe the bug

_(Mainly re-opening #1837 - @FatBirdie @Bilb)_

The client momentarily freezes / lags when switching between chats. 

The duration is extremely noticeable especially when switching to groups of sizeable member count: Delays averages about 2 to 3 seconds. 

I suspect it might have to be with the following output in the Console: 

```
INFO  2021-08-20T12:39:34.628Z getPubkeysInPublicConversation returned '300' members
/app/Session/resources/app.asar/js/logging.js:114 

WARN  2021-08-20T12:39:34.630Z updating mentions input members length 300
```

### To Reproduce

**Main target: "Session" open group**

- Start from Session splash page after client fully loaded
- Switch to a conversation with small amount of members (e.g. Note to Self, 1-to-1 chat): ~0.4 secs
- Switch to a group chat with small amount of members (Less than 50): ~1 secs
- Switch to a group chat with large member count (Greater than 1000): ~2.3 secs

### Screenshots or Logs

Exported a Performance Profile record for examination (in ZIP because GitHub)

[Profile-20210820T201730.json.zip](https://github.com/oxen-io/session-desktop/files/7021412/Profile-20210820T201730.json.zip)

### Other information (please complete the following information):

* Device: Linux (AppImage)
* OS: Zorin OS 15.3 (Ubuntu 18.04.01)
* Session Version or Git commit hash: 1.6.10*

---

_*Issue is also present in 1.6.11, but I did the Performance Profile recording in 1.6.10_

**Comment by eyeberic** [comment]
After clearing local data (as per #1886 ) and re-setup using the recovery phrase, this Issue does not occur anymore. 

I will still leave this Issue open, as the workaround of having to clear local data may not be acceptable to other users.

**Comment by Bilb** [comment]
I think I might have an idea of the issue. I'll get a fix for next release.

**Comment by Bilb** [comment]
@eyeberic did 1.7.0 help?

**Comment by eyeberic** [comment]
I did not experience the issue ever since the previous comment of clearing the local data, and did not notice any difference using 1.7.0. 

I will close this Issue for now, and will reopen and reference back to this if the Issue occurs again.
