### ISSUE TITLE
Improvements regarding tray icon

### ISSUE THREAD

**Issue by laurin-1** [oxen-io/session-desktop#1882]
First of, I would like to say that I really like the addition of the tray icon, however there are some improvements that can be made to it imo.

When showing Session after it was hidden in the tray, the active text field is the "Search for conversations or contacts" field and not the "Message" field which it should be imo.
![image](https://user-images.githubusercontent.com/87230375/130425050-1b314e4f-4424-40ce-9ddb-d41e4d3c1355.png)

It would also be nice if there was the option to show the amount of unread messages on the tray icon like it's possible with Signal's tray icon.

**Comment by laurin-1** [comment]
After the update to 1.7.0, scrolling down doesn't automatically mark messages as read anymore after Session was unhidden from the tray icon, making it practically unusable imo.
I'll just abstain from using the tray icon for now, and hope that this will be addressed in the future, I really like using Signal with its tray icon, and hope that Session will have the same functionality in the near future.

**Comment by Bilb** [comment]
@laurin-1 what's your os?

**Comment by laurin-1** [comment]
@Bilb I'm currently using Debian with KDE Plasma.

**Comment by laurin-1** [comment]
> After the update to 1.7.0, scrolling down doesn't automatically mark messages as read anymore after Session was unhidden from the tray icon, making it practically unusable imo. I'll just abstain from using the tray icon for now, and hope that this will be addressed in the future, I really like using Signal with its tray icon, and hope that Session will have the same functionality in the near future.

The issue hasn't got anything to do with the tray icon apparently, since I'm currently using it and it doesn't affect the behaviour, I'm also not sure whether the issue with the messages not being marked as read is even still present, it used to occur sometimes when lauching the client, restarting the client (multiple times) was a short term fix.

**Comment by laurin-1** [comment]
But it has worked fine as far as I remember for the last couple of days, and restarting the client once or twice isn't really a big issue, because once it's running you can just leave it running the entire day without the problem occuring.
The issue with it focussing on the searchbar after unhiding from tray instead of the message field still is present though.
And displaying the amount of unread messages on the tray icon would be nice as well.

**Comment by peepopoggers** [comment]
Still happening?
