### ISSUE TITLE
Issues with disabling link previews

### ISSUE THREAD

**Issue by laurin-1** [oxen-io/session-desktop#1883]
After updating to 1.6.11, although link previews are turned off in settings, they are still received, this should not happen since this feature uses the clearnet afaik, this worked correctly on previous versions.
![image](https://user-images.githubusercontent.com/87230375/130427421-584c03cc-ee47-443d-b2fd-399ae1e15020.png)
![image](https://user-images.githubusercontent.com/87230375/130428473-1417b9b0-1772-4d27-af1b-aa171c9ce853.png)
(Example of link preview, it's shown for YouTube videos as well)

Also, when enabling the feature in the settings, clicking the "Cancel" button to abort the activation does not work, the setting gets activated regardless which of the two buttons is clicked.
![image](https://user-images.githubusercontent.com/87230375/130427974-624d9cec-a008-4acc-9fda-d098b7c45d74.png)

**Comment by Bilb** [comment]
Hey,
Link previews are not metadata safe on the sending side only. 
On the receiving side, the image and everything is IN the message itself, so no fetch is done. So receiving a link preview is safe. This is the way it works on mobile so we made it that way on desktop too.

I'll get a fix for your other issue for next release

**Comment by laurin-1** [comment]
Thanks for the clarification that receiving link previews does not use the clearnet, I was confused because the warning dialog literally states "You will not have full metadata protection when sending or receiving link previews.", that should be updated as well then.
Thanks for addressing the UI bug as well.

**Comment by Bilb** [comment]
good catch for the localized string, I'll change it on crowdin

**Comment by slrslr** [comment]
> I'll get a fix for your other issue for next release

Hi, @Bilb on Linux AppImage 1.10.1 when i click to enable link previews there is a prompt to confirm the action, i cancel it, yet the option shows as enabled, even when i switch to messages and back to settings.
