### ISSUE TITLE
Unable to link devices

### ISSUE THREAD

**Issue by iqgustavo** [oxen-io/session-desktop#1889]
Sorry to bother you with more suggestions I only do it in case you or your team will find them useful. 

I was trying to use the application on Windows I started for the first time the application and I found an option that says link device so I enter my recovery phrase... it only displays an error too quickly that says something like it couldn't find my display name... but gives me no other option ... there is no back button  ... pushing alt+left (as in web pages ) doesn't get me back so the only option left is to push the top left cross that closes the program and restart to find the same problem ... finally I chose the other option ... seems like my devices are not linked but are still working... any help would be greatful on linking devices. android with windows

**Comment by Bilb** [comment]
Will get a fix in next release

**Comment by iqgustavo** [comment]
Great!
Best regards and congrats on a great app!!!
