### ISSUE TITLE
1.7.0 ignores paragraph breaks removed in composed messages.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#1898]
The UI overhaul of Session Desktop 1.7.0 causes paragraph breaks to be ignored.

If I compose a message thus:

```
Paragraph 1.
Paragraph 2.
Paragraph 3.
```

the message is actually sent as:

`Paragraph 1. Paragraph 2. Paragraph 3.`

So, multiple newline characters are seemingly being converted to a single space.

This will make the text of verbose buggers like me look even more intimidating and undigestible.

**Comment by ianmacd** [comment]
On closer inspection, it appears that it's just a display issue, because it's stripping paragraph breaks from every single message, not just the ones I send.

**Comment by JustVictor17** [comment]
https://github.com/oxen-io/session-desktop/issues/1901#issue-990400045

**Comment by Bilb** [comment]
@ianmacd can you check if 1.7.1 is good?

**Comment by ianmacd** [comment]
> @ianmacd can you check if 1.7.1 is good?

Fixed.

Many, many thanks.
