### ISSUE TITLE
Some icons (smileys) don't display (but on the Android app they display fine)

### ISSUE THREAD

**Issue by danmanrana** [oxen-io/session-desktop#1905]
I'm on Debian Unstable using v1.7.0 (AppImage; haven't tested the .deb yet) using the Fluxbox window manager. The missing ones display as what seem like small (boxed) X marks (kind of similar to the Unicode U+2612, 'ballot box with x'). 🦧 and 🦥 are examples.

**Comment by Bilb** [comment]
Just to be sure, those are not available in the right emoji panel right?

**Comment by pgenderson** [comment]
Doesn't seem like it. It's a blushing smiley with three small hearts.

**Comment by peepopoggers** [comment]
I do not see orangutan in the emoji picker. The emoji picker is outdated anyway as talked about in another issue. Not sure if that is relevant for this issue, but maybe these exception emojis are reliant on the OS for rendering or something.

**Comment by Bilb** [comment]
We switched to unicode emojis so this issue should be fixed
