### ISSUE TITLE
New messages can't be read

### ISSUE THREAD

**Issue by 144** [oxen-io/session-desktop#1914]
**Describe the bug**
New messages can't be "read", they are not showing as read.

**To Reproduce**
(untested, in my case i was using Session on mobile and when i launched Session on PC with the new update this bug appeared)
Type messages from alternative account to your main account while Session is disabled (on main).

**Screenshots or Logs**
It just shows messages and:
![image](https://user-images.githubusercontent.com/17101532/133320485-4ba87c54-2574-4440-9e8b-a11a89cd0685.png)
![image](https://user-images.githubusercontent.com/17101532/133320494-7a102a3b-e784-4f80-a2ad-7c4469e6cbd3.png)

Even tho I'm on the bottom of messages it still shows:
![image](https://user-images.githubusercontent.com/17101532/133320542-93f677ac-5d3c-4043-8e63-fa9aaddc8d8c.png)
clicking it does nothing

**Other information:**

* Device: PC
* OS: Windows 10
* Session Version: v1.7.1

**Comment by Bilb** [comment]
Right click on the conversation and "mark all as read" works? It's just to try to understand what is happening here

**Comment by 144** [comment]
> 
> 
> Right click on the conversation and "mark all as read" works? It's just to try to understand what is happening here

Seems like restarting Session a few times fixed the issue.

**Comment by 144** [comment]
Triggered this bug again, "Mark all as read" works, but it takes a while to update gui.

**Comment by 144** [comment]
Happens very often for me, with 2 devices linked Desktop and Mobile

**Comment by Bilb** [comment]
the read/unread message logic has quite changes since 8 months ago. If still happening please reopen
