### ISSUE TITLE
It's not working, the same error occurs.

### ISSUE THREAD

**Issue by lifwon** [oxen-io/session-desktop#1917]
It's not working, the same error occurs.
ERROR code 400 (Invalid ciphertext).

_Originally posted by @lifwon in https://github.com/oxen-io/session-desktop/issues/1894#issuecomment-919891026_

**Comment by lifwon** [comment]
Is this issue anything to do with the storage server as the request is hitting the storage server.

**Comment by Bilb** [comment]
@lifwon I would need your logs. 
there is a debug log window in the menu

**Comment by make-as-easy** [comment]
Im facing the error like in storage server :
```
Parsing payload of length: 873
 Ciphertext length: 785
 ciphertext length: 785
 process_onion_req
 Error decrypting 785 bytes onion request using 1: Could not finalise decryption
 Got an onion response (400 Bad Request) as edge node (after 296µs)

```

**Comment by Bilb** [comment]
Did you add some logs youself? Like that line `ONION_RESPONSE:TS:` ? Because I don't find that line anywhere in the source.

Also, are you running a dev build? or a release? If a dev build, can you give a `MULTI=2 yarn start-prod` a try and tell me if that works ?

**Comment by jagerman** [comment]
This doesn't look like an Oxen Service Node request; those service nodes aren't in the currently active Oxen SN list, and when I query one of them directly to request a swarm I get:
```json
{
  "mnodes": [
    {
      "address": "7ndrywiwbseabd6phhhh499idd1swobo5d89msob7ucg3s3czzyy.mnode",
      "ip": "65.2.3.37",
      "port": "19090",
      "port_https": 19090,
      "port_omq": 1090,
      "pubkey_ed25519": "e8864052b40d91808fcde739cd7ff518e56a4030d8cff5da01ecd86cdb2cbdc0",
      "pubkey_legacy": "e8864052b40d91808fcde739cd7ff518e56a4030d8cff5da01ecd86cdb2cbdc0",
      "pubkey_x25519": "c64036f3a6c085f0e3982971db85abefa7388216fcc8feee897109bdc8647340"
    },
```
which is clearly not an Oxen Storage Server response (the `"mnodes"` key and `.mnode` are obviously from some modified service node software).

**Comment by Bilb** [comment]
@make-as-easy 
I'm sorry, but at this point we cannot provide support for forks of our software stack/network.

**Comment by ssuriyayuvan** [comment]
> @make-as-easy
> I'm sorry, but at this point we cannot provide support for forks of our software stack/network.

Here I'm Using your service node only, but I'm facing same error.
```
Invalid ciphertext
```
