### ISSUE TITLE
Add code blocks.

### ISSUE THREAD

**Issue by necro-nemesis** [oxen-io/session-desktop#1928]
This isn't a request specific to desktop but it seemed as good as any place available to post it.

Is it possible we could have some markdown formatting usage in Session? In particular `lines and blocks of code`. It would add clarity when discussing code related issues.

**Comment by eyeberic** [comment]
Duplicate of #405

**Comment by necro-nemesis** [comment]
Seen. I'm not so hard over on cluttering the interface up with icons to use markdown personally. Telegram doesn't yet it's supported.

**Comment by KeeJef** [comment]
i think we would support this through markdown support, so closing for now
