### ISSUE TITLE
The Service Nodes/Session can't detect duplicate logins across platforms. Which behavior expected?

### ISSUE THREAD

**Issue by argonatorUberTF** [oxen-io/session-desktop#1945]
It is possible to duplicate login to Session with a mobile and desktop client and there is no notification alerting the user that their conversation might be surveilled. 
Steps to reproduce:
1. Install session desktop for Windows or Linux, restore with private passphrase.
2. Install mobile session for Android(I don't own  a iPhone to test). 
Login client 1, and then login client 2 on the same lan or different IPs.
Messages typed by client 1 are not necessarily echoed to client 2 of the same session ID.
Duplicate messages don't appear in public session chats. So the Service Nodes know something about message trafficking at the low level. 

Not sure if this is a feature people would not want or should it be opt-in with settings for such.
Otherwise alert the client 1 that someone just duplicate logged in with client 2 on a different device or different IP/location.
Email clients and web clients of secure logins usually notify and lockdown until backup authorization is provided (another account or Google Authenticator, etc.)
Signal supports this alert.
Or if the option to opt-in for seamless use from desktop to mobile to other platform hardware is allowed.

**Comment by KeeJef** [comment]
This is largely indented functionality, and is the way we support multi device functionality, by essentially restoring the same private key (derived from seed phrase) on both devices. 

We have thought about adding an additional hashed identifier to each new device which shares the same private key, which would allow for clients to display which or how many devices are using the same keys. But we are still working on that idea

**Comment by KeeJef** [comment]
Closing for #2180
