### ISSUE TITLE
Messages display incorrectly when users have diff timezones

### ISSUE THREAD

**Issue by toomuchacid** [oxen-io/session-desktop#1946]
**Describe the bug**
Messages sent between users are displayed based on the time it was sent according to the users device. when I was chatting with someone from Wyoming and I'm in Australia, their messages always went to the top of the conversation, since my Session app thought it was sent yesterday, despite the live conversation.

**To Reproduce**
Steps to reproduce the behavior: chat with someone in a vastly different timezone and different date.

**Screenshots or Logs**
![lost-in-time](https://user-images.githubusercontent.com/13181565/135545677-9416a354-2a90-474d-b7a1-e42a678f15e5.png)

**Other information (please complete the following information):**

* Device: PC Laptop intel.
* OS: Manjaro linux
* Session Version or Git commit hash: v1.7.0

**Comment by Bilb** [comment]
@toomuchacid could you please ask this person if he is sending the messages from desktop or mobile (which platforms) and which version is installed ?

**Comment by toomuchacid** [comment]
My side of the conversation, I use both iOS and Linux 1.7.0 and it was displayed the same way on both devices, I checked.As to the other participant, I don't know. On Fri, Oct 1, 2021 at 1:41 pm, Audric Ackermann ***@***.***> wrote:  
@toomuchacid could you please ask this person if he is sending the messages from desktop or mobile (which platforms) and which version is installed ?

**Comment by peepopoggers** [comment]
I have not seen this. If it happens to any of you, report your operating system information, time zone, version information and the same for the other person.

**Comment by Bilb** [comment]
no reactions for the last 2 months, closing this
