### ISSUE TITLE
Can't scan QR code from desktop in dark mode

### ISSUE THREAD

**Issue by jagerman** [oxen-io/session-desktop#2004]
If Session is in dark mode and I go to my profile -> QR code, my Android device refuses to find the QR code no matter how long I hover it over the code displayed on the screen.  In light mode it finds it instantly.

I played around with the image of the code, and found out it has to do with the amount of whitespace padding around the code -- I found some references that a QR code requires a minimum of two squares of padding on all sides (apparently with 4 recommended), but the QR code we display in dark mode only has 1 square width of padding on each side.

Unscannable dark mode QR currently produced by Session desktop:
![image](https://user-images.githubusercontent.com/4459524/139537767-01d2d8c1-38fc-427d-a00a-caaa3d2736c6.png)

I edited this in GIMP to add padding; with an extra block-width of padding all around my Android phone picks it up instantly, like it does in light mode:
![image](https://user-images.githubusercontent.com/4459524/139537806-4d60a26e-a2d6-4555-b0c1-9f271c7f69b7.png)

**Comment by peepopoggers** [comment]
This may be a specific thing with the app you are using, but this seems like a good option just so it does not trip out any more QR scanners. Normally there would not be a dark background around the edges so it may be thinking that it is part of the QR code.

**Comment by peepopoggers** [comment]
@Bilb would you mind adding a PR for your fix? thanks.

**Comment by peepopoggers** [comment]
I see this is fixed on the webrtc branch. :+1:

**Comment by Bilb** [comment]
Yeah, should be fixed now
