### ISSUE TITLE
(Feature Request) Export session ids of contacts

### ISSUE THREAD

**Issue by shashikanth171** [oxen-io/session-desktop#2005]
Select multiple conversations or contacts and export session ids

**Comment by peepopoggers** [comment]
Does the recovery phrase not do this?

**Comment by Bilb** [comment]
I am not too sure what is the usecase of this? SessionID do not mean much, without the info about to who they are associated.
If you get a list of 30 session IDs, you can save them but as soon as you want to message someone you are stuck with your list of 05.................................... without context. 

Or is it?

**Comment by Bilb** [comment]
https://github.com/oxen-io/session-desktop/issues/1972
