### ISSUE TITLE
(Feature request) Double-click to quote message (like Telegram)

### ISSUE THREAD

**Issue by hardBSDk** [oxen-io/session-desktop#2006]

**Comment by patoshii** [comment]
telegram mobile is swipe left or right on the message to quote.

**Comment by hardBSDk** [comment]
> telegram mobile is swipe left or right on the message to quote.

Not on desktop.

**Comment by peepopoggers** [comment]
This would be a good feature to have for efficiency. It is reply by the way not quote.

**Comment by Bilb** [comment]
Fixed on the latests releases
