### ISSUE TITLE
Pasting text into the message composition box moves the cursor to the end of the message.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2007]
**Describe the bug**

Pasting text into the message composition box moves the cursor to the end of the message.

If one is inserting text at the end of the existing message, this doesn't matter, but if one is inserting anywhere else, this is very unexpected behaviour.

This is present in desktop 1.7.4.

**Comment by peepopoggers** [comment]
I can reproduce this issue on 1.7.4, using linux.
Basically write out gibberish in the send message text box and then paste something at the front end of it. The cursor will move to the end when it should move to the end of the pasted text, not the entire message.

**Comment by ianmacd** [comment]
I've been trying to fix this bug the last few days, but it's a tough one for me to figure out.

The right place is obviously `ts/components/conversation/composition/CompositionBox.tsx`, but figuring out what's needed is tough.

I initially thought that `handlePaste` was the right place to fix this, but I think that the change isn't actually processed until `onChange`. At that point, though, knowledge of the pasted string has, I think, been lost, so the required changes to the code are not obvious to me.

@Bilb Can you provide any guidance here?

**Comment by Bilb** [comment]
I think that would come from here and I see a PR has been opened to fix the issue

https://github.com/signavio/react-mentions/issues/375

**Comment by ianmacd** [comment]
> I think that would come from here and I see a PR has been opened to fix the issue
> 
> [signavio/react-mentions#375](https://github.com/signavio/react-mentions/issues/375)

Well, no wonder this bug was driving me nuts: It's located outside Session itself.

Fixing it using the patch you linked to is problematic.

First of all, `MentionsInput.js` doesn't directly exist. It seems that the `.js` files are compiled from either the ESM of CJS files, and editing those isn't trivial. I assume it's the CJS file that is used, as that's what I believe Node uses.

Additionally, from the contents of the ESM and CJS files, it looks as if we're using an older version of `react-mentions`. I've nowupgraded my local version from 4.2.0 to 4.3.1, which triggered some dependency upgrades, but all appears to have gone well.

However, it's still not clear to me where or how to make the change in question.

I also don't understand why the PR hasn't been merged upstream. Has this project been abandoned?

I note that neither the Signal nor Element desktop clients have this bug, and both of those are also Electron, so there must be some way out of this.

**Comment by Bilb** [comment]
yeah, we would need to fork that repo, apply the change in our fork, and then require this new git repo as the source of react-mention

**Comment by ianmacd** [comment]
This seems to have been coincidentally fixed by other changes made to 1.9.x. I'm glad to see the back of this bug.
