### ISSUE TITLE
When changing the language the text cursor constantly jumps to another place and you have to constantly point to the text input field with the mouse

### ISSUE THREAD

**Issue by ghost** [oxen-io/session-desktop#2012]
When changing the language the text cursor constantly jumps to another place and you have to constantly point to the text input field with the mouse, on the operating system Windows 10, Windows 11

**Comment by peepopoggers** [comment]
I would ask for more information but this account no longer exists. If anybody else has this issue, please report here.

**Comment by Bilb** [comment]
Yeah, I don't get this user report neither. Closing it until we have more details
