### ISSUE TITLE
Reimplement the ability to search the current chat's messages for a string.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2016]
**Describe the bug**

The desktop client offers no way to search the current chat. The functionality was removed earlier this year for "performance reasons", but I would personally prefer to be able to make the choice myself to use it or not.

I can no longer remember how the feature worked before removal, but if reimplemented, it would ideally search not just the currently loaded buffer, but also load earlier messages on demand as the user scrolled back through matching messages.

**Comment by peepopoggers** [comment]
This is a very needed feature, at least in a simple form.

**Comment by sierra0scar** [comment]
Totally Agreed.

**Comment by Bilb** [comment]
Relates https://github.com/oxen-io/session-desktop/pull/2061

**Comment by Bilb** [comment]
The search feature has been brought back a few releases ago
