### ISSUE TITLE
Name not Shown in Group Chat

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-desktop#2017]
Sometimes names don't show in chat, and instead the user ID is shown.

Windows 10
Session 1.7.4

Image of Chat from Windows
![session-2021-11-09-143353](https://user-images.githubusercontent.com/1575546/140902009-f41f6c22-06a8-40a8-80a0-478324bac5d4.png)

Image of Chat from Android (same group)
![Screenshot_20211109-143632__01](https://user-images.githubusercontent.com/1575546/140901907-e54627d7-84a8-4e89-b9f4-46ba17f10cc2.jpg)

**Comment by peepopoggers** [comment]
I may be wrong but I think usernames are optional so ID's are used instead

**Comment by Sepero** [comment]
> I may be wrong but I think usernames are optional so ID's are used instead

You may be correct, but I believe you misunderstand the issue here. We can see the screen shot of the same chat on both Android and Desktop from above. The individual has a username set (as can be seen from the Android view of the chat). That username is not displaying in the Desktop program

**Comment by peepopoggers** [comment]
@Sepero I think it is a sync/update error of some sort. They might have updated their username and profile picture and I think the desktop client may not have updated.

**Comment by Sepero** [comment]
Understood

1. I have contacted the user Chief36 to confirm whether or not he has made a change to his profile recently.
2. I have seen other Desktop users complain regarding this issue previously, which is why I have filed this bug (on behalf of Desktop users). I have never see this issue on Android

**Comment by Sepero** [comment]
The reply from Chief36 in the matter, indicating his last changes were over 14 days before this incident

![Screenshot_20211116-185802](https://user-images.githubusercontent.com/1575546/141982758-6ff02d45-c488-458f-b4cd-fee2e49bd1ab.jpg)

**Comment by peepopoggers** [comment]
Hmm... weird. If anyone else has this issue maybe we could find more info

**Comment by Bilb** [comment]
It this still happening?
Feel free to reopen if yes
