### ISSUE TITLE
Respect blocked user list when fetching messages from open groups.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2019]
**Describe the bug**

When messages are fetched from open groups, messages from blocked Session ids are not weeded out by the client.

Whilst filtering out such messages may lead to a disjointed reading experience in the open group, I believe the user should be given that option. I would certainly enable it.

**Comment by peepopoggers** [comment]
What do you mean? Reading this is kind of confusing. Can you still see blocked users messages in groups?

**Comment by ianmacd** [comment]
> Can you still see blocked users messages in groups?

Yes. Most messaging clients actually have the same problem, but Session should make it a choice.

**Comment by Bilb** [comment]
I don't think this should be a choice. You blocked a user, you shouldn't see his messages.

**Comment by ianmacd** [comment]
> I don't think this should be a choice. You blocked a user, you shouldn't see his messages.

This approach works for me, but it's a significant change to the current behaviour, and also not what other clients, such as Telegram, do.

There's also the matter of messages that quote a blocked message. Will there be an indicator that the quoted message was blocked?
