### ISSUE TITLE
Full desktop width not used when displaying message containing an attachment.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2020]
**Describe the bug**

The desktop client was recently improved to use more of the screen's width when displaying messages, but any message that contains an image attachment (and possibly other types) is still displayed in a very narrow column. If the message contains a lot of text, this makes for an unpleasant reading experience that fills the vertical space of the screen.

**Comment by peepopoggers** [comment]
I think the design is partially intentional but I think that images can be made slightly bigger. I don't think they should span the whole screen like matrix though as it is annoying.

**Comment by ianmacd** [comment]
The point is that there's no reason to make a message with an image attachment any narrower than one without. The narrowness of such postings is probably just a remnant of the time when all postings had this width.

**Comment by KeeJef** [comment]
This is fixed in latest release since attachments have been moved outside of the message they belong to
