### ISSUE TITLE
Request: Enable github discussions

### ISSUE THREAD

**Issue by peepopoggers** [oxen-io/session-desktop#2021]
This would be useful to discuss issues such as project development ideas which are more of discussions than issues.

**Comment by Flam3z** [comment]
That could possibly be helpful for grabbing more feedback and insight for the devs on top of the current survey.

**Comment by peepopoggers** [comment]
@Flam3z I would like to open a thread discussing most wanted features and for discussing ideas with the direction of the app.

**Comment by Bilb** [comment]
Enabled
