### ISSUE TITLE
Feaature Request: Notes to Self - "permanent swarm condition":

### ISSUE THREAD

**Issue by sierra0scar** [oxen-io/session-desktop#2023]
A very poweeful feature would be to be able to add a self send note to self (as we already can) - but for it to be forever saved in the swarm - I know we only have two weeks - but what if just that thread was permantly saved in the node swarm ? - seeds or imprtant stuff could be super safe  .

**Comment by peepopoggers** [comment]
I agree

**Comment by Bilb** [comment]
I don't fix we are going to do this anytime soon. It would be too easy to fill the snodes of a swarm and thus impacting other users too. Also, we would somehow have to leak the metadata 'this message is mine and I want it store indefinetely'.
You can probably find other software to store those kind of information
