### ISSUE TITLE
The mobile app is out of sync with desktop app

### ISSUE THREAD

**Issue by peepo5** [oxen-io/session-desktop#2040]
**Describe the bug**
The mobile app is out of sync with desktop app.
When I join groups on either, no changes happen on the other device.

**To Reproduce**
1. Run session on desktop and android
2. Join an open group on android
3. It will not sync with desktop

(not sure if this is reproducible)

**Other information (please complete the following information):**

* Device: PC
* OS: PopOS 20.04
* Installation method: AppImage
* Session Version or Git commit hash: 1.7.4
--
* Device: Phone
* OS: CalyxOS
* Installation method: Aurora Store
* Session Version or Git commit hash: 1.11.12 (2315)

**Comment by KeeJef** [comment]
This should be fixed with the recent user config update
