### ISSUE TITLE
Resource

### ISSUE THREAD

**Issue by Ygarr** [oxen-io/session-desktop#2050]
Why are you framing users with cloudflare?

**Comment by Bilb** [comment]
What do you mean? Does this have anything to do with session-desktop?

**Comment by peepopoggers** [comment]
...

**Comment by Ygarr** [comment]
Is it lie?
![session](https://user-images.githubusercontent.com/14309871/144733276-e5c2f342-69aa-4faa-ab79-4ee904ca974e.png)

**Comment by majestrate** [comment]
last i checked we are in the process of decloudflaring our sites, session does not store anything messages on the blockchain either. that entire site reads like a satire so i am not sure if it's a joke or not.

just keep in mind, sometimes people post lies on the internet, often on anonymous message boards. I would keep this in mind when reading posts full of flamboyant opinions from internet randos.
