### ISSUE TITLE
Self Delete Message is broken

### ISSUE THREAD

**Issue by NerdyLuffy** [oxen-io/session-desktop#2052]
**Describe the bug**
[Self Delete Message](https://getsession.org/blog/self-deleting-messages) Feature does not work on Desktop app

**To Reproduce**
Enabled the Self delete message on the Mobile application, set the time for one day, have a chat for couple of days, now when you return to the desktop application you can see all the chat even though it has been deleted from the mobile application. Makes me wonder are messages and media really deleted from the servers or just marked as hidden after mentioned timeout ?

Also, I can see the entire conversation past 14 days on the Desktop application 

**Other information (please complete the following information):**

* Device: Iphone, Laptop
* OS: MacOS
* Session Version or Git commit hash: On Iphone -> 1.11.18(306), on MacOS -> v1.7.4

**Comment by InoMurko** [comment]
Yeah, this is actually really really bad!

**Comment by Bilb** [comment]
Messages stored on swarms are for 15 days at most.

**Comment by InoMurko** [comment]
Not in my experience. Messages were 2-3 months old.

**Comment by NerdyLuffy** [comment]
> Not in my experience. Messages were 2-3 months old.

Same

**Comment by NerdyLuffy** [comment]
> Messages stored on swarms are for 15 days at most.

I believe what you mean is a message/event for the device to **delete the message** is stored for 15 days at most, so if all the clients [ Mobile/Desktop ] do not sync in that time period then its lost and all the messages are preserved

**Comment by Bilb** [comment]
> > Messages stored on swarms are for 15 days at most.
> 
> I believe what you mean is a message/event for the device to **delete the message** is stored for 15 days at most, so if all the clients [ Mobile/Desktop ] do not sync in that time period then its lost and all the messages are preserved

No, I mean that when you send a message to your swarm, or someone else's swarm (not opengroups ofc), that message will be automatically deleted after 14 days, at most, nothing you can can extend that 14 days.
https://github.com/oxen-io/oxen-storage-server/blob/dev/httpserver/request_handler.h#L33

**Comment by pixloptr** [comment]
Mobile doesn't seem to ever search the swarm for messages when you link or continue your Session with the pass-phrase. Only the desktop application seem to do so. Easy temporary fix would probably be to only search the swarm for session ids. This will at least deal with the concern of messages being accessible even when they were deleted. I understand you already have some plans of implementing a more fluid swarm, so that the messages aren't only deleted locally. But in the meantime, this could adress the issue and it would be an acceptable workaround.

Keep up the good work.

**Comment by KeeJef** [comment]
Messages are deleted off a swarm after 14 days at maximum, so unless the database is erroneously being kept around i don't see how it would be possible to restore messages 2-3 months old, (lets reopen if we have a reproducible case supporting this theory). However there is a current issue with disappearing messages where disappearing messages are only currently deleted locally, so if you restore within 14 days those disappearing messages will reappear. We plan to patch this. Closing in favor of this #2048 which is the proposed fix
