### ISSUE TITLE
Session should redirect to a quoted message when clicked, not force the user to find it.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2053]
**Describe the bug**

This is the message displayed when the user clicks on the quoted part of a reply message:

![image](https://user-images.githubusercontent.com/749942/143771540-226d9d8f-c400-4f94-a32f-6e16f1dd335b.png)

If Session can find the message in question, why can it not load it and scroll to it?

Why is the user forced to find it himself, a task made very cumbersome by the removal of the ability to search the message buffer for a string (and covered in a separate issue, #2016).

**Comment by Bilb** [comment]
should be fixed in latest update.
