### ISSUE TITLE
Selecting a conversation does not open it at the position of the last read message.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2054]
**Describe the bug**

When one navigates to a chat that has received more than a page of new messages since it was last selected, Session fails to open that conversation at the point of the last read message. Instead, it is opened in the vicinity of the recently received messages, but not even at the most recently received message.

The following message is displayed at the top of the screen:

![image](https://user-images.githubusercontent.com/749942/143781874-5306aa50-332f-4a64-9754-a327de14e436.png)

This behaviour is neither intuitive nor useful. The location of the last read message should be preserved and used to resume reading, and preferably also synced between clients when the user uses multiple devices.

**Comment by Bilb** [comment]
should be fixed in latest update.
