### ISSUE TITLE
Session cant use GPU and then dies

### ISSUE THREAD

**Issue by pilot877** [oxen-io/session-desktop#2057]
**Describe the bug**
Session refuses to launch after failing to use my GPU

**To Reproduce**
Unsure, just ran it on openSUSE Tumbleweed after installing.

**Screenshots or Logs**
`pilot@localhost:~/Documents> ./session-desktop-linux-x86_64-1.7.4.AppImage 
Set Windows Application User Model ID (AUMID) { appUserModelId: 'com.loki-project.messenger-desktop' }
NODE_ENV production
NODE_APP_INSTANCE undefined
NODE_CONFIG_DIR /tmp/.mount_sessioIDwiXc/resources/app.asar/config
NODE_CONFIG {}
userData: /home/pilot/.config/Session
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
making app single instance
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":"app ready","time":"2021-11-30T07:42:41.105Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":"starting version 1.7.4","time":"2021-11-30T07:42:41.105Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":"updateSchema:","time":"2021-11-30T07:42:41.118Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":" Current user_version: 11","time":"2021-11-30T07:42:41.118Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":" Most recent db schema: 11","time":"2021-11-30T07:42:41.119Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":" SQLite version: 3.34.1","time":"2021-11-30T07:42:41.119Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":" SQLCipher version: 4.4.3 community","time":"2021-11-30T07:42:41.119Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":" (deprecated) schema_version: 94","time":"2021-11-30T07:42:41.119Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":"updateLokiSchema: Current loki schema version: 16; Most recent schema version: 16;","time":"2021-11-30T07:42:41.120Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":40,"msg":"Vacuuming DB. This might take a while.","time":"2021-11-30T07:42:41.122Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":40,"msg":"Vacuuming DB Finished","time":"2021-11-30T07:42:41.139Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":"%s: %s vaccumming db 17.328ms","time":"2021-11-30T07:42:41.140Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":40,"msg":"total message count:  0","time":"2021-11-30T07:42:41.142Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":"Ensure attachments directory exists","time":"2021-11-30T07:42:41.142Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":"Initializing BrowserWindow config: {\"show\":true,\"width\":882,\"height\":822,\"minWidth\":880,\"minHeight\":600,\"autoHideMenuBar\":false,\"backgroundColor\":\"#fff\",\"webPreferences\":{\"nodeIntegration\":false,\"enableRemoteModule\":true,\"nodeIntegrationInWorker\":false,\"contextIsolation\":false,\"preload\":\"/tmp/.mount_sessioIDwiXc/resources/app.asar/preload.js\",\"nativeWindowOpen\":true,\"spellcheck\":true},\"maximized\":false,\"x\":751,\"y\":309}","time":"2021-11-30T07:42:41.144Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":"spellcheck: user locale: en-GB","time":"2021-11-30T07:42:41.190Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":"spellcheck: available spellchecker languages:  [\"af\",\"bg\",\"ca\",\"cs\",\"cy\",\"da\",\"de\",\"de-DE\",\"el\",\"en-AU\",\"en-CA\",\"en-GB\",\"en-GB-oxendict\",\"en-US\",\"es\",\"es-419\",\"es-AR\",\"es-ES\",\"es-MX\",\"es-US\",\"et\",\"fa\",\"fo\",\"fr\",\"fr-FR\",\"he\",\"hi\",\"hr\",\"hu\",\"hy\",\"id\",\"it\",\"it-IT\",\"ko\",\"lt\",\"lv\",\"nb\",\"nl\",\"pl\",\"pt\",\"pt-BR\",\"pt-PT\",\"ro\",\"ru\",\"sh\",\"sk\",\"sl\",\"sq\",\"sr\",\"sv\",\"ta\",\"tg\",\"tr\",\"uk\",\"vi\"]","time":"2021-11-30T07:42:41.191Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":"spellcheck: setting languages to:  [\"en-GB\"]","time":"2021-11-30T07:42:41.191Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":"auto-update: starting checks...","time":"2021-11-30T07:42:41.209Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":"auto-update: checking for update...","time":"2021-11-30T07:42:41.253Z","v":0}
{"name":"log","hostname":"localhost.localdomain","pid":19361,"level":30,"msg":"Checking for update","time":"2021-11-30T07:42:41.253Z","v":0}
[19361:1130/174241.598022:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
pilot@localhost:~/Documents> 
`

**Other information (please complete the following information):**

* Device: PC
* OS: openSUSE Tumbleweed 20211128-0
* Session Version or Git commit hash: 1.7.4 Linux Desktop AppImage

**Comment by peepopoggers** [comment]
@pilot877 can you format this better please? use three of these -> ` to open and close

**Comment by Bilb** [comment]
This looks to be matching that bug report  https://forums.opensuse.org/showthread.php/560226-Electron-apps-fail-to-launch-FATAL-gpu_data_manager_impl_private-cc(415)-GPU-process-isn-t-usable

and the fix is to update electron to at least 13.5.0, the one we have currently is 13.1.9

**Comment by Bilb** [comment]
can you reach out to me on Session (see my github status for my SessionID) so I can send you a test build to give it a try?

**Comment by pilot877** [comment]
Forgot this was still open sorry. Yes the issue is fixed haha.
