### ISSUE TITLE
about delete messages

### ISSUE THREAD

**Issue by sakurayz** [oxen-io/session-desktop#2064]
Permanently delete the messages  in this conversation is just delete messages from me.  
Should add delete option for delete messages from me and everyone in this conversation. 
thanks.

**Comment by sakurayz** [comment]
delete message and delete for everyone are different, delete message is equivalent to clearing the screen, and delete for everyone is to completely delete the message from the server.

**Comment by sakurayz** [comment]
A communication app that pays attention to security, no need to clear the screen, and you need to completely delete messages, including messages sent by yourself and messages from the other party

**Comment by lucy2812** [comment]
At least the app should inform the user it's only your messages.  

"messages in this _conversation_" implies two things:

1)  Conversation is typically between 2 or more people (not counting talking to yourself).

2)  The conversation window on everyone's device.

**Comment by mdPlusPlus** [comment]
This seems to be already implemented.
![image](https://user-images.githubusercontent.com/9272131/190904170-506b577b-d31d-4707-89df-0042fe28779e.png)
