### ISSUE TITLE
Show Debug Log "Unhandled Error"

### ISSUE THREAD

**Issue by LeonardoMaracino** [oxen-io/session-desktop#2074]
Clicking on the "Show Debug Log" button will cause the app to show the "Unhandled Error".

Open Session app > Settings > Appearance > Show Debug Log

<img width="372" alt="Screenshot 2021-12-09 at 12 14 21" src="https://user-images.githubusercontent.com/57290045/145386826-d8557729-4fd9-4221-80d3-65a393c42a89.png">

MacBook Pro M1 (2020)
macOS 12 beta (21A5552a)
Session v. 1.7.4

**Comment by Bilb** [comment]
I believe this is related to #1634 feel free to reopen if not
