### ISSUE TITLE
Added to an unknown group called "no rules", without sharing my ID to anyone.

### ISSUE THREAD

**Issue by LeonardoMaracino** [oxen-io/session-desktop#2076]
**Describe the bug**
Me - and other dozens of users - have been added to an unknown group called "no rules", without our consent.
Also, I haven't shared my session ID with anyone.

**To Reproduce**
Be a Session user

**Screenshot**
<img width="1112" alt="Screenshot 2021-12-09 at 13 19 17" src="https://user-images.githubusercontent.com/57290045/145395912-973b71b6-28f5-483e-aaa7-d44fdb84ff7f.png">

**Logs*
https://debuglogs.org/6f833834ef8f2a1d0537bbaa1c7e0f9546a46ddf5a0836569c61ae8ece81eabf

**Notes**
I noticed that, a couple of minutes before being added to the group, an unknown user named "gaz" texted me a "\". This gaz, is also the "no rules" first user.
I can't get to understand how this/these people managed to get my ID, since I haven't shared it with anyone.

**Other information (please complete the following information):**

MacBook Pro M1 (2020)
macOS 12 Beta (21A5552a)
Session v. 1.7.4

**Comment by LeonardoMaracino** [comment]
> have you ever joined any public group?

Yes, months ago. Can people see my ID without requesting it?
Anyway, I think there should be no way to be automatically added to groups without specific consent.

**Comment by 144** [comment]
> > have you ever joined any public group?
> 
> Yes, months ago. Can people see my ID without asking me for it? Anyway, I think there should be no way to be automatically added to groups without specific consent.

Seems like someone grabbed your Session ID back then ( yes everyone can see it, you do not have to approve anything ).

**Comment by Bilb** [comment]
Referencing https://github.com/oxen-io/session-pysogs/issues/28 as we cannot fix this issue without it

**Comment by Bilb** [comment]
Closing this as this is related to our ongoing SPAM related issues https://github.com/oxen-io/session-desktop/issues/2032
