### ISSUE TITLE
Compression images without my knowledge

### ISSUE THREAD

**Issue by Ygarr** [oxen-io/session-desktop#2077]
The app let me down a lot. This is something of a level of Viber messenger or even worse
my receiver gets only pixels

**Comment by peepopoggers** [comment]
:joy:

**Comment by peepopoggers** [comment]
I was unaware session had compression?

**Comment by Ygarr** [comment]
So it doesn't turn off on top of that?

**Comment by Bilb** [comment]
can you send me a link to one of the image causing issues?

**Comment by Bilb** [comment]
Closing this until I get the link to the image causing issue
