### ISSUE TITLE
Cannot select and copy part of a message

### ISSUE THREAD

**Issue by beantaco** [oxen-io/session-desktop#2081]
I often want to copy just part of a message (with my mouse cursor) but I cannot. I can only right-click a message and copy its entire text. Please allow users to select and copy parts of messages.

**Comment by Bilb** [comment]
Which platform? This work fine for me

**Comment by Bilb** [comment]
You can just select it and hit CTRL-C

https://user-images.githubusercontent.com/1544279/145935639-1e8af047-aab8-4362-b29b-e8b29c351180.mp4

**Comment by beantaco** [comment]
Sorry but I characterized the problem based on past recollection. The problem I have had is described in #2082.
