### ISSUE TITLE
Messages replied to are not found

### ISSUE THREAD

**Issue by kunago** [oxen-io/session-desktop#2093]
**Describe the bug**
I use Session on a mobile and desktop. When I reply to a message on desktop and messages with mobile sync, on the mobile I see only "message cannot be found" or a similar message instead of the message I replied to. On desktop everything seems to be okay.

My assumption is that the messages on desktop can be encoded wrongly since I use Czech when composing them and it does have umltaus.

**To Reproduce**
- send a message on desktop
- take a look at the message on mobile; randomly the message you reply to is not found on mobile, although I can see it

**Screenshots or Logs**
None yet, I will try to take a screenshot

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac]
* OS: Windows 10; Android 11
* Session Version or Git commit hash:
  - Android: 1.11.13
  - Windows: 1.7.4

**Comment by kunago** [comment]
![image](https://user-images.githubusercontent.com/460971/146347197-6ade2f56-75aa-4f35-8ad8-b2e416c8176f.png)

The replied to message says that the original message was not found. But this happens only when I reply on desktop and see the messages on mobile.

**Comment by Bilb** [comment]
I believe this has been fixed in recent version. Feel free to reopen if not
