### ISSUE TITLE
Session Desktop douplicates or triples attachments and notification messages received from other devices on same ID

### ISSUE THREAD

**Issue by Norbert80** [oxen-io/session-desktop#2099]
Session Desktop is doublicating attachments and notification messages received from other devices on same ID

See screenshot
![image](https://user-images.githubusercontent.com/6921696/146528582-ca223c1f-1680-4aa7-8588-657418157f57.png)

Session Desktop build v1.7.4.

**Comment by Norbert80** [comment]
@Bilb could you please have a look on this issue?

**Comment by Norbert80** [comment]
Additional info:

- Me (Sender of these attachments) have taken the screenshot above
- I use 4 instances on same ID. (2x Android, 2x Linux Desktop)
- Attachments have been sent from one of my two Linux Desktops. Screenshot has been taken from the *other" Linux Desktop.
- Recipient (contact name: Sabine N.) runs Session Android (single device on her ID). She has saved the two attachements and provoked the file saved notifications (German: "Medien gespeichert...")
-

**Comment by Norbert80** [comment]
Now I have received an (one!) image from a contact's ID. Session Desktop displays it three times, while Session Android correctly displays it one time.

**Comment by Bilb** [comment]
I am unable to  reproduce this issue with the info I have

**Comment by Norbert80** [comment]
@Bilb I have sent you logs as requested via Session.

**Comment by KeeJef** [comment]
Is this still occurring? Haven't personally seen something like this in a while

**Comment by Norbert80** [comment]
> Is this still occurring? Haven't personally seen something like this in a while

Same for me. I will close it.
