### ISSUE TITLE
[Translate] Privacy Settings Menu Russian and other

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-desktop#2101]
Privacy Settings 
"Microphone" - "Микрофон"
"Allow access to microphone" - "Разрешить доступ к микрофону"

![1](https://user-images.githubusercontent.com/43858033/146623362-79c2ef77-cbad-43ee-ae16-c76547d65ab9.png)

**Comment by xbvrhlmb** [comment]
i say this in #1868

**Comment by 144** [comment]
https://github.com/oxen-io/session-desktop/issues/2104#issuecomment-997118477

**Comment by Bilb** [comment]
translations are to be put on crowdin. 
![image](https://user-images.githubusercontent.com/1544279/146709371-b207b57d-a392-4fcd-b11c-095b0c1d0096.png)
