### ISSUE TITLE
[BUG] call without microphone

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-desktop#2102]
if i not have microphone or webcam and try call to other contact, 
i see client message "allow microphone"
![0](https://user-images.githubusercontent.com/43858033/146623259-8054b6a7-43cb-4e3b-84e9-d2ddd356f380.png)

but in settings 
![1](https://user-images.githubusercontent.com/43858033/146623303-2dc7b859-b3d3-4c11-83e9-252b5edb5f3a.png)

Version: 1.7.5

**Comment by 144** [comment]
seems like there is no 'Voice and video calls' permission button for some reason, also does not show on my PC. 

version: 1.7.5
os: Debian bullseye

**Comment by peepopoggers** [comment]
Same here, using pop on 1.7.6

**Comment by Bilb** [comment]
should be fixed in the next release

**Comment by Bilb** [comment]
You can have a look at 1.8.0 which is a pre-release https://github.com/oxen-io/session-desktop/releases
