### ISSUE TITLE
[Translate] Show User Details in menu

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-desktop#2103]
if right click in profile you see "Show User Details" but translate in other lang not work.

Example Russian
"Show User Details" - "Показать Сведения о Пользователе" or "Показать Детальнее" or "Показать Подробнее"

**Comment by 144** [comment]
https://github.com/oxen-io/session-desktop/issues/2104#issuecomment-997118477

**Comment by Bilb** [comment]
Updated on crowdin
