### ISSUE TITLE
[Translate] Delete for everyone

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-desktop#2104]
in chat if right-click to self message see "Delete for everyone"
but not translate in other languages

### Russian Translate
"Delete for everyone" -  "Уадлить для всех"

Version: 1.7.5

**Comment by 144** [comment]
please take a look at this website - https://crowdin.com/project/session-desktop/ru
you can contribute translations there

**Comment by xbvrhlmb** [comment]
> please take a look at this website - https://crowdin.com/project/session-desktop/ru you can contribute translations there

i not like crowdin, and many developers sometimes forget to specify variables for it in the code, and in most cases this is the problem, since the translation exists, but the variable in the code has been changed.

**Comment by Bilb** [comment]
I can confirm that those keys are available for translations on crowdin, and in use in the code for the last couple of months
