### ISSUE TITLE
[BUG] Update 1.7.5 broke auth

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-desktop#2105]
if i click in client "Download update" and start new client 1.7.5
Session authorization lost, and me need again authorization and add recovery key.

OS: Linux [Arch]
Version: 1.7.5

**Comment by SolidFish888** [comment]
Same, but happened recently on 1.7.6 update. It's not the first time.

OS: Linux [Arch]
Version: 1.7.6

**Comment by Bilb** [comment]
So, actually the database was not encrypted on archlinux until this release. For more details you can have a look at https://github.com/signalapp/better-sqlite3/pull/3.

To summarize, the .so of the libsqlite packaged in the app was not used by the app on archlinux but instead the libsqlite from the system was used. 
That system library does not support encrypting but actually silently drops every call we make to encrypt it.

Unfortunately, there are no easy fix for that, except dropping the existing database on archLinux and create it again with the right library this time...

I forgot to include a note on the on the release notes. I will include it now.

**Comment by Bilb** [comment]
https://github.com/oxen-io/session-desktop/pull/2035
