### ISSUE TITLE
Debian 11, oxen-electron-wallet : Depends: libappindicator3-1 but it is not installable

### ISSUE THREAD

**Issue by JJenkx** [oxen-io/session-desktop#2106]
Debian 11, 

Trying to install this but there is a dependency not available in the Debian repos. Is there a workaround?

oxen-electron-wallet : Depends: libappindicator3-1 but it is not installable

**Comment by 144** [comment]
hey, I'm using Debian 11 as well, i got Session running using their deb repo, you can also use latest deb file with dpkg -i

**Comment by peepopoggers** [comment]
this does not seem relevant to this repo :o so maybe close

**Comment by Bilb** [comment]
this has nothing to do with session desktop => https://github.com/oxen-io/oxen-electron-gui-wallet
