### ISSUE TITLE
Home/end keys in typing box *also* scroll message window

### ISSUE THREAD

**Issue by jagerman** [oxen-io/session-desktop#2114]
When composing a message I frequently use Home/End to jump to the beginning of the text box (e.g. to prepend something to my existing message).

Home/End now move the cursor (as expected), but *also* scroll my message window to the top/bottom (unexpected and unwelcome).

This applies to the 1.8.0 release; I'm not sure when it was introduced, but I don't believe it was present in 1.7.4 (not sure about 1.7.5/6).

**Comment by beantaco** [comment]
I experience this issue in 1.7.6. I also find it unexpected and undesirable. I hope this will be fixed in future versions.
