### ISSUE TITLE
Duplication of typed input in message input box when using uim-anthy (Japanese IME)

### ISSUE THREAD

**Issue by beantaco** [oxen-io/session-desktop#2144]
*I have explained this issue in #1497 but realised I should create a new ticket for it.*

When using Japanese IME, users typically input hiragana "あさひ" either by alphabet "asahi" (romaji/ローマ字 using an alphabetic keyboard layout) or hiragana directly "あさひ" (using a hiragana keyboard layout). Converting the hiragana into other forms such as kanji "朝日" and katakana "アサヒ" is done by hitting a conversion key (Space for me), which brings up a list of conversion candidates. Selecting/committing/confirming the currently shown candidate is done by hitting another key (Enter for me).

Every time I hit Space or Up/Down to scroll through the list of candidates, the input hiragana gets duplicated in Session's message input box... exponentially, leading to strings like "あさひあさひあさひあさひ...".

This issue makes Session Desktop impractical to use for people who type Japanese using uim-anthy. There are other issues such as #2125 (known to affect ibus-anthy and ibus-mozc) and #1497 (unknown OS and IME) for people using other Japanese IMEs. Unless someone has a properly working combination of OS and Japanese IME, people who use Japanese either abandon Session or need to type Japanese into a separate text editor and then copy/paste the result into Session Desktop's message input box.

- Session Desktop 1.7.6
- OS: Debian buster
- Input method: uim-anthy

**Comment by fracting** [comment]
Can anyone here:
1. Test with the original react-mentions implementation to confirm you can reproduce any bug? Here is the original demo: https://react-mentions.vercel.app/ 
2. Test my hack on http://16.170.244.17:8080/ and give me some feedback?

This hack has some obvious issues, it messes up the mentioned highlight, but the text input part is working for me when I test with ibus-mozc (Japanese).

It would be great if some native Japanese speakers test it with different browsers + different OSs + different IME and provide me some feedback.

If the feedback is good I'll clean up the patch and propose a proper solution.

Here is the hack for who are curious: https://github.com/fracting/react-mentions/commit/b18354358438d5c88137a714f473ee8130dd06b1

**Comment by Bilb** [comment]
Closing this in favor of #2125
