### ISSUE TITLE
Provide a flatpak release

### ISSUE THREAD

**Issue by Amanse** [oxen-io/session-desktop#2146]
Instead of multiple linux packages there can just be one [Flatpak](https://flatpak.org/) release targeting all distros

**Comment by 144** [comment]
flatpak has its flaws, not everyone want to use it. in my opinion its better to provide precompiled packages for the most popular distros and an appimage(basically any distro can run it).

also there is a flatpak if you would want to use it; https://flathub.org/apps/details/network.loki.Session
