### ISSUE TITLE
Application goes white screened, mid sync

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-desktop#2148]
**Describe the bug**
As I open the app after not doing so for a couple of weeks, the ram usages on the app increases, thus staggering the app while it syncs messages. Then as I am waiting, all of a sudden the whole application goes white and I am unable to interact with the app, making me have to restart the app each time this happens.

**To Reproduce**
1. Don't log on for several weeks
2. Delete any old DMs you may have with other people.
**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: Desktop
* OS: Windows 10 
* Session Version or Git commit hash: 1.7.6

**Comment by Bilb** [comment]
Any chance you can start the app from the terminal and send me the logs?

**Comment by Flam3z** [comment]
@Bilb how may i do that?

**Comment by KeeJef** [comment]
Have seen this with some users in the office too @Bilb , Perhaps talk to Cam, he was running into this

**Comment by Bilb** [comment]
@Flam3z could you give 1.8.0 a try? It is a pre release for now but should include a fix for that issue.

https://github.com/oxen-io/session-desktop/releases/tag/v1.8.0

**Comment by Flam3z** [comment]
Session has not crashed so far as I deleted a boatload of dms, thank you.

**Comment by Bilb** [comment]
@Flam3z you mean using 1.8.0 or still using 1.7.6?

**Comment by Flam3z** [comment]
1.8.0

**Comment by Bilb** [comment]
ok. closing this then. feel free to reopen if needed
