### ISSUE TITLE
unexpected copied text in reverse order , when marked as newest to earliest

### ISSUE THREAD

**Issue by viisauksena** [oxen-io/session-desktop#2155]
**Describe the bug**
by copying messages from newest to earliest, they are pasted the same order, would expect that they are copied like any other textcopy - from top to bottom
maybe its intended - but kinda unusual 

**To Reproduce**
linux desktop app ./session-desktop-linux-x86_64-1.7.6.AppImage
copy text from newest to earliest with ctrl-c
paste it with ctrl-v
messages are pasted in reverse order 

* Device: Linux Amd64
* OS: Ubuntu based
* Session Version or Git commit hash: ./session-desktop-linux-x86_64-1.7.6.AppImage

**Comment by beantaco** [comment]
I haven't verified this happens in the current version, but I have experienced this issue too.

**Comment by KeeJef** [comment]
Closing issue in favor of https://github.com/oxen-io/session-desktop/issues/2155
