### ISSUE TITLE
Deleted messages came back after update

### ISSUE THREAD

**Issue by TMS-Namespace** [oxen-io/session-desktop#2166]
**Describe the bug**
Just got a notification message for updating my  windows client, did that, and immediately noticed that all deleted messages to my self (notes), are came back! (I deleted them with "Delete for everyone")

**Other information (please complete the following information):**

* Device: PC
* OS: Windows 10
* Session Version or Git commit hash: 1.7.7

**Comment by Bilb** [comment]
Deleting this in favor of #2052
