### ISSUE TITLE
Website Downloads are Unavailable

### ISSUE THREAD

**Issue by straussmaus** [oxen-io/session-desktop#2186]
**Describe the bug**
On the getsession.org website, you can see the "Linux" word under the "Desktop" section.  But there is no link to actually download.  Could be a javascript thing but how can a secure messenger expect people to use javascript?

**To Reproduce**
1.  Use Tor browser on medium

2. Go to getsession.org

3. Get excited when you see the word "Download."

4.  Try to download.  Just try.  I dare you

**Comment by straussmaus** [comment]
Update on this.  I can confirm the download link is NOT available on the smaller CSS/smaller screen.  So on a Tor browser with the default settings the download is not available.  You have to expand the browser to make the link work.

**Comment by yougotwill** [comment]
Hi @straussmaus, Thanks for bringing this to our attention. I have published a fix and confirmed everything works as expected in Tor with or without javascript.
