### ISSUE TITLE
Feature Request: Allow Client User to Save Complete Unicode Contact Text Session plus Metadata (Event Date/Time Stamp) for Complete/Scrollable Session in Time Ascending Order

### ISSUE THREAD

**Issue by JustaNormalGuy230** [oxen-io/session-desktop#2189]
Session Client Being Used: Windows x64 v1.7.7 on Windows 10 x64

  Currently. if one has a long, scrollable [Contact] Message Session (many pages) and would like to save it all, Ctrl-A will Mark the complete, scrolled text session, but Ctrl-C will not copy the complete marked text, just a block of that text messaging near the current, visible session on the screen.  Furthermore, that small subset of messaging text is saved LIFO versus FIFO (i.e. reverse chronological order or the bottom to top order on the screen) and hovered Metadata (such as the event/time/date stamp) is not saved with each message sent.

... I see two ways to resolve this, both which have advantages/disadvantages.  One is to mark/copy as described above, the other is to allow the user to Right Click on a Context Menu to do the complete Save for the full messages field (i.e., the chat text area).  Currently, a user can right click and copy a single message text, not all the messages in the scrollable message field.

... Great program and my apologies if this feature was already implemented and/or I missed something (I'm new here)!

**Comment by KeeJef** [comment]
Closing as part of #2383
