### ISSUE TITLE
Session wants message request approval for an attachment to Note-to-self.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2201]
**Describe the bug**

The new message request interface needs to treat Note-to-self as a special case.

**To Reproduce**

Try to send yourself an attachment via Note-to-self. Session will complain `You cannot send attachments until the conversation is approved.`

Not only is it illogical to require approval, but there seems to be no way to explicitly give that approval either.

**Comment by KeeJef** [comment]
I cant reproduce this, does this only happen when the attachment is the first message or is this fixed in the current version?

**Comment by KeeJef** [comment]
Closing due to lack of info
