### ISSUE TITLE
Session desktop doesn't know what country the node is in

### ISSUE THREAD

**Issue by LittleBigTea** [oxen-io/session-desktop#2219]
**Describe the bug**
When I click on the connection button which is supposed to show the nodes my messages are being sent through, some of them appear as undefined

**To Reproduce**
Let session running

**Screenshots or Logs**
![Session_2Gxdc27SIB](https://user-images.githubusercontent.com/81515107/158868897-98f1bba8-0161-4284-b564-f77429427206.png)
[session_debug_1647540898686.log](https://github.com/oxen-io/session-desktop/files/8289028/session_debug_1647540898686.log)

**Comment by Bilb** [comment]
We use this module to find without request where is located an ip.
https://www.npmjs.com/package/ip2country
And sometimes that offline list is not 100%.

**Comment by SArpnt** [comment]
was there any related commit? whether or not it's possible to find the location it still says undefined, which doesn't work with the ui and gives me the impression other code might have issues with it. it should say something like unknown.

**Comment by ianmacd** [comment]
> was there any related commit? whether or not it's possible to find the location it still says undefined, which doesn't work with the ui and gives me the impression other code might have issues with it. it should say something like unknown.

There's an outstanding PR (#2280) that would fix this issue.
