### ISSUE TITLE
Attachments cannot be downloaded when message has more than one.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2229]
**Describe the bug**

When a message has more than one attachment, the `Download attachment` option does not appear in the message context menu.

**To Reproduce**

Right-click a message with two or more photos attached. Note the missing entry to download attachments.

**Comment by Bilb** [comment]
well get a fix for this

**Comment by KeeJef** [comment]
Resolved in https://github.com/oxen-io/session-desktop/pull/2252
