### ISSUE TITLE
Enhancement: in-app discovery of open group servers and their groups

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2235]
I recently submitted a patch (#2230) to add to Session a button that opens the [Lokilocker site](http://lokilocker.com/Mods/Session-Groups/wiki/Session-Open-Groups) in the user's browser, allowing him to browse a manually maintained directory of open groups and select URLs for entry into Session.

The intention of the patch was more to highlight the need for better open group support more than it was an attempt to address the issue. Because clearly the best solution from a technical standpoint is to have open group discovery fully integrated in the software à la Telegram or a Usenet reader.

@KeeJef commented that "there is a larger discussion which needs to occur around open group discoverability before any new discoverability buttons/features are merged".

This GitHub issue is being opened as a publicly accessible venue for that discussion.

**Comment by KeeJef** [comment]
Primary issue is here

> Is there any responsibility on the listed open groups to avoid scam, drugs dealing, child porn, or any other illegal topic/content? When it is listed by the app, this will be Oxen's matter. And then Oxen has to respect and to fulfill the T&C from Alphabet and Apple as well, if the app is hosted on Play Store and AppStore.

If we were going to offer discoverablity i think it would need to be a whitelist type model, where open groups request to be added to the official in app discoverablity list. We would then check the group out and decide if they met the content standards, then they could be added. But this then opens up our ability to censor whatever groups we want.

Out of band discovery allows people to create whatever custom list they want with their own moderation standards and we already see a few community run lists like [Sessiongroups](https://sessiongroups.com/) , [SessionDirectory](https://session.directory/) and the [LokiLockerList](http://lokilocker.com/Mods/Session-Groups/wiki/Session-Open-Groups)

**Comment by ianmacd** [comment]
> Out of band discovery allows people to create whatever custom list they want with their own moderation standards and we already see a few community run lists like [Sessiongroups](https://sessiongroups.com/) , [SessionDirectory](https://session.directory/) and the [LokiLockerList](http://lokilocker.com/Mods/Session-Groups/wiki/Session-Open-Groups)

Is Lokilocker community-run?

Someone told me that you are the owner. Is it not yours? Or maybe you mean that you run it in your own name, not in that of the OPTF.

I have editing rights on that Wiki, but I can't remember how I got them.

**Comment by ianmacd** [comment]
> If we were going to offer discoverablity i think it would need to be a whitelist type model, where open groups request to be added to the official in app discoverablity list. We would then check the group out and decide if they met the content standards, then they could be added. But this then opens up our ability to censor whatever groups we want.

Note that there's no obvious reason to restrict what can be served up in in the desktop client, because there's no gatekeeper that can penalise you by kicking you out of its curated distribution outlet. Session Desktop doesn't rely on a third party for its distribution.

On Android, you could choose the Telegram model: a Play Store client and a Session.org client that differ in the details.

This is easy to do with a centralised service like Telegram. There, only the build version string is different, and on the server side they prevent clients from accessing controversial channels and groups.

Session would need to compile open group discovery out of the Play Store client, or maintain a carefully curated list of allowed groups, but that would indeed open you up to claims of censorship. Better to omit the feature.

Those who want open group discovery on Android would simply have to download the app from the OPTF. That seems like a reasonable and practical compromise, and would drive some people away from the Play Store towards first-party dsitribution. That seems like a bonus to me.

I'm not sure there's an obvious solution for iOS devices.

**Comment by KeeJef** [comment]
> Is Lokilocker community-run?
> 
> Someone told me that you are the owner. Is it not yours? Or maybe you mean that you run it in your own name, not in that of the OPTF.
> 
> I have editing rights on that Wiki, but I can't remember how I got them.

The Loki locker Gittea instance is run by us, but the repo which hosts that open group list is not run or administered by the team.

**Comment by ianmacd** [comment]
> The Loki locker Gittea instance is run by us, but the repo which hosts that open group list is not run or administered by the team.

Ah, I see.

Thank you for clarifying.

**Comment by Bilb** [comment]
Closing this as we can't do it for now as discussed
