### ISSUE TITLE
Feature Request: Ability to save messages in Disappearing Messages mode

### ISSUE THREAD

**Issue by GrahamboJangles** [oxen-io/session-desktop#2238]
Title

**Comment by Bilb** [comment]
Why would you?

**Comment by GrahamboJangles** [comment]
> Why would you?

@Bilb  I find it a very useful feature in Snapchat. I like having disappearing messages enabled all the time, but you never know when you want to save something. If the other person doesn't like it, they can always delete the message.

**Comment by GrahamboJangles** [comment]
> @GrahamboJangles Considering a lot of encrypted messaging apps go to the effort of restricting screenshot access from the phone OS inside their apps, I'm not sure if this feature really makes sense from an OPSEC perspective.
> 
> Do you mean having the ability to screenshot a message in a conversation, or the ability to mark a message as 'saved' which will override the Disappearing Messages mode, meaning it will not be deleted when the rest of the messages reach their time limit?

Yes, I mean the ability to mark a message as saved to override the disappearing messages. I don't think this conflicts with the OPSEC perspective — the author could always delete the message.

**Comment by eyeberic** [comment]
> If the other person doesn't like it, they can always delete the message

The same can be said regarding this feature request; If you want to save it, you can perform necessary actions (screenshot, copy-paste to another app / chat / Note to Self, etc.) to preserve it before it disappears.

**Comment by GrahamboJangles** [comment]
> > If the other person doesn't like it, they can always delete the message
> 
> The same can be said regarding this feature request; If you want to save it, you can perform necessary actions (screenshot, copy-paste to another app / chat / Note to Self, etc.) to preserve it before it disappears.

Yes of course. It's a nice to have, not a need. Just a suggestion, don't have to listen to me.

**Comment by Bilb** [comment]
I don't think this should be allowed. 
If you want to save its content, copy the text and send it in Note to Self or somewhere more longer term
