### ISSUE TITLE
Turning off read receipts should include media being seen

### ISSUE THREAD

**Issue by yougotwill** [oxen-io/session-desktop#2254]
**Describe the bug**
When you turn off read receipts no information about the media being saved should be sent to the sender.

**To Reproduce**
Alice and Bob both have "Read Receipts" turned off. Alice sends an image to Bob. Bob opens the image on his device. Alice sees a message in the conversation that says "Media saved by Bob". 

This should not happen if read receipts is turned off.

**Comment by KeeJef** [comment]
What's the status of this?

**Comment by yougotwill** [comment]
Fixed in https://github.com/oxen-io/session-desktop/pull/2334 and release in v1.9.0
