### ISSUE TITLE
Fix display of Cyrillic fonts.

### ISSUE THREAD

**Issue by BlitDev** [oxen-io/session-desktop#2255]
Times New Roman looks bad and doesn't match the font of the text in Session. Better change it to Arial-like

**Comment by BlitDev** [comment]
Above from the screenshots, everything looks fine. I think this is only in Cyrillic fonts.

**Comment by BlitDev** [comment]
![image](https://user-images.githubusercontent.com/79034202/163402051-195e9391-1c4a-4be0-9883-ab25499cb56b.png)

**Comment by peepopoggers** [comment]
I don't think this is on purpose. Mine looks like:
![image](https://user-images.githubusercontent.com/72892531/165285028-2776c7c0-d21f-4bfd-857e-0d6390566420.png)
So I think it may be a fallback for your language. I see at the bottom, there is no trouble however, so it must be due to the different font. Devs might be able to add a second font family for a fallback for the header.

**Comment by KeeJef** [comment]
Probably need a similar font to Wasa Bold, which is the font we use in Session that has Cyrillic alphabet, maybe there is something similar?

**Comment by BlitDev** [comment]
I think that enough people know the basics of English, even if their main language is not English, so it would be possible to simply add a language switching function in the application settings, since everything depends on the system settings now.
**But** this is more like an addition, in general, this is a bug, and it needs to be fixed.

**Comment by KeeJef** [comment]
Okay i think we can just fallback to Roboto when rendering Cyrillic scripts, since [Roboto supports Cyrillic ](https://en.wikipedia.org/wiki/Roboto)

**Comment by Bilb** [comment]
@BlitDev 
Does this look better? 
![image](https://github.com/oxen-io/session-desktop/assets/1544279/64e2c74c-1678-465f-a988-8754bd55fdbb)

**Comment by BlitDev** [comment]
> @BlitDev Does this look better? ![image](https://private-user-images.githubusercontent.com/1544279/260878213-64e2c74c-1678-465f-a988-8754bd55fdbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NjQ1MzgsIm5iZiI6MTcwMDk2NDIzOCwicGF0aCI6Ii8xNTQ0Mjc5LzI2MDg3ODIxMy02NGUyYzc0Yy0xNjc4LTQ2NWYtYTk4OC04NzU0YmQ1NWZkYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMDIwMzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE5ODc5NTBlNTFjY2U0YmZhOWYwNjZlMGI5MGI3Y2E0NmE1ZWI2OTIyOGY1NWNmMjU1YWQ2NDUwYzExYjRiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iVFGLJ8wXQb0DbkFOprAOdLQvmPYTCHzWdzBOig9gBY)
> 
> Looks like the Loor font doesn't support Cyrillic so I made it fallback to Roboto which is the only one we provided which supports it

Yes
