### ISSUE TITLE
[ Feature Request ] Create Group Chats With Only Yourself

### ISSUE THREAD

**Issue by 8227846265** [oxen-io/session-desktop#2259]
**Describe the bug**
Please add the function to be able to create group chats without needing to add another user.

**To Reproduce**
Create private group chat. Cannot create without adding a contact.

**Comment by peepopoggers** [comment]
I would like this too, I think the prospect of setting up a group before inviting anyone is better than inviting people then setting it up.

**Comment by KeeJef** [comment]
We are overhauling closed groups in the next few months including the creation process, ill pass this suggestion on to the UX team
