### ISSUE TITLE
Closed group invites key

### ISSUE THREAD

**Issue by Pantyhose-X** [oxen-io/session-desktop#2277]
Generate private_key
```
session://private_key=a03c383cf63c3c4efe67acc52112a6dd734b3a946b9545f488aaa93da7991238
```

`Expire After` is the duration for which the invite link will work for. Choose between never, 30 minutes, 1, 6, 12 hours or 1 full day.

![](https://support.discord.com/hc/article_attachments/360008519071/2_.jpg)

`Max Uses` is how many times the same link can be clicked before it expires. It can be set to have no limit, 1, 5, 10, 25, 50, or 100 uses.

![](https://support.discord.com/hc/article_attachments/360008519131/3_.jpg)

To create a `permanent invite`, select "`never`" under "`expire after`" and "no limit" under "`max uses`." By doing so, you'll generate a link that has `infinite uses` and won't become obsolete over any period of time. However, it's important to remember that `the only way anyone can access your server` is through an invite key so be careful with who you give it to!

![](https://support.discord.com/hc/article_attachments/360008519251/5_.png)

Once you’ve adjusted the settings to your needs, click “`Generate a New key`” and your new invite link will appear.

**Comment by KeeJef** [comment]
I see this as being a feature more for open groups than closed groups, this would be technically hard to accomplish in a closed group context
