### ISSUE TITLE
[Feature Request] Add more padding to messages

### ISSUE THREAD

**Issue by peepo5** [oxen-io/session-desktop#2287]
It would be nice if messages had more padding (for example, 10px), so it would look like this:
![image](https://user-images.githubusercontent.com/72892531/166953601-935133d0-97b7-4907-99e2-1ca124b935a9.png)
Instead of the current look:
![image](https://user-images.githubusercontent.com/72892531/166953654-9ac68805-845e-474b-8dba-de6ae8c1fb49.png)

**Comment by KeeJef** [comment]
We have increased padding since that screenshot was taken, i think currently our padding on messages is in a good spot
