### ISSUE TITLE
Deleting a message in a conversation causes a jump back to the unread messages marker.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2308]
**Describe the bug**

When a conversation is entered, an initial batch of messages is loaded for the user to read. When the user scrolls to the top or bottom of this batch, more messages are loaded on demand.

If the user (a moderator) deletes messages from this initial batch **before** a new batch is loaded, the reading position will suddenly leap back to the point of entry into the group, i.e. the unread message marker.

This bug has been present ever since Session was changed to enter a conversation at the point of the first unread message.

**To Reproduce**

1. Enter a conversation with unread messages, in which one is authorised to delete messages.
2. Scroll far enough down the screen that the point of entry scrolls off the top of the screen, but do **not** scroll so far that a new batch of messages is loaded. This loading causes a palpable pause in the scrolling and is easy to detect.
3. Delete a message.
4. Instead of remaining at the current cursor point, the messages window will now reset to the unread messages marker.

**Other information (please complete the following information):**

* Session Version: 1.8.5.

**Comment by ianmacd** [comment]
@Bilb @yougotwill When moderating, this bug is driving me batty. I've actually spent a few hours trying to fix it myself, but I can't manage to do it without breaking the functionality of entering a group at the first unread message.

Any chance one of you could give this a quick once-over?

**Comment by KeeJef** [comment]
I've seen this too when moderating, if you need help reproducing

**Comment by ianmacd** [comment]
I'm willing to trade OXEN for developer beverages at this point, if it means we can be rid of this bug. I run into this many times daily and it drives me nucking futs.

@Bilb Any chance you could have a look?

I've already spent an embarrassing number of hours trying to fix it myself, so far to no avail. I must be missing something really obvious.

**Comment by Bilb** [comment]
@ianmacd I don't seem to reproduce this issue.
Can you please confirm that those are the exact steps you do to have the issue?
Are you on windows?

https://user-images.githubusercontent.com/1544279/186554515-8d07c23b-1c99-46ad-acfe-b283aae30eed.mp4

**Comment by Bilb** [comment]
My bad, I can reproduce it on the bottom

**Comment by Bilb** [comment]
are you able to give a build with just that commit a try? 
https://github.com/Bilb/session-desktop/commit/b6387330905f52240221ce33de58d9624c07fb50

**Comment by ianmacd** [comment]
> @ianmacd are you able to give a build with just that commit a try?
> 
> [Bilb@b638733](https://github.com/Bilb/session-desktop/commit/b6387330905f52240221ce33de58d9624c07fb50)

You nailed it.

Looking at the code, I don't feel quite as bad about failing to come up with the solution now. I expected you to fix it with something trivial that I was overlooking, but the problem is actually trickier than that. The `store the didScroll state in the parent` approach is what I was failing to come up with in my own attempts.

This fix makes my life as a moderator considerably more pleasant. If you want to post your OXEN wallet address, I'll send you some beer tokens.

**Comment by Bilb** [comment]
all good. I am glad it works and we got that one fixed!
Just for reference it is waiting review in PR https://github.com/oxen-io/session-desktop/pull/2441

**Comment by KeeJef** [comment]
Closing as fixed
