### ISSUE TITLE
1.8.4 AppImage - Empty room/session/group - no messages - We've been away for a long time... Only fetching last messages of room '*'

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#2324]
**Describe the bug**

I have downloaded via https://getsession.org/download the .AppImage 1.8.4
Ran it on Linux Debian stable release (11).
Via personal message accepted request to join [group](http://session.noff.co:8700/memes?public_key=ea8f844e29c46eb685825165cfe4b9ea044fc52a144ac987c459d3275117e974). Yet it is empty (no messages in it), 52 members. Closed, started Session via command line. Still empty group, no messages despite inviter shows he sees the messages and says he replied the message i have posted to the group. Yet i see only mine message.. Checking console log it shows:

We've been away for a long time... Only fetching last messages of room 'memes'
For other sessions/groups it says: "No new messages for groupname... just updating our last fetched timestamp"

So this is confusing...

**Screenshots or Logs**

[debug log file](https://bin.disroot.org/?f93b1affd16fe77d#2zAVqqPz5hW9RpFzKbmN3Dzg4NVHtPZ6Ve2V1kGqxGVd) (exported from the app, pa$$w0rd: ses)

**Other information (please complete the following information):**

* Device: PC
* OS: Debian 11
* Session Version or Git commit hash: 1.8.4 (detail in the log linked above)

**Comment by KeeJef** [comment]
is this still occurring? haven't seen this in a while

**Comment by slrslr** [comment]
Thank you. I have not seen this issue since reporting this 1 year ago. I assume it is fixed..
