### ISSUE TITLE
With the 1.8.5 release on Windows, it's impossible to reply to a message containing an attachment.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2327]
**Describe the bug**

When the user uses the new 1.8.5 release on Windows to reply to a message containing an attachment, an uncaught `TypeError` exception occurs:

**To Reproduce**

1. Find a message containing an image.
2. Reply to it.
3. An exception occurs. Use `[Control]`+`[Shift]`+`I` and view the console to see it.

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/749942/169013791-5e064472-8055-4d9d-97b3-b850784e6d41.png)

**Other information (please complete the following information):**

* Device: PC
* OS: Windows 10
* Session Version: 1.8.5

**Comment by yougotwill** [comment]
@Bilb can we close this issue?
