### ISSUE TITLE
Copy Pasting a Message with @ into Private Message Results in a Long Hash

### ISSUE THREAD

**Issue by keyandthegate** [oxen-io/session-desktop#2349]
When I copy paste a message from a group channel into a pm channel that has an @ reference to a person in it, it ends up with a long hexadecimal sequence like `@9d6965fcae3531b92200552df3d760b5de6b8995041d83cbf9a5bd25bdc4434b81` (made-up example, not a real user). If the original person I was @-ing is a mutual friend (or the person I'm messaging themselves), @-references should still work in private messages.

**Comment by keyandthegate** [comment]
Also I suggest switching to [base62](https://en.wikipedia.org/wiki/Base62) (or urlsafe base64) instead of hexadecimal for brevity when this sort of thing does occur.

**Comment by keyandthegate** [comment]
Also isn't the length of that hash somewhat excessive? As it just needs to be a lookup it just needs to be long enough to avoid collisions right?

**Comment by KeeJef** [comment]
I think we should try to address this here #2383
