### ISSUE TITLE
Cannot remove some blocked contacts from list.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2352]
**Describe the bug**

I see a large number of blocked contacts that I cannot unblock. The button does nothing.

What's going on here?

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/749942/170830505-86eb0d05-d174-4b18-a391-8d800f32fee3.png)

**Other information (please complete the following information):**

* Session Version: 1.8.6

**Comment by KeeJef** [comment]
We've change the UI for this in recent update, does this issue still persist?

**Comment by KeeJef** [comment]
Closing as I'm assuming this has been fixed
