### ISSUE TITLE
A zoom factor > 100% makes it impossible to scroll the conversations panel.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2355]
**Describe the bug**

When the zoom factor is set to a value greater than 100%, the conversations panel can no longer be scrolled.

**To Reproduce**

1. On a client with more conversations than can be simultaneously displayed in the conversations panel, go to **Settings** and set the zoom factor to **120%**.
2. Return to the main screen.
3. Attempt to use the scrollbar to scroll down to the off-screen conversations.

**Other information (please complete the following information):**

* Session Version: 1.8.6

**Comment by KeeJef** [comment]
Working for me on 1.9.0, is this still occurring?

**Comment by ianmacd** [comment]
> Working for me on 1.9.0, is this still occurring?

No longer an issue in 1.9.1. I will close the issue.
