### ISSUE TITLE
Unblocking a user triggers a ghost message request.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2356]
**Describe the bug**

When a user is unblocked, a new ghost message immediately appears in the message request queue.

**To Reproduce**

1. Go to **Settings**→**Blocked contacts** and unblock a user.
2. Go to **Settings**→**View Message Requests** and observe that there is now a bogus, empty message request from the unblocked user.

**Other information (please complete the following information):**

* Session Version or Git commit hash: 1.8.6.

**Comment by KeeJef** [comment]
Yep i'm reproducing this on my client too

**Comment by KeeJef** [comment]
No longer seeing this behavior, assuming its been fixed
