### ISSUE TITLE
Passphrase for your seed

### ISSUE THREAD

**Issue by Sygiclogic** [oxen-io/session-desktop#2363]
I've seen an issue rise up the past weeks from community members about adding a passphrase to the seed phrase

 it would almost me impossible to steal your full seed phrase in case of a malicious actor gets his hands on your device , because the passphrase is an extend of the seed phrase

Or in a dangerous situation where you are forced to show your "seed" you can go to setting and show them your seed without a security risk because the passphrase is always hidden and a extend of your full seed

**Comment by beantaco** [comment]
The private key and Session ID are derived from the seed phrase. If a password were also needed to recover the private key, a different Session ID would be obtained for each possible password (including no/empty password).

When an attacker forces a Session user to reveal their private key, they will not stop at receiving just the seed phrase, they will also demand the password and verify that the seed phrase and password together are correct by comparing the result Session ID against the known Session ID. If the Session user attempts to disclose the seed phrase without the password, or a wrong password, the attacker would detect the deception.

Assuming the above scheme, given Session IDs are "public" (disclosed to people, not kept secret), I don't see how password protection would add security.

**Comment by KeeJef** [comment]
A PIN code unlock when opening Session, disconnected from device unlock would accomplish the same benefit i think. If an attacker had unlocked device access they still have to know your PIN to enter Session. Encrypting the phrase with a password probably be more confusing and doesn't prevent reading the private keys from memory when the app signs messages.
