### ISSUE TITLE
[Feature request] Make message delivery indicators optional

### ISSUE THREAD

**Issue by beantaco** [oxen-io/session-desktop#2369]
Session has optional read receipts, in case people wish to notify their correspondents they have read messages.

However, message delivery indicators are currently not optional. If a user A sends user B a message, user A gains some information about if and when user B receives the messages, and whether or not user B is currently online. There is currently no way to disable this.

This request is for an option, similar to read receipts, that allows Session users to exercise their consent to have these message delivery indicators sent.

**Comment by KeeJef** [comment]
What do you mean by message delivery indicators? Could you provide a screenshot?

**Comment by KeeJef** [comment]
Closing due to lack of info
