### ISSUE TITLE
Pop-up Notifications Block the Text Box (after copying a chat)

### ISSUE THREAD

**Issue by ThinkALot** [oxen-io/session-desktop#2373]
Session displays unwanted notifications that slide in from the lower right corner of the Session window, and remain for several seconds. **These notifications are a nuisance because they block my view of the text-input box.** 

Each time a notification is displayed:
* I have to manually dismiss it by aiming my mouse at the little x and clicking it.
or
* I have to wait 5 seconds for it to disappear. **I certainly don't need 5 seconds to read 3 words, and anyway, the information displayed is not useful.**

The actions that trigger the notifications include:

- Copying the text of a previously sent or received chat. This causes the following useless notification to be displayed: "Copied to clipboard".
- Pressing the Enter key while the cursor is in the message compose box, when it contains no text. The notification is "Please enter a message body".

These notifications are unnecessary, they interfere with my use of Session, and they remain for far too long.

Suggested solutions:

1. Please **display the notifications elsewhere**, such as in the left pane, so that they do not block my view of the text I am trying to type.
2. **Allow users the freedom to set the duration of the notification**, from 0 seconds to 10 seconds, according to their personal preference. That way, users who don't like the notifications could turn them off, or at least make them disappear sooner.

Thanks.

I'm using Session on Windows 11 on a desktop computer.

**Comment by KeeJef** [comment]
We use the toast notifications to display quite a few notifications to the user and i find them quite useful, i cant think of a case where they interfere with the user interface frequently enough vs the valuable information that they provide to warrant any changes. 

Would be open to merging a PR which modified the time they display for, but closing this for now

**Comment by ThinkALot** [comment]
You have based your decision on your own personal preferences. The users' preferences likely differ, depending on the individual.

That's why I suggested allowing the user to modify the display time of the notifications, as they see fit. For example, users should be able to set the display time to 0 seconds, or 5 seconds, or 10 seconds, or whatever they prefer. That would be more democratic. And it should be easy to accomplish, assuming your team has expert programming skills.

Please consider that.

Thanks.

Paul


________________________________
