### ISSUE TITLE
[Feature Request] Add GIFs to desktop apps

### ISSUE THREAD

**Issue by SisyphusRising** [oxen-io/session-desktop#2374]
When I click the "+" symbol next to the message box on the Linux and Windows desktop app I'm not given the GIF option. I'm immediately taken to file uploads instead. 

Could we include the GIF option on the desktop apps?

**Comment by powline99** [comment]
Requested the same thing: https://github.com/oxen-io/session-desktop/issues/2391

**Comment by KeeJef** [comment]
Closed as duplicate
