### ISSUE TITLE
[Feature Request] Add emoji reactions to messages

### ISSUE THREAD

**Issue by SisyphusRising** [oxen-io/session-desktop#2375]
Add emoji reactions to messages (similar to Element, Discord, or Telegram). Instead of each person replying with a gigantic emoji in response to a message, just add the ability to respond to the message itself with a mini version of the emoji appended to it. Declutters chat space, visually consolidates everything, and simplifies emoji responses.

**Comment by KeeJef** [comment]
Closed as duplicate of #1577
