### ISSUE TITLE
Messages getting out of order

### ISSUE THREAD

**Issue by aaqsoi** [oxen-io/session-desktop#2377]
When I send a message, sometimes the reply appears above the message I sent. Basically making it out of order.

For example, I might send "Hey anon how are you" and anon would reply "I'm good thanks" This message would appear above mine as if they sent it before I even asked. Not a serious issue but can be a bit disorientating when reading the chats.

It is, however, worth mentioning that this issue only occurs when speaking with my friend who lives on a different continent from me. Everyone who I speak to that also lives in Europe doesn't have this issue.

**Comment by KeeJef** [comment]
Do you have a reproducible case for this?

**Comment by KeeJef** [comment]
Closing for now until we can find something reproducible
