### ISSUE TITLE
IM - Session Mac desktop version cannot receive messages

### ISSUE THREAD

**Issue by OliviaC235** [oxen-io/session-desktop#2378]
IM - Session Mac desktop version cannot receive messages. But messages can be sent

**Comment by product-think2049** [comment]
same problem. In mainland China
cannot receive messages, cannot send messages in Mac
(Android, iPhone is OK.)

**Comment by product-think2049** [comment]
Here is the log 
[session_debug_1656464228551.log](https://github.com/oxen-io/session-desktop/files/9006383/session_debug_1656464228551.log)

**Comment by Bilb** [comment]
> Same here. Latest macOS, latest app version, can't connect or send/receive messages. Firewall is off. Default route table. Phone apps connect fine.

Sam here, can you send me your logs?

**Comment by Bilb** [comment]
> IM - Session Mac desktop version cannot receive messages. But messages can be sent
Are you on macOS beta?

**Comment by InoMurko** [comment]
My log:
```
WARN  2022-06-29T07:09:19.661Z [path] Got status at destination: 401
WARN  2022-06-29T07:09:19.661Z Couldn't reach snode at: (...ac28d5); setting his failure count to 2
ERROR 2022-06-29T07:09:19.661Z [path] lokiRpc::processingOnionResponse - Rethrowing error Bad Path handled. Retry this request. Status: 401'
WARN  2022-06-29T07:09:19.661Z onionFetchRetryable attempt #4 failed. 0 retries left...
WARN  2022-06-29T07:09:19.661Z onionFetchRetryable failed  Bad Path handled. Retry this request. Status: 401
WARN  2022-06-29T07:09:19.662Z retrieveNextMessages attempt #1 failed. 1 retries left... Error
```

**Comment by KeeJef** [comment]
Is this still occurring in 1.9.0?

**Comment by InoMurko** [comment]
> Is this still occurring in 1.9.0? 

Nop!
