### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by saravananp-001** [oxen-io/session-desktop#2384]
**error /Users/apple/Downloads/session-desktop-1.8.6/node_modules/better-sqlite3: Command failed.**
Exit code: 1
Command: npm run build-release
Arguments:
Directory: /Users/apple/Downloads/session-desktop-1.8.6/node_modules/better-sqlite3
Output:
> better-sqlite3@7.5.0 build-release
> node-gyp rebuild --releasegyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@16.13.0 | darwin | x64
(node:19799) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/local/bin/python2
gyp info spawn args [
gyp info spawn args  '/Users/apple/Downloads/session-desktop-1.8.6/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args  'binding.gyp',
gyp info spawn args  '-f',
gyp info spawn args  'make',
gyp info spawn args  '-I',
gyp info spawn args  '/Users/apple/Downloads/session-desktop-1.8.6/node_modules/better-sqlite3/build/config.gypi',
gyp info spawn args  '-I',
gyp info spawn args  '/Users/apple/Downloads/session-desktop-1.8.6/node_modules/node-gyp/addon.gypi',
gyp info spawn args  '-I',
gyp info spawn args  '/Users/apple/.node-gyp/16.13.0/include/node/common.gypi',
gyp info spawn args  '-Dlibrary=shared_library',
gyp info spawn args  '-Dvisibility=default',
gyp info spawn args  '-Dnode_root_dir=/Users/apple/.node-gyp/16.13.0',
gyp info spawn args  '-Dnode_gyp_dir=/Users/apple/Downloads/session-desktop-1.8.6/node_modules/node-gyp',
gyp info spawn args  '-Dnode_lib_file=/Users/apple/.node-gyp/16.13.0/<(target_arch)/node.lib',
gyp info spawn args  '-Dmodule_root_dir=/Users/apple/Downloads/session-desktop-1.8.6/node_modules/better-sqlite3',
gyp info spawn args  '-Dnode_engine=v8',
gyp info spawn args  '--depth=.',
gyp info spawn args  '--no-parallel',
gyp info spawn args  '--generator-output',
gyp info spawn args  'build',
gyp info spawn args  '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
 TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
 ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
/Users/apple/Downloads/session-desktop-1.8.6/node_modules/better-sqlite3/deps/extract.js:8
process.on('unhandledRejection', (err) => { throw err; });
                      ^Error: TAR_BAD_ARCHIVE: Unrecognized archive format
  at Unpack.warn (/Users/apple/Downloads/session-desktop-1.8.6/node_modules/tar/lib/warn-mixin.js:19:40)
  at Unpack.warn (/Users/apple/Downloads/session-desktop-1.8.6/node_modules/tar/lib/unpack.js:220:18)
  at Unpack.<anonymous> (/Users/apple/Downloads/session-desktop-1.8.6/node_modules/tar/lib/parse.js:81:14)
  at Unpack.emit (node:events:402:35)
  at Unpack.[emit] (/Users/apple/Downloads/session-desktop-1.8.6/node_modules/tar/lib/parse.js:285:12)
  at Unpack.[maybeEnd] (/Users/apple/Downloads/session-desktop-1.8.6/node_modules/tar/lib/parse.js:401:17)
  at Unpack.[consumeChunk] (/Users/apple/Downloads/session-desktop-1.8.6/node_modules/tar/lib/parse.js:432:21)
  at Unpack.write (/Users/apple/Downloads/session-desktop-1.8.6/node_modules/tar/lib/parse.js:364:25)
  at Unpack.end (/Users/apple/Downloads/session-desktop-1.8.6/node_modules/tar/lib/parse.js:477:14)
  at Pipe.end (/Users/apple/Downloads/session-desktop-1.8.6/node_modules/minipass/index.js:75:17) {
 recoverable: false,
 file: '/Users/apple/Downloads/session-desktop-1.8.6/node_modules/better-sqlite3/deps/sqlcipher.tar.gz',
 cwd: '/Users/apple/Downloads/session-desktop-1.8.6/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3',
 code: 'TAR_BAD_ARCHIVE',
 tarCode: 'TAR_BAD_ARCHIVE'
}
make: *** [b857c92884e9598d609f6be182a2595df7a8e00f.intermediate] Error 1
rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack   at ChildProcess.onExit (/Users/apple/Downloads/session-desktop-1.8.6/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack   at ChildProcess.emit (node:events:390:28)
gyp ERR! stack   at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/Users/apple/.nvm/versions/node/v16.13.0/bin/node" "/Users/apple/Downloads/session-desktop-1.8.6/node_modules/.bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /Users/apple/Downloads/session-desktop-1.8.6/node_modules/better-sqlite3

**Comment by saravananp-001** [comment]
When i install npm i am facing the error in installation. here i am using **node version 16.13.0**

**Comment by novacoole** [comment]
I am experiencing install errors related to the same package:
```
error /Users/nova.c/Documents/code/github/session-desktop/node_modules/better-sqlite3: Command failed.
Exit code: 1
Command: npm run build-release
Arguments:
Directory: /Users/nova.c/Documents/code/github/session-desktop/node_modules/better-sqlite3
Output:
> better-sqlite3@7.5.0 build-release
> node-gyp rebuild --release

gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@16.13.0 | darwin | arm64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /opt/local/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/Users/nova.c/.nvm/versions/node/v16.13.0/bin/node" "/Users/nova.c/Documents/code/github/session-desktop/node_modules/.bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /Users/nova.c/Documents/code/github/session-desktop/node_modules/better-sqlite3
```

**Comment by KeeJef** [comment]
Is this still occurring when building from latest? Build instructions here https://github.com/oxen-io/session-desktop/blob/clearnet/BUILDING.md

**Comment by the-master7** [comment]
Hi session team,
                        Im also facing this better-sqlite3 installation error. Kindly request that the Session team resolves this error(windows machine).

**Comment by KeeJef** [comment]
@tomobre did you run into this recently when building on Windows?

**Comment by KeeJef** [comment]
Please reopen if this is still occurring, but closing now due to lack of recent reports
