### ISSUE TITLE
[Feature Request] Session ID URL

### ISSUE THREAD

**Issue by flolu** [oxen-io/session-desktop#2385]
Telegram has a feature for URL sharing like `https://t.me/<username>` to message a specific user. I would like to be able to generate a URL like: `https://getsession.org/id/<session_id>` to share with people. In that way they could easily message new users if they already have Session. I think it would also help to onboard new users.

**Comment by httpjamesm** [comment]
The session ID should not be passed as a URL path as it would give session servers extra metadata. It should instead be added as a URL fragment and rendered client-side.

**Comment by beantaco** [comment]
My guess is Telegram has a web app that people can access via the URL and then message the user. However, Session does not have this.

What benefits could sharing URL have over sharing just the Session ID?

**Comment by flolu** [comment]
Yes, Telegram does this over its web application. And you're right. Hence it's probably not feasible to implement.

For the second question: I think it could help to onboard new people. Users might put their "Session URL" on their website. Clicking on the link would (1) open the chat, if the user has Session installed or (2) redirect to session installation options, if the user does not have Session installed.

**Comment by Bilb** [comment]
Closing this if favor of #1072
