### ISSUE TITLE
Need to introduce a method to know the number of login sessions

### ISSUE THREAD

**Issue by JanetMw** [oxen-io/session-desktop#2387]
There is a security concern that the user cannot check how many devices the account was logged in. If the private key gets stolen, the attacker can receive and decrypt messages in the past 14 days and there is no way to know the attack takes place, or changing the password.
Messaging app has a much greater attack surface than cryptocurrency wallet software, an attacker can send the payload directly through the messaging app.
I wish there to be a function that tells how many devices were logged in with a random name of each device. We also want to restrict the access of previous message for new login device by authorization on the old device.
It can be hard to be implemented on DAPP, just try your best. Thanks!

**Comment by KeeJef** [comment]
Duplicate of #2180
