### ISSUE TITLE
[Feature Request] Add Gifs Usage on Desktop Software & Add emoji reactions to messages

### ISSUE THREAD

**Issue by powline99** [oxen-io/session-desktop#2391]
1)  I click the "+" symbol and unlike mobile apps there is no gif / giffy option to send on the Linux and Windows desktop ver. Gifs for the desktop versions please. 

2) Please add emoji reaction ability to individual messages if clicked like telegram / discord/ whatsapp (Thumbs up, down, heart, fire, love, clapping, smile, head explode, shock, angry, cry, celebrate, throw up, poop, pray )

Thanks!

**Comment by KeeJef** [comment]
Closed as duplicate #1482
