### ISSUE TITLE
[bug/antifeature] Conversion of last occurring space in messages to non-breaking space

### ISSUE THREAD

**Issue by beantaco** [oxen-io/session-desktop#2396]
Session (Desktop / 1.8.6 / Linux) silently converts the last occurring standard space ` ` (0x20) into a non-breaking space ` ` (0xa0) when sending messages.

For example, if the typed message is `Hello world!` with a standard space, the space between `Hello` and `world!` is converted to a non-breaking space before sending.

Both sent and received messages are affected. I haven't tested what happens when there are non-breaking spaces present in the typed message. I don't know whether or not the same thing happens on Session Android/iOS or Session Desktop non-Linux.

1. Is the conversion intentional, or is it a bug?
2. If the conversion is intentional, what is its purpose?

When the user copies message text, they won't copy the text as originally typed by the sender, they will copy the message modified with the space conversion. This can cause problems when there is interaction with external processes:
- Pasting text into elsewhere will lead to annoying/undesirable non-breaking spaces in the destination document.
- Verifying checksums or cryptographic signatures will fail when the expected message is the original typed message.

Therefore, I believe the Session client should not perform the space conversion, especially not silently, unless there is a compelling reason to do so.

**Comment by burtonemily** [comment]
Hi there, thank you so much for taking the time to report this bug! We hate bugs as much as you do — reporting them helps make Session better for everyone. Our team is currently looking into this issue, we will keep you updated once we know more.

**Comment by jagerman** [comment]
Can confirm with some screenshots.  Here's a message (I've resized the window to be *just* large enough to fit on one line):
![image](https://user-images.githubusercontent.com/4459524/183149220-b3d96b88-72fa-4f19-998c-57088b3264e1.png)
and if I resize the window just slightly smaller both words wrap together to the next line:
![image](https://user-images.githubusercontent.com/4459524/183149309-8031df0e-0cdc-4884-b4e0-5e58ce84248f.png)

**Comment by fracting** [comment]
It only happens when you send a message to another person, when you send to "Note to self" it doesn't happen, that's why we failed to reproduce this bug last time.

**Comment by fracting** [comment]
```
diff --git a/ts/models/message.ts b/ts/models/message.ts
index 2096133ee..ab473bb6c 100644
--- a/ts/models/message.ts
+++ b/ts/models/message.ts
@@ -470,7 +470,7 @@ export class MessageModel extends Backbone.Model<MessageAttributes> {
       convoId: this.get('conversationId'),
     };
     if (body) {
-      props.text = this.createNonBreakingLastSeparator(body);
+      props.text = body;
     }
     if (this.get('isDeleted')) {
       props.isDeleted = this.get('isDeleted');
```

The above hack solves the issue for me. Not sure why we want to replace the text here, someone else can comment?

@KeeJef @Bilb

**Comment by fracting** [comment]
This part of code was inherited from Signal, not sure why they do that:

```
commit 3c69886320c33756962c8e0900728eed1ca041cf
Author: Scott Nonnenberg <scott@signal.org>
Date:   Mon Jul 9 14:29:13 2018 -0700

    Finish new Message component, integrate into application

    Also:
    - New schema version 8 with video/image thumbnails, screenshots, sizes
    - Upgrade messages not at current schema version when loading messages
      to show in conversation
    - New MessageDetail react component
    - New ConversationHeader react component
    - ```

**Comment by fracting** [comment]
Latest Signal Desktop still has the call to createNonBreakingLastSeparator(), but Signal does not have this bug.

I'll leave it for the dev team to investigate, or pick up again over the weekend if no one else response.

**Comment by fracting** [comment]
Yeah crazy, now I respect Signal people less then before lol.

**Comment by fracting** [comment]
I don't understand how Signal prevents the `0xa0` from being copied to the clipboard? Did they implement a hidden layer without the text replacement?

**Comment by ianmacd** [comment]
> The above hack solves the issue for me. Not sure why we want to replace the text here, someone else can comment?

There's another call to `createNonBreakingLastSeparator()` in the same file. We can rip that out, too, followed by the function itself:

```
index 1da75a943..4c4067cf7 100644
--- a/ts/models/message.ts
+++ b/ts/models/message.ts
@@ -67,7 +67,6 @@ import _, {
   map,
   partition,
   pick,
-  reduce,
   reject,
   size as lodashSize,
   sortBy,
@@ -474,7 +473,7 @@ export class MessageModel extends Backbone.Model<MessageAttributes> {
       convoId: this.get('conversationId'),
     };
     if (body) {
-      props.text = this.createNonBreakingLastSeparator(body);
+      props.text = body;
     }
     if (this.get('isDeleted')) {
       props.isDeleted = this.get('isDeleted');
@@ -534,16 +533,6 @@ export class MessageModel extends Backbone.Model<MessageAttributes> {
     return props;
   }
 
-  public createNonBreakingLastSeparator(text: string) {
-    const nbsp = '\xa0';
-    const regex = /(\S)( +)(\S+\s*)$/;
-    return text.replace(regex, (_match, start, spaces, end) => {
-      const newSpaces: any =
-        end.length < 12 ? reduce(spaces, accumulator => accumulator + nbsp, '') : spaces;
-      return `${start}${newSpaces}${end}`;
-    });
-  }
-
   public processQuoteAttachment(attachment: any) {
     const { thumbnail } = attachment;
     const path = thumbnail && thumbnail.path && getAbsoluteAttachmentPath(thumbnail.path);
@@ -643,7 +632,7 @@ export class MessageModel extends Backbone.Model<MessageAttributes> {
       if (quote.text) {
         // do not show text of not found messages.
         // if the message was deleted better not show it's text content in the message
-        quoteProps.text = this.createNonBreakingLastSeparator(sliceQuoteText(quote.text));
+        quoteProps.text = sliceQuoteText(quote.text);
       }
 
       const quoteAttachment = firstAttachment
```

**Comment by fracting** [comment]
Actually, Signal removed createNonBreakingLastSeparator in Mar 2022, my previous statement was based on outdated code.

commit e08d9baabaf65f6d9c8886a94180cee98636c419
Author: Fedor Indutny <79877362+indutny-signal@users.noreply.github.com>
Date:   Mon Mar 21 14:46:20 2022 -0700

    Remove createNonBreakingLastSeparator

**Comment by fracting** [comment]
@ianmacd Thanks Ian, I stole you code, test it locally, and created a pull request #2675

**Comment by ianmacd** [comment]
> @ianmacd Thanks Ian, I stole you code, tested it locally, and created a pull request #2675

No stealing there. That code writes itself.

Thanks for submitting it. I've seen that non-breaking space code many times, and it has always puzzled me, but I didn't think about it very deeply.
