### ISSUE TITLE
WIndows build not build in MacOS

### ISSUE THREAD

**Issue by the-master7** [oxen-io/session-desktop#2398]
I tried Windows build in my macOS but did not build Windows; it only takes from runner os. Please give me suggestions.

**Comment by Bilb** [comment]
Hey,
looks like you need to add some flags for electron-builder to build your app for windows from macos: https://www.electron.build/multi-platform-build.html
> By default build for current platform and current arch. Use CLI flags --mac, --win, --linux to specify platforms. And --ia32, --x64 to specify arch.


Also, we are using some native binaries so I am pretty sure trying to build Session for another platform is not going to work.
Easiest way would probably to get a windows virtual machine on your macOS, and build from there

**Comment by the-master7** [comment]
Thank you for your quick response. I try the window machine.
