### ISSUE TITLE
cannot find path in china

### ISSUE THREAD

**Issue by anyuzu99** [oxen-io/session-desktop#2401]
**Describe the bug**
cannot find path in china the first time started, while ios and android client can find the path.
after proxy/vpn enabled once and the path is found, later the path can be found without proxy/vpn.

**To Reproduce**

1. connect to china network
2. start session

**Other information (please complete the following information):**

* Device: macOS
* OS: macOS 12.5
* Session Version or Git commit hash: 1.8.6

**Comment by KeeJef** [comment]
Do you have any logs for this. If so if you could send them to me at 05d871fc80ca007eed9b2f4df72853e2a2d5465a92fcb1889fb5c84aa2833b3b40 that would be great

**Comment by anyuzu99** [comment]
the problem seem to be solved in the latest release, but the first time connect seems to be really slow in china. check the debug file below.

[session_debug_first.txt](https://github.com/oxen-io/session-desktop/files/9313580/session_debug_first.txt)
[session_debug_second.txt](https://github.com/oxen-io/session-desktop/files/9313581/session_debug_second.txt)

**Comment by KeeJef** [comment]
Thanks for the report, closing now since issue seems to be resolved, but we are still monitoring reports of slow performance in China
