### ISSUE TITLE
Hashes for github release 1.9.1 do not match

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [oxen-io/session-desktop#2424]
The signed hashes posted on the release page do not match the uploaded files.

I wanted to test out session but upon downloading it and verifying the sha256 hash of the executable, it did not match with what was given. Some files match up while others do not.

Checked as follows:
```
root@holly-vps:~/session# wget --quiet https://github.com/oxen-io/session-desktop/releases/download/v1.9.1/latest-linux.yml
root@holly-vps:~/session# wget --quiet https://github.com/oxen-io/session-desktop/releases/download/v1.9.1/latest.yml
root@holly-vps:~/session# wget --quiet https://github.com/oxen-io/session-desktop/releases/download/v1.9.1/session-desktop-linux-amd64-1.9.1.deb
root@holly-vps:~/session# wget --quiet https://github.com/oxen-io/session-desktop/releases/download/v1.9.1/session-desktop-win-1.9.1.exe
root@holly-vps:~/session# wget --quiet https://github.com/oxen-io/session-desktop/releases/download/v1.9.1/session-desktop-win-1.9.1.exe.blockmap
root@holly-vps:~/session# sha256sum *
79fa5a822be65c263c0ed74c1c5f335c3e0046499d5c8ea5617fed14e6674cc8  latest-linux.yml
bf8195711efd5e29ee9c3393df9783a94554690d9f26669e419d890b4767b6eb  latest.yml
0bd66f5b16035635e44b7109d6ad535570fd3267d80b2b92edeaf0c7f7831325  session-desktop-linux-amd64-1.9.1.deb
7a381bebf3b451e9909e2185138b94df330ee48922e5f94805b6fd77172fa4fa  session-desktop-win-1.9.1.exe
948ac2e7802d5477f602aee4783ddce3a839869fd25b47900ed8e994666cb099  session-desktop-win-1.9.1.exe.blockmap
root@holly-vps:~/session#
```

It seems that the hashes for the windows releases do not match as they should be the following:
```
79fa5a822be65c263c0ed74c1c5f335c3e0046499d5c8ea5617fed14e6674cc8 -> OK 
0861564d0e7d73d27c7f0d456d404e56dec51701f99091d4522cbe592af92b43 -> Does not match!
0bd66f5b16035635e44b7109d6ad535570fd3267d80b2b92edeaf0c7f7831325 -> OK
f8df2ef28e78d61cd3d99554a503c2b3d13f3379e67761bf971e35596d522f33 -> Does not match!
d71bc828119b9fc47c526923bbaab24ab1c03e03ac669feffd6fc7a8c967347b -> Does not match!
```

I also checked the mac blockmap and it didn't match either. The hashes for the windows release 1.9.0 do match.

Please provide an explanation as to why this differs.

<details>
<summary>Signed signatures from release</summary>
<pre>
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

The following hashes have been signed for verification using keejef's GPG keys
located in the oxen core repository at https://github.com/oxen-io/oxen-core/blob/master/utils/gpg_keys/KeeJef.asc.

SHA256 Hashes

latest-linux.yml 79fa5a822be65c263c0ed74c1c5f335c3e0046499d5c8ea5617fed14e6674cc8 
latest-mac.yml e2505abe96618d07a7fa9e06d38fecae4782e0da2f2b0c456bb7ade0aa92ea9f
latest.yml 0861564d0e7d73d27c7f0d456d404e56dec51701f99091d4522cbe592af92b43
session-desktop-linux-amd64-1.9.1.deb 0bd66f5b16035635e44b7109d6ad535570fd3267d80b2b92edeaf0c7f7831325
session-desktop-linux-x64-1.9.1.freebsd 966821b1b17884a56c5f19a30f6e1b793c262005d07ffeb513d9543cf14cd385
session-desktop-linux-x86_64-1.9.1.AppImage 65cddbb64bcde22738ec81a281e1491b1e1dc1b33e6fb8ae20ec6999c5a6ad14
session-desktop-linux-x86_64-1.9.1.rpm 7e8e327fccbe07d78fbf6be89a1c55fdbc16c5856f0516d4bbfcacabb645ad2d
session-desktop-mac-1.9.1.dmg dd342dcb7ee432674a9cd72d56c135d0fc6234bd654c36f2ebd12fe015a21b07
session-desktop-mac-1.9.1.dmg.blockmap 677d719ddbba345cd06e4f3e47c89ec4e9c9fdcb34745ffaaa049e2b49fa4faa
session-desktop-mac-1.9.1.zip d7acefbb21163c58f06f82d547012b0883452fac094b7af1c1935d315fc4bf62
session-desktop-win-1.9.1.exe f8df2ef28e78d61cd3d99554a503c2b3d13f3379e67761bf971e35596d522f33
session-desktop-win-1.9.1.exe.blockmap d71bc828119b9fc47c526923bbaab24ab1c03e03ac669feffd6fc7a8c967347b
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBCgAGBQJi9fF1AAoJEKyXFIlc5F1VzXcH/032FGY8AMLFHqplsD5t+WKO
y8uZt/sNvXQWVGH+TLIusdIhd0VwSIDVtpHj9wL5huxlMVB9FvxjCX6iXMD/4RZy
ahHJy3ZiS54JwRxv58SXAQAelAz8np/PvUknq0+vLXucwwL8hjtwVFbQ3oXSPeNc
dI7pHrS9m5rZCg4gHusVLrrlTGB2a+TpbVNff7/mweS3h1Jz7cAo1yT2raTqA2Ob
L5HXJ+JrpMUEPRb7FWjnx92ydDEUBsgFnkFC0fVQ35qhF2R3Sh35ZZe0l6Q79IPc
OsxzWJZ4fFBgZ21/lPvMZda7I5McB3mPj6ng3kx+gcW6/XUKrorWOMs1SP2p0NU=
=uL1y
-----END PGP SIGNATURE-----
</pre>
</details>

**Comment by HoLLy-HaCKeR** [comment]
I double-checked this to make sure it is not corruption during the download, and the same hash I found appears in chocolatey's repositories: https://gist.github.com/choco-bot/478db8b538cc03195366250cce36d9b6#file-install-txt-L149

**Comment by HoLLy-HaCKeR** [comment]
Additionally, it seems that Session v1.9.0 is digitally signed while v1.9.0 is not!

**Comment by KeeJef** [comment]
Strange, i was pretty sure i did sign those releases, must have been an issue with the Github upload, signed builds have been put back up

**Comment by HoLLy-HaCKeR** [comment]
Hashes match up now. The windows builds have different hashes from the initial listing but I assume that's because they got signed again. Closing this issue now, thanks!
