### ISSUE TITLE
lost message

### ISSUE THREAD

**Issue by sakurayz** [oxen-io/session-desktop#2427]
I found that there were some cases where messages were lost, I got new messages after overwriting the install with a newer version.

Open groups that have left are automatically returned

**Comment by sakurayz** [comment]
Is the missing message related to the Hide Message Request Banner?

Is this function practical? It feels hindering the transmission of the message.

**Comment by KeeJef** [comment]
There is insufficient information to diagnose what the issue might be here, please reopen the issue if you can provide device information and Session version info.
