### ISSUE TITLE
WIndow production build issue

### ISSUE THREAD

**Issue by the-master7** [oxen-io/session-desktop#2430]
C:\Users\ms\Downloads\dev\session_desktop>yarn build-release-publish:win32
yarn run v1.22.19
$ yarn build-release-publish-non-linux
$ cross-env SIGNAL_ENV=production $(yarn bin)/electron-builder --config.extraMetadata.environment=$SIGNAL_ENV --publish=always
/electron-builder was unexpected at this time.

C:\Users\ms\Downloads\session_desktop>  "C:\Users\ms\Downloads\session_desktop\node_modules\.bin\\node.exe"  "C:\Users\ms\Downloads\session_desktop\node_modules\.bin\\..\cross-env\src\bin\cross-env.js" SIGNAL_ENV=production $(yarn bin)/electron-builder --config.extraMetadata.environment=$SIGNAL_ENV --publish=always
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by KeeJef** [comment]
Closing in favor of #2420
