### ISSUE TITLE
Make link previews inert or allow users to hide link previews

### ISSUE THREAD

**Issue by beantaco** [oxen-io/session-desktop#2440]
Session Desktop (1.9.1) has an option to enable/disable generating link previews (disabled by default), but no option to enable/disable displaying link previews. When these link previews are clicked/tapped, the default browser is launched and the link is fetched.

While some users may desire link previews, some other users may dislike them. At least, I consider the generation and display of link previews to be undesirable and security risk.

- Following links causes browser requests that are subject to network surveillance (DNS lookup, user IP address exposure), therefore compromising (at least partially) Session's communication secrecy/anonymity. *(It should be noted that many people don't configure their default browser, adopt surveillance browsers or have not hardened their browsers.)*
- Having the default browser get launched is annoying (with small risk of damage or productivity loss) when a link preview is activated by accident and not by the user's will.
- The link could be malicious, potentially compromising the web browser or fetching content that causes harm to the user. *(May be more likely in public chats than closed conversations.)*

Further, given their large surface area, link previews increase the likelihood users activate them by accident.

I request at least points 1 or 2 below, preferably all points; points 1 and 3 could be merged:

1. Make link previews inert (unclickable).
2. Add an option to suppress/display link previews.
3. Add an option to make URLs inside messages inert.

**Comment by KeeJef** [comment]
I think the way that Session Desktop currently handles link previews is appropriate. Link previews are all generated client side by the sender of the link preview, and everything in the link preview is loaded by the receipent using onion requests, including the attached thumbnail image (from Session file server) and description text (included in the message). 

When you click on a link preview you also see a dialog box which warns you about opening links, i think this is enough to cover the concerns you have about accidental exposure

![image](https://user-images.githubusercontent.com/27277414/207235593-8a2e7e85-0c8d-4ac9-8316-32cf627d2289.png)

**Comment by beantaco** [comment]
Given the user is prompted before clicked links are followed, I agree that Session Desktop handles link previews appropriately. Thank you for your comment.
