### ISSUE TITLE
[bug] Message and call notification is unreliable when both phone app and desktop app is logged in.

### ISSUE THREAD

**Issue by KamikazeRaven** [oxen-io/session-desktop#2456]
**Describe the bug**
Notification is really unreliable when both phone app and desktop app is logged in to the same account. The most frustrating issue is that in many situations neither phone app nor desktop app will notify for new messages. I never knew I received new messages until I open the app and check. Sometimes my phone app would ring notification when I check messages on desktop app.

**To Reproduce**
Steps to reproduce the behavior: Login the same account on both mobile phone app and desktop app. Leave both app running in the background. Ask a friend to send a message to you at an random time. If your phone app received the notification, reply to your friend and ask him/her to respond to your message shortly after. Leave your phone at resting mode (put it down and just let it rest). You might not receive notifications for subsequent messages.

**Screenshots or Logs**
No screenshots.

**Other information (please complete the following information):**

* Device: [Pixel 4a, Desktop PC]
* OS: [Android 12 (kernel version 4.14.261), Windows 10 Pro]
* Session Version or Git commit hash: phone app: version1.13.7 (2885). Desktop app: v1.8.6

**Comment by KeeJef** [comment]
Has this improved in subsequent versions of Session Desktop? Personally Session Desktop notifications have always been reliable for me, since they are only based on background polling the Service Node network. But interested to see if anyone else has run into this on Session Desktop.

**Comment by KeeJef** [comment]
Closing for now, as no one else has reported this, and no response from original poster
