### ISSUE TITLE
Disjointed messages

### ISSUE THREAD

**Issue by Diggett** [oxen-io/session-desktop#2476]
**Describe the bug**
Messages between both Linux Appimage and Flatpak versions have severe latency issues when used to contact Session on iOS. Extremely disjointed conversations with messages up to 30 mins late arriving between previous sent messages. This only seems to happen on the Linux clients but it could equally be something with the iOS app. This has only occured in the last couple of weeks and it's altogether possible that I'm doing something wrong that I've not considered. It is a shame though as it's made the app impossibe to use for instant messaging. I think it's great. 

**To Reproduce**
Unaware how to reproduce. Seems to happen almost constantly.

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: PC
* OS: Debian11
* Session Version or Git commit hash:

**Comment by KeeJef** [comment]
Is this still occurring? Would be interested to get logs from both devices in question

**Comment by KeeJef** [comment]
Closing due to lack of info
