### ISSUE TITLE
Add a public API to Session to query values

### ISSUE THREAD

**Issue by techducks** [oxen-io/session-desktop#2477]
Is there a way to integrate an API to query information that is written to your "own" profile?

Example: I store a value in my session ID: age = 18, this value can then be queried via a public API. 

Background: With the service of https://keyoxide.org/ you can link online accounts based on PGP. For this, a PGP fingerprint must be stored in each account, which is queried by Keyoxid. For this a public API must be available. Please have a look at the documentation of Keyoxid.

**Comment by Bilb** [comment]
> own" profile?
if you mean your application data, there is no way as it is potentially encrypted with a user defined password (and stored in the encrypted DB)

**Comment by techducks** [comment]
You are correct. I am asking for a way that is not encrypted and can be accessed through a public API. So you can add some information to your "account" and other people or systems can get this information by asking the public API what information is stored for Session-ID xyz.

**Comment by KeeJef** [comment]
If people want to link metadata to their Session ID, they can use an external service to do so. I do not think that we should include this capability in the protocol itself.
