### ISSUE TITLE
Feature Request: Twit filter (block selected user) for open groups

### ISSUE THREAD

**Issue by BrianHare** [oxen-io/session-desktop#2478]
The mods do a pretty good job keeping things under control in the open groups, but there are still times it'd be handy to be able to prevent a particular user's posts from appearing in the client. Their messages would still arrive as part of the group traffic, just not be displayed on my client. (Back in the day of Usenet messages relayed over Fidonet - Yes, I know, I'm old - this was commonly known as a 'twit filter.' I'm sure there's some other term for it now.) As an added feature, it should probably be impossible to block a moderator in this way. I can block a user in private chat/groups, but can't find a way to do it in open groups. 

Not a super-high-priority feature, I'll grant, but it'd be nice. Please toss it into the priority queue and we'll see where it shakes out. Thanks for building a great product!

**Comment by KeeJef** [comment]
Actually this is currently the way blocking works, if you block someone you wont see their messages in open groups/communities. As a note, after the introduction of ID blinding for open groups/communities you need to block the user per server if you haven't interacted with them before.

**Comment by fracting** [comment]
> Actually this is currently the way blocking works, if you block someone you wont see their messages in open groups/communities. As a note, after the introduction of ID blinding for open groups/communities you need to block the user per server if you haven't interacted with them before.

Does that mean you need to send a message request to the person you don't like first and get accepted so that you can block that person?

**Comment by ianmacd** [comment]
> Does that mean you need to send a message request to the person you don't like first and get accepted so that you can block that person?

It does indeed.

**Comment by fracting** [comment]
> > Does that mean you need to send a message request to the person you don't like first and get accepted so that you can block that person?
> 
> It does indeed.

This is not a well-designed behavior then. @KeeJef

**Comment by KeeJef** [comment]
> > Does that mean you need to send a message request to the person you don't like first and get accepted so that you can block that person?
> 
> It does indeed.

I don't think that's the case, 1.10.4 i can block a user in an open group by clicking on their profile image, then going to three dot menu and blocking, this doesn't require i send a message to them (This is in a group with blinding enabled)

**Comment by ianmacd** [comment]
> I don't think that's the case, 1.10.4 i can block a user in an open group by clicking on their profile image, then going to three dot menu and blocking, this doesn't require i send a message to them (This is in a group with blinding enabled)

Ah, yes. It does work that way now. Thanks.
