### ISSUE TITLE
Desktop not working

### ISSUE THREAD

**Issue by FatBirdie** [oxen-io/session-desktop#2499]
My Session client has been quiet for some time now, thought people just stopped using it. Installed it on my mobile, and see that I can send from my desktop to my mobile, but not the other way around. People have been getting my messages for 2 months now via desktop, but I haven't been receiving anything back just as with my mobile now.

Tried clearing the .config/Session completely, and set up a new Session ID, but to no use. 

Checking the log on desktop, and this is all there is:
Operating System: Linux 5.4.0-125-generic linuxCommit Hash: 184c70f9703da476e1be054543b3f8b47145a218Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Session/1.7.7 Chrome/91.0.4472.164 Electron/13.6.3 Safari/537.36 node/14.16.0 env/production
INFO  2022-09-15T09:10:16.890Z Loaded this list of log files from logPath:

**Comment by ianmacd** [comment]
1.7.7 is really old and doesn't work properly with the current version of the software that the service nodes are running.

Upgrade to the latest version and you should find that your problems disappear.

**Comment by FatBirdie** [comment]
I grabbed the latest appimage from git, after clearing, and it still didnt work.

**Comment by FatBirdie** [comment]
Don't know why it would report the wrong version if its not 1.7.7 on git right now

**Comment by ianmacd** [comment]
> Don't know why it would report the wrong version if its not 1.7.7 on git right now

If you're still seeing 1.7.7 in the log, you're either still running that version somehow, or you're looking at an old log file.

**Comment by yougotwill** [comment]
In version 1.7.7 the auto updating mechanism was broken. We have since fixed it but it was not backwards compatible. Since you used the latest app image and cleared your config folder I see no reason why it shouldn't work. If you can confirm you are running the latest version (`v1.10`) and still have an issue would appreciate you uploading your logs so we can help debug the issue 😊

**Comment by m-j** [comment]
I had the same issue and I can confirm that manually uninstalling and installing newer version solves this issue.
