### ISSUE TITLE
[Feature Request] Community "Spaces"

### ISSUE THREAD

**Issue by tommxcd** [oxen-io/session-desktop#2508]
Adding some way to group multiple open groups into "spaces", or something similar to how Matrix does it. This would be beneficial for big communities who need multiple different discussion channels for different topics while keeping them all in one place.

Or maybe making it so that you could have multiple different discussion channels within one open group?

**Comment by mdPlusPlus** [comment]
*Some* kind of organization tool would be nice. It gets really confusing really quick once you entered a bunch of groups and have gotten a few messages from different contacts.

**Comment by KeeJef** [comment]
Closing for the more general suggestion of "Folders" #2041 which i think would be cool
