### ISSUE TITLE
Emoji reactions not shown on all open group postings.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2544]
I've waited a long time before posting this issue, because it's hard to gather specifics and I loathe being vague, but the problem persists and I have been unable to get to the bottom of it.

Simply put, some postings in open groups do not have their emoji reactions displayed. The same posting in the Android client shows the reactions.

This phenomenon occurs even when using the desktop client is the poster of the reaction. The reaction is properly posted and can be seen using other clients, but does not appear in the desktop client, and thus also cannot be retracted by it.

**To Reproduce**

1. Join an open group, such as any of those available on `sog.caliban.org`.

2. Post emoji reactions to a variety of random messages.

3. Some (I believe **most**) postings will not be updated to display the reactions.

4. Use the Android client to verify that the reactions were correctly posted.

Session Version: Latest `HEAD` of `clearnet`, tagged v1.10.2.

**Comment by ianmacd** [comment]
Also confirmed to be an issue in 1.10.1 official.

**Comment by slrslr** [comment]
20 days later, I would describe my issue same way.

```
Operating System: Linux 5.10.0-18-amd64 linux Commit Hash: 2e364ade1b6e6aec981f36784a7cc2c57465cc55 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Session/1.10.3 Chrome/98.0.4758.141 Electron/17.4.10 Safari/537.36 node/16.13.0 env/production
INFO  2022-10-27T03:55:06.123Z app ready
INFO  2022-10-27T03:55:06.123Z starting version 1.10.3
INFO  2022-10-27T03:55:06.176Z updateSchema:
INFO  2022-10-27T03:55:06.176Z  Current user_version: 11
INFO  2022-10-27T03:55:06.176Z  Most recent db schema: 11
INFO  2022-10-27T03:55:06.176Z  SQLite version: 3.37.2
INFO  2022-10-27T03:55:06.176Z  SQLCipher version: 4.5.1 community
INFO  2022-10-27T03:55:06.176Z  (deprecated) schema_version: 3589
...
INFO  2022-10-30T19:30:53.715Z SOGS Mutation Cache: Entry updated! {"server":"[REDACTED]","room":"test","changeType":0,"seqno":27,"metadata":{"messageId":15,"emoji":"🌼","action":"ADD"}}
WARN  2022-10-30T19:30:53.948Z processOnionRequestErrorOnPath: {}
WARN  2022-10-30T19:30:53.949Z [path] Got status: 404
INFO  2022-10-30T19:30:53.949Z incrementBadPathCountOrDrop starting with guard (...c90ac3)
INFO  2022-10-30T19:30:53.949Z handling bad path for path index 0
WARN  2022-10-30T19:30:53.950Z Failure threshold reached for snode: (...bfaeab); dropping it.
WARN  2022-10-30T19:30:53.950Z Droppping (...bfaeab) from snode pool. 1602 snodes remaining in randomPool
INFO  2022-10-30T19:30:53.992Z dropping snode (...bfaeab) from path index: 0
WARN  2022-10-30T19:30:53.992Z Failure threshold reached for snode: (...6d673f); dropping it.
WARN  2022-10-30T19:30:53.993Z Droppping (...6d673f) from snode pool. 1601 snodes remaining in randomPool
INFO  2022-10-30T19:30:54.025Z dropping snode (...6d673f) from path index: 0
WARN  2022-10-30T19:30:54.026Z Droppping (...c90ac3) from snode pool. 1600 snodes remaining in randomPool
INFO  2022-10-30T19:30:54.073Z Dropping path starting with guard node (...c90ac3); index:0
```

I have tried to post 2 various emoji to 1 post of other person in my own community. There was app restart between the attempts. It does not show up (yet in recent emoji list last used emoji is topped up to 1st position) and i see above log lines.
