### ISSUE TITLE
Choose language when installing the desktop app

### ISSUE THREAD

**Issue by mockinbirdy** [oxen-io/session-desktop#2554]
There is no way to choose your language when you install the desktop version. It automatically chooses the one set by OS (which is also kinda sus for this kind of app). It is very frustrating for people who speak several languages, especially if they want to use English as their main language for session.
Please, fix it 1) by providing an option to change the application language after it has been installed and 2) by providing language options in installation process.

**Comment by ianmacd** [comment]
> There is no way to choose your language when you install the desktop version. It automatically chooses the one set by OS (which is also kinda sus for this kind of app). It is very frustrating for people who speak several languages, especially if they want to use English as their main language for session. Please, fix it 1) by providing an option to change the application language after it has been installed and 2) by providing language options in installation process.

Until this is properly implemented, you can try the following:

If you're on Windows, try running from a `.bat` file and pass `--lang=en-GB` or whatever to the binary. This won't affect the language of the spell-checker, however.

If you're on Linux, run with `LANG=en_GB.UTF-8`.

**Comment by mockinbirdy** [comment]
Oh well, I guess deleting unnecessary .pak also helps.

**Comment by KeeJef** [comment]
Closing this as i think #1877, is probably the better approach (putting this setting in the settings page instead of onboarding)
