### ISSUE TITLE
Unable to copy or save QR code image

### ISSUE THREAD

**Issue by zellchristensen** [oxen-io/session-desktop#2586]
**Describe the bug**
The QR code image of your session ID cannot be copied or saved.

**To Reproduce**
Click on your profile icon on the left.
Click on the small QR code icon to the top right of your profile image.
Attempt to copy or save the image.

**Other information (please complete the following information):**

* Device: PC
* OS: Windows 7
* Session Version or Git commit hash: v1.10.3 / 2e364ade1b6e6aec981f36784a7cc2c57465cc55

**Additional Information**
There is a COPY button underneath the session ID text that will copy the text ID but there is no such button for the QR code.

**Suggestions**
I think it would be better to eliminate the floating QR code over the profile icon on the profile section entirely.  Instead, the QR code should just be below it since the session ID is already there in plain text.  This would save the user a click.  Then the user can just click on the image itself to copy to clipboard or click on the text ID to copy it.

![image](https://user-images.githubusercontent.com/38737447/198812976-42360a88-e72a-4653-991f-78d92a174e70.png)

**Comment by KeeJef** [comment]
Yeah a save to file option for the QR code would be good

**Comment by Bilb** [comment]
Closing this in favor of https://github.com/oxen-io/session-desktop/issues/1860
