### ISSUE TITLE
[Linux] Profile picture not loaded to Session

### ISSUE THREAD

**Issue by WX4300** [oxen-io/session-desktop#2591]
**Describe the bug**
I just linked my Android account to the Linux version of the app, the profile picture is not present on linux

**To Reproduce**
1. Use Session on Android
2. Set your profile pic on Android
3. Link / Restore your account on Linux
4. After importing your account the profile picture is not present on Linux

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: PC
* OS: Linux - Solus OS
* Session Version or Git commit hash: v1.10.3

**Comment by mdPlusPlus** [comment]
Have you tried to send a message on Linux after switching? Did it update your profile picture then?

**Comment by KeeJef** [comment]
There's definitely issues with this code, I've seen profile images not restored before. We're updating the way config messages are handled in the new year, these are the messages which restore your profile image, display name,contacts, etc... when you link a device. Lookout for those updates

**Comment by KeeJef** [comment]
User config changes are live, syncing of profile images across devices should be much more reliable, closing this for now
