### ISSUE TITLE
[Feature request] Allow AppImages to be updated using AppImage tools

### ISSUE THREAD

**Issue by WX4300** [oxen-io/session-desktop#2602]
AppImageUpdate: https://github.com/AppImageCommunity/AppImageUpdate
AppImageLauncher: https://github.com/TheAssassin/AppImageLauncher

![image](https://user-images.githubusercontent.com/113265063/202316665-b2578563-c01a-4c5e-9922-df6e1616bcac.png)

**Comment by KeeJef** [comment]
I think our current update methods are probably more appropriate, we have a .deb package which is distributed through a repository at https://deb.oxen.io, which you can auto update from, and we have in app updates which trigger when a new Github release is made. Closing for now
