### ISSUE TITLE
AppImage locks up when trying to paste

### ISSUE THREAD

**Issue by 2011** [oxen-io/session-desktop#2605]
**Describe the bug**

Suddenly, I can not paste anything without the app locking up (cursor stops blinking, mouse clicks do absolutely nothing). I have tried restarting several times, and as soon as I attempt to paste anything in the message field (any contact), the app just stops responding, and I have to kill it externally (I can "close" session, but all of the processes continue to run).

**To Reproduce**

See above.

**Screenshots or Logs**

[debug.log](https://github.com/oxen-io/session-desktop/files/10052523/debug.log)
[log.log](https://github.com/oxen-io/session-desktop/files/10052526/log.log)

**Other information (please complete the following information):**

* Device: linux (obviously)
* OS: [5.10.69]
* Session Version or Git commit hash: 991ddd1cbaa1948c865b5e8ad9b2b8137f04641c Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Session/1.10.4 Chrome/98.0.4758.141 Electron/17.4.10 Safari/537.36 node/16.13.0 env/production

**Comment by KeeJef** [comment]
Is this still occurring on the latest version of Session desktop?

**Comment by 2011** [comment]
No, I didn't have that problem from 1.10.5 onward (and I completely forgot about this bug report).
