### ISSUE TITLE
Feature Request: Remove ability to download audio message

### ISSUE THREAD

**Issue by secularaloha** [oxen-io/session-desktop#2608]
Currently, audio messages can be downloaded in the desktop app (not sure on mobile). I don't think this should be allowed.

**Comment by KeeJef** [comment]
Audio messages are already being downloaded so they can be played in the application, so removing the UI option to download them to a configurable location doesn't really increase user security. Closing for now

**Comment by mdPlusPlus** [comment]
How would one go about downloading an audio message? I don't see any option to select and download them.

**Comment by KeeJef** [comment]
@mdPlusPlus I meant that to play an audio message your device downloads the audio message in the background to your device, this action is not visible to the user, but it is happening already.

**Comment by mdPlusPlus** [comment]
I am aware of that, but I'm having trouble understanding what the OP @secularaloha meant. It sounds like there is some way to download audio messages to a selectable location just like any other file attachments, but I can't find a UI element to do so.
