### ISSUE TITLE
Notification count does not reflect the sum of unread messages across all conversations.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2613]
The notification count in the leftmost panel reflects only the number of unread messages in the conversation to have most recently received a message, whereas it should reflect the sum of unread messages across **all** conversations.

For illustrative purposes, the low ceiling of 99 unread messages has been removed here, or all that would be seen is `99+`. The visual capping of the total unread count at 99 is itself rather odd, since individual conversations are capped at 9999 (a limit also removed in this screenshot).

![image](https://user-images.githubusercontent.com/749942/205104985-25093e56-32a2-4f25-9e62-cc972878822b.png)

* OS: Windows 11
* Session Version: Head of `clearnet` branch.

**Comment by Bilb** [comment]
@ianmacd when you say you removed the 99 low ceiling. Do you mean on the the UI only, or also in the logic.
If only UI, the fix might be in 

`ts/state/seelctors/conversations.ts`
```ts

    if (
      unreadCount < 100 && // Increment this to the desired ceiling
      conversation.unreadCount &&
      conversation.unreadCount > 0 &&
      conversation.currentNotificationSetting !== 'disabled'
    ) {
      unreadCount += conversation.unreadCount;
    }
```
