### ISSUE TITLE
Link Previews Error

### ISSUE THREAD

**Issue by oxenreport** [oxen-io/session-desktop#2614]
small bug report: when go to settings and try to enable link previews, you get popup windows warning with two buttons: OK and Cancel. the options stays on regardless what you chose (it should go back to OFF if Cancel is selected after the warning is shown). Platform: WIN10, latest ver

**Comment by KeeJef** [comment]
user also uploaded this video, which shows the specific issue

https://user-images.githubusercontent.com/27277414/205562256-88dfad6f-c3f8-4f75-9f11-8ec1207b815d.mp4

**Comment by KeeJef** [comment]
This is fixed now
