### ISSUE TITLE
Session Desktop does not show emoji reactions when there is a conflict of message.id (serverID)

### ISSUE THREAD

**Issue by fracting** [oxen-io/session-desktop#2617]
**Describe the bug**

For some users, on Session Desktop, in some public Session Community, some emoji reactions do not show.

As far as I know, all three users who reported the same experience have a common character:
We all subscribe to both `Off-Topic` (as known as `offtopic`) and `Poweruser Feedback` (as known as `user`)

**To Reproduce**

Communities:
* Off-Topic: 
  * ConversationID: `publicChat:offtopic@https://sog.zcyph.cc`
  * URL: `https://sog.zcyph.cc/offtopic?public_key=b7ec84eb480a17994cadfbbc36ec7f48f900adb8ded09d307ad52d1383632f78` 

* Poweruser Feedback
  * ConversationID: `publicChat:user@http://116.203.51.179`
  * URL: `http://116.203.51.179/user?public_key=39016f991400c35a46e11e06cb2a64d6d8ab6652e484a556b14f7cf57ed7e73a`

Actors:
* Alice, Session Desktop
* Bob, any Session client

Steps:

1. Alice subscribes to `offtopic` earlier than `17/11/2022, 02:52:30`, and caches old enough conversation history containing the conflicting message.

2. Alice subscribes to `user` earlier than `30/11/2022, 21:13:17`, which again caches old enough conversation history containing the other conflicting message.

3. Bob subscribes to `user`, sends an emoji reaction to any recent message, like the one with message ID `1306`: `Thanks, the spam comments were deleted and my replies are also deleted. Sorry for the inconvenience!`

4. Alice checks `user` again.

Expect result: Alice should be able to see the emoji reaction sent by Bob.
Actual result: Alice can't see any recent emoji reactions.

**Screenshots or Logs**

I added some log in the `getMessageByServerId` function, and found a conflict of message IDs. One message from `user` and the other message from `offtopic` share the same message ID `1306`, unfortunately, the `.get()` function only returns the first row from query result which does not necessarily match the right one. When it returns the wrong message, the emoji does not shown. 

```
function getMessageByServerId(serverId: number) {
  const row = assertGlobalInstance()
    .prepare(`SELECT * FROM ${MESSAGES_TABLE} WHERE serverId = $serverId;`)
    .get({
      serverId,
    });

  if (!row) {
    return null;
  }

  return jsonToObject(row.json);
}
```

```
[
  {
    "id": "5713c630-78e2-405f-9b32-705d3e8d5a3d",
    "json": "{\"serverTimestamp\":1668613950983,\"serverId\":1306,\"sent_at\":1668613950983,\"received_at\":1668613950983,\"isPublic\":1,\"conversationId\":\"publicChat:offtopic@https://sog.zcyph.cc\",\"messageHash\":\"\",\"unread\":0,\"type\":\"incoming\",\"direction\":\"incoming\",\"source\":\"15b4059f3d6ae4ebefb4925cf21f6d2b71f7cd2192adff8129e56b14521227d767\",\"expireTimer\":0,\"id\":\"5713c630-78e2-405f-9b32-705d3e8d5a3d\",\"flags\":0,\"preview\":[],\"attachments\":[],\"body\":\"Let's be honest. The phama and medical industries are businesses. There is no money in healthy people.\\n\\nWe don't need constant boosters to live. Also, t's not my civic duty to have a job of who knows what just so I can wave my virtue signaling flag.\",\"errors\":[]}",
    "unread": 0,
    "expires_at": null,
    "sent": null,
    "sent_at": 1668613950983,
    "conversationId": "publicChat:offtopic@https://sog.zcyph.cc",
    "received_at": 1668613950983,
    "source": <skip>,
    "hasAttachments": null,
    "hasFileAttachments": null,
    "hasVisualMediaAttachments": null,
    "expireTimer": 0,
    "expirationStartTimestamp": null,
    "type": "incoming",
    "body": "Let's be honest. The phama and medical industries are businesses. There is no money in healthy people.\n\nWe don't need constant boosters to live. Also, t's not my civic duty to have a job of who knows what just so I can wave my virtue signaling flag.",
    "serverId": 1306,
    "serverTimestamp": 1668613950983,
    "serverHash": null,
    "isDeleted": null
  },
  {
    "id": "ed3fa301-da52-4601-b2b3-a303266ee413",
    "json": "{\"body\":\"Thanks, the spam comments were deleted and my replies are also deleted. Sorry for the inconvenience!\",\"preview\":[],\"attachments\":[],\"sent_at\":1669803197577,\"expireTimer\":0,\"serverTimestamp\":1669803197577,\"conversationId\":\"publicChat:user@http://116.203.51.179\",\"source\":\"05d4768bc1b7959d8d1334e2c68a60afd720a3bc1708c994a42878e3d11f434538\",\"type\":\"outgoing\",\"direction\":\"outgoing\",\"unread\":0,\"received_at\":1669803193881,\"id\":\"ed3fa301-da52-4601-b2b3-a303266ee413\",\"hasAttachments\":0,\"hasVisualMediaAttachments\":0,\"hasFileAttachments\":0,\"serverId\":1306,\"isPublic\":1,\"sent\":1,\"sync\":1,\"synced\":1,\"sentSync\":1}",
    "unread": 0,
    "expires_at": null,
    "sent": 1,
    "sent_at": 1669803197577,
    "conversationId": "publicChat:user@http://116.203.51.179",
    "received_at": 1669803193881,
    "source": <skip>,
    "hasAttachments": 0,
    "hasFileAttachments": 0,
    "hasVisualMediaAttachments": 0,
    "expireTimer": 0,
    "expirationStartTimestamp": null,
    "type": "outgoing",
    "body": "Thanks, the spam comments were deleted and my replies are also deleted. Sorry for the inconvenience!",
    "serverId": 1306,
    "serverTimestamp": 1669803197577,
    "serverHash": null,
    "isDeleted": null
  }
]
```
**Other information (please complete the following information):**

* Device: [Mac]
* OS: [12.6]
* Session Version or Git commit hash: 1.10.4

**Comment by fracting** [comment]
This hack, while obviously ugly, it demonstrates a potential approach to fix. By matching both `conversatoinId` and `serverId` when query the database, I can see new emojis from the `user` public community eventually. Old messages had been cached in database already and is not showing even with the hack.

**This hack will break the other public community of course, just a quick hack to proof what was wrong.**

```
function getMessageByServerId(serverId: number) {
  const row = assertGlobalInstance()
    .prepare(`SELECT * FROM ${MESSAGES_TABLE} WHERE conversationId = 'publicChat:user@http://116.203.51.179' AND serverId = $serverId;`)
    .get({
      serverId,
    });

  if (!row) {
    return null;
  }

  return jsonToObject(row.json);
}
```

**Comment by fracting** [comment]
[0001-hack-get-message-by-conversation-id-and-server-id.txt](https://github.com/oxen-io/session-desktop/files/10146664/0001-hack-get-message-by-conversation-id-and-server-id.txt)

Attached is a better hack which works for me.

What really makes me concerned is:
1. Shouldn't message.id / serverId a unique ID in the first place? With such a small number it seems hard to not to have conflicts
2. Is there any hidden bugs in other callers of `getMessageByServerId`?

I'll leave it to the dev team for a proper fix.

**Comment by ianmacd** [comment]
> What really make me concerned are:
> 
> 1. Shouldn't message.id / serverId a unique ID in the first place? With such a small number it seems hard to not to have conflicts

I'm confused by the code, which seems to refer only to `serverId` when fetching messages, never the message id (`id`).

How are server ids even assigned? Does each SOGS instance decide its own server id, or does Session allocate an id to each server the user adds a subscription from?

**Comment by fracting** [comment]
> > What really make me concerned are:
> > 
> > 1. Shouldn't message.id / serverId a unique ID in the first place? With such a small number it seems hard to not to have conflicts
> 
> I'm confused by the code, which seems to refer only to `serverId` when fetching messages, never the message id (`id`).
> 
> How are server ids even assigned? Does each SOGS instance decide its own server id, or does Session allocate an id to each server the user adds a subscription from?

I'm equally confused, the naming of serverId is ambiguous, not sure what it really means, not sure if there is a more surprising mistake here.

**Comment by Bilb** [comment]
> How are server ids even assigned? Does each SOGS instance decide its own server id, or does Session allocate an id to each server the user adds a subscription from?

For message sent to a community/sogs, we get a serverId once the message is successfully sent.
For message sent to a swarm (closed group or private chats), there is a no such id. In that case we usually rely on the messageHash or the sentTimestamp to identiy a message.


Thanks for the details bug report. We will need to forward the conversationId on all calls to make sure we can use it in the `getMessageByServerId()`
I'll find some time to have a look.

**Comment by fracting** [comment]
Thanks for looking into this. serverId sounds ambiguous, it sounds like unique ID on sogs level, but as you explained it’s actually ID on message level. Maybe it should be called serverMessageId / serverSideMessageId / messageReceiptId instead.

**Comment by ianmacd** [comment]
> Thanks for looking into this. serverId sounds ambiguous, it sounds like unique ID on sogs level, but as you explained it’s actually ID on message level. Maybe it should be called serverMessageId / serverSideMessageId / messageReceiptId instead.

I'm already running with your patch, for which many thanks.

Perhaps you could formally submit it as a pull request, in the hope of getting the fix merged into Session sooner. You can just take the commit from my own fork (https://github.com/ianmacd/session-desktop/commit/77d3687c03b12a91e48ba74deae373c38fbb5540) to save time, if you wish.

**Comment by fracting** [comment]
Hi @ianmacd , is this issue a duplicate of https://github.com/oxen-io/session-desktop/issues/2544 ?

Sorry I didn't search for github duplicated issue before creating this one and wasn't aware that you've already reported one, I should have a better search next time.

**Comment by fracting** [comment]
> > Thanks for looking into this. serverId sounds ambiguous, it sounds like unique ID on sogs level, but as you explained it’s actually ID on message level. Maybe it should be called serverMessageId / serverSideMessageId / messageReceiptId instead.
> 
> I'm already running with your patch, for which many thanks.
> 
> Perhaps you could formally submit it as a pull request, in the hope of getting the fix merged into Session sooner. You can just take the commit from my own fork ([ianmacd@77d3687](https://github.com/ianmacd/session-desktop/commit/77d3687c03b12a91e48ba74deae373c38fbb5540)) to save time, if you wish.

Hi @ianmacd thanks for testing the patch!

My hack is not complete, as @Bilb mentioned, there are other instances of `getMessageByServerId()` need to be fixed which requires some more refactoring.

I'm not familiar with the entire codebase and I think it's safer for @Bilb to make the change. Appreciate for taking care of the issue @Bilb !

**Comment by Bilb** [comment]
@ianmacd saw your changes and made a comment. If you make a PR of it I'll merge it.
Thanks

**Comment by ianmacd** [comment]
> @ianmacd saw your changes and made a comment. If you make a PR of it I'll merge it. Thanks

I've made the changes and will submit the PR after some sleep.

There are still a few calls to `getMessageByServerId()` remaining in the code, however.

It appears that we can get away with at least some of these, because the context in which they're called results in the right message being addressed. A couple of them look problematic, though, and working `conversationId` into those will have a knock-on effect that will touch a lot of code elsewhere.

On the other hand, this patch **may** be all that is needed, as it does seem to address the missing emoji problem.

**Comment by ianmacd** [comment]
> Can we consider adding a warning log or TODO/FIXME in the original getMessageByServerId() function to point out the potential risk? Otherwise, we might fix one bug but hide other potential bugs deeper, and hit ourselves in the foot with accumulated tech debt.

I made a couple of very minor changes to the code and committed the patch on your behalf.

I also included the requested FIXME where `getMessageByServerId()` is defined.
