### ISSUE TITLE
Scroll/jump of the timeline in group when some messages are removed - cancels emoji selecting dialog.

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#2619]
When the Session group is active and i try to add emoticon/emoji to someone's post, it often fails due to the timeline "jump" vertically due to someone remove offtopic messages, it hide the dialog where one is selecting the emoticon/emoji.

Similar issue: #2308

* Device: PC
* OS: Debian with KDE
* Session Version or Git commit hash: AppImage 1.10.4, 991ddd*

**Comment by KeeJef** [comment]
Requires investigation

**Comment by KeeJef** [comment]
Sounds like the same issue as #2536

**Comment by Bilb** [comment]
Yeah, those two issues have probably the same root cause (the whole tree is rerendered when a new messages comes in, but it should not be)

**Comment by Bilb** [comment]
keeping track of this in https://github.com/oxen-io/session-desktop/issues/2536
