### ISSUE TITLE
Collapsible sidebar

### ISSUE THREAD

**Issue by rauldipeas** [oxen-io/session-desktop#2621]
**Describe the bug**
There are any plans to make Session interface responsive with a collapsible sidebar?

**To Reproduce**
I'm using KDE with [Bismuth](https://github.com/Bismuth-Forge/bismuth) to tiling my windows.

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/12108031/206195421-14f4ec3d-649a-4fef-8b86-f9d46afdc5b7.png)

**Other information (please complete the following information):**

* Device: PC
* OS: Kubuntu 22.04
* Session Version or Git commit hash: Latest available on `apt` repository.

**Comment by mdPlusPlus** [comment]
See #2492

**Comment by KeeJef** [comment]
Closing for now, but yes we are intrested in doing #2492 and potentially #1304
