### ISSUE TITLE
Sending only an image as a reply to a quoted message loses the quoted message.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2625]
**Description**

When performing a 'Reply to Message', if only an image (i.e. without accompanying text) is sent, the message is decoupled from the original message and the image is sent as a non-quoting message.

**To Reproduce**

1. **Reply to Message**
2. Paste an image into the composition box.
3. Send the message.

Note that the original message, which was quoted during composition, is now gone, and one's own message has been sent as a top-level message.

* Session: 1.10.4
* OS: Windows 11

**Comment by yougotwill** [comment]
Interesting. Will look into it when I can. Thanks Ian 🙏

**Comment by mdPlusPlus** [comment]
Same thing happens when you reply to a message with a link and have link preview generation enabled. The link preview gets generated and overwrites the attached reply (on Android at least, I can't remember right now whether this happened on desktop, too.)
