### ISSUE TITLE
Feature: Disallow setting nickname for self for privacy reason?

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#2631]
There was an idea that for privacy reason,

in communities (public groups) should not appear user custom nicknames, but instead of it part of the SessionID.

Users should not override how their appear in a community/private chat, but other people can label them for themself. Similar to a SMS/phone contacts - you label others, not that they set nickname to appear for you when they call you.

This may also prevent confusion when someone pretend to be someone else or make an impression and users may act more carefully, knowing they are dealing with some random unknown person.

**Comment by KeeJef** [comment]
This would decrease the usability of Session inside of open groups pretty significantly, To be able to have a conversation it helps to be able to quickly identify the users in that conversation and this would make it much harder

**Comment by KeeJef** [comment]
Closing this one based on my above comment
