### ISSUE TITLE
A post-blinding message that quotes a pre-blinding message cannot be used to jump to the quoted message.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2636]
I enabled Session id blinding for `sog.caliban.org` on 2023-01-01 at 00.00 UTC. The server runs PySOGS 0.3.6.

If I now compose a new reply message, X, quoting another message, Y, posted prior to enabling id blinding, clicking on the quoted part of Y does not redirect Session to message Y in the timeline. Instead, `Original message not found` is displayed in a toast.

This occurs with Session 1.10.4.

**Comment by KeeJef** [comment]
Closing this as all SOGS should have migrated to blinding by now, and this will only affect pre blinded messages reducing the chance of running into this
