### ISSUE TITLE
[user experience] Direct messaging related UI is confusing

### ISSUE THREAD

**Issue by grinapo** [oxen-io/session-desktop#2637]
First time user experience:
It seems logical that if I want to DM someone then I click on their icon, get their data sheet and select direct messaging. However I haven't found it for tens of minutes, looking every menu and button.

Later I have been told that clicking the icon actually immediately opens the chat, and the bottom strip is actually a message box. This is extremely not obvious.

It would be nice if the upper pane would contain some indicator text like "You can start messaging the user by typing into the bottom textbox" or like.

**Comment by KeeJef** [comment]
Agree, we have this on other platforms

**Comment by KeeJef** [comment]
Looks like we will be handling this one internally

**Comment by ianmacd** [comment]
> Looks like we will be handling this one internally

I suggest the following fix, which I'm using in my own client:

https://github.com/ianmacd/session-desktop/commit/6e4616cc34981010e4fd7ade60c24f200702cbdc

The dialogue for the desired behaviour is already there, but isn't being used.

**Comment by KeeJef** [comment]
This has been fixed by adding text in the empty conversation. "You have no messages from xxxxx. Send a message to start the conversation"
