### ISSUE TITLE
can't leave a group

### ISSUE THREAD

**Issue by danielb2** [oxen-io/session-desktop#2647]
**Describe the bug**

tried to leave a group multiple times on multiple devices, but the group keeps reappearing. it's in fact the official "session" group which is incredibly off-topic. I was hoping to get support at some point, but now it appears I'm stuck with it.

**To Reproduce**

not sure, and my best guess is due to how session syncs, it's an issue because not all my devices are on at the same time (desktop, laptop, mobile phone).

but this is my best guess:

1. join group
2. have multiple devices login and use account
3. close all devices
4. leave group on one of them
5. wait

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: Mac, Android
* OS: Monterey
* Session Version or Git commit hash: this issue has persisted for over a month now. desktop, laptop: 991ddd1cbaa1948c865b5e8ad9b2b8137f04641c, android 1.16.3

**Comment by KeeJef** [comment]
Should have this fixed soon with our config message management changes

**Comment by KeeJef** [comment]
Should be fixed now
