### ISSUE TITLE
Message with quote is mis-rendered as plaint text message without quote body on Desktop if the expected quote body was sent from a linked iOS client of the same account and the replier is using Session mobile client

### ISSUE THREAD

**Issue by fracting** [oxen-io/session-desktop#2655]
**Describe the bug**
This is a sibling of https://github.com/oxen-io/session-ios/issues/768 and https://github.com/oxen-io/session-android/issues/1076

**To Reproduce**

* Sender: Alice on iOS (this is crucial: Neither replacing Alice on iOS with Alice on Desktop 1 nor Alice on Desktop 2 won't reproduce the bug)
* Replier: Bob on iOS or Android (replacing Bob on mobile with Bob on Desktop can't reproduce the bug)
* Viewer: Alice on Desktop
* Community with blinded Id enabled

1. Alice on iOS sends a test message to the community: `This is Alice from iOS`
2. Bob quotes and replies to Alice's message in the community: `Quote "This is Alice from iOS" by Bob"`
3. Alice on Desktop checks the conversation history in the community

Alice on Desktop shows an orphan plaint text message sent from Bob, instead of a message with a quote to Alice's original message.

**Screenshots or Logs**

-------------
**Alice's view on iOS**

<img src="https://user-images.githubusercontent.com/194342/214065948-b266d313-3fa7-4b19-90e6-bab71a99cf30.jpeg" width=347 />

-------------

**Bob's view on iOS**
<img width="347" alt="Screen Shot 2023-01-24 at 1 29 38 am" src="https://user-images.githubusercontent.com/194342/214066811-ec145b2d-592e-4e05-8323-860b6400ce6d.png">

-------------

**Alice's view on Desktop**
<img width="471" alt="Screen Shot 2023-01-24 at 1 29 49 am" src="https://user-images.githubusercontent.com/194342/214067040-d66b28d1-a4d3-472a-b696-ac200e124814.png">

Note that the quoted body is missing

-------------

**Other information (please complete the following information):**

This might be a side effect of a Session iOS bug instead of a Session Desktop bug, but at least it reveals a Session Desktop UI flaw: in the worst case, Session Desktop should fallback to a message with the quote body "Original message not found" rather than fallback to a plain text message, which might cause the original sender to miss important replies.

* Device: [Mac]
* OS: [macOS 12.6]
* Session Version or Git commit hash: Session Desktop 1.10.4 + Session iOS 2.2.4

**Comment by fracting** [comment]
There are lots of combinations to test:

* 4 combinations of (Viewer account, Sender account, Replier account) after deduplication on symmetric cases:
```
[
  (Alice, Alice, Alice),
  (Alice, Alice, Bob),
  (Alice, Bob, Bob),
  (Alice, Bob, Carol)
]
```

* 27 combinations of (Viewer device, Sender device, Replier device)
```
{Android, iOS, Desktop} * {Android, iOS, Desktop} * {Android, iOS, Desktop}
```

Totally 4 * 27 = 108 theoretical different cases to test.

It would be a nightmare to manually exhaust all these combinations.

Better to gradually migrate as many cross-platform features into libsession as possible so we can reduce the number of cases needs to be tested.

**Comment by fracting** [comment]
> If we view relationships as directed arrows rather than undirected links, then there are even more test cases.
Likely to be (1+3+3+27) * 27 = 918 cases in total.

This reminds me of property based testing:

https://dev.to/jdsteinhauser/intro-to-property-based-testing-2cj8
https://hypothesis.works/articles/quickcheck-in-every-language/

Is property based testing used in any Oxen projects at the moment? Seems like a good fit for  https://github.com/oxen-io/libsession-util

**Comment by fracting** [comment]
Here is a small subset of bugs I found:


| Viewer        | Sender    | Replier                                              | Issue                                                           | URL                                                    |
|---------------|-----------|------------------------------------------------------|-----------------------------------------------------------------|--------------------------------------------------------|
| Alice Desktop | Alice iOS | Alice iOS \| Alice Android \| Bob iOS \| Bob Android | Alice Desktop can't see any quote body, fallbacks to plain text | https://github.com/oxen-io/session-desktop/issues/2655 |
| Alice iOS     | Alice iOS | Bob iOS \| Bob Android \| Bob Desktop                | Alice iOS shows "Original message not found" in quote body      | https://github.com/oxen-io/session-ios/issues/768      |
| Alice Android | Bob iOS   | Bob iOS                                              | Alice Android shows "Original message not found" in quote body  | https://github.com/oxen-io/session-android/issues/1088 |
| Alice Android | Alice Android | Bob Android \| Bob iOS \| Bob Desktop | Alice Android shows quote content correctly, but the original author is displayed as an unblinded Id, should display "You" instead | https://github.com/oxen-io/session-android/issues/1076 |

If we consider different combinations of original message types and reply message types, then there are even more weird bugs, I haven't had a chance to write them down yet.

**Comment by KeeJef** [comment]
Thanks, i think we will need to circle back on reply/quote behavior and have another look at this logic. Regarding testing @burtonemily might want to have a look at this too

**Comment by fracting** [comment]
Thanks for responding.

I think It's tricky to implement automated tests involving multiple devices at the same time. If the message parser and sender from {Android, iOS, Desktop} can be extracted and rewritten as a common library, then test automation will be much easier and the test cases needed might be reduced by a factor of `3*3*3=27`.

The risk of implementing a common message library is, it would give spam bots a lot of advantages.

If a common session message library is released someday, either a paid model needs to be implemented, or a grey list (traffic limit for new users) mechanism needs to be implemented for Session Community.

**Comment by burtonemily** [comment]
Thanks @fracting, I will take a look at these use cases and include them into our current regression (manual) suite. I am currently in the process of automating the regression test suite, which should be finished soon (fingers crossed). 
I've also taken a further look (and will continue my research) into property based testing, thanks for your suggestions.

**Comment by fracting** [comment]
Glad to see the progress and thanks for taking care of the hard work!

Just some thought, I guess it would be too much responsibility for high-level QA (UI test, end-to-end test) if the architect is not friendly enough for low-level test automation or if the code base does not have enough low-level test coverage. In the test pyramid, the lower level of the architect, the more intensive test coverage needs to be done, otherwise it would be a nightmare for high-level QA. Applying techniques like property based testing might require support from the entire dev team, working together to gradually apply them in daily development and shift the development practice.

https://martinfowler.com/articles/practical-test-pyramid.html

**Comment by jagerman** [comment]
> Glad to see the progress and thanks for taking care of the hard work!
> 
> Just some thought, I guess it would be too much responsibility for high-level QA (UI test, end-to-end test) if the architect is not friendly enough for low-level/medium-level test automation or if the code base does not have enough low/medium level test coverage. In the test pyramid, the lower level of the architect, the more intensive test coverage needs to be done, otherwise it would be a nightmare for high-level QA. Applying techniques like property based testing might require support from the entire dev team, working together to gradually apply them in daily development and shift the development practice.
> 
> https://martinfowler.com/articles/practical-test-pyramid.html

One of the long-term development directions for Session is to separate more of the low-level code (which currently has duplicate implementations in the three Session clients) into a common library.  That's started (https://github.com/oxen-io/libsession-util/) for upcoming config messages changes, but obviously has much more potential.  It takes a while to go through such refactors/transitions, though.

**Comment by fracting** [comment]
I asked ChatGPT to generate some test cases for the quote and reply feature.

Here is my prompt:

> In a group chat, there are three type of characters. First we have some posters, who send the first messages. Then we have some repliers, who quote and reply some posters' messages. Finally we have some viewers, who read the messages. Anyone can be a poster, a replier or a viewer, or a combination of any of them. Please write a comprehensive list of test cases to test the group message quote and reply behavior.

ChatGPT:

> Sure, here is a comprehensive list of test cases to test the group message quote and reply behavior:
> 
> Verify that posters can send a message to the group chat without quoting or replying to any message.
> 
> Test if repliers can quote a poster's message by clicking on the "quote" button or using a keyboard shortcut.
> 
> Verify that repliers can edit the quoted message before sending their reply.
> 
> Test if repliers can add their own text to the quoted message before sending their reply.
> 
> Verify that repliers can reply to multiple quotes in a single reply.
> 
> Test if repliers can reply to a quote with another quote.
> 
> Verify that viewers can see the quoted message in the context of the reply.
> 
> Test if viewers can access the original message by clicking on the quoted message.
> 
> Verify that posters can delete their original message and it is removed from the group chat, including any replies and quotes of the message.
> 
> Test if repliers can delete their reply, and the quoted message remains in the group chat.
> 
> Verify that viewers can report an inappropriate message, including a quoted message or reply.
> 
> Test if the reply and quote behavior works correctly in different languages and locales.
> 
> Verify that the reply and quote behavior works correctly with slow or unreliable network connections.
> 
> Test if the reply and quote behavior works correctly on different devices and screen resolutions.
> 
> These test cases should help ensure that the group message quote and reply behavior works correctly and provides a high-quality user experience.
> 
> 
> 
> 
Me:
> more

ChatGPT:
> Sure, here are some additional test cases related to the group message quote and reply behavior:
> 
> Verify that the reply and quote functionality is accessible to users with disabilities and follows accessibility guidelines.
> 
> Test if the reply and quote functionality works correctly in different group sizes, including small and large groups.
> 
> Verify that the reply and quote functionality works correctly with a mix of text, images, and files.
> 
> Test if the reply and quote functionality works correctly when messages contain emojis, special characters, and symbols.
> 
> Verify that the reply and quote functionality works correctly with messages that have been edited by the poster.
> 
> Test if the reply and quote functionality works correctly when messages are sent in different formats, such as plain text, markdown, or rich text.
> 
> Verify that the reply and quote functionality works correctly when messages are sent from different platforms, such as web, mobile, or desktop.
> 
> Test if the reply and quote functionality works correctly when messages are sent by members with different roles, such as moderators or administrators.
> 
> These additional test cases will help to cover a wide range of scenarios and edge cases, ensuring that the group message quote and reply behavior works correctly for all users.
> 
> 
> 
> 
Me:
> more

ChatGPT:
> Sure, here are some more test cases related to the group message quote and reply behavior:
> 
> Verify that the reply and quote functionality is available for messages that have been deleted by the poster.
> 
> Test if the reply and quote functionality works correctly with messages that have been archived by the group.
> 
> Verify that the reply and quote functionality works correctly with messages that have been restored from archive by the group.
> 
> Test if the reply and quote functionality works correctly with messages that have been edited by the replier.
> 
> Verify that the reply and quote functionality works correctly with messages that have been sent by members who have left the group.
> 
> Test if the reply and quote functionality works correctly with messages that have been sent by members who have been removed from the group.
> 
> Verify that the reply and quote functionality works correctly with messages that have been sent to multiple groups.
> 
> Test if the reply and quote functionality works correctly with messages that have been sent as direct messages.
> 
> These additional test cases will help to cover a wide range of scenarios and edge cases, ensuring that the group message quote and reply behavior works correctly for all users in different scenarios.

**Comment by fracting** [comment]
Some of the test cases generated by ChatGPT obviously do not apply to Session, for example:

> 5. Verify that repliers can reply to multiple quotes in a single reply.
(We don't support multiple quotes in a single reply)

and

> 25. Test if the reply and quote functionality work correctly with messages that have been archived by the group.
(We don't have archived message)

The majority of test cases do make sense though.

See also another example of test cases generated by ChatGPT:
https://github.com/oxen-io/session-android/issues/1104#issuecomment-1420538017

**Comment by fracting** [comment]
Update: https://github.com/oxen-io/session-ios/issues/768 has been fixed in iOS 2.2.8.
This one itself can still be reproduced when interacting with iOS 2.2.8.

**Comment by yougotwill** [comment]
@fracting I think this will be fixed by https://github.com/oxen-io/session-desktop/pull/2757 ?

**Comment by fracting** [comment]
> @fracting I think this will be fixed by #2757 ?

I'll retest in an hour and report back.

**Comment by fracting** [comment]
@yougotwill confirming working for me in 5369131529d73c10cca62447245df1496871809e

I'll retest after an official release is published and close this issue at that time.

**Comment by yougotwill** [comment]
@fracting awesome news. Thanks for that 🙏

**Comment by KeeJef** [comment]
Closing as resolved
