### ISSUE TITLE
Cannot connect to network behind Tor transproxy

### ISSUE THREAD

**Issue by kaizushi** [oxen-io/session-desktop#2657]
**Describe the bug**
I cannot use Session because I am already behind a transparent Tor proxy. Because of this I cannot connect to the network and use Session. Clicking the 'Path' button has one see a loading sign indefinitely. 

**To Reproduce**
Run Session desktop on a private network behind a transparent Tor proxy.

**Other information (please complete the following information):**

* Device: PC
* OS: Debian Bullseye
* Session Version or Git commit hash: 1.10.4 (flatpak)

**Workaround**

I am not sure if it is possible but maybe there is a way to run Session so that it connects directly and leaves things to my transproxy. Perhaps there is some kind of command line argument? Running Session with a direct connection to the Internet so that it can work is an unacceptable compromise. I always work behind a transparent Tor proxy on principle and this is not changing.

**Comment by Bilb** [comment]
We don't support proxy for now.
You can have a look at those other issues to see if any  of those comments help
https://github.com/oxen-io/session-desktop/issues/1557
https://github.com/oxen-io/session-desktop/issues/1139

**Comment by KeeJef** [comment]
Closing for now
