### ISSUE TITLE
Message delay in the main box

### ISSUE THREAD

**Issue by User-McUserface** [oxen-io/session-desktop#2685]
Latest Session desktop on Win 11.

First few words appear on the left, in the conversations column preview, but then it can take 3-5 seconds until that same message shows up in the conversation thread view.

**Comment by KeeJef** [comment]
Cannot reproduce, is it possible to show a screen recording of the issue?

**Comment by User-McUserface** [comment]
Tried to reproduce on the latest version.

I can still notice that the preview and main window are not fully synchronized in displaying the message content but the delay is nowhere near what it used to be when I opened this issue.

Will keep an eye on it.

**Comment by KeeJef** [comment]
Closing this one, looks these are well synced for me
