### ISSUE TITLE
Multimedia file playback does not work if extension is wrong - detect real media file format/type to allow playback anyway?

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#2686]
Hello,

on Session desktop 1.10.7 when i send GIF animated file with .mp4 extension, it allows download only, not playback.
When renaming to .gif, then it plays fine.
Is it reasonable for Session to detect real file type and allow playback even the file is named with wrong extension?
It would improve user experience.

**Comment by KeeJef** [comment]
Not sure if Session should handle this case

**Comment by KeeJef** [comment]
Closing as i don't believe it's the responsibility of Session to resolve incorrect file extensions
