### ISSUE TITLE
if the app works in the background, chat messages are marked as read on open (check comments!) 

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#2698]
**Describe the bug**
In (at least) Windows, if app is working in the background and the chat is opened, when you open the app, you find yourself in the very bottom, and every unread message is marked as read.

**To Reproduce**
Open the app. Open any chat and minimize the Session window. Then open it, when you get a few new messages (you get the notifications still OK tho)

Other information:

Device: PC
OS Windows 10
Session v. 1.10.7 (last at 09.03.2023)

**Comment by KeeJef** [comment]
Closing for now, can reopen if this is still occurring
