### ISSUE TITLE
Can't delete photos, which hasn't been sent because of an error

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#2714]
Can't delete photos, which hasn't been sent because of an error. They just stupidly leave hanging in the chat.

![2023-03-20_095806](https://user-images.githubusercontent.com/122599546/226279707-218fc856-9f98-46e9-9906-6ac6ed9e93c4.png)

**Comment by KeeJef** [comment]
Yeah this should be fixed, Good first issue to add the normal options to delete to failed to send messages

**Comment by KeeJef** [comment]
Just realized this is a duplicate of https://github.com/oxen-io/session-desktop/issues/2704
