### ISSUE TITLE
Hi-res image view on Session desktop

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#2717]
If the image is large, the text becomes unrecognizable, and the image can be viewed properly only by downloading it. The image eg. can be opened full-screen (as in Telegram), or zooming option can be added.

![image](https://user-images.githubusercontent.com/122599546/227139946-2a8c5ada-f3fe-4340-8bde-9806f76b9264.png)
![image](https://user-images.githubusercontent.com/122599546/227140067-acbc0257-0019-4c93-bdaa-fadf9a1922a9.png)

**Comment by KeeJef** [comment]
Closing in favor of https://github.com/oxen-io/session-desktop/issues/1871
