### ISSUE TITLE
[Feature request] Allow multiple own accounts (with different contacts and settings) at the same time

### ISSUE THREAD

**Issue by ElsAr4e** [oxen-io/session-desktop#2719]
If you use Jami (https://docs.jami.net/user/all-features-by-client.html) you can use multiple own accounts with different contacts and different settings for each own account.

It would be great if you were able to have these options using Session too.

For example one own user account doesn't allow calls the other account allows calls.

**Comment by KeeJef** [comment]
Closing in favor of https://github.com/oxen-io/session-desktop/issues/421
