### ISSUE TITLE
Many people unable to send images in DM, is Fileserver down?

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#2724]
Suddenly many people report issue sending image via PM(DM).

> Can't send files in DM or in groups.
> It's not even possible to send LINKS with (image) preview in DMs or in groups.

> Also getting issues with sending attachments

> I've also been having issues with sending attachments in 1 on 1 dms, started a few days ago not allowing me to send anything over 2mb file size.

> Image sending via PM fails, latest log lines:
> Message.saveErrors: null Error: upload to file server v2 of redacted.png failed\n    at uploadToFileServer ([REDACTED]/ts/session/utils/Attachments.js:74:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Promise.all (index 0)\n    at async Promise.all (index 0)\n    at async MessageModel.uploadData ([REDACTED]/ts/models/message.js:589:47)\n    at async MessageModel.retrySend ([REDACTED]/ts/models/message.js:648:74)\n    at async [REDACTED]/ts/components/conversation/message/message-content/MessageContextMenu.js:152:13","time":"2023-04-02T05:54:26.825Z","v":0}
> ❗❗

* Device: PC
* OS: Linux appimage
* Session Version or Git commit hash: 1.10.7

**Comment by KeeJef** [comment]
See here https://github.com/oxen-io/session-ios/issues/809
