### ISSUE TITLE
1.10.7 works fine, 1.10.8 fails to start

### ISSUE THREAD

**Issue by robertnixprog** [oxen-io/session-desktop#2737]
I get the below error when trying to start 1.10.8.  I'm on Debian buster.  1.10.7 works fine (it gets `config/get: Successfully read user config file`, `config/get: Successfully read ephemeral config file`.)

I tried running strace on `/opt/Session/session-desktop` (I don't think it followed-through with `/opt/Session/chrome-sandbox`) and it wasn't clear from the output why it could be failing.

I'm sticking with 1.10.7.

```
$ session-desktop
ESC[?2004l^MSet Windows Application User Model ID (AUMID) { appUserModelId: ESC[32m'com.loki-project.messenger-desktop'ESC[39m }
NODE_ENV production
NODE_APP_INSTANCE undefined
NODE_CONFIG_DIR /opt/Session/resources/app.asar/config
NODE_CONFIG {}
userData: /home/robert/.config/Session
config/get: Did not find user config file, cache is now empty object
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance
```

**Comment by Bilb** [comment]
Hey, does it just hang on making app single instance?
If yes, that might just mean that another Session is currently running (or have a zombie process?). Can you make sure there is no other session running on your system? I had a look at the changes again and there are really not much, so I am confused.

I'll give a debian buster build a go as you are the second user making such a report

**Comment by robertnixprog** [comment]
I'm certain that that's not the problem.  If I quickly switch back and forth between 1.10.7 and 1.10.8,, 1.10.7 always works and 1.10.8 always fails.

I double-checked and it looks like both `buster` and `bullseye` are using the same `.deb` file.  Which seems weird since, with the `libc6` change, they are quite different.

I should also note that 1.10.8 works perfectly on my two other Debian `bullseye` machines.  So, it's something specific to `buster`.  I didn't check whether the shared libraries in `/opt/Session` changes between versions, but, if so, that may be one possible explanation.

**Comment by Ruler2023** [comment]
Note that on my issue after installing 1.10.8 and failing to start (freeze at the start screen) then 1.10.7 would start but the path light would stay red.   Older versions would also not reach a working green path light.  The only resolve for me was to replace the .config Session folder with a good copy from another machine.   I think it would be a good thing is Session is more able to recover from issue's in the .config/Session folder but of course also prevention from anything wrong happening there in the first place. Also in my case i'm running Manjaro.

**Comment by robertnixprog** [comment]
@Ruler2023 - I'm glad you responded because I wanted to clarify that, with 1.10.8, the UI does not come up at all.  Session exits right away.

![image](https://user-images.githubusercontent.com/5586524/232329668-c5c697a6-da61-49eb-9661-d90edf152884.png)

**Comment by Ruler2023** [comment]
@robertnixprog that is the error i got when i tried running Session without the .config/Session folder ; just before replacing it from the laptop that had a good copy.  oddly enough the option "copy error and quit" got me nothing in the clipboard. And "Clear all data" also did not result in a good start afterwards but just the same error again.

**Comment by Bilb** [comment]
@robertnixprog can you reach out to me from another device to Session at `054774a456f15c7aca42fe8d245983549000311aaebcf58ce246250c41fe227676` ?

**Comment by Ruler2023** [comment]
Sure , nothing seems to happen when i add that SessionID though. Find me on session with ONS name "Rule"

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by Bilb** [comment]
The issue appears to be related to github actions having removed the support of ubuntu-18.04.
We used to build on ubuntu 18.04 but had to bump to ubuntu 20.04.
We did some testing and the exact same database works fine when the Session binary used is compiled from ubuntu-18.04, but crashes on start when Session was compiled on ubuntu-20.04.

**Comment by robertnixprog** [comment]
I assume that by "had to bump to ubuntu 20.04" implicitly implies that Debian buster is no longer supported via the apt (deb) repo, https://deb.oxen.io .

FWIW, the Appimage always works.  I guess this is the workaround.

**Comment by Ruler2023** [comment]
I always only use the appimage. I have Manjaro Linux.  How many distro's are tested before release?

**Comment by Bilb** [comment]
> I assume that by "had to bump to ubuntu 20.04" implicitly implies that Debian buster is no longer supported via the apt (deb) repo, https://deb.oxen.io .
> 
> FWIW, the Appimage always works. I guess this is the workaround.

The appImage I gave you was one specifically compiled on ubuntu 18-04. Not an official appImage. I assume the official appAimage, built on ubuntu 20-04 has the same issue as the deb

**Comment by robertnixprog** [comment]
You're right.  Just tried it and the canonical Linux 1.10.8 Appimage failed for me.

I'll stick with 1.10.7 until I manage to upgrade to Debian bullseye (probably next year).

**Comment by sifr01** [comment]
I am having issues with release 1.10.8 and I am on debian buster. Downgrading to release 1.10.7 seems to fix the issue.
<details>
  <summary> Here is my debug log: </summary>

```
user@session-desktop:~$ session-desktop 
Set Windows Application User Model ID (AUMID) { appUserModelId: 'com.loki-project.messenger-desktop' }
NODE_ENV production
NODE_APP_INSTANCE undefined
NODE_CONFIG_DIR /opt/Session/resources/app.asar/config
NODE_CONFIG {}
userData: /home/user/.config/Session
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
making app single instance
{"name":"log","hostname":"session-desktop","pid":1119,"level":30,"msg":"app ready","time":"2023-05-15T11:24:44.662Z","v":0}
{"name":"log","hostname":"session-desktop","pid":1119,"level":30,"msg":"starting version 1.10.8","time":"2023-05-15T11:24:44.664Z","v":0}
initializeSql sqlnode
Made sure db folder exists at: /home/user/.config/Session/sql
{"name":"log","hostname":"session-desktop","pid":1119,"level":30,"msg":"migrateDatabase: Migration without cipher change failed {\"code\":\"ERR_DLOPEN_FAILED\"}","time":"2023-05-15T11:24:44.708Z","v":0}
{"name":"log","hostname":"session-desktop","pid":1119,"level":30,"msg":"migrateDatabase: migrateSchemaVersion failed {\"code\":\"ERR_DLOPEN_FAILED\"}","time":"2023-05-15T11:24:44.709Z","v":0}
{"name":"log","hostname":"session-desktop","pid":1119,"level":50,"msg":"error {}","time":"2023-05-15T11:24:44.709Z","v":0}
{"name":"log","hostname":"session-desktop","pid":1119,"level":30,"msg":"Database startup error: Error: db is not set\n    at Object.initializeSql ([REDACTED]/ts/node/sql.js:93:19)\n    at showMainWindow ([REDACTED]/ts/mains/main_node.js:608:25)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async App.<anonymous> ([REDACTED]/ts/mains/main_node.js:582:9)","time":"2023-05-15T11:24:44.710Z","v":0}
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[1156:0515/122444.961899:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[1174:0515/122444.997300:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Unhandled Promise Rejection: Error: neither globalInstance nor initialized is initialized.
    at assertGlobalInstanceOrInstance (/opt/Session/resources/app.asar/ts/node/sql.js:53:15)
    at getById (/opt/Session/resources/app.asar/ts/node/sql.js:239:17)
    at Object.getItemById (/opt/Session/resources/app.asar/ts/node/sql.js:208:12)
    at getSpellCheckSetting (/opt/Session/resources/app.asar/ts/mains/main_node.js:76:32)
    at showMainWindow (/opt/Session/resources/app.asar/ts/mains/main_node.js:614:46)
    at async App.<anonymous> (/opt/Session/resources/app.asar/ts/mains/main_node.js:582:9)
{"name":"log","hostname":"session-desktop","pid":1119,"level":50,"msg":"Unhandled Promise Rejection: {}","time":"2023-05-15T11:24:47.917Z","v":0}
{"name":"log","hostname":"session-desktop","pid":1119,"level":50,"msg":"(node:1119) UnhandledPromiseRejectionWarning: Error: neither globalInstance nor initialized is initialized.\n    at assertGlobalInstanceOrInstance ([REDACTED]/ts/node/sql.js:53:15)\n    at getById ([REDACTED]/ts/node/sql.js:239:17)\n    at Object.getItemById ([REDACTED]/ts/node/sql.js:208:12)\n    at getSpellCheckSetting ([REDACTED]/ts/mains/main_node.js:76:32)\n    at showMainWindow ([REDACTED]/ts/mains/main_node.js:614:46)\n    at async App.<anonymous> ([REDACTED]/ts/mains/main_node.js:582:9)\n(Use `session-desktop --trace-warnings ...` to show where the warning was created)","time":"2023-05-15T11:24:47.929Z","v":0}
{"name":"log","hostname":"session-desktop","pid":1119,"level":50,"msg":"(node:1119) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see [REDACTED] (rejection id: 2)","time":"2023-05-15T11:24:47.929Z","v":0}
```

</details>

**Comment by robertnixprog** [comment]
FWIW, I just noticed that, with the release of signal-desktop 6.20, it too has the same problem.  The clock is ticking for me to upgrade to bullseye...

**Comment by popey** [comment]
> The issue appears to be related to github actions having removed the support of ubuntu-18.04. We used to build on ubuntu 18.04 but had to bump to ubuntu 20.04. We did some testing and the exact same database works fine when the Session binary used is compiled from ubuntu-18.04, but crashes on start when Session was compiled on ubuntu-20.04.

Aha! Thanks for this comment. I maintain a [snap of session-desktop](https://snapcraft.io/session-desktop) which has been stuck at 1.10.7 until now. Your comment flipped a switch in my head. 

I have bumped the build config so it now builds on 20.04, which has 'fixed' the issue. Once the latest build of 1.11.2 finishes, I'll push it to the stable channel after testing. The snap is of course an unofficial build, but might be helpful for people who are on older releases of desktop operating systems (so long as they're not snapd-objectors (and no, I don't care if they are, they don't need to tell me)) :D.

**Comment by robertnixprog** [comment]
FWIW, I tried getting the snap version of session-desktop, but snap itself wouldn't work on Debian buster.

In the end, I upgraded to Debian bullseye (Debian 11).  Now, session-desktop 1.11.2, snap, and signal-desktop all work flawlessly.

**Comment by Bilb** [comment]
Glad to see it was just a system upgrade to fix this issue. Closing this
