### ISSUE TITLE
Lock with PIN code, but no way to set up PIN code?

### ISSUE THREAD

**Issue by bohwaz** [oxen-io/session-desktop#2741]
Android.

In the FAQ I can read about using a PIN code to encrypt the database. In the settings I see a toggle for locking Session.

When I enabled locking, Session asks me for a fingerprint. But I want to set up a PIN code, not use the same fingerprint I'm using for unlocking the screen :)

Thanks!

**Comment by Bilb** [comment]
Hey, I think this is relevant to mobile only so can you please open your issue in https://github.com/oxen-io/session-android/ or https://github.com/oxen-io/session-ios please.

**Comment by bohwaz** [comment]
Ah! Thanks I didn't see I wasn't in the correct repo. Actually this issue seems to be what I'm talking about: https://github.com/oxen-io/session-android/issues/424
