### ISSUE TITLE
Multiple attachment files in a community post has all same name when saving

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#2743]
It appears that in a community when post has multiple image attachments, all have same name (when saving it), for example "session-attachment-2023-04-16-0123456.jpeg".
IMO the attachment name within one post would be handy to be unique so one does not need to rename each one:

**Other information (please complete the following information):**

* Device: PC
* OS: Linux AppImage
* Session Version or Git commit hash: 1.10.8

**Comment by RubenGarcia** [comment]
Recommendation: call the attachments "session-attachment-2023-04-16-0123456-1.jpeg" .. "session-attachment-2023-04-16-0123456-<n>.jpeg"

**Comment by RubenGarcia** [comment]
types/Attachment.ts
getSuggestedFilename already has an index parameter for this, which is passed along from the calling function save.
but this parameter is not used in the calling function.
util/attachmentsUtil.ts
saveAttachmentToDisk.

saveAttachmentToDisk should have a new parameter index, which should be "" at
components/conversation/message/message-content/MessageAttachment.tsx
components/lightbox/LightboxGallery.tsx changes to:
```
    void saveAttachmentToDisk({ ...mediaItem, conversationId: selectedConversation,  
        index: props.selectedIndex });
```
components/conversation/message/message-content/MessageContextMenu.tsx
changes to:
```
        index: targetAttachmentIndex,
```

**Comment by RubenGarcia** [comment]
I'll try to get a patch for this.

**Comment by RubenGarcia** [comment]
Work in progress
https://github.com/RubenGarcia/session-desktop/pull/1

**Comment by RubenGarcia** [comment]
If somebody else wants to tackle this, please do. This is my first patch here, so I will take a while to get used to the project.

**Comment by RubenGarcia** [comment]
@slrslr with this the first attachment keeps the name, but following attachments will have 001,002, ... added to them so the names are now unique.

**Comment by RubenGarcia** [comment]
I also have a branch which adds support to download all attachments in a message:
https://github.com/RubenGarcia/session-desktop/tree/DownloadAll
Would you be interested in that functionality?

**Comment by mrjackson6969** [comment]
Any new update regarding this change?

**Comment by RubenGarcia** [comment]
The patch needs to be approved by a developer, and I have not received any input yet.
Feel free to use the patch when you compile session.

**Comment by Bilb** [comment]
Hey, thanks for the PR!
I made some comments to that PR, let me know how it goes.

**Comment by RubenGarcia** [comment]
Also, have a look at https://github.com/oxen-io/session-desktop/pull/2928 when you have time.
