### ISSUE TITLE
Can't delete those messages in channels, which have been not sent because of an error.

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#2745]
**Describe the bug**
Can't delete those messages in channels, which have been not sent because of an error. They just leave hanging.

![image](https://user-images.githubusercontent.com/122599546/233071777-6c84c0c3-1555-4aca-8928-3038e456423c.png)

* Device: PC
* OS: Win 10
* Session v. 1.10.8

**Comment by Bilb** [comment]
Hey, yeah we keep messages locally when we cannot delete them remotely.
In that case, that message has no serverId I suppose, and so the remote delete fails.
I guess we'd need a "Delete For Me" action when the message is in a failed state.
Shouldn't be too hard

**Comment by Bilb** [comment]
this should be fixed with https://github.com/oxen-io/session-desktop/pull/3061
