### ISSUE TITLE
window10，It cannot find path

### ISSUE THREAD

**Issue by CatSir** [oxen-io/session-desktop#2748]
**Describe the bug**
![355582672734534](https://user-images.githubusercontent.com/4581108/233842639-065765fa-043f-47ab-9346-5a2701a4e170.png)

**Logs:** 
[session_debug_1682251322311.txt](https://github.com/oxen-io/session-desktop/files/11303840/session_debug_1682251322311.txt)

**Comment by Momen66** [comment]
I have the same problem could someone help  please 
network timeout at: https://seed1.getsession.org:4443/json_rpc
network timeout at: https://seed2.getsession.org:4443/json_rpc
network timeout at: https://seed3.getsession.org:4443/json_rpc
