### ISSUE TITLE
notifications small feature request

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#2749]
![image](https://user-images.githubusercontent.com/122599546/234362593-8cf15a81-108d-4ea2-a10d-305093aafcfd.png)
notifications on the image shall also be turned of for the groups, for which i've turned the notifications off

**Comment by Bilb** [comment]
Hey, can you send me more details about this? the disabled conversation should not add their unreadCount to the global one already
    if (
      globalUnreadCount < 100 &&
      isNumber(conversation.unreadCount) &&
      isFinite(conversation.unreadCount) &&
      conversation.unreadCount > 0 &&
      conversation.currentNotificationSetting !== 'disabled'
    ) {
      globalUnreadCount += conversation.unreadCount;
    }
