### ISSUE TITLE
[Suggestion] about SOGS link

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#2754]
Suggestion about SOGS; sorry, if in wrong place.
So, the SOGS use links (eg. http://session.aaa.uk/sogsname?public_key=aaa...) to join. But the very first thing to instinctively do when a user sees the link, is to click it - SPECIALLY, if the link is posted in the net (eg. FB publication, that says: "yo join my session group: http://session.aaa.uk/sogsname?public_key=aaa...).

That's why it would be very great, if the link would at very least show link to Session site instead of 404 error, and in best case - even a short instruction, how to use it properly (instead of opening).

...if it's possible

![image](https://github.com/oxen-io/session-desktop/assets/122599546/ea4d0b85-bfc8-4b8c-a3e7-735202632337)

**Comment by Bilb** [comment]
That change would need to happen server side, so in https://github.com/oxen-io/session-pysogs/ 
Can you open an issue there instead, if none already exists
