### ISSUE TITLE
Session ID can't find path.

### ISSUE THREAD

**Issue by Prototypelove** [oxen-io/session-desktop#2755]
**_Device: PC
OS: Windows 10
Session ID v1.8.6_**

Greetings, knuclehead here. Im new to github so im sorry if im not concise enough here.
TL;DR Session app on PC wont find a path and my messagens wont reach my peers. But on mobile it works (i can show you if you want).
 
When i click to see the path in Session ID it just stuck loading.
![image](https://github.com/oxen-io/session-desktop/assets/133606380/c78f2432-b06e-447a-9052-2df8ba1dfa70)
Here goes the log/files/appuration

![image](https://github.com/oxen-io/session-desktop/assets/133606380/7e5f44f6-7531-403f-9a6d-107af0cdbc3e)

Sorry for the POORLY edited post but this is my first hour on Github...

**Comment by Bilb** [comment]
Hey, it looks like you are on 1.8.6.
This issue should be fixed on the latest build 1.10.8: https://github.com/oxen-io/session-desktop/releases/tag/v1.10.8

**Comment by KeeJef** [comment]
Interested in when you last downloaded / updated Session? did hear some reports last week that the website might have been giving people an old download link in some cases

**Comment by yougotwill** [comment]
> Interested in when you last downloaded / updated Session? did hear some reports last week that the website might have been giving people an old download link in some cases @yougotwill

V1.8.6 is the version where the auto updates were broken. @Prototypelove You will need to update manually by downloading the latest release and installing it.

**Comment by yougotwill** [comment]
@KeeJef Have updated the latest fallback version on getsession.org to v.1.10.8. Should resolve the issue. Sometimes if we hit the github api too often we use this value. It was originally set to v1.8.6

**Comment by Prototypelove** [comment]
> Interested in when you last downloaded / updated Session? did hear some reports last week that the website might have been giving people an old download link in some cases @yougotwill

I downloaded Session ID from the site on 05/12/2023. I did not updated anything.

**Comment by Prototypelove** [comment]
![image](https://github.com/oxen-io/session-desktop/assets/133606380/9da11d16-5a3e-4a03-aece-b2cbab9130d1)

**Comment by Prototypelove** [comment]
I will manually update the Session ID
and try to give a feedback.

**Comment by Prototypelove** [comment]
![image](https://github.com/oxen-io/session-desktop/assets/133606380/9830fb68-bd61-4647-bf72-047f082cfc8f)
I downloaded direclty from the site. It gave me the 1.10.8 version now.
Its fixed!!!!

**Comment by yougotwill** [comment]
@Prototypelove Glad we solved the issue! Thanks for letting us know. Closing now
