### ISSUE TITLE
more images count barely visible (minor!)

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#2762]
![image](https://github.com/oxen-io/session-desktop/assets/122599546/d25ca67c-ca61-47ec-9af0-f34a997fd3de)

more images count barely visible, if the image is white. please add outline to the numbers

**Comment by DevAdeelAhmad** [comment]
hi @qdhj, I have recreated the issue and it's sill there. I have a solution for it. But I cannot install the dependencies. I have gone through the Contributing File but still I am unable to install the dependencies. Can you help me with that? I want to contribute to this project. You can message me on Discord. My username is (adeelahmad1). Your help will be appreciated.

**Comment by KeeJef** [comment]
Fixed in #2952
