### ISSUE TITLE
session not working at whonix

### ISSUE THREAD

**Issue by officerhi** [oxen-io/session-desktop#2764]
normal id identifies but I can't send any message

**Comment by officerhi** [comment]
Is there anyone who can help?

**Comment by Bilb** [comment]
did you get a path at all? green or red dot on the bottom left?
I suppose whonix uses a proxy to root the network out, but Session does not support running through a proxy currently

**Comment by Bilb** [comment]
Duplicate of #2712 #1139

**Comment by officerhi** [comment]
As far as I understand, I'll have to wait for proxy support. so how long does this take? do you have an idea?
