### ISSUE TITLE
[BUG] deleted dialogs appear again undeleted

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#2780]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. delete dialog
2. wait about a week or so
3. they appear again

![image](https://github.com/oxen-io/session-desktop/assets/122599546/6c89a241-8c64-430c-b31c-4f243e2a538e)

As you can see by the dates, they appear at the same moment again

### Desktop Version

v1.10.8

### Anything else?

1. Windows 10, PC, 8ee731b2a5311ff02963c6a3720d2dec4a71afea

[session_debug_1686220951754.txt](https://github.com/oxen-io/session-desktop/files/11687007/session_debug_1686220951754.txt)

**Comment by Bilb** [comment]
the userconfig release we are working on should help for the syncing logic. Still a work in progress currently though. Please give  a try to the next release (not sure of the release date yet) to see if that fixes your issue

**Comment by KeeJef** [comment]
This should be fixed post user config release, closing for now
