### ISSUE TITLE
[BUG] Can read deleted messages - big one!

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#2790]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Session desktop opened, first app loads messages, then - post-factum - deletes them. Very dummy way to operate, innit..? 
I've just managed to successfully read two compromising messages from my friend in these 1.5-2 seconds, before they appeared as deleted.

### Desktop Version

v1.10.8

### Anything else?

1. PC
2. Windows 10
3. 8ee731b2a5311ff02963c6a3720d2dec4a71afea

**Comment by krlabs** [comment]
We confirm, that when you log in to SESSION Desktop (Windows/Linux), previously deleted messages on your mobile device (Android) are pulled up in the private chat. Then they suddenly disappear (or not suddenly if the operating system is heavily loaded). This bug also poses a security risk, so we expect an update in the near future.

**Comment by KeeJef** [comment]
Duplicate of https://github.com/oxen-io/session-desktop/issues/2048 , basically disappearing messages don't update the TTL of the message on the swarm currently, which causes messages less than 14 days old to be restored when device is restored from seed. We will have a release which fixes this soon
