### ISSUE TITLE
[BUG] message selection mode for deleting should not cause timeline jumps to quoted posts

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#2797]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On Session desktop 1.10.8 (AppImage), when selecting community posts to be deleted as admin, i often accidentally click into the part of the post where A) is emoticon which cause voting and B) user quote other user and this causes jump of the timeline to different position on the timeline. This is annoying and makes the moderation more time consuming for me. Maybe if session support [Back button that would allow jumping back](https://github.com/oxen-io/session-desktop/issues/2721), it would not be problem.

### Expected Behavior

IMO it would be better to prevent these timeline jumps and emoticon voting in the mode of selecting messages to be deleted.

### Desktop Version

1.10.8

### Anything else?

Linux Deb.

**Comment by KeeJef** [comment]
Unable to reproduce this in 1.11.4, i think this might be fixed?

**Comment by KeeJef** [comment]
Okay i think i have misunderstood this issue, it sounds like this issue is related to ban and delete all causing the screen to jump away from the post that was selected to ban and delete. 

I misunderstood and though this issue was related to clicking quoted messages when you were in message selection mode.

**Comment by slrslr** [comment]
Sorry I misunderstood. You are right, i can no longer reproduce this issue, so I am closing it. I have opened new issue #2976 where community timeline jumps due to ban/delete.
