### ISSUE TITLE
[BUG] Latest version of session desktop (for Windows) not available on getsession.org

### ISSUE THREAD

**Issue by mattman71** [oxen-io/session-desktop#2831]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have session desktop version 1.10.8 installed, verified hash and all. I re-installed it to confirm this behavior.

Version 1.10.8 is the latest available when I go to [getsession.org/download](https://getsession.org/windows)

However, after running for a minute or so, I'm prompted for an upgrade.
![image](https://github.com/oxen-io/session-desktop/assets/13487987/c565cc5e-7a4e-4237-bab0-de06f8a7f7ff)

I've visited the [updates channel on sogs](https://open.getsession.org/r/session-updates/) to investigate if this is a legit update, but there are no dates or any indication that this is expected.

With all of the key and signature protection going on with this sensitive app, I'm just not sure what to think here. Without seeing details or dates or anything to cross-reference what's going on, and given the fact that it wants to upgrade something I just installed fresh from the download on the home page -- I'm very suspicious.

### Expected Behavior

I would expect a fresh install from getsession.org/download to not immediately prompt for an upgrade. Or some kind of information given to confirm it's a legit update and/or from where it's getting it, with validation information (hash, etc.).

### Steps To Reproduce

- Windows 10 22H2
- Installed session desktop (for Windows), version 1.10.8
- Run app
- Wait a while (1-5 minutes)
- Receive "There is a new version of Session available" update prompt, with Download or Later selections
- Go to https://getsession.org/download, click Windows link to confirm already have the latest
- Visit sogs session updates channel to looks for clues if this is legit or something suspicious going on
- Write issue because you can't tell :)

### Desktop Version

1.10.8

**Comment by KeeJef** [comment]
We did indeed release a new version of Session desktop here https://github.com/oxen-io/session-desktop/releases/tag/v1.11.0 version 1.11.0 , for me https://getsession.org/download points towards v1.11.0. Signatures can be found on the Github releases page, but yeah perhaps we could make the auto upgrade screen more informational.

**Comment by yougotwill** [comment]
The download page on the website was probably being rate limited by github. The fallback version for the link was 1.10.8. I've updated it to 1.11.0 so this issue should be fixed. @KeeJef

**Comment by mattman71** [comment]
Confirmed, it's pointing to 1.11.0 now. I swear I was sober when I wrote that! The rate limit sounds plausible. Thanks for checking.

Is that sogs site the best place to look for news about updates? Any chance it could get some post timestamps? Or am I looking at it the wrong way somehow?

Anyway, I'll close the bug. Thanks for the sweet app and the endless work I'm sure goes into it!
