### ISSUE TITLE
[Pidgin Integration] <libPurple>

### ISSUE THREAD

**Issue by beadon** [oxen-io/session-desktop#2841]
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

Have you considered writing a (prpl) plugin for Pidgin ?  This would extend the reach into traditional messaging and allow context switching between secure and insecure messaging without the overhead required when writing messages.

This also could help merge the UI elements between Pidgin and Session - improving the Pidgin interface, and lowering the overhead of managing so many UIs for Session alone.

### Anything else?

Reference GitHub : https://github.com/pidgin/pidgin

Plugins already supported : https://pidgin.im/plugins/?publisher=all&query=&type=

**Comment by beantaco** [comment]
I have never used Pidgin and can't see the detail of this feature request, but I'm concerned about what it means to integrate it with Session.

I don't like the idea of communications of different security properties (in this case, Session vs Pidgin) being mixed into a single app. Signal allowed (and still does?) both insecure SMS messages and encrypted Signal messages to be sent/received within the same app, and I thought that was a disaster.

Why is this a problem? Users might mistakenly forward messages that were received (or sent by themselves) using the more secure protocol to another person using the less secure protocol, or might mistakenly send a message using the less secure protocol.

It reminds me of the security issues with encrypted email, where the sending user must configure encryption properly and not forget to enable it. I myself have accidentally sent emails that were supposed to be encrypted as unencrypted. Furthermore, even when I send encrypted emails to people, they often reply to me unencrypted, therefore exposing the encrypted contents and defeating the purpose of the encryption. The same issues generally exist in all messaging systems that don't enforce/mandate encryption or other security properties.

**Comment by KeeJef** [comment]
This would be something that would be easier for a community member to do once LibSession is much more developed, but right now integrating Session into other clients isn't our focus. Closing for now, but happy for discussion to continue

**Comment by beadon** [comment]
Ok, will take you up on further discussion.

The proliferation of "ways to communicate" to different people, on different platforms, with different styles is really out of control.  The methods of SMS, iMessage, WhatsApp, Snapchat, Instagram, Discord, Yahoo Messenger, MSN Messenger, Twitter, Facebook messengers, and wayyyy more are really just accessing (the same) people through a different medium.

When accessing people the medium (system of messaging) is chosen today because it offers different levels of features.  Some messages are private, some public, some expiring, and each system expects some level of different interaction - like a "culture" of behavior.  With the number of different platforms and the number of different systems it's pretty ridiculous if you think about it - how many different clients need to be created to do what is effectively the same thing :  send / receive a message to a user, track relies and respond.

Pidgin offers the ability to be that one client that prevents the need from running all of those clients in parallel.

I see the need for security with Session.  I believe there's a way to integrate Session as a method to send/receive replies and then, if necessary, purge information about conversations.  A properly implemented Pidgin plugin for Session would wrap the message and deliver it to a Session library to manage according to any rules configured for the message(s).

My goal is:
1. increase the adoption of session by integrating message passing APIs (integrating a crypto wallet if necessary)
2. Lower the cost of managing session from a developer / corporation standpoint.  This allows the team to focus on the things that truly differentiate Session instead of dealing with a whole lot of boilerplate code that has been done hundreds of times before.
3. Increase the usage of Pidgin for secure message systems.

For-Pay solutions like Trillian exist for the same reason - managing a bunch of chat clients is just a waste of effort.

Thoughts ?

**Comment by beantaco** [comment]
I acknowledge there are issues with too many messaging systems and clients. There's too broad a "market" of messaging systems and clients for people to choose from. All except the most dominant messaging systems miss out on attracting new people via network effects. There's also management overhead with having multiple clients, accounts and devices.

Personally I use about half a dozen clients that each send/receive messages using one of a few messaging systems (Session and email among others), over multiple accounts and multiple devices. I don't see a problem with using and managing multiple clients simultaneously. I guess it's only a problem when the user is overwhelmed by having too many clients, accounts or devices.

Having multiple clients makes me (the user) aware of different security contexts, and enforces compartmentalization as opposed to having all my messages in one bucket. It's a feature, not a bug, that I can't send or receive unencrypted or traceable messages using a Session client. Though beyond my control, I also wouldn't want my contacts to have Session messages in any client not dedicated to Session.

About goal 1 to increase adoption of Session, I don't have any good ideas that could actually achieve significant adoption of Session, but I suspect Session users need to let people know their Session ID. These days I see people mostly advertise their email address, phone number, Instagram etc.

I believe Session devs and the wider community need to keep maintaining Session and the clients. Can you elaborate what is your idea is for achieving goal 2?

For my above/previous comments, honestly I don't believe goal 3 is good for Session.
