### ISSUE TITLE
[BUG] MAC For Arm Desktop Session Network connection error！

### ISSUE THREAD

**Issue by badboycxcc** [oxen-io/session-desktop#2855]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

MAC For Arm Desktop Session Network connection error！
Unable to send messages！

### Desktop Version

v1.11.0

**Comment by badboycxcc** [comment]
<img width="85" alt="截屏2023-08-15 上午9 34 56" src="https://github.com/oxen-io/session-desktop/assets/72059221/d9fe611e-bda1-4c15-a43f-a01bfa68419c">

**Comment by BirdInFire** [comment]
you will wait long, they don't care about Mac, and even less for Mac ARM

**Comment by KeeJef** [comment]
ARM builds aren't supported currently, closing in favor of #1635 #2781
