### ISSUE TITLE
More pings than necessary

### ISSUE THREAD

**Issue by BeaudanBrown** [oxen-io/session-desktop#288]
From watching the visualisation at consensus and then reading this piece of code I wrote a while ago
```
    if (!envelope.isP2p) {
      const timestamp = envelope.timestamp.toNumber();
      const now = Date.now();
      const ageInSeconds = (now - timestamp) / 1000;
      if (ageInSeconds <= 120) {
        lokiP2pAPI.pingContact(envelope.source);
      }
    }
```
I think we are pinging contacts who we already believe are online
This should probably be changed to be a bit more nuanced

**Comment by majestrate** [comment]
a common gotcha is timestamps from the future, make sure to check for that too.
