### ISSUE TITLE
Black screen only after green logo

### ISSUE THREAD

**Issue by GianMarco-Tavazzani** [oxen-io/session-desktop#2892]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

MacBookPro7,1  OS X 10.13.6 After download I had a Session number (05a7cd3b6691f62ed514684c945794422c3df0c1190fb92be8806916bbd9f3bb1f), gave my name (GianMarco)  and then… nothing! I restarted it, I made a deep system maintenanche, I ever deleted it radically (with AppCleaner) and reinstalled it: when I open it, on the black screen compares the green "S" which isappears after seconds and only the black screen stays, without any word, link, as well as the menubar, as it could not connect
Thank you

### Expected Behavior

something showing up to can manage the app

### Steps To Reproduce

MacBookPro7,1  OS X 10.13.6

### Desktop Version

v1.11.0

### Anything else?

MacBookPro7,1  OS X 10.13.6

**Comment by Bilb** [comment]
Hey, yeah we only support macos 10.15 as shown on the release page currently. This is because we upgraded electron.
