### ISSUE TITLE
[Feature] Ability to PIN a messsage to a chat or room

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#2895]
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

[This question](https://github.com/oxen-io/session-desktop/issues/2010) is closed for no reason. The ability for client to read pinned message shouldn't be too complicated to make, but it _really_ useful and needed.

Ability to pin multiple messages is optional, but also warmly appreciated.

**Comment by LuLuLoLu** [comment]
Duplicate of #2010

**Comment by KeeJef** [comment]
That issue isn't closed, still open, hence this being closed as a duplicate :)
