### ISSUE TITLE
[BUG] Session 1.11.1 on Windows 7 - The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library KERNEL32.dll 

### ISSUE THREAD

**Issue by whatebert** [oxen-io/session-desktop#2909]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello
I'm using Windows 7 and as of the latest update 1.11.1, it always gives me the following error on boot
"The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library KERNEL32.dll"

I googled this error and it seems to be a problem with multiple apps that only happens on Windows 7.

### Expected Behavior

successful boot

### Steps To Reproduce

1. On Windows 7, boot Session 1.11.1

### Desktop Version

1.11.1

### Anything else?

Windows 7

**Comment by KeeJef** [comment]
Windows 7 and 8.1 support has been dropped, see https://github.com/oxen-io/session-desktop/issues/2898

**Comment by whatebert** [comment]
At least please stop updating messages from 1.11.0 on windows 7 please....
