### ISSUE TITLE
[Feature] "preferences" window

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#2985]
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

Section of settings named "preferences", where you can modify next preferences being on by default for the conversations:
1. Are messages automatically deleted?
1.5. How fast?
2. Is the ability to receive voice messages on by default?
3. Are reactions you're leaving anonymous by default? 
4. etc

**Comment by KeeJef** [comment]
Most of these settings would belong in the conversations menu i would think, closing this for now, if you want to pull these items out as individual feature requests feel free
