### ISSUE TITLE
Question: Isn't session shutting down late 2023? 

### ISSUE THREAD

**Issue by atdiausx2** [oxen-io/session-desktop#2987]
There were like a year ago some  announcements that Session is intending to shut down 31.12.2023. 
Now I am not even able to find the link to it, while the product seems active. Was this waivered if anything actually took place somewhen? 

Thanks and apologies for awkward question that is arguably out of "Issues" scope.

**Comment by KeeJef** [comment]
No, you might have gotten Session confused with Wickr, which is shutting down at the end of the year https://www.theverge.com/2022/11/19/23468065/wickr-free-encrypted-messaging-app-shutting-down-amazon-web-services
