### ISSUE TITLE
[BUG]  Appimage will no longer Start on Ubuntu (18.04.6 MATE) after overwriting older config?

### ISSUE THREAD

**Issue by leirbag28** [oxen-io/session-desktop#2997]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pops up an error that prevents Session from Opening further so it doesnt work

I am having an Error that pops up with the Appimage on Ubuntu
OS: Ubuntu 18.04.6 LTS
DE: MATE
Arch: 64 bit
Session version (and previous version also)  1.11.5

I don't remember what I did to cause this but I think upon starting it first asked me a question perhaps to replace something and I probably said YES...but I could be way off that this is how it happened, but I know it happened for sure when I replaced the old one (I suspect it creates a separate config on my system other than withing itself as an Appimage? and it tried to overwrite that old one with this newer version)

 time this pops up whether I start the Appimnage by double clicking or dropping it into the Terminal (which I did on purpose to show you what happens behind the scenes if it helps which I posted the log? in the "Anything Else" box below):

![Session Error-2023-12-11_10-16](https://github.com/oxen-io/session-desktop/assets/57868255/8c3fe269-3a8e-4889-ae00-3c6f4db4aa39)

### Expected Behavior

Should work as normal and take me to the sign in/Sign up screen?

### Steps To Reproduce

I dont exactly remember but When starting the Newer version (as I already had an older Appimage version) I think it asked me to replace a config perhaps because the newer Session changed the way it saved or where it stroed things? I really dont remember) and then when the new one starts I get the errors and it closes.

### Desktop Version

v1.11.5

### Anything else?

when I drop the AppImage into the MATE Terminal to start it that way: (look way at the bottom for the other error before reading this as to possibly not waste time)

chromium@bionic-pc:~$ '/home/chromium/Downloads/12-11-23/session-desktop-linux-x86_64-1.11.5.AppImage' 
Set Windows Application User Model ID (AUMID) { appUserModelId: 'com.loki-project.messenger-desktop' }
NODE_ENV production
NODE_APP_INSTANCE undefined
NODE_CONFIG_DIR /tmp/.mount_sessio8WvC7K/resources/app.asar/config
NODE_CONFIG {}
userData: /home/chromium/.config/Session
config/get: Successfully read user config file
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance
[10178:1211/100814.718896:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.portal.Settings' on object at path /org/freedesktop/portal/desktop
INTEL-MESA: warning: Haswell Vulkan support is incomplete
{"name":"log","hostname":"bionic-pc","pid":10178,"level":30,"msg":"app ready","time":"2023-12-11T15:08:15.130Z","v":0}
{"name":"log","hostname":"bionic-pc","pid":10178,"level":30,"msg":"starting version 1.11.5","time":"2023-12-11T15:08:15.131Z","v":0}
{"name":"log","hostname":"bionic-pc","pid":10178,"level":30,"msg":"locale is en-US","time":"2023-12-11T15:08:15.137Z","v":0}
initializeSql sqlnode
Made sure db folder exists at: /home/chromium/.config/Session/sql
{"name":"log","hostname":"bionic-pc","pid":10178,"level":30,"msg":"migrateDatabase: Migration without cipher change failed /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by [REDACTED].unpacked/node_modules/@signalapp/better-sqlite3/build/Release/better_sqlite3.node)","time":"2023-12-11T15:08:15.152Z","v":0}
{"name":"log","hostname":"bionic-pc","pid":10178,"level":30,"msg":"migrateDatabase: migrateSchemaVersion failed {\"code\":\"ERR_DLOPEN_FAILED\"}","time":"2023-12-11T15:08:15.156Z","v":0}
{"name":"log","hostname":"bionic-pc","pid":10178,"level":50,"msg":"error {}","time":"2023-12-11T15:08:15.156Z","v":0}
{"name":"log","hostname":"bionic-pc","pid":10178,"level":30,"msg":"Database startup error: Error: db is not set\n    at Object.initializeSql ([REDACTED]/ts/node/sql.js:84:19)\n    at showMainWindow ([REDACTED]/ts/mains/main_node.js:612:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async App.<anonymous> ([REDACTED]/ts/mains/main_node.js:586:9)","time":"2023-12-11T15:08:15.157Z","v":0}
Gtk-Message: 10:08:15.527: GtkDialog mapped without a transient parent. This is discouraged.
Unhandled Promise Rejection: Error: neither globalInstance nor initialized is initialized.
    at assertGlobalInstanceOrInstance (/tmp/.mount_sessio8WvC7K/resources/app.asar/ts/node/sqlInstance.js:18:15)
    at getById (/tmp/.mount_sessio8WvC7K/resources/app.asar/ts/node/sql.js:220:66)
    at Object.getItemById (/tmp/.mount_sessio8WvC7K/resources/app.asar/ts/node/sql.js:190:12)
    at getSpellCheckSetting (/tmp/.mount_sessio8WvC7K/resources/app.asar/ts/mains/main_node.js:76:32)
    at showMainWindow (/tmp/.mount_sessio8WvC7K/resources/app.asar/ts/mains/main_node.js:618:46)
    at async App.<anonymous> (/tmp/.mount_sessio8WvC7K/resources/app.asar/ts/mains/main_node.js:586:9)
{"name":"log","hostname":"bionic-pc","pid":10178,"level":50,"msg":"Unhandled Promise Rejection: {}","time":"2023-12-11T15:08:23.796Z","v":0}
Gtk-Message: 10:08:23.823: GtkDialog mapped without a transient parent. This is discouraged.
chromium@bionic-pc:~$ C

**Comment by Bilb** [comment]
Hey, 
As written on our release page, Session requires a linux distribution with a glibc of at least 2.28, so at least Ubuntu 20.04. 
https://github.com/oxen-io/session-desktop/releases/tag/v1.11.5

That's probably your issue. Could you try on a more recent ubuntu version and let me know if you still have an issue?
Thanks

**Comment by Bilb** [comment]
just linking the two issues together https://github.com/oxen-io/session-desktop/issues/2777

**Comment by Bilb** [comment]
Closing this in favor of https://github.com/oxen-io/session-desktop/issues/2997
