### ISSUE TITLE
Cursor issue in Wayland

### ISSUE THREAD

**Issue by sr66139p** [oxen-io/session-desktop#3000]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The cursor in Wayland mode does not change to the correct cursor for its position leading to confusion. It will stay as the edge cursor even in the middle of the window where it cannot resize the corresponding side. 
[Screencast from 2023-12-31 20-14-08.webm](https://github.com/oxen-io/session-desktop/assets/144626133/af063054-2f04-4388-8524-8b7fe9ab504e)

### Expected Behavior

I expect the cursor to change to reflect its current capabilities. In this case switching to the default cursor when not at the edge of the window

### Steps To Reproduce

In Gnome 43.9 (Wayland session) run "./session-desktop-linux-x86_64-1.11.5.AppImage --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto" from the terminal

### Desktop Version

1.11.5 Appimage

### Anything else?

I am using Debian GNU/Linux 12 (bookworm) x86_64

**Comment by mpretty-cyro** [comment]
Jira ticket SES-1379
