### ISSUE TITLE
No more running in Debian 10 - reason: certificate has expired

### ISSUE THREAD

**Issue by MundoDasCPUs** [oxen-io/session-desktop#3003]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Today the Session Desktop don't connect to server and sync. I was using normal in this morning when my messages don't go in determined moment. I'm tried to backup my account but the software don't get the way to servers. In terminal sow the requisition and can see a certificate expired.   

### Steps To Reproduce

Debian 10 

### Desktop Version

1.10.7

### Anything else?

{"name":"log","hostname":"xeon","pid":22666,"level":40,"msg":"getRandomSnode: failed to fetch snodes from seed. Current pool: 0","time":"2024-01-04T04:33:20.217Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":40,"msg":"buildNewOnionPathsWorker attemp #2 failed. 2 retries left... Error: Cannot rebuild path as we do not have enough snodes: 0","time":"2024-01-04T04:33:20.218Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":40,"msg":"requestSnodesForPubkeyRetryable attempt #2 failed. 2 retries left...","time":"2024-01-04T04:33:20.218Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":40,"msg":"getSnodePoolFromDBOrFetchFromSeed: not enough snodes in db (undefined), Fetching from seed node instead... ","time":"2024-01-04T04:33:20.766Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"fetchSnodePoolFromSeedNode with seedNodes.length 3","time":"2024-01-04T04:33:20.766Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"getSnodeListFromSeednode starting...","time":"2024-01-04T04:33:20.766Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"fetchSnodePoolFromSeedNodeRetryable starting...","time":"2024-01-04T04:33:20.767Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"getSnodesFromSeedUrl starting with [REDACTED]","time":"2024-01-04T04:33:20.767Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"insecureNodeFetch => plaintext for getSnodesFromSeedUrl  [REDACTED]","time":"2024-01-04T04:33:20.767Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":40,"msg":"fetchSnodePoolFromSeedNodeRetryable attempt #1 failed. 3 retries left... Error: request to [REDACTED] failed, reason: certificate has expired","time":"2024-01-04T04:33:21.041Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"SessionSnodeAPI::buildNewOnionPaths - building new onion paths...","time":"2024-01-04T04:33:21.765Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":40,"msg":"getSnodePoolFromDBOrFetchFromSeed: not enough snodes in db (undefined), Fetching from seed node instead... ","time":"2024-01-04T04:33:21.766Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"fetchSnodePoolFromSeedNode with seedNodes.length 3","time":"2024-01-04T04:33:21.766Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"getSnodeListFromSeednode starting...","time":"2024-01-04T04:33:22.765Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"fetchSnodePoolFromSeedNodeRetryable starting...","time":"2024-01-04T04:33:22.765Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"getSnodesFromSeedUrl starting with [REDACTED]","time":"2024-01-04T04:33:22.765Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"insecureNodeFetch => plaintext for getSnodesFromSeedUrl  [REDACTED]","time":"2024-01-04T04:33:22.765Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":40,"msg":"fetchSnodePoolFromSeedNodeRetryable attempt #2 failed. 2 retries left... Error: request to [REDACTED] failed, reason: certificate has expired","time":"2024-01-04T04:33:23.039Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"getSnodeListFromSeednode starting...","time":"2024-01-04T04:33:25.765Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"fetchSnodePoolFromSeedNodeRetryable starting...","time":"2024-01-04T04:33:25.765Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"getSnodesFromSeedUrl starting with [REDACTED]","time":"2024-01-04T04:33:25.765Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":30,"msg":"insecureNodeFetch => plaintext for getSnodesFromSeedUrl  [REDACTED]","time":"2024-01-04T04:33:25.765Z","v":0}
{"name":"log","hostname":"xeon","pid":22666,"level":40,"msg":"fetchSnodePoolFromSeedNodeRetryable attempt #3 failed. 1 retries left... Error: request to [REDACTED] failed, reason: unable to get local issuer certificate","time":"2024-01-04T04:33:26.209Z","v":

**Comment by KeeJef** [comment]
You will need to update to the latest version of Session Desktop 1.11.5, we updated the seed node pinned certificates, which can cause this issue in non-updated clients
