### ISSUE TITLE
[BUG] Audio attachment playback is stopped/interrupted when Session desktop is loading new content in the community timeline (during scrolling)

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#3046]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

Join community http://157.230.25.186/music?public_key=31e9a433530ac82b0740065c4ab17022162cb2e0315b3857a96de752a5027206
Find any audio attachment and play it
Now hit Home or End keyboard key to jump up/down in the timeline
The playback stops when the Session scrollbar on the right reaches either top or a bottom and the Session starts preloading next/newer content...

### Expected Behavior

Playback should not be interrupted. I would actually prefer if even community switching would not interrupt it.

### Desktop Version

1.12.0

### Anything else?

Linux Debian oldstable with KDE with Session Desktop AppImage 1.12.0.

**Comment by yougotwill** [comment]
Relates to https://github.com/oxen-io/session-desktop/issues/1959 Closing for now.
