### ISSUE TITLE
Long amazon link causes open url dialog box to not display the choice buttons open or copy url

### ISSUE THREAD

**Issue by Ruler2023** [oxen-io/session-desktop#3048]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when sharing long URL's over session messenger android and clicking them. on my small phone display (google pixel 3 with grapheneOS) the long URL cvauses me to not reach the choice buttons on how to handle the URL. (open or copy).  There is a bit of scrolling but not enough to reach all the way down.

### Expected Behavior

expected behavior would be a URL that is shortened or reduced in font size to fit the screen size, or the ability to fully scroll down to reach the choice buttons of the dialog.   Or both.

### Steps To Reproduce

1.  On a small display phone,  share a long character product URL of for example amazon.   2. on the receiving end with also a small display, click the URL.   3. Be annoyed to not have any options to choose.

### Desktop Version

1.17.4

**Comment by Ruler2023** [comment]
realized it should of been added to session-android git. So this can be removed

**Comment by Bilb** [comment]
ok, closing this in favor of https://github.com/oxen-io/session-android/issues/1431
