### ISSUE TITLE
[Feature] I can no longer ban/unban ID in a community

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#3050]
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

In Session Desktop 1.12.0 (i have AppImage) some options of a community three dots menu, were moved to the right panel (found by clicking community icon) but not all important menu entries were transferred. For example I am missing ban/unban custom user ID (it was available in a three dots menu which is missing now).

I have tried to run earlier Session 1.11.5 but it failed at this line:
`"level":30,"msg":"sql channel error with call getAllConversations: Error: formatRowOfConversation: an invalid key was given in the record: expirationMode\n    at formatRowOfConversation ([REDACTED]/ts/node/database_utility.js:80:15)\n    at [REDACTED]/ts/node/sql.js:419:63\n    at Array.map (<anonymous>)\n    at getAllConversations ([REDACTED]/ts/node/sql.js:416:58)\n    at IpcMainImpl.<anonymous> ([REDACTED]/ts/node/sql_channel.js:21:28)\n    at IpcMainImpl.emit (node:events:513:28)\n    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88632)\n    at WebContents.emit (node:events:513:28)","time":"...","v":0}`

**Comment by slrslr** [comment]
Three dots menu is also missing for contacts. Its absence is the issue because:
`when i click an avatar in a community, i am switched to a contact/1to1 conversation, and when i want to copy that contact ID or do other action, i have no way to do it without three dots menu, since my contact list is very long in order to find the contact easily and mouse right click the contact in order to see the menu.`

**Comment by KeeJef** [comment]
Right click on the community in the conversations bar, the option should be there still. 

![image](https://github.com/oxen-io/session-desktop/assets/27277414/5260604d-ba0b-4e51-90aa-099b84b96725)

**Comment by slrslr** [comment]
You are right. I had a habit of using three dots menu. But note that yours mentioned option is not available when the Conversations search/filter is used: #2829
