### ISSUE TITLE
Are local files encrypted?

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#3069]
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

Are local files encrypted? Specifically if I put password on Session. It would be dumb to get caught on expropriated device cuz local files (photos, documents, etc) were unencrypted.

**Comment by KeeJef** [comment]
Yes, if you use a password to protect your Session account, then files and your database remain encrypted locally and cannot be accessed without the password.
