### ISSUE TITLE
Document PGP release signature usage on getsession.org/download

### ISSUE THREAD

**Issue by maltfield** [oxen-io/session-desktop#3078]
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

Document how to cryptographically verify downloads on the  getsession.org download page

### Expected behaviour

When I go to download the Session desktop client, I should also see instructions on how to verify the authenticity of the file after download and before install. Or, at least, a link to the document that describes this.

### Actual behaviour

I see no mention about cryptographic authenticity verification on the download page

 * https://getsession.org/download

### Steps to reproduce
1. Go to https://getsession.org/download
2. Click "Linux" (or whatever platform I'm on)
3. See the AppImage is downloading
4. Look around on page for the word "verify" or "PGP" or "GPG" or "signature"
5. ???
6. Get confused and open ticket

**Comment by maltfield** [comment]
Note: This is *not* a support request asking for information on how to verify release signatures.

The only resolution to this ticket is by updating the getsession.org download page with the information (or a link-to the information) that documents how users can verify release signatures.

**Comment by maltfield** [comment]
Here are some examples of "verifying this release" project documentation from other projects

1. https://www.apache.org/info/verification.html#CheckingSignatures 
1. https://docs.featherwallet.org/guides/linux#verifying-the-download-optional 
1. https://support.torproject.org/tbb/how-to-verify-signature/ 
1. https://ubuntu.com/tutorials/how-to-verify-ubuntu 
1. https://tails.net/install/expert/index.en.html#verify-key 
1. https://calyxos.org/install/verify/#additional-verification

**Comment by keybreak** [comment]
https://github.com/oxen-io/session-desktop?tab=readme-ov-file#verifying-signatures

**Comment by maltfield** [comment]
Yes, so one solution to this would be to https://getsession.org/download

with text that says "to verify the authenticity of this release with PGP, please see [Verifying Signatures](https://github.com/oxen-io/session-desktop?tab=readme-ov-file#verifying-signatures)"

**Comment by yougotwill** [comment]
@maltfield Thanks for this comprehensive write up. Sorry to be a pain but would you mind moving this issue to the getsession.org repo https://github.com/oxen-io/session-website/issues

**Comment by maltfield** [comment]
Ticket moved to https://github.com/oxen-io/session-desktop/issues/3078
