### ISSUE TITLE
[BUG] <Session Appimage Version 1.12.3 unusable due to graphical glitches on Garuda Linux>

### ISSUE THREAD

**Issue by qunYp3dZSyLjoEoEg** [oxen-io/session-desktop#3102]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I updated to Sesion 1.12.3 and restarted for the first time, it completely bugged out and due to graphical glitches I am unable to use the application (image provided). It does let me log in, but the log in Screen is similarly bugged out. I don't know how I might be able to provide logs or where to find them, but if those are necessary please tell me how I might be able to get them. I am only now writing this report, even though I updated pretty much immediately when 1.12.3 came out, since it didn't come to my mind to search for the github repo. 
I am on Garuda Linux, running on X11. I have a 7800X3d and a Radeon 6950XT and am running it via Appimagelauncher. If anything else is necessary for debugging, please ask. 
Edit: Without Appimagelauncher, 1.12.2, 1.12.1 and 1.11.5 is also affected, after downloading it from github, so maybe an issue with my system? My current glibc version is glibc 2.39+r52+gf8e4623421-1

![image](https://github.com/oxen-io/session-desktop/assets/107102989/78c84e28-22ef-4639-a55c-d580a8736bc7)

![image](https://github.com/oxen-io/session-desktop/assets/107102989/26ec2b4c-216d-4f2e-ae80-455dbf4cea88)

### Expected Behavior

Sesssion should not have graphical glitches preventing me from using the app

### Steps To Reproduce

I wouldn't know how?

### Desktop Version

1.12.3

**Comment by KeeJef** [comment]
Could you start the app from the command line, and see if there are any relevant errors being logged? Also is it possible that this issue could this be linked to this one https://github.com/oxen-io/session-desktop/issues/3112 ?
