### ISSUE TITLE
[BUG] win11 conversations leaking into google search

### ISSUE THREAD

**Issue by jnorthrup** [oxen-io/session-desktop#3103]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

we write ze konverzsachon und ve zee ze zocialization of our konverzunfroogen!

![image](https://github.com/oxen-io/session-desktop/assets/73514/34fd5162-9b37-4b98-a6af-34c772db56ea)
[...]
profit!
![image](https://github.com/oxen-io/session-desktop/assets/73514/70d3ae17-2746-4e89-8fde-9656d98ab957)

### Expected Behavior

no monetized session conversations.

**Comment by KeeJef** [comment]
Sorry, i don't understand the issue which is being reported here? can you please provide a more detailed written explanation of the issue in English.

**Comment by jnorthrup** [comment]
Im reporting a sniffer that picked up on my session conversation and presented my exact mention back on youtube front page, using windows 11 brave browser.  

The mention of Eddie Van Halen is absolutely one of a kind for me in years.  similarly i have no bookmarks or history containing van halen or Eddie Van Halen 

I have some theories, none of them involve google being informed knowingly about an Eddie Van Halen mention.

I will keep an eye out for the situation recurring in other contexts, but i do hope it helps to report this.

**Comment by KeeJef** [comment]
Okay, there isn't anything in the Session app which communicates any of the messages you type or send to any third party,  so hard to see how this would occur.

**Comment by keybreak** [comment]
No wonder.
The Idea of using secure / private messenger on Spyware OS full of keyloggers and AI (both Win / Mac) - nullifies the concept of **any** secure and private messenger - there's nothing you can do about it except stop using the OS.

In order to prevent it - all Session can do is stop wasting resources and energy on Windows / Mac builds and restrict them...which is not optimal, but at least it's one way to make sure no single side of a conversation will be compromised.

As things are now, i myself have to explicitly ask and trust people that i talk with to never use Session on Win / Mac / iOS....and on Android that at least they have FOSS keyboard installed, and it doesn't connect to the internet.

**Comment by jnorthrup** [comment]
there's this isn't a fort knox installation luckily i have some wiggle room before i get overwhelmed with zombies and have to reinstall.

first things to check is adhesions like opt-ins.  im suspect that the opting in of windows preview features does indeed give a preview to them.  there are other dll's that can be dated to the incident and checked for recent installs.  this isn't normally a thing i spend time on and aside from well meaning recceomndations of hygeine, this isn't a call for that, but I'm agreeable to simple suggestions that others may know of to come up with a/b discriminators for this and other fun occasions of windows binaries sharing too much.

**Comment by keybreak** [comment]
It's impossible to "fix" Windows by flipping options, changing registry or even pirate-build iso with supposedly cut off stuff.
It will be re-surfaced on next update, you don't control Windows.

Just use Linux, and be aware that if someone you're talking with on Session uses Win / Mac / iOS / Android (with default keyboard) - your conversations with such person can and will be compromised by their OS.

**Comment by KeeJef** [comment]
Closing this for now, as its not really something that is in scope for Session to tackle

**Comment by jnorthrup** [comment]
which authors put thier name on some kind of security in the client or the dev tools?  "saying windowz is insecure dont use it" is a cop-out.  @KeeJef 

the distinct lack of any discussion about actual security here is pretty concerning on the viability of even using this client on the majority desktop platform.  we don't simply pass plain text and blame the sniffers for showing it
