### ISSUE TITLE
[Feature] Add macOS arm64 release [with solution]

### ISSUE THREAD

**Issue by jinyuzu99** [oxen-io/session-desktop#3106]
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

For the [build-binaries.yml](https://github.com/oxen-io/session-desktop/blob/unstable/.github/workflows/build-binaries.yml), simple change the `macos-11` to `macos-latest` can build release for arm64 only.

I have already tested, it works almost no bugs on my Apple M2, please check out at [my Actions](https://github.com/jinyuzu99/session-desktop/actions/runs/9028576061)/macOS-production.

The only problem here is the `macos-latest` only build arm64 without x86 support, I currently couldn't find a perfect way to solve that.

### Anything else?

Have a try on my macOS arm64 build: https://github.com/jinyuzu99/session-desktop/actions/runs/9028576061/artifacts/1490340904

**Comment by pottsandpans** [comment]
This is being tracked internally on Jira via SES-1062

**Comment by AndreiRegiani** [comment]
@pottsandpans why does the team work behind a private Jira like a proprietary product? why not use GitHub Projects if you need a board? it doesn't feel very FOSSy for external contributors right now, is there a public team chat (i.e. Discord) where the team chat?

**Comment by KeeJef** [comment]
> @pottsandpans why does the team work behind a private Jira like a proprietary product? why not use GitHub Projects if you need a board? it doesn't feel very FOSSy for external contributors right now, is there a public team chat (i.e. Discord) where the team chat?

We mainly use Jira to track various tasks, create sprints, interlink tasks and perform more complex project management strategies, from what I've seen from Github Projects, its not quite as flexible as Jira in terms of more complex project management. We do have a dev Session community here, which community members can jump into to ask dev related questions https://open.getsession.org/session-dev?public_key=a03c383cf63c3c4efe67acc52112a6dd734b3a946b9545f488aaa93da7991238

**Comment by yougotwill** [comment]
Resolved by https://github.com/oxen-io/session-desktop/pull/3163 and the next release will include arm64 builds!
