### ISSUE TITLE
[BUG] <title>can't connect to routine just after uapdate to 12.5 version

### ISSUE THREAD

**Issue by noneper** [oxen-io/session-desktop#3127]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I updated just desktop of Session promted me. But, it can't path building right now. I always use the desktop very well before this updating : ) . Thanks for you any help!

### Desktop Version

v 1.12.5

**Comment by sakurayz** [comment]
Is this a major bug, and it went live without testing

**Comment by KeeJef** [comment]
Do you have logs from Session Desktop? Need those to understand why you can no longer connect to the network

**Comment by sakurayz** [comment]
Session-android v1.18.6 released at the same time is also not available for login

**Comment by sakurayz** [comment]
session for windows log

Operating System: Windows_NT 10.0.19044 win32 Commit Hash: 2f6d071f202a4c21e08df7e265c8572e5753c5fe Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Session/1.12.5 Chrome/114.0.5735.289 Electron/25.8.4 Safari/537.36 node/18.15.0 env/production
INFO  2024-08-06T05:00:07.266Z app ready
INFO  2024-08-06T05:00:07.266Z starting version 1.12.5
INFO  2024-08-06T05:00:07.271Z locale is en-US
INFO  2024-08-06T05:00:07.271Z showing main window
INFO  2024-08-06T05:00:07.326Z updateSchema:
INFO  2024-08-06T05:00:07.326Z  Current user_version: 11
INFO  2024-08-06T05:00:07.327Z  Most recent db schema: 11
INFO  2024-08-06T05:00:07.327Z  SQLite version: 3.42.0
INFO  2024-08-06T05:00:07.327Z  SQLCipher version: 4.5.5 community
INFO  2024-08-06T05:00:07.327Z  (deprecated) schema_version: 311
INFO  2024-08-06T05:00:07.328Z updateSessionSchema: Current loki schema version: 37; Most recent schema version: 37;
INFO  2024-08-06T05:00:07.378Z attachment_downloads count 0
INFO  2024-08-06T05:00:07.378Z conversations count 5
INFO  2024-08-06T05:00:07.379Z encryptionKeyPairsForClosedGroupV2 count 0
INFO  2024-08-06T05:00:07.379Z guardNodes count 3
INFO  2024-08-06T05:00:07.379Z identityKeys count 0
INFO  2024-08-06T05:00:07.379Z items count 34
INFO  2024-08-06T05:00:07.380Z lastHashes count 13
INFO  2024-08-06T05:00:07.380Z loki_schema count 37
INFO  2024-08-06T05:00:07.380Z messages count 104
INFO  2024-08-06T05:00:07.380Z messages_fts count 252
INFO  2024-08-06T05:00:07.381Z messages_fts_config count 1
INFO  2024-08-06T05:00:07.381Z messages_fts_content count 252
INFO  2024-08-06T05:00:07.382Z messages_fts_data count 10
INFO  2024-08-06T05:00:07.382Z messages_fts_docsize count 252
INFO  2024-08-06T05:00:07.383Z messages_fts_idx count 8
INFO  2024-08-06T05:00:07.383Z nodesForPubkey count 2
INFO  2024-08-06T05:00:07.391Z openGroupRoomsV2 count 0
INFO  2024-08-06T05:00:07.391Z seenMessages count 2
INFO  2024-08-06T05:00:07.391Z sqlite_sequence count 2
INFO  2024-08-06T05:00:07.391Z sqlite_stat1 count 20
INFO  2024-08-06T05:00:07.391Z sqlite_stat4 count 267
INFO  2024-08-06T05:00:07.392Z unprocessed count 0
INFO  2024-08-06T05:00:07.435Z Ensure attachments directory exists
INFO  2024-08-06T05:00:07.453Z Initializing BrowserWindow config: {"show":true,"minWidth":880,"minHeight":600,"backgroundColor":"#1B1B1B","webPreferences":{"nodeIntegration":true,"enableRemoteModule":true,"nodeIntegrationInWorker":true,"contextIsolation":false,"preload":"[REDACTED]\\preload.js","nativeWindowOpen":true,"spellcheck":true},"maximized":false,"autoHideMenuBar":true,"width":880,"height":820,"x":519,"y":14}
INFO  2024-08-06T05:00:07.849Z spellcheck: user locale: en-US
INFO  2024-08-06T05:00:07.849Z spellcheck: available spellchecker languages:  ["af","bg","ca","cs","cy","da","de","de-DE","el","en","en-AU","en-CA","en-GB","en-GB-oxendict","en-US","es","es-419","es-AR","es-ES","es-MX","es-US","et","fa","fo","fr","fr-FR","he","hi","hr","hu","hy","id","it","it-IT","ko","lt","lv","nb","nl","pl","pt","pt-BR","pt-PT","ro","ru","sh","sk","sl","sq","sr","sv","ta","tg","tr","uk","vi"]
INFO  2024-08-06T05:00:07.849Z spellcheck: setting languages to:  ["en-US","en"]
INFO  2024-08-06T05:00:11.772Z background page reloaded
INFO  2024-08-06T05:00:11.773Z environment: production
INFO  2024-08-06T05:00:11.775Z Storage fetch
INFO  2024-08-06T05:00:12.066Z initializeLibSessionUtilWrappers alldumpsInDB already:  [{"publicKey":"[REDACTED]","variant":"UserGroupsConfig"},{"publicKey":"[REDACTED]","variant":"UserConfig"},{"publicKey":"[REDACTED]","variant":"ConvoInfoVolatileConfig"},{"publicKey":"[REDACTED]","variant":"ContactsConfig"}]
INFO  2024-08-06T05:00:12.474Z refreshAllWrappersMappedValues took 39ms
INFO  2024-08-06T05:00:12.475Z ConversationController: done with initial fetch in 62ms.
INFO  2024-08-06T05:00:12.487Z Cleanup: starting...
INFO  2024-08-06T05:00:12.490Z Cleanup: Found 0 messages for cleanup
INFO  2024-08-06T05:00:12.496Z Cleanup: complete
INFO  2024-08-06T05:00:12.498Z listening for registration events
INFO  2024-08-06T05:00:12.500Z connect
INFO  2024-08-06T05:00:13.120Z getOnionPath: Must have at least 2 good onion paths, actual: 0, attempt #0
INFO  2024-08-06T05:00:13.123Z SessionSnodeAPI::buildNewOnionPaths - building new onion paths...
INFO  2024-08-06T05:00:13.194Z getOnionPath: Must have at least 2 good onion paths, actual: 0, attempt #0
INFO  2024-08-06T05:00:13.236Z SessionSnodeAPI::buildNewOnionPaths, snodePool length: 2168
INFO  2024-08-06T05:00:13.251Z Building 3 onion paths based on guard nodes length: 3, other nodes length 2167 
WARN  2024-08-06T05:00:13.253Z buildNewOnionPathsWorker attempt #1 failed. 3 retries left... Error: did not find a single snode which can be the edge
INFO  2024-08-06T05:00:14.242Z those variants needs push: ""
INFO  2024-08-06T05:00:14.260Z SessionSnodeAPI::buildNewOnionPaths - building new onion paths...
INFO  2024-08-06T05:00:14.262Z SessionSnodeAPI::buildNewOnionPaths, snodePool length: 2168
INFO  2024-08-06T05:00:14.273Z Building 3 onion paths based on guard nodes length: 3, other nodes length 2167 
WARN  2024-08-06T05:00:14.274Z buildNewOnionPathsWorker attempt #2 failed. 2 retries left... Error: did not find a single snode which can be the edge
INFO  2024-08-06T05:00:15.282Z SessionSnodeAPI::buildNewOnionPaths - building new onion paths...
INFO  2024-08-06T05:00:15.282Z SessionSnodeAPI::buildNewOnionPaths, snodePool length: 2168
INFO  2024-08-06T05:00:15.285Z Building 3 onion paths based on guard nodes length: 3, other nodes length 2167 
WARN  2024-08-06T05:00:15.286Z buildNewOnionPathsWorker attempt #3 failed. 1 retries left... Error: did not find a single snode which can be the edge
INFO  2024-08-06T05:00:16.288Z SessionSnodeAPI::buildNewOnionPaths - building new onion paths...
INFO  2024-08-06T05:00:16.289Z SessionSnodeAPI::buildNewOnionPaths, snodePool length: 2168
INFO  2024-08-06T05:00:16.298Z Building 3 onion paths based on guard nodes length: 3, other nodes length 2151 
WARN  2024-08-06T05:00:16.302Z buildNewOnionPathsWorker attempt #4 failed. 0 retries left... Error: did not find a single snode which can be the edge
WARN  2024-08-06T05:00:16.303Z buildNewOnionPathsWorker failed with did not find a single snode which can be the edge
INFO  2024-08-06T05:00:16.305Z getOnionPath: Must have at least 2 good onion paths, actual: 0, attempt #1
INFO  2024-08-06T05:00:16.306Z SessionSnodeAPI::buildNewOnionPaths - building new onion paths...
INFO  2024-08-06T05:00:16.307Z getOnionPath: Must have at least 2 good onion paths, actual: 0, attempt #1
INFO  2024-08-06T05:00:16.309Z SessionSnodeAPI::buildNewOnionPaths, snodePool length: 2168
INFO  2024-08-06T05:00:16.312Z Building 3 onion paths based on guard nodes length: 3, other nodes length 2167 
WARN  2024-08-06T05:00:16.313Z buildNewOnionPathsWorker attempt #1 failed. 3 retries left... Error: did not find a single snode which can be the edge
INFO  2024-08-06T05:00:16.398Z destroyExpiredMessages: Loading messages...
INFO  2024-08-06T05:00:16.410Z destroyExpiredMessages: convosToRefresh: []
INFO  2024-08-06T05:00:16.411Z destroyExpiredMessages: complete
INFO  2024-08-06T05:00:16.425Z Loading 0 messages took 5ms to load.
INFO  2024-08-06T05:00:17.107Z about to pollNodeForKey of (...cbcf9f63) from snode: (...e10103) namespaces: 0,2,3,5,4 
INFO  2024-08-06T05:00:17.118Z getOnionPath: Must have at least 2 good onion paths, actual: 0, attempt #0
INFO  2024-08-06T05:00:17.324Z SessionSnodeAPI::buildNewOnionPaths - building new onion paths...
INFO  2024-08-06T05:00:17.325Z SessionSnodeAPI::buildNewOnionPaths, snodePool length: 2168
INFO  2024-08-06T05:00:17.333Z Building 3 onion paths based on guard nodes length: 3, other nodes length 2167 
WARN  2024-08-06T05:00:17.335Z buildNewOnionPathsWorker attempt #2 failed. 2 retries left... Error: did not find a single snode which can be the edge
INFO  2024-08-06T05:00:18.348Z SessionSnodeAPI::buildNewOnionPaths - building new onion paths...
INFO  2024-08-06T05:00:18.349Z SessionSnodeAPI::buildNewOnionPaths, snodePool length: 2168
INFO  2024-08-06T05:00:18.357Z Building 3 onion paths based on guard nodes length: 3, other nodes length 2167 
WARN  2024-08-06T05:00:18.367Z buildNewOnionPathsWorker attempt #3 failed. 1 retries left... Error: did not find a single snode which can be the edge
INFO  2024-08-06T05:00:19.368Z SessionSnodeAPI::buildNewOnionPaths - building new onion paths...
INFO  2024-08-06T05:00:19.368Z SessionSnodeAPI::buildNewOnionPaths, snodePool length: 2168
INFO  2024-08-06T05:00:19.376Z Building 3 onion paths based on guard nodes length: 3, other nodes length 2167 
WARN  2024-08-06T05:00:19.377Z buildNewOnionPathsWorker attempt #4 failed. 0 retries left... Error: did not find a single snode which can be the edge
WARN  2024-08-06T05:00:19.377Z buildNewOnionPathsWorker failed with did not find a single snode which can be the edge
INFO  2024-08-06T05:00:19.379Z getOnionPath: Must have at least 2 good onion paths, actual: 0, attempt #2
INFO  2024-08-06T05:00:19.379Z SessionSnodeAPI::buildNewOnionPaths - building new onion paths...
INFO  2024-08-06T05:00:19.380Z getOnionPath: Must have at least 2 good onion paths, actual: 0, attempt #2
INFO  2024-08-06T05:00:19.380Z getOnionPath: Must have at least 2 good onion paths, actual: 0, attempt #1
INFO  2024-08-06T05:00:19.381Z SessionSnodeAPI::buildNewOnionPaths, snodePool length: 2168
INFO  2024-08-06T05:00:19.384Z Building 3 onion paths based on guard nodes length: 3, other nodes length 2167 
WARN  2024-08-06T05:00:19.384Z buildNewOnionPathsWorker attempt #1 failed. 3 retries left... Error: did not find a single snode which can be the edge
INFO  2024-08-06T05:00:20.131Z Sending message to conversation [REDACTED] with networkTimestamp:  1722920420137
INFO  2024-08-06T05:00:20.450Z SessionSnodeAPI::buildNewOnionPaths - building new onion paths...
INFO  2024-08-06T05:00:20.451Z SessionSnodeAPI::buildNewOnionPaths, snodePool length: 2168
INFO  2024-08-06T05:00:20.454Z Building 3 onion paths based on guard nodes length: 3, other nodes length 2167 
WARN  2024-08-06T05:00:20.464Z buildNewOnionPathsWorker attempt #2 failed. 2 retries left... Error: did not find a single snode which can be the edge
WARN  2024-08-06T05:00:20.535Z tried to upload file to FileServer without image.. skipping
INFO  2024-08-06T05:00:20.535Z Upload of message data for message [REDACTED] 1722920420137 is finished in 41ms.
INFO  2024-08-06T05:00:20.539Z OutgoingMessageQueue: Processing sync message
INFO  2024-08-06T05:00:20.602Z getOnionPath: Must have at least 2 good onion paths, actual: 0, attempt #0
INFO  2024-08-06T05:00:20.606Z Loading 1 messages took 14ms to load.
INFO  2024-08-06T05:00:21.518Z SessionSnodeAPI::buildNewOnionPaths - building new onion paths...
INFO  2024-08-06T05:00:21.520Z SessionSnodeAPI::buildNewOnionPaths, snodePool length: 2168
INFO  2024-08-06T05:00:21.536Z Building 3 onion paths based on guard nodes length: 3, other nodes length 2167 
WARN  2024-08-06T05:00:21.537Z buildNewOnionPathsWorker attempt #3 failed. 1 retries left... Error: did not find a single snode which can be the edge
INFO  2024-08-06T05:00:22.502Z getAllFromCache
INFO  2024-08-06T05:00:22.506Z getAllFromCache loaded 0 saved envelopes
INFO  2024-08-06T05:00:22.548Z SessionSnodeAPI::buildNewOnionPaths - building new onion paths...
INFO  2024-08-06T05:00:22.549Z SessionSnodeAPI::buildNewOnionPaths, snodePool length: 2168

**Comment by Bilb** [comment]
Hey, could you give the last release a try?
 thanks

**Comment by Bilb** [comment]
Considering this fixed.
