### ISSUE TITLE
[Feature] update to 1.13.0 possibly caused inactive input field on "New message"/"Join community"

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#3151]
- [X] I have searched the existing issues

### What feature would you like?

In recent Session Desktop update (I am on Linux, AppImage), I have noticed more inconvenience regarding adding contact/community.
When i click the + button and one of the:
"New message"
"Join community"
the input text field for the ID or address is not highlighted by default. I have to aim and click.
It would be nice to save the time of the user and make it more convenient again by activating the input fields by default, so user can just Ctrl+V.

**Comment by KeeJef** [comment]
Should probably just focus when the user sends keystrokes, we changed this field slightly recently this is a side effect of that change

**Comment by yougotwill** [comment]
Will look into it. 👍
