### ISSUE TITLE
[BUG] Community/group posted image missing a thumbnail since v1.13.0, but it shows when i switch to other community and back

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#3156]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Did you make any change regarding community and group attachments displaying in recent 1.13.0? Because around the time I have upgraded to this version (Linux AppImage), mine posted picture does not show a thumbnail until I switch to other community or group and back. Please examine your recent changes to see if anything could impact this?

### Steps To Reproduce

1. attach an image (the issue happened for any file I have tried (jpg, png))
2. it created a thumbnail when i have dropped the image using mouse drag and drop
3. yet posted image does not show any thumbnail, until:
4. click other community in the conversation list and back to see the thumbnail now

### Desktop Version

1.13.0

### Anything else?

Debian 11 with KDE, Session desktop AppImage

**Comment by HowTheyBurnCables** [comment]
I've had this happen in DMs too, not just community and group conversations. Seems to be happening across operating systems as well as I experienced it on Windows.

**Comment by KeeJef** [comment]
Yep, we're aware of this one, tracked internally via SES-2546 @yougotwill
