### ISSUE TITLE
[BUG] Images are not SHOWN 

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#3177]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not sent, nor recieved images, both in SOGS and DM, are SHOWN in the app (though they're recieved succesfully and can be eg. downloaded to be viewn on PC).

No same problem on mobile, so it seems to be exactly desktop's problem.

![image](https://github.com/user-attachments/assets/b32732f1-c4be-47aa-a9f4-67af4f412cbb)

### Details

App version: v1.13.1
OS: Windows 10
Git commit hash: 907eac8d968b69d9993f254e95ce437d370aee6f

**Comment by yougotwill** [comment]
Hi @qdhj this will be fixed in an upcoming release. Thanks for reporting. See https://github.com/oxen-io/session-desktop/pull/3170

**Comment by yougotwill** [comment]
Fixed in [v.1.13.2](https://github.com/oxen-io/session-desktop/releases/tag/v1.13.2)
