### ISSUE TITLE
[BUG] Win11 yarn install --frozen-lockfile Command Run failed

### ISSUE THREAD

**Issue by legiorange** [oxen-io/session-desktop#3212]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want build on Windows11 but  It take me 3day. It seem like Windows need install cmake-js too.

3day. Linux is fine. 

### Steps To Reproduce

PS session-desktop)> yarn install --frozen-lockfile      
yarn install v1.22.21
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
[4/6] Linking dependencies...
warning " > focus-trap-react@10.2.3" has unmet peer dependency "prop-types@^15.8.1".
warning " > @testing-library/user-event@14.5.2" has unmet peer dependency "@testing-library/dom@>=7.21.4".
[5/6] Building fresh packages...
[1/6] ⠐ @signalapp/better-sqlite3
[2/6] ⠐ libsession_util_nodejs
[6/6] ⠐ postinstall-prepare
[4/6] ⠈ electron
error  F:\session-desktop\node_modules\libsession_util_nodejs: Command failed.
Exit code: 1
Command: cmake-js compile --runtime=electron --runtime-version=25.8.4 -p16 --CDSUBMODULE_CHECK=OFF --CDLOCAL_MIRROR=https://oxen.rocks/deps --CDENABLE_ONIONREQ=OFF
Arguments:
Directory: F:\session-desktop\node_modules\libsession_util_nodejs
Output:
info find VS using VS2022 (17.11.35312.102) found at:
info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
                                                                                 

### Desktop Version

1.13.2

**Comment by Aerilym** [comment]
Did you follow the windows build instructions? If you follow them you should have everything you need to build Session Desktop. https://github.com/oxen-io/session-desktop/blob/unstable/CONTRIBUTING.md#windows

**Comment by legiorange** [comment]
Sorry I've given up. I won't fork until there are further steps to optimize the build in the session or I switch to Linux.

Thanks for your reply.

**Comment by Aerilym** [comment]
Sorry to hear that, unfortunately there's a lot of conflicting issues making building on windows difficult, the instructions we have will work from scratch (on a fresh windows install), but there are issues if you have visual studio already installed, if you decide to give it a go again, the one think I'd suggest you do is open visual studio installer and manually install the c++ build tools.
