### ISSUE TITLE
[BUG] 1.14.0 unhandled error: \"Uncaught RangeError: Incorrect locale information provided\";\"[REDACTED]/node_modules/react-dom/cjs/react-dom.production.min.js

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#3221]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Under session-desktop-linux-x86_64-1.14.0.AppImage the interface of the app is blank (in my case black) after launch and repeated launch does not help. I have to return to a previous version which is working.

[Log](https://drive.proton.me/urls/WPVYVJ6Y9R#BTpVEytvRhXQ) (password is the name of the Session's new token) shows a message in the title of the issue. Log expires in ~1 month for privacy reason.

### Desktop Version

1.14.0

### Anything else?

Debian 11 with KDE

**Comment by Bilb** [comment]
Hey, can you let me know what returns

echo "LC_ALL $LC_ALL"
echo "LANGUAGE $LANGUAGE"
echo "LANG $LANG"

**Comment by slrslr** [comment]
@Bilb it returns:

```
LC_ALL 
LANGUAGE en_US:en
LANG en_US.UTF-8
```

**Comment by Bilb** [comment]
ok, can you start the app correctly with
`LANGUAGE=en_US session-desktop.appImage`
?

**Comment by Bilb** [comment]
I guess that semicolon is `:en` up the formatting of some timestamps (and throwing)

**Comment by slrslr** [comment]
Yes, this workaround worked, thank you for the quick attention.

**Comment by pottsandpans** [comment]
This issue has been resolved.
