### ISSUE TITLE
[BUG] 1.14.0 shows only black frame after update

### ISSUE THREAD

**Issue by WilliWolfsmilch** [oxen-io/session-desktop#3223]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

after updating to v1.14.0 Session shows only a black frame.
![Uploading screenshot.JPG…]()

### Desktop Version

v.14.0

### Anything else?

System Information: Linux 5.15.0-119-generic, Node.js 18.15.0 linux x64
Commit Hash: 18862abf59d095cd0573311aed6e4bfc13115436

**Comment by yougotwill** [comment]
@WilliWolfsmilch Can you try upgrade to our latest release and see if the issue still happens? 🙏

**Comment by WilliWolfsmilch** [comment]
I just upgraded to v1.14.2
It works great again! Thank you for the fast fix.
![Screenshot from 2024-09-30 10-21-09](https://github.com/user-attachments/assets/f602daa9-e1c1-4c06-89d4-dba969bbb7eb)

**Comment by yougotwill** [comment]
You are welcome 🙏
