### ISSUE TITLE
[MINOR COSMETIC] "Copy link" button invisible

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#3230]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Last update accidentaly made "copy link" button invisible, if not hovering it with mouse.

![image](https://github.com/user-attachments/assets/b93ee4e1-8f68-493d-82a7-1db62c271742)

### Desktop Version

v1.14.2

### Anything else?

git hash 3cadc54e44295a073ab46dd134f66410652bc66e

**Comment by pottsandpans** [comment]
Thanks! This is being tracked internally on Jira SES-2755.
