### ISSUE TITLE
Panic delete client database

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#393]
There should be a way for a client device to quickly delete all of their account information, messages and data  from their messenger.

**Comment by sachaaaaa** [comment]
Desktop already has this via Task bar menu Loki Messenger -> Preferences -> Clear Data.
But I can't seem to find that option on mobile.

**Comment by Mikunj** [comment]
> Desktop already has this via Task bar menu Loki Messenger -> Preferences -> Clear Data.
> But I can't seem to find that option on mobile.

I'm not sure if mobile has it at all 🤔

**Comment by JeffRockatansky** [comment]
Shouldn't this issue be closed then?
