### ISSUE TITLE
Message deletion requests for non chat channels

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#396]
For non group chats we would like to have the ability for one client to request the deletion of **his own** messages on the other clients device, if the message is received by the other client the deletion should happen immediately from the receiving clients device. 

We should also include a dialogue box which indicates that when a client requests the deletion of their own message it will only be deleted if the other client actually receives that message deletion request (i.e message deletion is not guaranteed)

**Comment by Bilb** [comment]
this is unsending which is done already
