### ISSUE TITLE
Emoji Search (Shortcodes)

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#452]
Discord has a great feature where if you type the : character a little emoji search box appears where you can search emojis based on name, this should be added to Loki messenger 

![image](https://user-images.githubusercontent.com/27277414/63924888-6e85b780-ca8c-11e9-81bd-9aabd17bf1f3.png)

**Comment by KeeJef** [comment]
https://gist.github.com/oliveratgithub/0bf11a9aff0d6da7b46f1490f86a71eb

**Comment by Bilb** [comment]
this has been fixed with recent releases
