### ISSUE TITLE
GUI and Usability Enhancements for the Android Loki Messenger

### ISSUE THREAD

**Issue by CryptoFirefly** [oxen-io/session-desktop#496]
Enhancements for the Loki Messenger for the Full release. These will help enhance the experience for the average users who are used to some of such features from other leading messengers and apps.

1. Access to Settings / Options page for the Messenger
> The way to reach the settings screen is not intuitive and requires the user to click on his own Avatar to reach the settings page. This is not clear and the users may find it difficult to find it initially. Just like the Chat screen, where there are three "DOTS" on the right to open the chat specific chat settings, similar three dots can be used to have a link to the Main setting page. 

Or we could also use a GEAR icon on the top right to make it even more intuitive for users to reach that page. 

2. Pin Chats to Top
> A feature to Pin upto 5 chats to the Top would be a nice feature to add, as we add many users, the key contacts can then be pinned.

3. Addition of Comments / Additional Reference for our Contacts
As Contacts are currently free to change their Names and the person who has added them has no way to keep any record. E.g. if someone adds my public key and my Name initially is "Jay" and later, i change my name to "Loki Admin", then i appear as "Loki Admin" the user has no control and would not know when that happened and may potentially send some sensitive info to me. 

While we cannot control what others do, we can give a Free Text locally App level data to save Comments. We can also put a note that, importing the pvt keys to a new device may not port this data, if currently that will be a challenge. Atleast at the user's setup, he can store some comments to remember who he added. 

Another option to safe guard would be that Change of Name by users is allowed only Once per Month, as usually people should not require to change names that often. As public key IDs are not human readable or memorable, we need such safe guards.

4. Disappearing messages 
> Currently its not clear that the disappearing message time is only from a sender's perspective, or its from when the reader opens it. 

E.g. if i set the time as 10 seconds, and the receiver only opens it an hour later. Seems he may not see the message in the conversation at all. Ideally it should appear for 10 seconds when the receiver opens the message. 

If the above is not feasible, somewhere in the settings, this needs to be clear of the current feature in a smart way to explain to users. 

5. Reply & Quote Feature
> Not very essential for 1st version, but the option to Quote a previous text (only if its not a disappearing message) would be a good feature. So if replying to a long conversation, users are able to click reply quoting a previous message. 

The Quote feature can work my long press on a message and choosing among options such a Reply, Copy, Forward, Delete etc.

**Comment by CryptoFirefly** [comment]
For the group Chats, 

1. include the Count of the number of members in the group
2. Admin Tags against admin accounts
3. Can admin set the disappearing message in Group and Announcement Channels? 
Probably the setting to allow for the same, as some group chats may need that for privacy and validity of information reasons, so that they disappear after a specified period.
4. Clicking the Group Chat Avatar icon should open some "Information Page", so the admin can describe the group rules, about the group and probably it lists the members, with all admins listed first in sequence, even if their last online is not as recent. So sort by Admins, then others. And within this group can be sub-sorted by last online.

**Comment by KeeJef** [comment]
Pretty much all of this has been implemented now
