### ISSUE TITLE
GIF preview issues

### ISSUE THREAD

**Issue by Mikunj** [oxen-io/session-desktop#507]
**Describe the bug**
When you get a link preview with a gif, it fails to render on mac even though it works on windows.

**To Reproduce**
1. Send `https://tenor.com/view/judge-judy-dancing-fortnite-gif-14899688` to a mac client.

It won't render on mac but it'll work fine on windows.

**Comment by sachaaaaa** [comment]
Previews seems to work on mac, under the right conditions. 
- have link previews enabled (it's disabled by default)
- send a https link from the whitelist domains
- the link must be a sharing link poiting to an html page, not the image itself.

But there are definitely issues, especially when submitting the link before waiting for the preview to finish loading.

**Comment by Mikunj** [comment]
Direct link to GIfs (or other images) also don't work

**Comment by Mikunj** [comment]
It should've but there seems to be weird edge cases which might still need to be handled.
