### ISSUE TITLE
Open group polling breaks (After 24 hours)

### ISSUE THREAD

**Issue by neuroscr** [oxen-io/session-desktop#510]
**Describe the bug**
public chat stops updating

**To Reproduce**
just wait long enough

**Screenshots or Logs**
no JS errors in the inspector. Usually takes about 24 hours (maybe it's related to my computer going to sleep)

**Other information (please complete the following information):**

* Device: MAC
* OS: 10.14
* Loki messenger Version or Git commit hash: 1.0.0beta-5

**Comment by Bilb** [comment]
@neuroscr is it fixed already? I did a fix about this a month ago or so
