### ISSUE TITLE
Allow users to assign names to other users

### ISSUE THREAD

**Issue by trosel** [oxen-io/session-desktop#522]
As a user, I want to have different names with different groups of people (gamer handle vs Family nickname).

As a user, I want to be able to overwrite a friend's username with my preferred name for them.

- [ ] During account creation / on-boarding, explicitly mention the option to leave the username field blank and (optionally) give them a random username via something like https://github.com/alenoir/username-generator
- [ ] When I long press or right click on a user message, I should see the option to "assign nickname" next to the "copy public key" option
- [ ] Clicking "assign nickname" will prompt me for a new name for the user
- [ ] My nicknames-to-publickeys map will be stored in an encrypted config either locally on my device or somehow integrated with Multi-Device Syncing https://github.com/loki-project/loki-messenger/issues/415

**Comment by alexandrestein** [comment]
Any news on this?

I see the button in the interface but it doesn't do any thing.
![Screenshot from 2020-06-04 13-06-01](https://user-images.githubusercontent.com/5431025/83749616-40a95100-a664-11ea-8064-e8e606673637.png)

I believe that this is a mandatory feature if you many contact.
I guess the goal is to have a secure messaging solution for all. :wink:

**Comment by trymeouteh** [comment]
+1 for contacts management. To have a contacts section were you can add names to your contacts and easily import/export this contact list and have it sync between your devices.

**Comment by Bilb** [comment]
@alexandrestein this should be fixed in latest releases
