### ISSUE TITLE
Device mapping [Stage 2] (Encrypted Device Mappings)

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#545]
Device mappings are currently stored on a the Loki file server, and are stored directly under each users public key. So for example they may look like 

```
Device mapping
{
Primary key = xxxxxx
Secondary key = xxxxxx
}
```
this is not great, since the Server that holds these mappings can draw a connection between a primary public key and and secondary key, this is inevitable if public keys are exposed, but often a public key can be exchanged out of band, this removes the need to expose the key publicly.

So instead of dealing with cleartext storage of keys we can use some encryption to ensure unless the storage server knows the related public keys they cant workout what mappings they are holding or the relationships between those mappings. 

Basically in this proposed scheme, before each client stores their mapping on the public server they should deterministically derive a symmetric key from the primary key and then encrypt both the primary and secondary keys with it. The device mapping should then become

```
Device mapping 
{
Encrypted primary key = xxxxx
Encrypted secondary key = xxxxx
}
```

Because the generation of the symmetric key is entirely deterministic it means anyone you give your primary keys to can work out what your encrypted primary key would be, and they can simply ask the Loki file server for the encrypted key and decrypt it client side. This way the Loki file server knows nothing about the device mappings or the public keys it stores, and the requests also don't reveal anything about the keys being requested.

**Comment by neuroscr** [comment]
still need public mappings for the public chat

**Comment by KeeJef** [comment]
Public chat that everyone joins is slated to be deleted in the future, once we move into opt in joinable chats when the user joins a chat they should just give thier public key to the Server, using this the server should be able to grab their mappings from the respective Swarm / Loki file server, depending on where we are at in our device mapping [stages]
