### ISSUE TITLE
Device Mapping [Stage 3](Store Device Map in Swarm)

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#547]
Right now Device mappings are stored on the Loki file server, it should be possible to delegate this task to Swarms of storage servers. 

What i'm thinking is, each primary public key maps to a Swarm, so we should be able store device mappings in the same way as #545 except we would store them across the whole swarm, since the user who needs the mapping will always have the public key of the other user they should always know where to look for their device mappings.

Regarding the actual storage, i think we could probably let the mapping sit in a Swarm for 90 days at a time, after this we can expire the mapping, and if the client is comes online at any point they may update and refresh that mapping to ensure it doesnt expire

**Comment by neuroscr** [comment]
I think it will help with the metadata leakage problem at the file server. However we need to be able to add all the types of queries we need to the storage servers. So far I see:
- get map by single pubkey
- get maps from these pubkeys

and service nodes are more trusted (and tested), so may it could withhold invalid signatures (if it doesn't past the SN test, it's not likely to pass the messenger client tests). Though I could see change management issues with that.
