### ISSUE TITLE
Expand link preview supported domains in all platforms

### ISSUE THREAD

**Issue by trosel** [oxen-io/session-desktop#552]
**Either** include more websites like:

- twitter (direct links to tweets)
- facebook (facebook events, posts, etc)
- medium (articles)

**Or** allow multiple options for link previews in the settings;

- block all
- enable approved link previews
- enable all link previews

What exactly is the risk of allowing all link previews? The major concern about this really depends on your risk level, right?

**Comment by neuroscr** [comment]
> What exactly is the risk of allowing all link previews?
leaking your IP. Someone sharing an URL to a server they control, they can get an IP of everyone they share with (and opens it).

**Comment by trosel** [comment]
@neuroscr In that case, maybe we can just expand it to the most popular websites, some of which I linked above.
