### ISSUE TITLE
Invite Links [Stage 1 Blacklist invites]

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#582]
Stage 1 invite links will involve building out the UI for invites, This will link up with the the creation of https://github.com/loki-project/loki-messenger-public-server/issues/9 a blacklist. Essentially every server should define whether it would like to have a whitelist or blacklist before the server is created. 

Stage 1 invite links are for blacklist chats only (blacklist meaning anyone can join, but certain public keys can be banned) Stage 1 invite links are simply messages that can be received from any user that encode the server domain name. when these invite messages are clicked the server is automatically added. 

This ability should be given to every member who joins a blacklist chat, and it probably should sit in the settings/cog menu, of the group chat you are currently in.

**Comment by neuroscr** [comment]
backend endpoint has been created but has not been deployed to chat-dev
