### ISSUE TITLE
Nickname not shared from mobile to secondary device

### ISSUE THREAD

**Issue by sachaaaaa** [oxen-io/session-desktop#628]
When a mobile (primary device) pairs with a desktop (secondary device), the mobile's nickname is not applied to the desktop account automatically after pairing.

**Comment by Mikunj** [comment]
I've confirmed that it **DOES** apply the mobile nickname (android wasn't sending it correctly before) but due to some message (haven't confirmed which one) the nickname gets reset to none.

A nickname will never be able to be empty from mobile as we always enforce a display name on registration.
