### ISSUE TITLE
Version 2 Multi Device

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#640]
Version 2 Multi device reduces the overall complexity of multi device for open groups and removes the need for device mappings to be stored on the Loki file server. 

Pairing - Primary device shares its Loki messenger private key with the secondary device (For open groups chat usage), this can be done using an encrypted message to the secondary device. Secondary device also shares its public keys with the primary device during pairing.

Replacing LFS device mapping - Instead of storing device mappings publicly on the Loki file server device mappings should be sent after a friend request is accepted. When sharing a public key so that a friend can add you, you should always share the primary devices public key. Secondary devices should poll the primary devices swarm for any friend requests for the primary devices public key, because the secondary device has the primary devices private keys the secondary device can accept a friend request on behalf of the primary device. When a friend request is accepted the device mappings are sent as a response. This means that only friends who are accepted get your device mappings

Receiving - Receiving is unchanged, once a friend has your device mappings they send a message to both devices swarms. Secondary devices poll their own swarm and primary devices poll their own swarm.

Sending - To ensure sent messages are properly synced, if either the primary or secondary device sends a message they must send a copy of that message to either the secondary or primary devices swarm. This is unchanged

Open groups - Since both devices can now share the same public + private key pair they can both sign messages that appear as if they are coming from the same device for open groups, where ratcheting doesn't matter. this also means validation does not need to be done using a device mapping client side. 

This scheme reduces the complexity for open groups and increases privacy, only sharing device mapping with those you have accepted as friends.

**Comment by neuroscr** [comment]
I think we need some clarity on how the ratcheting would work when two devices share a pubkey
