### ISSUE TITLE
Better Network time 

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#642]
I have run into quite a few desktop messenger users who are getting timestamp errors, this due to a misconfigured local clock. We are now properly exposing this error to the user, so they know there is an issue with their timestamp.

Many users dont' really know what to do with this information though, so i would like to write some Loki docs documentation about how to correctly set the local clock on different OS's and when the error is encountered a link to this doc should be provided in the desktop app 

The longer term solution could be for the app to maintain its own time which it fetches from the Service Node network on startup, this would avoid bad local clocks altogether

**Comment by fadelm0** [comment]
Hi @KeeJef, is there a guide already written somewhere on how to correctly set the local clock on windows?
Because it's giving me this error, while the clock seems to be correct, so I don't know what it's referring to. Could you give me some pointers?

**Comment by KeeJef** [comment]
You just need to sync your clock to network time instead of setting it manually

**Comment by fadelm0** [comment]
I actually figured out the problem. I _was_ syncing the time but using time.nist.gov , and when I changed it back to time.windows.com it worked. Thanks!

**Comment by KeeJef** [comment]
We keep time locally from the Service Node network now
