### ISSUE TITLE
Uncouple pubkey/tokens from attachment when using file server

### ISSUE THREAD

**Issue by neuroscr** [oxen-io/session-desktop#664]
Right now, when we upload files, a token is required. We need to change the file server class to have 2 ADN clients (one with tokens for multidevice and one with a static token) and make the attachment endpoint use the new "static token" client.

**Comment by Mikunj** [comment]
what would the difference be with the old tokens and these new static tokens? how do we get them?

**Comment by neuroscr** [comment]
thinking the static token would just be "loki" but I still need to create it in the database, so that it will work
