### ISSUE TITLE
Session restoration improvements

### ISSUE THREAD

**Issue by Mikunj** [oxen-io/session-desktop#686]
These are a list of things that need to be changed to get similar session restore experiences across devices:
- Show a banner at the top when we prompt a user for a session restore
- Show the original signal messages (Bad encrypted, no session)
- Store the restoration time. If we received a `FRIEND_REQUEST` message that was sent before this time then we ignore it

Bugs (Desktop):
- Receiving a background friend request with the `SessionRestore` flag set and with no body causes `Friend request accepted` message to show up in the chat.
    - Sending a `SessionRestore` message and receiving a confirmation causes `Friend request accepted` message to show up in the chat.
- We should still show the original message which caused the session restore dialog to show up
    - Bad Encrypted or No session messages, this way users have some context about the issue

Bugs (Mobile):
- There is no indication for when a session restore was successful
    - Desktop shows `Secure session reset succeeded`

**Comment by Bilb** [comment]
most of that is related to the friend request logic
