### ISSUE TITLE
Loki File Server binning

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#688]
Client devices should be adding padding to the closest MB (Potentially too high) for each file uploaded to the Loki file server, this ensures that uploads to the Loki file server do not have an overly distinct file size which could be used for out of band correlation attacks.  

This will ensure that each file uploaded will mix nicely into one of the distinct size bins 1,2,3....8,9,10 MB which will have lots of other files of the same size.

**Comment by KeeJef** [comment]
It seems Signal is doing some padding but we need to investigate whether this is sufficient

**Comment by Bilb** [comment]
this it the way we are doing it on desktop (inherited from Signal desktop)

```
  const paddedSize = Math.max(
    541,
    Math.floor(Math.pow(1.05, Math.ceil(Math.log(originalAttachmentLength) / Math.log(1.05))))
  );
```
  
  Of course, this is disabled for opengroup chats as the attachments are not encrypted for those

**Comment by Bilb** [comment]
and ios is doing the same: https://github.com/signalapp/SignalCoreKit/blob/master/SignalCoreKit/src/Cryptography.swift#L208
