### ISSUE TITLE
Investigate Message ordering

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#695]
Right now some messages (Reported specifically on Android) appear out of order, there have been some changes to Signals message ordering and those changes may have caused issues. 

We need to investigate how all platforms do message ordering and ensure we are talking the same approach across all platforms to ensure consistency. Ideally we should avoid the using the local clock of the device as a source to order messages and should either rely on network time or some counter which increments for each new message added to the chat

**Comment by Mikunj** [comment]
On android messages are ordered by the time that they were received.
see: `getConversation(long threadId, long offset, long limit)` in `MmsSmsDatabase`

**Comment by KeeJef** [comment]
We have decided that we will be using the senders timestamp to order messages

**Comment by RyanRory** [comment]
For Android, the original codes are using the sender's timestamp to order the messages. When we write a message into the local database, we are using the sender's timestamp as the receiving time. See: `insertMessageInbox(IncomingMediaMessage retrieved, String contentLocation, long threadId, long mailbox)` in `MmsDatabase` and `SnsDatabse`.
For iOS,  the original codes are using an increasing counter to create a sort id for each message. See: `TSInteraction.m`. For public chats, before writing the messages into the local database, the original codes sort the message by the sender's timestamp. See: `pollForNewMessages()` in `LokiPublicChatPoller.swift`.

> On android messages are ordered by the time that they were received.
> see: `getConversation(long threadId, long offset, long limit)` in `MmsSmsDatabase`

**Comment by KeeJef** [comment]
@msgmaxim will need to check this on desktop

**Comment by msgmaxim** [comment]
On desktop we use `received_at` (set by the sender) to sort the messages.

**Comment by cammellos** [comment]
@msgmaxim Hey, just for your information, maybe you discussed this already.

In terms of message sorting, you can use the sender timestamp, which I take is fine in most cases and might very well be your best option.

In our case (https://github.com/status-im) we had to change it as it might result in the following scenario:

1) User A sends a message (m1)
2) User B receives a message
3) User B replies to user a message (m2)

If the clocks are not synchronized (say user A clock is ahead of user B), m1 might potentially be ordered after m2 , this was particularly visible when exchanging messages programmatically at the protocol level. 

To overcome this we use basically lamport timestamp, but with the sender timestamp as a basis:

`clock = max(timeNow, lastMessageTimestamp+1)` 

Which has all the properties of Lamport timestamp (causally ordered messages), with the addition of working well in group chats or when there are gaps in the message history. (using normal timestamps a user joining a public chat and not having received any message would start from 1, potentially ordering their message in the past).

Care need to be taken making sure that users don't make the logical clock race ahead, which is one of the drawbacks of this method + the extra piece of state that you need keep around.

Briar uses the same method https://code.briarproject.org/briar/briar/blob/master/briar-android/src/main/java/org/briarproject/briar/android/privategroup/conversation/GroupControllerImpl.java#L170 I believe. 

Not suggesting you do the same, but thought it was worth sharing the experience.

Thanks for the project, amazing work!

**Comment by msgmaxim** [comment]
@cammellos The scenario you described might indeed be a problem (though it seems rare), thank you for pointing it out! We will look into incorporating your approach in the near future.
