### ISSUE TITLE
Opt-in: placeholders for disappearing messages

### ISSUE THREAD

**Issue by yidakee** [oxen-io/session-desktop#698]
Minor issue first, I haven't used Loki Messenger much, so it is natural I completely missed out on disappearing messages. I'm so used to Wickr (that has the option next to text input) that I didnt even notice it in the options section - it was a complete surprise it had already been implemented. Please make this a featured feature for Sessions!

Major issue:

Preamble. I've been using Wickr for about 6 years in a group of 350 people. We use Whastapp for group messages and Wickr for 1:1 privacy. We used another before I honestly can't remember. Point being, I'm a Wickr Me power user along with 350 other guys. Many starting to get into crypto big time. Was waiting for the rebrand to hopefully convince all to switch to just Sessions. Unfortunately, I wont be able to do so.

We use auto-destruct message feature as standard, and sometimes it goes days before the other party reads it. These guys are scattered all over the world. Think of this as a social mesh network, where I only have personal relationships with some of them. 

The way Loki Messenger uses disappearing messages is the timer starts on sender's device immediately. On Wickr, the timer only starts when the receiver opens and reads it. We use this as a feature, when the timer starts it serves as "sms receipt" type message back. Not only do I know the message was read, it sometime may trigger an action.

"Hey Alice, when you send me the message to X identity, if it gets read, please proceed with action A" - for example, a security feature against 3rd party gaining access to a specific device.

Even at a lower security level, people need to know if the person has read the message or not. Otherwise, when waiting for a response, sender may end up using an alternate comms system to check up with the recipient. If the message sits there unread, sender knows delivery is still pending.

Without such "receipt" type message, Alice sends Bob a text with auto-destruct say 30 minutes. Alice is sitting there wondering if the system is actually working, if Bob actually got the message or if he has read it or not.

What we don't like about Wickr at all is that the sender's message is still readable until the receiving end opens the message and triggers the timer. This is also a security risk, however it is the best compromise we have found so far. What we also HATE to death is that the actual message window also disappears. Sometimes auto-destruct with different settings makes it so reading back concatenated messages makes it really confusing.

Sessions has the perfect opportunity to fix all of this by being the best of both worlds.

Here is what I suggest;

- Alice sends message with 30m auto-destruct to Bob.
- 30m elapses and message is not deleted on Alice's phone, rather the message window changes color with text "delivered" is displayed instead of the original text. 
- Next day Bob reads the message and triggers the 30m auto-destruct timer. Alice receives an update on that message window where text changes from "delivered" to "30m auto-destruct activated" - Incredibly useful feature would be a count-down timer on this!
- After 30m, Bob's message changes color and original message changes to "deleted", and also on Alice's device.
- The actual message window does not disappear, leaving the original thread of message interchange intact, leading to much better communication flow. 

Hope it made sense and is aligned with Session's design! Again, this "receipt" issue is the only reason I wont be introducing Sessions to this group, hence the clickbaity title

**Comment by natedagger** [comment]
I think the idea is worth it as an option, as I don’t think this is a one-off concern. 

The bigger picture here is Loki has previously said it would like to target loyal niche audiences and make them fanatics and everyday users. How can the team go about speaking to different targeted groups and set Session up to have these custom options? 
Keep the default options toward the “regular” users who just want privacy, and then take the best features of other messaging apps, if possible and if the juice is worth the squeeze.

**Comment by ada4charity** [comment]
@natedagger If the primary goal of Session is to cater to whistleblowers, journalists & reporters, freedom fighters, protest groups etc - they need to be able to coordinate efforts and events, so some sort of asynchronous feedback mechanism is key

**Comment by yidakee** [comment]
@natedagger If the primary goal of Sessions is to cater to whistleblowers, journalists & reporters, freedom fighters, protest groups etc - they need to be able to coordinate efforts and events, so some sort of asynchronous feedback mechanism is key.

If it's for shits 'n giggles, then as is is just fine. But for more serious type of events, the "sms receipt" I described above can be a lifesaver in certain situations.

Ex: Bob has 2 devices, or 2 Sessions ID's. Alice sends Bob1 and Bob2 a message. If Bob2 gets opened and read, Alice knows the device has been intercepted by a 3rd party.

**Comment by KeeJef** [comment]
I've just tested Desktop to Desktop, and the functionality your describing exists in Loki Messenger, when a message is sent the timer for disappearing starts on when the other device first sees the message. The only thing that's missing is the placeholders messages that you describe, that would be placed after a message is deleted. I'm on the fence about those placeholders, because even though the content of the message would not be revealed if someone got access to your device, they would see that you sent a bunch of messages to X person as indicated by the placeholders. Maybe it could be an opt in feature

**Comment by yidakee** [comment]
@KeeJef - I did test on Loki Android, I now realize this issue in on the wrong place. I can confirm the timer starts when the message is sent, not when it is opened. Anyway, for you consideration, the more options, the wider Sessions will cater to different folk

**Comment by KeeJef** [comment]
This should now be working as normal on all platforms (message timer starts when user reads the message)
