### ISSUE TITLE
Android/Desktop: Linked Devices drops link

### ISSUE THREAD

**Issue by CodeShot** [oxen-io/session-desktop#699]
Have tried linking devices two times. Both times the secondary device appeared in the list of linked devices correctly. Shortly after the device disapears from the list of linked devices. When using the secondary account without link it looks like it is working but it isn't really working. Send is not working but some messages are received though the devices are not linked anymore. The pub-key is same on both devices (though not linked).
Primary device: Android
Secondary device: Ubuntu 18.04 (up to date)

**Comment by Mikunj** [comment]
Hey, could you try setup this link with a new public key and do the same steps up until the linked device disappears and paste the public key of the primary device here?

**Comment by CodeShot** [comment]
Will have to do it on a different device as I dont want to lose contacts
and logs, but yes I can try to reproduce the problem on a other device.

Is there a chance that the pubkey i currently use is broken? (Asking
because there are some indications that the errors I get are not that
general, or else others would've brought them to your attention already)

**Comment by Mikunj** [comment]
Did you somehow restore from seed at anytime?

**Comment by CodeShot** [comment]
No.
