### ISSUE TITLE
Improve Message ordering

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#722]
Loki messenger on all devices now uses the senders timestamp to order messages, however we have become aware of an issue with this scheme (pointed out by @cammellos) which we want to resolve in the long term.

The issue is If Sender and Recipient clocks are out of sync then when messages are added to the conversation the senders messages will be in order but may appear above previous messages. Further a malicious sender could modify timestamps to arbitrarily insert messages into different parts of the conversation. 

We want to take a three pronged approach to fixing a majority of this issue 

1. Ensure that when clients startup they check in their local clock against some trusted network time source, if they are out of sync warn the user their clock is out of sync
2. At the client level reject the sending of messages with timestamps 10 seconds into the future or 30 seconds in the past
3. At the Loki Storage Server level refuse to store messages where the proof of work timestamp is 10 seconds in the future or 1 minute in the past 

These changes will ensure that honest clients have synced timestamps, and dishonest clients will only have a small windows in which they can make modifications to their own timestamps.

There are some possible problems here, If PoW takes significantly long this could delay the message long enough that the timestamp is no longer in the valid range 

and 

Malicious clients can still intentionally misorder messages in the 1 minute timeframe to change the context of a conversation. 

Both of these will require further thought as we don't just want all new messages appearing at the bottom of the conversation, sometimes want messages to be reordered based on the honest order the sender sent them in

**Comment by HostFat** [comment]
Are there any news on this issue?

**Comment by KeeJef** [comment]
Some of these changes have been implemented, some have caused more issues than they are worth, message ordering is now generally pretty good on Session, so i'm closing this
