### ISSUE TITLE
Public chats are not synced multi device

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#728]
This shows up on Android at least, not sure if its the same on all linked devices, but if a public chat is joined on the primary, like the Loki dev chat it is not automatically joined on the secondary device. This means the user must manually join all chats again on their linked device

**Comment by neuroscr** [comment]
this is across all platforms, a later phase multidevice stage

**Comment by Bilb** [comment]
For desktop, it was fixed with https://github.com/loki-project/session-desktop/pull/907
