### ISSUE TITLE
Buttons Non functioning on Desktop

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#799]
We are having issues with some desktop installs where the user cannot get past creating a sessionID or restore from seed, the buttons are simply not able to be pressed. This is not on all desktop installs, only some

**Comment by KeeJef** [comment]
Atleast for seed restoration i think this might have something to do with seed formatting, seeds created on Android do not restore on desktop

**Comment by neuroscr** [comment]
I did fix one bug tonight if you entered an invalid pubkey, it wasn't informing the user, so it was just sitting loading... Otherwise I didn't encounter this in my testing tonight.

**Comment by Bilb** [comment]
is the OS always the same for this bug? Never saw it on Linux so far

**Comment by Bilb** [comment]
Mikunj fixed an issue related to android seed being invalid as desktop seed at https://github.com/loki-project/session-android-service/pull/33

**Comment by Bilb** [comment]
Might be related to https://github.com/loki-project/session-desktop/issues/990

**Comment by Bilb** [comment]
No updates for 10 months. Closing this for now
