### ISSUE TITLE
When you click on open group it should go to the last message

### ISSUE THREAD

**Issue by abenhamo** [oxen-io/session-desktop#804]
Obtained:
When you click on open group, the first message of the queue is displayed
Expected:
When you click on open group it should go directly to the last message

**Comment by KeeJef** [comment]
Possibly Linked with this issue #847

**Comment by Bilb** [comment]
I don't think most users want to be taken to the last messages but want instead to be put at the start of the unread messages.
If really a user wants to be put at the last message, he can just mark all messages as read with the right click menu on the conversation item.
