### ISSUE TITLE
Windows: Feature Use Right Click Drop Down Options Over Icons

### ISSUE THREAD

**Issue by necro-nemesis** [oxen-io/session-desktop#810]
Clicking on user icon opens profile. Recommend clicking on it again closes profile screen vs having to relocate the mouse to the "x" and clicking it on the profile popup. Also right click on icon once profile info open could offer drop down with a copy Session ID to clipboard.

Similarly right click on member icon could offer drop down to start private Session.

**Comment by KeeJef** [comment]
Implemented
