### ISSUE TITLE
Inactivity causes open groups to scroll to top

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#837]
After a period of inactivity in desktop messenger (Usually a few hours) when i open messenger all of the group chats scroll back to the first message, instead of remembering the position i ended the chat at

![image](https://user-images.githubusercontent.com/27277414/74292483-3e0cae00-4d8c-11ea-8704-69cdf3df3f71.png)

**Comment by neuroscr** [comment]
weird haven't experienced this on MacOS
