### ISSUE TITLE
Accessing Settings menu resets public chats

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#847]
If you type something into the text field of a public chat and don't send it, and then you go to the settings menu, when you come out of the Settings menu the public chats are slow to load, they delete your unfinished messages and they also scroll the chat to the top, instead of starting where you left off

**Comment by KeeJef** [comment]
ill also add to this, that after exiting the settings menu none of the ... options beside each message work

**Comment by Bilb** [comment]
Closing as implemented already
