### ISSUE TITLE
Windows: Set ApplicationViewTitleBar to integrated colors

### ISSUE THREAD

**Issue by necro-nemesis** [oxen-io/session-desktop#882]
Windows titlebar defaults to white which looks a bit homebrew. Set the values to a colors that works with the theme.

**Comment by Bilb** [comment]
Not easy todo as we depend on electron for this.
An issue on electron side marked as wontfix: https://github.com/electron/electron/issues/1582

Looks like the only way currently is to disable the native title bar and implement one in html/css, using those plugins: https://github.com/AlexTorresSk/custom-electron-titlebar
