### ISSUE TITLE
Improve readability for Right to Left languages (Arabic, Hebrew) 

### ISSUE THREAD

**Issue by ihubgit** [oxen-io/session-desktop#904]
the default font, especially for RL languages, is really not a very nice one and at the default size quite difficult to read...

**Comment by KeeJef** [comment]
what do you mean by RL languages?

**Comment by ihubgit** [comment]
Right-to-left, such as Hebrew, Arabic etc.

**Comment by Bilb** [comment]
Closing this as we made the app more accessible for RTL languages. The font looks fine to me, feel free to reopen if it's still not readable
![image](https://user-images.githubusercontent.com/1544279/104875555-ab1bc100-59a9-11eb-8e03-3fa337c9d6c2.png)
