### ISSUE TITLE
Verify Long term key updates are disabled

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-desktop#947]
Signal allows users to update long term keys when moving to a new device, because there is a mapping between a users phone number and their long term keys. It puts a message in all conversations when this happens saying that the "safety numbers" for that user has changed 

This should not be possible in Session since your long term key is your identity, you should not be able to change to a new long term key without appearing as a completely different contact and having to do a friend request again. 

We need to confirm that all parts of the old Signal system are disabled

**Comment by Bilb** [comment]
I think that was managed by the rotateKeyListener.js file which was removed a while ago
