### ISSUE TITLE
After device pairing, contact is synced but am unable to message them

### ISSUE THREAD

**Issue by gt7599a** [oxen-io/session-desktop#963]
**Describe the bug**
My friend D sent a session request, I accepted it on mobile, later I linked a windows desktop client to my existing session ID, D is present but the desktop client shows it as 
"Pending Acceptance"  I can send D messages from Mobile and they show in the windows client but I can't send messages from the desktop client.

**To Reproduce**

1. Create a new user account on android mobile
2. friend D initiates contact request (March 6, 2020)
3. accepted D's request on mobile
4. Link my account from my Android to to Windows Desktop client
5. contact D on windows client shows as "Pending Acceptance"

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/12285358/76178618-dc0c6080-61f2-11ea-804f-8c3b2021b1f0.png)

**Other information (please complete the following information):**

* Device: [Pixel 2xl]
* OS: [Android]
* App Version [1.0.5]

* Device: [Windows Laptop]
* OS: [Win 10]
* App Version [1.0.4]

**Comment by KeeJef** [comment]
I think this might have to do with setting disappearing messages before a friend request is accepted, ive heard about that happening before. This is something @Brice-W should look into

**Comment by Brice-W** [comment]
Here is a test case I ran a few times with the same behaviour, so I post it here:

I have my Android Session with 3 one-to-one conversations started (one with an iOs device, one with MacOS Desktop device and one with an other Android device (called Android2 to avoid confusion)).
When I link a Windows Desktop to my Android, I receive on iOs, Android2 and MacOS Desktop a new friend request from a new ID (that ID is the same on the 3 devices, but is different from the one of my Android).
On Windows, I can’t message these devices (same issue as described in the case above), except the MasOS, which accepts the request automatically (probably related to issue 989, so I won’t test that for this particular issue).
When I accept the friend requests, I can chat with my Windows Session, but messages from these 3 devices are not showing on my Android. When I message them back from Windows, messages are showing on my Android.

**Comment by Bilb** [comment]
closing this as we removed the friend request logic.
