### ISSUE TITLE
Attempting to Pair an already paired Device Crashes the Android Mobile App

### ISSUE THREAD

**Issue by Skelaton4** [oxen-io/session-desktop#972]
**Describe the bug**
My Desktop says my mobile is Not Paired (But it is) When attempting to Re-Pair(scanning the QR code) it crashes the Android Mobile app.

**To Reproduce**
Pair Mobile to Desktop, Attempt to scan QR code and pair again, crashes the mobile app

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.
![image](https://user-images.githubusercontent.com/28955674/76316522-1e947280-62b1-11ea-824a-4198cffe370d.png)

**Other information (please complete the following information):**

* Device: Samsung Galaxy S9+
* OS: Windows 10/Android 10 
* Session Version or Git commit hash: V.1.0.5 on mobile and Desktop 1.0.4

**Comment by Bilb** [comment]
Closing this as Multi device as been disabled for a while, and when we will add it back, it will work completely differently.
