### ISSUE TITLE
UNABLE_TO_GET_ISSUER_CERT_LOCALLY / unable to get local issuer certificate

### ISSUE THREAD

**Issue by neuroscr** [oxen-io/session-desktop#973]
**Describe the bug**
Heather can't join her open group on Desktop

I've verified our cert is fine on the server side: https://www.ssllabs.com/ssltest/analyze.html?d=ui.getsession.org
And ofc the local usually means something is up with the local (non-remote) certs.

**To Reproduce**
try to join ui.getsession.org

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.
https://debuglogs.org/0155fb0ecac9cef44abd86d8f6d6abeaec4ad568607fa71aad5254dd41c1e781

**Other information (please complete the following information):**

* Device: Mac
* OS: MacOS 10.15.3
* Session Version or Git commit hash: 1.0.4

**Comment by KeeJef** [comment]
@Mikunj not sure if this is related to open group bugs you've just fixed

**Comment by neuroscr** [comment]
It's not related

**Comment by Bilb** [comment]
Closing this is as no one else had this issue
