### ISSUE TITLE
Minimize to tray (not taskbar)

### ISSUE THREAD

**Issue by kekukui** [oxen-io/session-desktop#983]
add toggle in [`Appearance Settings`] : "minimize to tray"

* OS: Windows
* Session Version: 1.0.4

**Comment by gitmaker032** [comment]
This is sorely lacking. It would also be great to see the autorun function on boot and also autoload to tray by default.

**Comment by danrobi11** [comment]
https://github.com/loki-project/session-desktop/issues/1081

**Comment by Bilb** [comment]
With  https://github.com/oxen-io/session-desktop/pull/1581 you can now start the app and make it show to tray with `--use-tray-icon`
