### ISSUE TITLE
Unable to create an account

### ISSUE THREAD

**Issue by cubetastic33** [oxen-io/session-desktop#990]
**Describe the bug**
I am trying to use session, but I'm unable to even create an account! It just stays on the same sign up screen
**To Reproduce**
- Open the session desktop app
- Attempt to sign up
**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.
![image](https://user-images.githubusercontent.com/33519300/77090792-a86cda00-6a2d-11ea-8ca9-5bcad8f98869.png)

**Other information (please complete the following information):**

* Device: HP Pavilion
* OS: Arch Linux
* Session Version or Git commit hash: I'm not sure how I figure this out, but it's the latest version in the AUR as of 2020-03-19T16:36Z

**Comment by saschaseewald** [comment]
Same problem here!

**Comment by KeeJef** [comment]
@saschaseewald are you also using Arch linux?

**Comment by saschaseewald** [comment]
I'm using Ubuntu.

**Comment by Bilb** [comment]
@saschaseewald  @cubetastic33 could you try one of the latest builds and let me know if this still happens to you ?

**Comment by cubetastic33** [comment]
I'm not able to build it now...
![image](https://user-images.githubusercontent.com/33519300/103666743-08237a00-4f9b-11eb-831e-c248e2ad4f9e.png)
Does it require python 2 to build?

**Comment by Bilb** [comment]
@cubetastic33 yes, looking at the error, it expects python2 to be available (or maybe the default)

**Comment by Bilb** [comment]
Closing this for now. Feel free to reopen if this error still happens
