### ISSUE TITLE
Can't link iOS device to macOS 

### ISSUE THREAD

**Issue by ldub** [oxen-io/session-desktop#997]
**Describe the bug**
Linking does not work. Stuck on "Waiting for Authorization" screen on iOS, and  nothing happens on the desktop client.

**To Reproduce**
1. on macOS, click Link New Device
2. on iOS, tap link device and scan the QR code
3. you are now stuck. nothing happens.

**Screenshots or Logs**

![image](https://user-images.githubusercontent.com/3114081/77221253-7fb81380-6b05-11ea-9f56-05eb67db0075.png)

![IMG_8696](https://user-images.githubusercontent.com/3114081/77221260-8d6d9900-6b05-11ea-96c7-24ec80d84574.jpg)

**Other information (please complete the following information):**

* Device: macbook + iPhone
* OS:  macOS Catalina + iOS 13.3
* Session Version or Git commit hash: v1.0.5 macOS, not sure on iOS

**Comment by cswoodruff** [comment]
I'm seeing this same issue with ...
OS: macOS Mojave 10.14.6 + iOS 13.3.1
Session v1.0.5 macOS

**Comment by mc1472** [comment]
I got the same thing on arch linux and andriod
Latest arch and android 9
Session 1.0.5 linux and latest in play store

**Comment by rayheffer** [comment]
Same issue for me.

Windows 10 Desktop + iOS 13.3.1

**Comment by KeeJef** [comment]
With the latest updates for iOS and Android and Desktop are you still experiencing these issues?
